### ISSUE TITLE
DeltaStation Tritium Fire in waste

### ISSUE THREAD

**Issue by Kalesonki** [Skyrat-SS13/Skyrat-TG#10003]
## Reproduction:
Engineering roundstart has SM waste pipenet recycling valve open by default. Together with freezers connected to waste loop, it cause temperature to rise above plasma self-ignition temperature point (373 K), resulting in lasting plasma and later tritium fire, causing radiation leaks across whole station.

**Comment by gonenoculer5** [comment]
Doing toxins in waste now. 😎

**Comment by Zergspower** [comment]
Engineering redesign resolved this
