### ISSUE TITLE
Admin Tools: Toggle Entering - Does not appear to work. 

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#10035]
## Reproduction: 
Server Panel > Toggle Entering. 

It appears the Toggle Entering verb no longer blocks users from joining the game if activated. Was recently used to attempt to stop players from joining a doomed round where the bugs required a restart shortly after investigation.

**Comment by Zergspower** [comment]
seems to function in the current version
