### ISSUE TITLE
as ghost explosion screen shake misaligns camera and never returns

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10069]
Reporting client version: 514.1547

## Round ID:
3887

## Testmerges:
- [Events audit, moving overrides to modular files + TEMP FIX](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9941)
- [CROSSLINK + Population control cap](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979)
- [[FUCK] Fixing the external organs, for real this time(?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023)
![Screenshot_2 - Copy](https://user-images.githubusercontent.com/13283561/146023990-ce565b8d-50e4-437b-bc29-71d6f08ba5c2.png)

- [911 Rework: Button Relocation, Cops -> Marshals, Confirmation Prompts, S.W.A.T. Rework, Dogginos, and Treason.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10008)

**Comment by Zergspower** [comment]
tried to reproduce and cannot
