### ISSUE TITLE
TGUI Camera Search Error

### ISSUE THREAD

**Issue by jwc1015** [Skyrat-SS13/Skyrat-TG#10065]
Reporting client version: 514.1571

## Round ID:
3879

## Testmerges:
- [Events audit, moving overrides to modular files + TEMP FIX](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9941)
- [CROSSLINK + Population control cap](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979)
- [[FUCK] Fixing the external organs, for real this time(?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023)
- [911 Rework: Button Relocation, Cops -> Marshals, Confirmation Prompts, S.W.A.T. Rework, Dogginos, and Treason.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10008)

## Reproduction:
Upon typing anything in the search box of cameras as the AI, I got the following error:
NOTICE: It worked fine with the other search functions, like the tracker.

TypeError: Unable to get property 'toLowerCase' of undefined or null reference
   at Anonymous function (http://127.0.0.1:49887/tmp2196/tgui.bundle.js:1:953180)
   at Anonymous function (http://127.0.0.1:49887/tmp2196/tgui.bundle.js:1:41117)
   at filter (http://127.0.0.1:49887/tmp2196/tgui.bundle.js:1:87906)
   at onInput (http://127.0.0.1:49887/tmp2196/tgui.bundle.js:1:953152)
   at t.handleInput (http://127.0.0.1:49887/tmp2196/tgui.bundle.js:1:372962)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"jwc1015","interface":"ListInput","window":{"key":"[0x21098f8b]-main","size":null,"fancy":1,"locked":0}}

**Comment by Tastyfish** [comment]
This is an upstream issue already reported and fix submitted for review https://github.com/tgstation/tgstation/issues/63390

**Comment by jwc1015** [comment]
Ah, ok! Sorry about missing that, thank you!

**Comment by jwc1015** [comment]
Just in case anyone wants to know if this is being fixed, the TG PR https://github.com/tgstation/tgstation/pull/63394 will fix it when it gets merged.
