### ISSUE TITLE
Baked Cheese lacks a cooking recipe

### ISSUE THREAD

**Issue by MassacreDemigirl** [Skyrat-SS13/Skyrat-TG#10068]
Reporting client version: 514.1566

## Round ID:
3886

## Testmerges:
- [Events audit, moving overrides to modular files + TEMP FIX](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9941)
- [CROSSLINK + Population control cap](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979)
- [[FUCK] Fixing the external organs, for real this time(?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023)
- [911 Rework: Button Relocation, Cops -> Marshals, Confirmation Prompts, S.W.A.T. Rework, Dogginos, and Treason.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10008)

## Reproduction:
/obj/item/food/baked_cheese has no crafting recipe, and thus cannot be made

**Comment by YakumoChen** [comment]
@ErdinyoBarboza have you tried baking a cheese?
