### ISSUE TITLE
Moths dont get their wings

### ISSUE THREAD

**Issue by Gaerist5** [Skyrat-SS13/Skyrat-TG#10155]
## Testmerges:
#9979: 'CROSSLINK + Population control cap' by Gandalf2k15 at commit 282e52fb71
#10023: '[FUCK] Fixing the external organs, for real this time(?)' by GoldenAlpharex at commit 247b928782
#10060: '[MIRROR] Field of View and Blindness improvements [bounty + upstream push] [MDB IGNORE]' by SkyratBot at commit 89661dce51

## Reproduction:
When creating a character with the species "Mothman", enabling the "Wings" checkmark will not give any wings, while unchecking it will give the character a single set of wings that you cant change.
[Moth Pic 1](https://i.imgur.com/bBahesB.png)
[Moth Pic 2](https://i.imgur.com/3LICHRI.png)

The wings options work fine for all the other races though.
[Synthetic Lizard Pic 1](https://i.imgur.com/Jv2eNHt.png)
[Synthetic Lizard Pic 2](https://i.imgur.com/5i6nhf2.png)

To recreate the bug create a mothman character and try to give them wings.

**Comment by Zergspower** [comment]
moffs can have wings again - issue resolved
