### ISSUE TITLE
CRITICAL bug with Power Armor

### ISSUE THREAD

**Issue by Suspect-One** [Skyrat-SS13/Skyrat-TG#10171]
## Round ID: 
2203 (we're playing on Russian one)

## Testmerges: 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9919

## Reproduction: 
1. make a powerarmor (either by spawning it or by making it manually through forging)
2. install armor upgrades in it. For test purposes, we will be using 5 melee armor upgrades (if PA is upgraded with anomaly core = 30 upgrade points) which equals to 100 MELEE ARMOR total = invincibility in melee.
3. you now have power armor with 100 melee armor (or just MELEE X).
4. now look at any clothing which doesn't naturally have armor (chef aprons, sunglasses, even sex toys lol)
5. every clothing item which naturally doesn't have any resistances now have 100 melee armor GLOBALLY everywhere in the round

![image](https://user-images.githubusercontent.com/45109527/146886762-9eb3a5ee-587d-4c2e-b554-3cfce6eab2fa.png)

Each time you insert upgrade in PA, it increases the armor values across every non-armored clothing item in the game which exists. Even new spawned items immediately gain that armor value for some reason. The only way we found to fix it in game is to find PA and remove installed upgrades in it.

**Comment by GoldenAlpharex** [comment]
Very good choice of picture. 💯
