### ISSUE TITLE
Intellicard doesn't detect AI inside of it

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#10179]
Reporting client version: 514.1569

## Round ID:
3955

## Testmerges:
- [CROSSLINK + Population control cap](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979)
- [[FUCK] Fixing the external organs, for real this time(?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023)
- [[MIRROR] Field of View and Blindness improvements [bounty + upstream push] [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10060)

**Comment by Zergspower** [comment]
cards seem to work in current build, tacking this one to an age fix over time
