### ISSUE TITLE
Might not be a bug but I don't think the hash brick should contain cocaine.

### ISSUE THREAD

**Issue by pantherpusher** [Skyrat-SS13/Skyrat-TG#10209]
https://github.com/Skyrat-SS13/Skyrat-tg/blob/04fbf88162097e628bc534e7ef8ff837f04d030f/modular_skyrat/modules/morenarcotics/code/thc_item.dm#L19-L26

**Comment by ghost** [comment]
Confirmed still a thing
~~Don't know enough about drugs to know what I'd even change this to so~~
nvm it's a brick of another drug, easy fix
