### ISSUE TITLE
GenTurf and Spaced entierty of security at round start

### ISSUE THREAD

**Issue by ro3ger** [Skyrat-SS13/Skyrat-TG#10218]
## Round ID:3977

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tg station hosted servers:Not tested but they don't have Ice box skyrat set up
[Round ID]: 3977

**Comment by ghost** [comment]
was closed by #10214 @tf-4 (I think you're who I ping for bugs)
