### ISSUE TITLE
Human "members" are a pixel wide under 11 inches.

### ISSUE THREAD

**Issue by gonenoculer5** [Skyrat-SS13/Skyrat-TG#10226]
## Reproduction:

Acquire member.
Set to 11 inches.
Notice that it looks normal.
Set to 10 inches.
Scream in unending agony as your member is compressed into the equivilent size of a pencil.

**Comment by Quill-Weave** [comment]
Working as intended. Poor, poor humans.

Checked the .dmis to be sure.
