### ISSUE TITLE
Ghost roles don't use prefs characters and instead randomhuman you

### ISSUE THREAD

**Issue by Ebin-Halcyon** [Skyrat-SS13/Skyrat-TG#10220]
Reporting client version: 514.1557

Ghost roles spawn as random humans instead of prefs characters, due to the fact that #10075 was made and not retrofitted for our ghost roles.

## Round ID:
3978

## Testmerges:
- [CROSSLINK + Population control cap](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9979)
- [[FUCK] Fixing the external organs, for real this time(?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10023)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)

## Reproduction:

Spawn in sleeper.
click sleeper.
spawn as prefs character.
Get spawned as random human instead.

**Comment by YakumoChen** [comment]
close please

**Comment by Ebin-Halcyon** [comment]
> close please

The issue isn't fixed.

**Comment by YakumoChen** [comment]
read the linked PR wrong, oops
