### ISSUE TITLE
Icebox Gen Turf north of brig

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#10263]
## Testmerges: 
#9979: 'CROSSLINK + Population control cap' by Gandalf2k15 at commit 282e52f
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a9

## Reproduction:
Walk north of brig.
Behold the green squares

https://discord.com/channels/596783386295795713/640760727489085450/924276593080291348
https://cdn.discordapp.com/attachments/640760727489085450/924276592484687973/genturf.png
https://cdn.discordapp.com/attachments/640760727489085450/924276592681836614/genturfgenturf.png
https://cdn.discordapp.com/attachments/640760727489085450/924276592891531314/genturfgenturfgenturf.png
https://prnt.sc/24hkwpq

**Comment by gonenoculer5** [comment]
https://gyazo.com/c625a1069de63e80d167fd4de6e7b65b

**Comment by ghost** [comment]
@tf-4 
Was closed by #10214 (Which was merged before the bug report, the server just wasnt updated)

**Comment by GuiltyNeko** [comment]
> Was closed by #10214 (Which was merged before the bug report, the server just wasnt updated)

For some reason it takes folks two days hit the update server button after merging a PR to make a map stop killing people? It's fixed yes, closing now.
