### ISSUE TITLE
Reactive armor constructed from anomaly cores is always stealth

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#10260]
## Testmerges:
#9979: 'CROSSLINK + Population control cap' by Gandalf2k15 at commit 282e52fb71
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc

## Reproduction:
Get anomaly core from anomaly
Put anomaly core in reactive armor
Behold the stealth reactive armor
Get somebody to punch you
Behold your invisibility, despite having use a pyro anomaly core, or what have you

**Comment by tf-4** [comment]
No longer reproducible
