### ISSUE TITLE
Icebox mapping issues

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#10264]
## Testmerges:
#9979: 'CROSSLINK + Population control cap' by Gandalf2k15 at commit 282e52f
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a9

Icebox brig/permabrig is 0 kPa at roundstart
Icebox brig/permabrig firelocks are effectively useless due to the open top of the permabrig, serving only to restrict movement through the area, without doing what they're meant to do
Icebox brig southeast maint door is security access instead of brig access
Icebox brig equipment room has a staircase going up into a wall, and a drop with no guard rail on the opposite side
Icebox courtroom is missing a wire and pipes under the tile in front of the maintenance door
Icebox telecomms control room, with the 2 extra consoles and announcement computer, is set to -100 celsius, at 100 kPa
Probably more I can't remember

**Comment by ghost** [comment]
brig atmos was fixed by #10214 (which was merged before this bug report)
brig has been that way for months
staircase was fixed by #10214 (again, merged before this report)

**Comment by ghost** [comment]
Huh
The tcomms thing is TG's doing, not ours. Good to know.

**Comment by GuiltyNeko** [comment]
> brig atmos was fixed by #10214 (which was merged before this bug report) brig has been that way for months staircase was fixed by #10214 (again, merged before this report)

Skyrat doesn't know how to update the server within less than 2 days after a fix is merged to make a map stop killing people
