### ISSUE TITLE
certain borg models invisible again

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10281]
Reporting client version: 514.1547

## Round ID:
4000

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)

**Comment by Sonic121x** [comment]
likely cause by this #10259

**Comment by Zergspower** [comment]
Issue was resolved
