### ISSUE TITLE
Security HUDSunglasses/NVG HUD's don't work as eye protection for pepperspray.

### ISSUE THREAD

**Issue by mazzinsanity** [Skyrat-SS13/Skyrat-TG#10297]
Reporting client version: 514.1557

## Round ID:
4009

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)

## Reproduction:

Wearing Security HUDSunglasses or Security NVG HUD's and a security mask still leaves you vulnerable to pepperspray.

**Comment by kannthus** [comment]
This appears to be working as intended. Neither the HUDSunglasses nor the Security Mask give the Pepperproof flag. Logically pepperspray is a mist that glasses can't stop.

You'd have to wear a normal gas mask or riot helmet, those both have pepperproof. Also, I'd advise writing this in #development-suggest
