### ISSUE TITLE
Blueshield can't access the armory tac locker in their office on Blueshift

### ISSUE THREAD

**Issue by mazzinsanity** [Skyrat-SS13/Skyrat-TG#10340]
Reporting client version: 514.1557

## Round ID:
4040

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:

Their ID card doens't have the access to open it.

![image](https://user-images.githubusercontent.com/77054674/147701037-e5b96cd9-2619-4ebf-a0f9-ebd01d2a258c.png)

**Comment by Zergspower** [comment]
I believe this is Alert locked - with BS out of rotation it may be better to ask in the Blueshift dev channel instead
