### ISSUE TITLE
Low oxygen adapted lungs have some wacky typos, could be the same with the other custom lungs.

### ISSUE THREAD

**Issue by mazzinsanity** [Skyrat-SS13/Skyrat-TG#10342]
Reporting client version: 514.1557

## Round ID:
4040

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:
![image](https://user-images.githubusercontent.com/77054674/147706073-2c48422a-1e06-402c-8312-353f339d0795.png)

**Comment by Tastyfish** [comment]
yeah... the hot_message and cold_message have the completely wrong type of text in them. They're filled into "You feel [message] in your [organ]" but contain complete sentences.

**Comment by Tastyfish** [comment]
Worse, the messages don't make sense anyway. They trigger when the organ's threshold is breached regardless, not a specific other magic number temperature, so the sensation would be the same regardless of lung type if they're displayed. They lung subtypes should probably not change them at all.

Edit: I suppose the damage levels vary, so they can probably be kept if fixed grammatically.
