### ISSUE TITLE
Slime storage "draw multiple" option does not work

### ISSUE THREAD

**Issue by ThePainkiller** [Skyrat-SS13/Skyrat-TG#10367]
Reporting client version: 514.1575

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:

Attempting to withdraw multiple slime cores from the slime storage via the button to imput a number of items to withdraw does not withdraw any slime cores at all, forcing you to do it one by one. The "Min" and "max" options set the number to the respective one, but setting a number yourself does not get "saved" and it's impossible to withdraw even 1 or all at a time from the very same options.

**Comment by Zergspower** [comment]
_thankfully_ this has been fixed
