### ISSUE TITLE
Agent Cards cannot replicate Blueshield trim

### ISSUE THREAD

**Issue by Zonespace27** [Skyrat-SS13/Skyrat-TG#10376]
## Reproduction:

1. Get an agent card
2. Use the chameleon change function
3. Realize there isn't a blueshield trim

**Comment by YakumoChen** [comment]
> ## Round ID: 4058
> ## Reproduction:
> 1. Get an agent card
> 2. Use the chameleon change function
> 3. Realize there isn't a blueshield trim

Do you mean the color of the ID or the icon

**Comment by Zonespace27** [comment]
i specifically mean the Icon on the ID, and thus the sechud icon as well

**Comment by Zergspower** [comment]
Able to confirm this is functional now
