### ISSUE TITLE
Prayer Beads Null Rod uses incorrect methods of role checking and thus does not recognize the Chaplain as the Chaplain

### ISSUE THREAD

**Issue by Jezzared** [Skyrat-SS13/Skyrat-TG#10373]
Reporting client version: 514.1568

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [[TM-Only] Fixing MODsuits a bit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10273)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:
Be the chaplain, change your null rod into the prayer beads, and attempt to pray with them (by clicking on yourself or someone else).

This was mentioned on another server, and someone decided to look at the code there.
![beadcode](https://user-images.githubusercontent.com/96926864/147840179-caac0706-f6ff-41d1-bd49-7bfaa741b90f.png)
![beadsnip](https://user-images.githubusercontent.com/96926864/147840120-c79128fd-4e37-4fc1-beb1-bcaa9a794ef1.png)

**Comment by Zergspower** [comment]
Fixed in #10481
