### ISSUE TITLE
Tacticasual Uniform Sprite Issue

### ISSUE THREAD

**Issue by Leudoberct1** [Skyrat-SS13/Skyrat-TG#10390]
When alt-clicking the tacticasual uniform to swap it to its alternate appearance, it instead swaps to a full-body GMOD stlye pink-and-black checkered pattern, as if the sprite is wrong or something.

**Comment by gonenoculer5** [comment]
Ironically its not supposed to have an alt sprite but if someone could just please make one where its literally just the pants instead of the tanktop id love you forever.

**Comment by ghost** [comment]
Should have been closed by the syndicate spritefile cleanup PR

**Comment by Zergspower** [comment]
Resolved
