### ISSUE TITLE
Repairing janibots with a welder makes you both attack and repair them with the same click

### ISSUE THREAD

**Issue by chizzyyyy** [Skyrat-SS13/Skyrat-TG#10411]
Reporting client version: 514.1568

## Round ID:
4081

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:
Swipe your ID on a harmed janibot, click on the little yellow toolbox to turn off the maintenance lock, weld it. 
Below is an attached image of me clicking on the janibot **once.**

![pain pain pain](https://user-images.githubusercontent.com/90527540/147926162-a211743c-ce3e-48eb-9caf-a0be85db6dae.PNG)

**Comment by ghost** [comment]
Possible TG issue?

**Comment by Zergspower** [comment]
seems resolved
