### ISSUE TITLE
Ling transform is broke

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#10426]
#### Description of issue

Changeling transform doesn't change species, ears, tails, etc
Also character preview doesn't update when you transform

#### Difference between expected and actual behavior

![image](https://user-images.githubusercontent.com/10399117/147991085-6102d92b-ca15-4fad-af30-49f936d89408.png)
I'm supposed to be a human. I look like half-felinid, half-moth, half freak.

#### Steps to reproduce
Be ling
Get sting
Transform into someone else with funny animal parts (or a moth)
Wonder why you still have your original non-human parts

## Round ID
4087

## Testmerges:
The following pull requests are currently test merged:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 6289f1c9f6
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit be8ffc759c

**Comment by GoldenAlpharex** [comment]
Probably a problem with the fact that is should somehow do some preferences applying, but doesn't.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13527 https://github.com/Skyrat-SS13/Skyrat-tg/pull/14190
