### ISSUE TITLE
Toxin Tests not working properly

### ISSUE THREAD

**Issue by Aether217** [Skyrat-SS13/Skyrat-TG#10436]
Reporting client version: 514.1557

## Round ID:
4097

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)

## Reproduction:

I was doing toxins research via a chemical payload which had the stats of 1/3/7 which theoretically should clear the first 2 bomb tests. The game for some reason believes that this is not enough to pass the 0/0/1 requirement for is this thing on. I tried other mixes with even just a meth nade but it was still not giving us the research.
![Screenshot_48](https://user-images.githubusercontent.com/80391087/148115694-3c8a78ad-d956-41a3-ad4c-850f7603d20d.png)
This happened in a previous round as well but I just thought it was a fluke.

**Comment by YakumoChen** [comment]
It probably needs to go above the target number

**Comment by gonenoculer5** [comment]
This is indeed purely just a visual thing as it does clear the two tests. I had something similar happen with oil slime cores not long ago, its a bug with the second test I believe. Unsure what causes it.

**Comment by Zergspower** [comment]
current Toxins appear to function correctly, assuming resolved
