### ISSUE TITLE
ice-based Turf Emote

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-TG#10458]
Since i'm pretty sure TG does not have the turf emotes, i'm putting this here.

the title says it all effectively, an ice-based *turf emote that, i dunno, makes the tile under you visually frosted?

**Comment by YakumoChen** [comment]
Feature requests should go on discord, this is for bug reporting.

**Comment by Zergspower** [comment]
Add to the development suggest in discord
