### ISSUE TITLE
Cannot make Weakened Virus Plasma, Synapt throws the plasma into the atmos

### ISSUE THREAD

**Issue by Ruediger4** [Skyrat-SS13/Skyrat-TG#10528]
## Round ID: 4131

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # (It can be found in the Status panel or retrieved from https://sb.atlantaned.space/rounds ! The round id let's us look up valuable information and logs for the round the bug happened.)-->

## Reproduction:

You simply cannot make Weakened Virus Plasma. The steps would be virus food -> pour liquid plasma into virus food beaker -> it becomes virus plasma -> pouring synaptizine would _IDEALLY_ make Weakened Virus Plasma but instead it consumes the virus plasma and shoots it into the air, polluting the atmos w/plasma and the synapt remaining in the beaker.

**Comment by tf-4** [comment]
The reaction heats the chemicals too much and sends the plasma into the air

**Comment by tf-4** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/10783
