### ISSUE TITLE
Ghost roles cant use Created Vendors

### ISSUE THREAD

**Issue by Zenitheevee** [Skyrat-SS13/Skyrat-TG#10585]
## Testmerges:

#8842
#10232
#10093
#10331

## Reproduction:

Issue: Creating a vendor gives ghost roles an unaccessible vendor they cant use. After using an Account Registration Machine, The vendor will then throw up an NTOS error. In the backend, Its failing to read the /datum/job/unassigned and its title.

Steps of Recreation
Step 1: Make vendor. How you get the refill is up to you
Step 2: Try to use it. You require an account, and therefor cant use it
Step 3: Register account on ID
Step 4: Try to use vendor again. Get thrown a NTOS error and cry.

**Comment by Zergspower** [comment]
Fixed to where it correctly requires an ID on non-ghost spawned vendors
