### ISSUE TITLE
Cleaner grenades do not qdel after being spent

### ISSUE THREAD

**Issue by Zenitheevee** [Skyrat-SS13/Skyrat-TG#10587]
## Testmerges:

#8842
#10232
#10093
#10331

## Reproduction:

Expected behavior: Should either Qdel or be labeled as "Spent". Currently does neither

Steps of Recreation:
Step 1: get cleaner grenade. How you do this is your task, not mine
Step 2: Use it
Step 3: Be confused why there's another cleaner grenade, Try to use it and realize you cannot.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10336
