### ISSUE TITLE
Shooting range duplicating windoor

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10604]
Reporting client version: 514.1575

## Round ID:
4161

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)
- [[MODULAR] Port Tarkon (New Ghostrole/Space ruin) [Ready for Review/Testing]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10331)

## Reproduction: Metastation Interesting bug. It's possible to duplicate windoor assemblies and airlock electronics as many times as you want if you just repeatedly crowbar the electronics out.

 I went to the sec firing range, and went to disassemble the windoor. I opened it, screwed the panel open, and then crowbarred it. That ended up dropping airlock assemblies and creating a duplicate windoor assembly on the same tile as the shooting range door. Crowbarring the shooting range door made more airlock electronics and windoor assemblies.

It only seems to work with that one particular shooting range windoor, however, and presumably any other windoor that spawns at roundstart. 

<!-- **For Admins:** Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them. -
![Screenshot_1 - Copy](https://user-images.githubusercontent.com/13283561/149009001-2cdb9300-ab2f-4290-96fc-887dd10e2d53.png)
->

**Comment by Tastyfish** [comment]
I was able to reproduce this for any windoor on upstream tg. The issue should be created upstream.

**Comment by tf-4** [comment]
https://github.com/tgstation/tgstation/pull/64145

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10750
