### ISSUE TITLE
Custom AI hologram

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#10602]
Reporting client version: 514.1569

## Round ID:
4160

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)
- [[MODULAR] Port Tarkon (New Ghostrole/Space ruin) [Ready for Review/Testing]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10331)

**Comment by tf-4** [comment]
I've seen people use them since

**Comment by Zergspower** [comment]
Resolved in current state
