### ISSUE TITLE
Tram station delivery Disposals not working fully.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10664]
Reporting client version: 514.1575

## Round ID:
4184

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)
- [Revert "[MIRROR] Harddel Fix Pack #42 + Better Live Reftracking Support [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10642)

**Comment by Jolly-66** [comment]
We've had a handful of map resets that have occurred since this issue was opened, and probably has been fixed then. If this isn't the case, please let me know.

**Comment by GreytideSkye** [comment]
Still a concern as of Shift 9557. Crate bounces between two different disposals sorters.

**Comment by nikothedude** [comment]
is this upstream? or localized down hyere

**Comment by GreytideSkye** [comment]
Valid point. Don't know.
