### ISSUE TITLE
Sentient disease doesnt fucking work and I cant force manual cough

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#10728]
Reporting client version: 514.1561

## Round ID:
4207

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)
- [Revert "[MIRROR] Harddel Fix Pack #42 + Better Live Reftracking Support [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10642)

## Reproduction:
Infect first host. try to make them cough. it doesnt work. 
host infected had a modsuit originally. 
I tried unsymptoming and resymptoming voluntary cough and it didnt work.
host may have had another disease Idunno.

Help.

**Comment by tf-4** [comment]
Oh wait this is already fixed just needs server update
