### ISSUE TITLE
Alternative breathing races dont spawn with their air in Port Tarkon

### ISSUE THREAD

**Issue by Psychodeath42** [Skyrat-SS13/Skyrat-TG#10732]
## Round ID:
4210

## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 8f7280e765
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit 9bfee413f5
#10642: 'Revert "[MIRROR] Harddel Fix Pack #42 + Better Live Reftracking Support [MDB IGNORE]"' by Gandalf2k15 at commit 3552d1f131

## Reproduction:
In the ghost role P-T sleeper you spawn at the Port Tarkon. If you are a Vox you will spawn without a mask or a nitrogen tank, making it impossible to survive. May also happen to plasmamen and those with the alternative air quirks.

**Comment by Zergspower** [comment]
sadly this expands to all ghost-roles - ahelp until a solution is found but it is very much noted in a few other tickets
