### ISSUE TITLE
OPFOR, Objective text gets cut off.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10748]
Reporting client version: 514.1575

## Round ID:
4217

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)
- [The Opposing Force (OPFOR) - Ready for review/testing](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10093)
- [bluespace miner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10610)

**Comment by Zergspower** [comment]
outdated issue, text showed at EOR is directed now to the reasoning rather than the title

**Comment by tobjv** [comment]
This isnt about EOR. In the OPFOR panel that staff see, the text limit is/was (will have to check to see if it still does it) would just cut off
