### ISSUE TITLE
MOD Standard Cores have ERROR sprite

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#10768]
## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 8f7280e765
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit 9bfee413f5
#10610: 'bluespace miner' by jjpark-kb at commit 1bcbcba4f2

## Reproduction:
Spawn in a standard MOD core. Look at the ERROR sprite

![image](https://user-images.githubusercontent.com/62698555/149743232-b50c5311-8953-4dd9-a4a0-c99bc4870054.png)

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/10864
