### ISSUE TITLE
Modular Suits take two modular cores

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#10769]
## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 8f7280e765
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit 9bfee413f5
#10610: 'bluespace miner' by jjpark-kb at commit 1bcbcba4f2

## Reproduction:
Print out a modular suit and put a core in like normal.
After finishing the suit notice that it doesn't accept a power cell and says it has no core
Place another core in after which it accepts the power cell

**Comment by Zergspower** [comment]
Resolved after PR change
