### ISSUE TITLE
New security gear sprites not working for Vox

### ISSUE THREAD

**Issue by mo2x** [Skyrat-SS13/Skyrat-TG#10772]
New security gear sprites not working for Vox. I'm trying out a lot of new armor options and they don't work 

![unknown](https://user-images.githubusercontent.com/90127544/149791560-798678de-5dad-4785-9c6b-20c05102a5ab.png)

**Comment by Quill-Weave** [comment]
That seems to be the sprite preview. I don't know if you've got it set to show job equipment or not.

I tested the new armor, and on my end, it works!

![image](https://user-images.githubusercontent.com/103809013/163691625-04f49138-19b3-479b-8b1f-6d1e5d3fa43c.png)
![image](https://user-images.githubusercontent.com/103809013/163691633-d79dbaf8-1ce4-4988-a71f-22627d2c8250.png)
![image](https://user-images.githubusercontent.com/103809013/163691637-d2034896-c450-4dbf-817f-dbca8a9a07d4.png)

Cannot reproduce!

**Comment by Jolly-66** [comment]
Confirmed someone couldn't properly replicate the issue. If this is still prevalent, please let me know and I'll reopen this issue.
