### ISSUE TITLE
RoboTact spontanious lack of variables (NaN%I!)

### ISSUE THREAD

**Issue by Furminium** [Skyrat-SS13/Skyrat-TG#10792]
## Reproduction:
Orbited around a ghost on another Z-level on icebox station, took up the opportunity of a positronic as it popped up(no ping upon activation curiously), was inserted into borg shell(4kcell,full), checked crew list, printed upgrades(inducer,adv.mat., circuit man, self repair, affection, rped, rped, ion thruster (all not in that order)), walked towards engineering, examined pacman generator, cut half a grille, opened few doors and set a firelock to stay open, enabled lamp, opened rotobact to turn lamp brighter when the error of this https://prnt.sc/26ex4h4 occured, started writing ticket ingame and on git, opened upgrade list to list upgrades, the window, in the meantime, became this: https://prnt.sc/26ex8kj

Notable: as ghost, examined interdyne rtgs, including one an admin spawned and deleted. The ai i was bound to on creation left sometime between my creation and me writing the ticket.

**Comment by SpookyTheFox** [comment]
When this happens, it's all borgs that seem effected by it. It also often corrects itself within a handful of minutes. To me, this indicates it may be a server side process hanging up and messing up the UI, rather than the UI itself going out.

**Comment by Zergspower** [comment]
outdated issue, the update to modular tablets resolved it
