### ISSUE TITLE
Shrouds and Veils block flavor text preview

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#10802]
## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 8f7280e765
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit 9bfee413f5
#10610: 'bluespace miner' by jjpark-kb at commit 1bcbcba4f2

## Reproduction:
Write flavor text for your character and examine yourself
See the flavor text preview and look closer prompt
Put on a polychromic veil
Now examine yourself and see only Examine Closely prompt

**Comment by tf-4** [comment]
Pretty sure this is a feature.
