### ISSUE TITLE
Enclave Coinage Doesn't Greentext.

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#10819]
## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10232: '[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!' by GoldenAlpharex at commit 8f7280e765
#10093: 'The Opposing Force (OPFOR) - Ready for review/testing' by Gandalf2k15 at commit 9bfee413f5
#10610: 'bluespace miner' by jjpark-kb at commit 1bcbcba4f2

## Reproduction: Spawn in as the Enclave. Do your objective. The credits stored within the Cargo Hold console doesn't register round-end, resulting in a redtext.
![image](https://user-images.githubusercontent.com/71103211/150083313-a89f591b-f9fc-49f2-aace-9e3909dd31ae.png)

**Comment by ghost** [comment]
Issue with all pirates, and I believe a TG one at that.
Either way this bug is out-of-date with the death of the Enclave, rest in piss
