### ISSUE TITLE
Dying as a construct made by the syndicate soulstone kit instantly crashes your game

### ISSUE THREAD

**Issue by chizzyyyy** [Skyrat-SS13/Skyrat-TG#10901]
Reporting client version: 514.1568

## Round ID:
4288

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)

## Reproduction:
I'll tell you how to reproduce it step by step how it happened:
Be chaplain antag, buy the bootleg cult kit with the soul stones and constructs and whatnot
Get a person's soul, put it into the construct shell, pick jugg
Now when they die, they will effectively crash to desktop, their game freezing forcing a reboot of the whole client. On my end it also forced me to download the server files.

## Comments:

I talked with other constructs after the round and they told me that they crashed as well, so I'm likely not the only one experiencing this
The specifics are probably not so specific, the only problem is probably the whole jugg conversion thing, but I included chappy and other variables that might have a play in this..

**Comment by Zergspower** [comment]
This was probably related to BYOND version - unable to reproduce
