### ISSUE TITLE
Crafting system sometimes uses whole cheese wheels instead of the wedges

### ISSUE THREAD

**Issue by ThatGuyPhil** [Skyrat-SS13/Skyrat-TG#10914]
## Round ID:
4292

## Testmerges:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10823: 'rev revert' by Gandalf2k15 at commit 58ec183702
#10486: '[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor' by Kapu1178 at commit 72a8b374ae
#10829: 'lobby camera' by jjpark-kb at commit b8cd1b76a9

## Reproduction:
I noticed cheese wheels vanishing as I made food that uses cheese wedges as a ingredient. The cheese wheels were next to me on a table since I planned to cut them up after but they mightve been used instead of the cheese wedges.

**Comment by tf-4** [comment]
What food was made? Are you sure it was using them, or is it a "maybe" they were used?

**Comment by ThatGuyPhil** [comment]
I made cheese pizza and I think cheese sandwiches

**Comment by vinylspiders** [comment]
This hath been fixed. 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12076

**Comment by tf-4** [comment]
see above
