### ISSUE TITLE
Delta station AI sat transit tube dispenser is unwrenched

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#10933]
## Testmerges: 
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10823: 'rev revert' by Gandalf2k15 at commit 58ec183702
#10486: '[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor' by Kapu1178 at commit 72a8b374ae
#10829: 'lobby camera' by jjpark-kb at commit b8cd1b76a9

## Reproduction: 
Attempt to walk into tube dispenser.
Walk over it, and not into it.
Wrench down dispenser.
Walk into it.
Swoosh away to the AI sat.

**Comment by tf-4** [comment]
The map reset will have picked this up.
