### ISSUE TITLE
Eigenstasium not making Bluespace lockers.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10938]
Reporting client version: 514.1575

## Round ID:
4298

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)

**Comment by tf-4** [comment]
Spraying is currently janky in general. Probably that.

**Comment by Zergspower** [comment]
Bug noted but related to spraying against objects on walls (lamps included) - simply move them a tile away and spray them and they work normally
