### ISSUE TITLE
Using a gun with telekinesis makes the bullets come from your body instead of the gun

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#10941]
## Testmerges: 
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10823: 'rev revert' by Gandalf2k15 at commit 58ec183702
#10486: '[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor' by Kapu1178 at commit 72a8b374ae
#10829: 'lobby camera' by jjpark-kb at commit b8cd1b76a9

## Reproduction:
Put a gun on the ground with the safety off
Have a BODY next to it
Use TK to hit the body with the gun, firing the gun at the body/person/other
Witness bullets MAGICALLY coming from your body instead of the gun which could even be on the other side of a window, doing not even SLIGHTLY what you expect it to do.

**Comment by Zergspower** [comment]
no longer able to fire weapons with TK, so I guess issue resolved?
