### ISSUE TITLE
Being Paraplegic stops you from getting skill chips inserted/removed.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10946]
Reporting client version: 514.1575

## Round ID:
4299

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)

**Comment by azrael-x86** [comment]
talked about it with some maintainers in tg, this is an issue with tgui. more info at your issue on tg
