### ISSUE TITLE
Chat filter seems broken. Not prompting users on if they can use "Cope" and other restricted words.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#10971]
Reporting client version: 514.1575

## Round ID:
4307

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)

**Comment by Zergspower** [comment]
Resolved in current version
