### ISSUE TITLE
"HELP AI ASORBING ME IN SAT"- Ai can, inexplicably, roll ling.

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#10997]
Reporting client version: 514.1575

## Round ID:
4318

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)

## Reproduction:
So, some details. had ling enabled in tator prefs, had myself on an alt job title. Nothing else of note.

as for an image
![image](https://user-images.githubusercontent.com/37010048/151081006-d88e7110-677b-4edd-9426-1a914d107867.png)

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/11016
