### ISSUE TITLE
Ai cryo don work.

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#10999]
Reporting client version: 514.1575

## Round ID:
4318

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)
- [[BOUNTY] For Christmas, a new Cyborg model! Cargo Cyborgs!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10232)

## Reproduction:
Use ai cryo feature, Ai job slot doesn't open up.

**Comment by Zergspower** [comment]
AI Cryo functional again
