### ISSUE TITLE
Writing on paper crashes the writing interface.

### ISSUE THREAD

**Issue by malleyeno** [Skyrat-SS13/Skyrat-TG#11048]
Reporting client version: 514.1575

## Round ID:
4333

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [lobby camera](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10829)
- [[MODULAR] Safeguard V3.0: Also known as Crewsimov](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10905)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)

## Reproduction:
Take any blank page, and try to write on it using a pen. On the page, click on Edit, then try to type. You will receive a blue screen for the page interface.

**Comment by tf-4** [comment]
Fix already open upstream

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/11095
