### ISSUE TITLE
Recent PR made mobs way too fast and also made projectiles sometimes fire twice on the same tick 

### ISSUE THREAD

**Issue by chizzyyyy** [Skyrat-SS13/Skyrat-TG#11057]
Reporting client version: 514.1568

## Round ID:
4336

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[SEMI-MODULAR] [CURSED AS FUCK] Client-Side input window & Typing Indicator refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486)
- [[MODULAR] Safeguard V3.0: Also known as Crewsimov](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10905)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [people will now cause dirt buildup](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11023)
- [Fixes protected roles getting antagonist](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11016)

## Reproduction:
The recent PR #10889 has made all of the mobs unbearably fast, able to easily catch up to you and kill you. This includes megafauna, xenos, etc. For some reason, sometimes shots are also fired twice in the same tick, such as that time when a xeno queen spat out 2 neurotoxin shots in 1 frame, or when spam shooting a KA at mobs, up to three of the "hitmarkers" show up, the chat even printing out that you shot twice.

**Comment by tf-4** [comment]
fix open upstream https://github.com/tgstation/tgstation/pull/64351
