### ISSUE TITLE
Taur shoes vanish on equip

### ISSUE THREAD

**Issue by kannthus** [Skyrat-SS13/Skyrat-TG#11074]
## Round ID:

N/A

## Reproduction:

Equiping shoes on-to a taur model, causes them to vanish from the HUD. (Nor change the model sprite). Merely puts shoes on with any of the taur models, for this example I used the Cybernetic Lizard

https://user-images.githubusercontent.com/32248891/151574687-54df3e70-2254-4753-a8e4-15d92829dae5.mp4

**Comment by Quill-Weave** [comment]
![image](https://user-images.githubusercontent.com/103809013/163690385-708000f8-e142-4540-93d8-0aede048c810.png)

Seems to work fine now!

**Comment by Zonespace27** [comment]
> ![image](https://user-images.githubusercontent.com/103809013/163690385-708000f8-e142-4540-93d8-0aede048c810.png)
> 
> Seems to work fine now!

i'm seeing some clipping with the sprite, mind making an issue report for that @Quill-Weave?
![image](https://user-images.githubusercontent.com/41448081/163690423-bad52e3c-b31d-4fca-b284-2ad68562946d.png)

**Comment by Quill-Weave** [comment]
Do you mean my tail? That's me using a normal tail w/a taur body attached.

Unless you mean the feeties, @Zonespace27 

I also tested it again as a Synthetic Lizardperson, just to be sure.

![image](https://user-images.githubusercontent.com/103809013/163690532-a991ac43-5bb1-4f0b-9430-ce63ef3d5752.png)

**Comment by Quill-Weave** [comment]
> > ![image](https://user-images.githubusercontent.com/103809013/163690385-708000f8-e142-4540-93d8-0aede048c810.png)
> > Seems to work fine now!
> 
> i'm seeing some clipping with the sprite, mind making an issue report for that @Quill-Weave? ![image](https://user-images.githubusercontent.com/41448081/163690423-bad52e3c-b31d-4fca-b284-2ad68562946d.png)

Report is here! #12831
