### ISSUE TITLE
Missing character creation things

### ISSUE THREAD

**Issue by SquidNeko** [Skyrat-SS13/Skyrat-tg#1109]
Hairstyle missing:
Long twintails

Polychromic Backpack missing.

Loadout items missing:
PAI Device
TTS Device

Comment to loadout:
All the Polychromic i used to use before is now all donator items. :c

Quirks missing:
Mute (Negative)
Allergic (Negative)
Flammable Skin (Negative)
Fist of steel (Positive)
Quick Step (Positive)

**Comment by StarHorder** [comment]
I didn't see monophobia on there, either

**Comment by Gandalf2k15** [comment]
This should have been addressed.
