### ISSUE TITLE
Random character slots won't let you change languages on characters.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#11108]
Reporting client version: 514.1575

## Round ID:
4359

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction: Went to change languages on a character. was not able to, I had points available.

Tried on new slot, that slow worked.

**Comment by Tastyfish** [comment]
Could be database corruption of some form since this appears to only happen with a portion of old character slots.

**Comment by Zergspower** [comment]
Resolved in current version
