### ISSUE TITLE
Blueshift teleporter room lacks lights and working shutters

### ISSUE THREAD

**Issue by Zonespace27** [Skyrat-SS13/Skyrat-TG#11124]
## Round ID: 4364

![image](https://user-images.githubusercontent.com/41448081/151684375-2ec9066b-4c4b-4d2e-a62b-8fcef41ea9fb.png)

## Reproduction:

1. Go to blueshift teleporter room
2. Flip the light switch
3. realize there are no lights in the room in the first place
4. Try and open the shutters in your pain
5. Realize the shutters don't open
6. scream into the void

**Comment by tf-4** [comment]
Isn't there a light directly in front of you in that screenshot? It's just broken.

**Comment by Zonespace27** [comment]
> Isn't there a light directly in front of you in that screenshot? It's just broken.

I am blind.

**Comment by GuiltyNeko** [comment]
In our defense, it's one light that's really hard to see in a room without any light in it, since it's just ONE light, and lights break on their own.
