### ISSUE TITLE
Blueshift Evac Has No Shuttle Roof

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#11125]
## Testmerges: #8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232
#10895: '[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs' by theOOZ at commit e3a6b5611c
#10823: 'rev revert' by Gandalf2k15 at commit 58ec183702
#10833: '[partially modular] advanced handcuff stuff' by jupyterkat at commit 488075f1c3

## Reproduction: 
>call the evac shuttle
>it comes depressurized
>look up
>there's no roof to keep the air in

**Comment by YakumoChen** [comment]
This is getting fixed upstream
https://github.com/tgstation/tgstation/pull/64493

**Comment by zeratino** [comment]
zamn!
