### ISSUE TITLE
Robotics Control Console doesn't list cyborgs

### ISSUE THREAD

**Issue by Proximitron** [Skyrat-SS13/Skyrat-TG#11209]
Reporting client version: 514.1575

## Round ID:
4390

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [rev revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[partially modular] advanced handcuff stuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10833)
- [[Semi-Modular] Synthetic Rebalance III: A Rope of Sand](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)

## Problem

Only cyborgs on the current level of the console can be reached
This is very supid expecially for Blueshift, as the ship has multiple levels.

## Reproduction:

Using the Robotics Control Console

**Comment by SpookyTheFox** [comment]
This is intentional to prevent making consoles off station and messing with the borgs. Similar with AI, if they are on the wrong Z level, they don't link new borgs, and their powers are capped to that Z level.
Where it's not working right, is multi-z. Which makes this an upstream issue as well.

**Comment by Proximitron** [comment]
I sort of guessed this was intentional, thank you for elaborating. What i meant is, that this should work over all z-levels of the same station. If the z-levels are only floors not dimensions or different "maps".

**Comment by Zergspower** [comment]
Resolved in current version
