### ISSUE TITLE
Interdyne vendors can be chosen for Rampant Brand Intelligence

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#11329]
## Testmerges:
n/a but it could be an issue with Icebox

## Reproduction:

as title
This can lead to the event being impossible to correctly resolve if there are no players on Interdyne (and is also a breach of immersion)

**Comment by tf-4** [comment]
```
/datum/round_event/brand_intelligence/start()
	for(var/obj/machinery/vending/V in GLOB.machines)
		if(!is_station_level(V.z))
			continue
		vendingMachines.Add(V)
```
Shouldn't be happening. Possibly icebox issue.

**Comment by YakumoChen** [comment]
Interdyne probably shouldn't spawn on the Middle Icebox level, only the Lower.

Building glass floors and finding Interdyne is pretty silly in its own right.

**Comment by tf-4** [comment]
Agreed

**Comment by Zergspower** [comment]
cant reproduce and havn't seen this happen in months
