### ISSUE TITLE
Unable to close jobslots created from events

### ISSUE THREAD

**Issue by kannthus** [Skyrat-SS13/Skyrat-TG#11332]
## Round ID:

4438

## Reproduction:

Job slots opened by the "Paperwork mishap" event are not able to be closed by the HoP, regardless of how much is overflowing the roles for example, here is the machine with my ID inside, I can open as many jobs as I'd like, but never close them, this is the fun aftereffect of 2 of these events in one shift.
![CleanShot 2022-02-07 at 02 08 53](https://user-images.githubusercontent.com/32248891/152714087-44490bfb-5879-4619-9a3c-cb833b782956.png)

To produce:
Run a "Paperwork mishap" event and notice how you are unable to close any of the overloaded jobs, cry while command shout at you for not fixing an unfixable issue.

**Comment by YakumoChen** [comment]
I think this is intentional.

**Comment by kannthus** [comment]
> I think this is intentional.

Thats unfortunate if so, but at the same time you are not able to close any jobs slots _you_ open either. The close button seems to be entirely dysfunctional. I was also under the impression the event was designed so the HoP has to close the slots, especially since they have 30s between each slot closed/opened (being the balance to it)

**Comment by ghost** [comment]
Not intentional, you're supposed to be unable to close jobs and put them BELOW the set limit; you're indeed meant to be able to close any excess, such as those caused by the paperwork event.

**Comment by YakumoChen** [comment]
The 30 second job slot cooldown has existed for far longer than the rework of this event. The raising the min cap of jobs as part of the event (preventing it closing) is also supposedly intended, but I cannot find where it was PR'd to change the behavior of the event. The event as I know it is supposed to close the Assistant job slot and replace it with another, removing this takes the teeth out of the event.

**Comment by Zergspower** [comment]
Feature rather than a bug as it's a paperwork mishap from CC rather than something stationside causing it (meaning they send you the crew)

**Comment by kannthus** [comment]
> Feature rather than a bug as it's a paperwork mishap from CC rather than something stationside causing it (meaning they send you the crew)

That may be true, but also you can't close slots under _any_ conditions, even ones you open yourself
