### ISSUE TITLE
Borer eggs can't be orbited

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#11364]
## Testmerges:

[#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit 9da9168232](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
[#10895: '[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs' by theOOZ at commit a8f7ae1049](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#10821: '[Semi-Modular] Synthetic Rebalance III: A Rope of Sand' by Nerev4r at commit cfe5e213f2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)
[#11253: 'Xenoarch base' by jjpark-kb at commit 095cafbcbd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11253)
[#11270: 'Event voting system, prelude to event planner' by Gandalf2k15 at commit d768db0883](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11270)
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11334: '[SEMI-MODULAR] Makes security record photo generation not happen all at once' by monster860 at commit 90893f7e21](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11334)

## Reproduction:

be ghost
borer egg in ghost spawn list and on orbit menu
clicking jump does nothing, attempting to orbit does nothing

**Comment by Zergspower** [comment]
Resolved in current version, acting as designed
