### ISSUE TITLE
Teleporter hub in space ruin not able to be entered

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#11378]
Reporting client version: 514.1569

## Round ID:
4454

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[MIRROR] Tgui input hotfix [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11333)

**Comment by YakumoChen** [comment]
did you properly link the hub with the teleporter unit? You have to do some tooling sometimes with teleporters to make them link.

**Comment by Zergspower** [comment]
confirmed bug exists, rebuilt on ship and still would not let me walk into it. Built it just outside the ship and it worked - assuming some sort of protection is in place

**Comment by Zergspower** [comment]
https://github.com/tgstation/tgstation/pull/74991
