### ISSUE TITLE
Event voter (admin) and random events both roll.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#11410]
Reporting client version: 514.1575

## Round ID:
4463

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[Semi-Modular] Synthetic Rebalance III: A Rope of Sand](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)
- [Xenoarch base](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11253)
- [Event voting system, prelude to event planner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11270)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Black Mesa Source Vox #2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11393)
- [Revert "[MIRROR] Adds moveloop bucketing, uses queues for the singulo rather then sleeps [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11398)

**Comment by Zergspower** [comment]
TM concluded, closing this out
