### ISSUE TITLE
Abductor spawns (probably other ghost spawns) are scuffed

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#11435]
## Issue:
Abductors spawn in with whatever animal parts your currently selected character slot comes with. For example, my catgirl character (aka all of them) selected gives the abductor spawn ears and a tail.
Also the disguise vest didn't work at first and fixing it caused abductor tongues to break.

I've also heard that similar issues happen when spawning as ash lizards and likely other ghost roles that change your race from off-human

Related: #10426

## Round ID:
447x I can't remember but its easy to reproduce

## Testmerges:

Mob parts issue

## Reproduction:
Spawn some abductors

**Comment by Zergspower** [comment]
Resolved in current version

**Comment by YakumoChen** [comment]
@Zergspower not resolved
