### ISSUE TITLE
Sentient disease infecting people on interlink while disease is on station?

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#11480]
Reporting client version: 514.1575

## Round ID:
4491

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[Semi-Modular] Synthetic Rebalance III: A Rope of Sand](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)
- [Xenoarch base](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11253)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Revert "[MIRROR] Adds moveloop bucketing, uses queues for the singulo rather then sleeps [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11398)

**Comment by Zergspower** [comment]
This was unintentional and handled at the OOC level
