### ISSUE TITLE
New Chaplains Cannot Select a New Sect

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#11525]
Reporting client version: 514.1575

## Round ID:
4515

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0.5] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[Semi-Modular] Synthetic Rebalance III: A Rope of Sand](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

## Reproduction: When joining the round as a Chaplain, if a previous one has cryo'd, you cannot select your own Sect (if none has been chosen). You also do not spawn spawn with your original bible, nor the religion you created. 
![image](https://user-images.githubusercontent.com/71103211/154159919-10f9ae1e-b142-4de6-8aca-873850741820.png)
![image](https://user-images.githubusercontent.com/71103211/154159955-50c3abed-126f-4523-8617-ee3c27fd2062.png)
![image](https://user-images.githubusercontent.com/71103211/154159992-2e9fb573-dc64-4021-ab24-60239861ae2b.png)

**Comment by malleyeno** [comment]
I managed to reproduce the issue on a test environment of current master branch.

![image](https://user-images.githubusercontent.com/47365670/154834967-9227b706-cbfc-4792-9712-97bb22dd9f42.png)
![image](https://user-images.githubusercontent.com/47365670/154834973-770090fc-1206-4f60-91dc-b665122879c0.png)
![image](https://user-images.githubusercontent.com/47365670/154834991-0199a191-4b9c-4309-9a65-dd5469cfabe5.png)
