### ISSUE TITLE
orbiting animation bugs

### ISSUE THREAD

**Issue by azrael-x86** [Skyrat-SS13/Skyrat-TG#11547]
reporting client version 514.1571
## Round ID:
4524

## Testmerges:

[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11509: 'Heretic Buffs, the Rebuffening' by SpaceVampire at commit d381ec3674](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)

## Reproduction:

orbit a player, double click another player to orbit to them and move around. you can now move around whilst still in the orbit animation.

![Capture](https://user-images.githubusercontent.com/88991542/154370239-d69dd2b3-b586-4aa2-afb0-7629785a97d6.PNG)

**Comment by jjpark-kb** [comment]
this should have been fixed in a recent mirror PR
