### ISSUE TITLE
Ranged Armor Does not Work

### ISSUE THREAD

**Issue by MassacreDemigirl** [Skyrat-SS13/Skyrat-TG#11544]
**Ranged Armor Does not Work**

## Testmerges:
![image](https://user-images.githubusercontent.com/25566633/154360939-74768948-db00-46eb-a1d8-6896edf64f4c.png)

## Reproduction:
Literally any armor against any ranged type of attack does not protect

**Comment by KathrinBailey** [comment]
it's all been known about now
