### ISSUE TITLE
Latex Gloves leave prints (I was previously told they were the ones that Didn't on Skyrat. Please disregard)

### ISSUE THREAD

**Issue by CMDR-Gungnir** [Skyrat-SS13/Skyrat-TG#11557]
Reporting client version: 514.1568

## Round ID:
4529

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
(Probably irrelevant)

## Reproduction:
Step 1) Wear Latex Gloves
Step 2) Touch a bunch of stuff
Step 3) See prints left behind when you scan 'em.

Now, most of my experience comes from TG proper, where latex are supposed to leave prints behind and your standard Black Gloves don't. But ever since I've bene playing here, I've always been told it's different here, and latex are the ones that leave no prints, and your standard Detective Gear Black Gloves DO leave them.

If I'm wrong, or it's no longer supposed to be the case, then ignore this. But when I ahelped to ask if it was changed or something, they suggested making an Issue Report anyway.

**Comment by kannthus** [comment]
> If I'm wrong, or it's no longer supposed to be the case, then ignore this. But when I ahelped to ask if it was changed or something, they suggested making an Issue Report anyway.

Peoples knowledge or opinion on this matter are quite different from person-to-person, but you are definitely right in your assumption:

![CleanShot 2022-02-19 at 01 03 45](https://user-images.githubusercontent.com/32248891/154779645-b3d21414-83d6-4804-90b3-88a8e16cb552.png)

The only gloves **With** print transmission are
- /gloves/cut - Fingerless insulated gloves
- /gloves/fingerless - Fingerless gloves
- /gloves/color/latex - Latex gloves
- /gloves/bracer - Bone bracers
- /gloves/rapid - Gloves of the North Star
- /gloves/tackler - Gripper gloves (and **all** its subtypes)
- /gloves/ring - All "Rings" and its subtypes (for obvious reasons)

**Comment by YakumoChen** [comment]
There is a lot of misinformation thrown around on the discord. It's much more reliable to check the code.

If this bug is resolved, you may press the close button on the bottom to resolve the issue.

**Comment by CMDR-Gungnir** [comment]
Oh- I didn't realize I could do that myself, sorry. I'll click the button for that now.
