### ISSUE TITLE
Can't use hotkey to drop items in left hand.

### ISSUE THREAD

**Issue by MaxwellB23** [Skyrat-SS13/Skyrat-TG#11587]
Reporting client version: 514.1578

## Round ID:
4540

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [Adds Tailoring to the Barber job. Reworks Barber haircuts. New uniform for the Barber to replace codersprites.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11503)

## Reproduction:

Whenever I try to use the hotkey "Q" to drop something in my left hand, I cannot. The drop button still works, as does the hotkey with the right hand.

**Comment by kannthus** [comment]
Are you playing a Synthetic character by any chance? As if so it is likely related to this: 

https://github.com/Skyrat-SS13/Skyrat-tg/issues/11589

**Comment by Zergspower** [comment]
Fixed in a PR thankfully
