### ISSUE TITLE
Trying to drop an item in the left hand as a synthetic does not work.

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-TG#11589]
Reporting client version: 514.1578

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [Adds Tailoring to the Barber job. Reworks Barber haircuts. New uniform for the Barber to replace codersprites.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11503)

## Reproduction:

Spawn as a synthetic and pick up anything in your left hand, trying to drop it with the keyboard shortcut will not work. Of note, the left hand is the same hand used for the charging cord which also uses the drop function to unequip the implant.

**Comment by kannthus** [comment]
Managed to replicate this, I'd agree its most likely related to the charging cord

**Comment by Zergspower** [comment]
someone borked with implants and broke us beepers, thankfully it has been fixed.
