### ISSUE TITLE
Borg CI overlay turns off when you say anything.

### ISSUE THREAD

**Issue by nikothedude** [Skyrat-SS13/Skyrat-TG#11677]
## Testmerges:
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11509: 'Heretic Buffs, the Rebuffening' by SpaceVampire at commit 76c81bd3c6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
[#11638: 'Fixes projectiles ignoring armor' by SpaceVampire at commit 98be6ec98c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11638)

## Reproduction:
Step 1: Pop CI as a borg.
Step 2: Press T.
Step 3: Press enter.
The CI overlay vanishes despite CI being enabled.

**Comment by Zergspower** [comment]
This specific issue resolved but CI in another fashion is not
