### ISSUE TITLE
Unable to create statues of Tallborgs

### ISSUE THREAD

**Issue by MaxwellB23** [Skyrat-SS13/Skyrat-TG#11691]
Reporting client version: 514.1578

## Round ID:
4574

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [Fixes projectiles ignoring armor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11638)

## Reproduction:

It is impossible to make a statue of cyborgs that have the tallborg chassis type. Reproduce by attempting to select a tallborg cyborg as the subject for a carving block.

**Comment by Zonespace27** [comment]
Not a bug.
