### ISSUE TITLE
BlackMarket Chevvy ship unable to be used. Warning: Shuttle connection severed!

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#11710]
Reporting client version: 514.1575

## Round ID:
4588

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [Fixes projectiles ignoring armor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11638)
- [Adds Tailoring to the Barber job. Reworks Barber haircuts. New uniform for the Barber to replace codersprites.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11503)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

**Comment by Zergspower** [comment]
related to the Chevvy update - though it has been since resolved
