### ISSUE TITLE
Character creation is EXTREMELY broken

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#11758]
-Use Skintones does not work for genitals / boobs
-Quirks system broken, making new characters will try and transfer quirk balance and break, possibly leaving you with a bunch of invisible quirks and a broken quirk balance.
-There is no way to reset quirk balance
-Language learning is broken, you can't add or subtract languages

**Comment by Zonespace27** [comment]
Please add steps for reproduction; currently can't reproduce any of these

**Comment by YakumoChen** [comment]
@Zonespace27 
Quirks bug is:
When opening a new character slot (as in, selecting any slot named "Character x") it will first attempt to partially port the currently selected character file, including quirks, preferences etc
Deleted quirks are not removed from character saves, if a new character is made from a character with a deleted quirk, the quirks list will break on "port", turning all quirks invisible and maintaining the quirk balance. Spawning in still gave me all the original quirks. Since they're invisible you aren't able to delete positive quirks. The character I had ported from had all 6 positive quirk slots used.

**Comment by YakumoChen** [comment]
Languages:
I am unable to add or subtract known languages from any of my characters, period.

**Comment by YakumoChen** [comment]
Skintones
I only play human and felinid characters. Selecting breasts or genitalia will give the current colour selected for the part. Enabling the "use skintones" option changes the hue of the colour slightly but said parts remain non-skintone.

**Comment by YakumoChen** [comment]
@Zonespace27 the language issue turns out to be identical to the quirk thing, I have "phantom languages" that cannot be reset and take up points.

**Comment by Zergspower** [comment]
Resolved in current version
