### ISSUE TITLE
The Ghoul Species is Broken :(

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#11755]
## Testmerges:[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11509: 'Heretic Buffs, the Rebuffening' by SpaceVampire at commit 76c81bd3c6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
[#11638: 'Fixes projectiles ignoring armor' by SpaceVampire at commit 98be6ec98c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11638)
[#10346: '[NON-MODULAR]Fixes corrupt photo records' by nevimer at commit 7534a9947a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction: Pick the ghoul species.
![image](https://user-images.githubusercontent.com/71103211/155830525-a40825d2-80d6-428e-a1a4-d168aaaa3802.png)

**Comment by theselfish** [comment]
I'm guessing this is an issue related to #12497

**Comment by ghost** [comment]
Is this species even still in game?

**Comment by vinylspiders** [comment]
> Is this species even still in game?

Yes and it looks like this has been fixed. 
![image](https://user-images.githubusercontent.com/13398309/217737103-dd22e349-3df2-4702-ab0f-f1d73bb85b33.png)

**Comment by vinylspiders** [comment]
@lessthnthree fixed

**Comment by vinylspiders** [comment]
@Jolly-66 this one too! ghouls work now
