### ISSUE TITLE
Shibari ropes not working as intended.

### ISSUE THREAD

**Issue by Peppercornzz** [Skyrat-SS13/Skyrat-TG#11778]
## Reproduction: It is currently impossible to obtain the shibari-groin-covering underwear item, either through the underwear choice menu, in character creation, or by tying someone's groin with shibari ropes.

Step 1: Get Shibari ropes, and target the groin.
Step 2: Click on someone.
Step 3: Nothing happens, after it gives the proper chat span about you are tying someone.

I have tried it wearing no underwear, wearing full clothing, etcetera. None of it works.

**Comment by Peppercornzz** [comment]
After further testing, it seems this is only an issue with people for certain sets of genitals.

**Comment by Zonespace27** [comment]
> After further testing, it seems this is only an issue with people for certain sets of genitals.

Which ones?

**Comment by Zergspower** [comment]
marking this closed if nothing comes up from this, tried ropes and it worked on male and female

**Comment by Zonespace27** [comment]
If the issue is found out or defined in the future, reopen this
