### ISSUE TITLE
Rainbow extract reaction makes Clusterbang Segments

### ISSUE THREAD

**Issue by Trigillass** [Skyrat-SS13/Skyrat-TG#11811]
## Round ID: 
4631

## Testmerges:
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11509: 'Heretic Buffs, the Rebuffening' by SpaceVampire at commit 76c81bd3c6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
[#10346: '[NON-MODULAR]Fixes corrupt photo records' by nevimer at commit 7534a9947a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#11646: '[Modular] Separates Prog. traitor balancing' by theOOZ at commit 27c0d19d39](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11646)
[#11793: '[DNM] [TM-Only] Revert "The Impact Soundening"' by GoldenAlpharex at commit 58f679b04d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11793)

## Reproduction:
When adding 5 units of Plasma to Rainbow Slime Extract, the reaction will create Clusterbang Segments along with random slime extracts. A single Clusterbang Segment is guaranteed per each individual reaction and the Clusterbangs are fully functional. The Plasma reaction below 5 units still works as intended.

**Comment by Zergspower** [comment]
seems like it was resolved as i cant replicate this
