### ISSUE TITLE
Anthromorph Insect digitgrade sprites are plantigrade

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat-TG#11839]
This is #8353, Ozzo did a thing but yeah _sob._
Anthromorphic Insects digitgrade legs are m̶i̶s̶s̶i̶n̶g̶ ̶t̶h̶e̶i̶r̶ ̶s̶p̶r̶i̶t̶e̶s̶.̶ ̶!̶  (this was meant to be crossed out) **They are plantigrade now** 

## Reproduction:

Make a Anthromorphic Insect and give them Digitgrade legs. B̶e̶t̶t̶e̶r̶ ̶g̶e̶t̶ ̶a̶ ̶w̶h̶e̶e̶l̶c̶h̶a̶i̶r̶!̶ (this too)  its plantigrade.

**Comment by nevimer** [comment]
Yeah. The sprites don't exist. We can copy another species sprites over, to fill the void.

**Comment by Zergspower** [comment]
Resolved in current version
