### ISSUE TITLE
Ashwalkers cannot use blowguns

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-TG#11865]
Reporting client version: 514.1578

While normally an ashwalker can't get their hands on bamboo very easily the fact that they can't use one of the quintisential tribal ranged weapons seems a bit iffy.

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [production/fishing skills, forge/ceramics/glassblow cleanup](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11795)

## Reproduction:

Spawn as an Ashwalker, use bamboo cuttings to make a blowgun and syringe, cry when you realize you can't reenact the beginning of Raiders of the Lost Ark against the miners

**Comment by Zonespace27** [comment]
Fixed by #11918
