### ISSUE TITLE
Station Bounced Radio - Not working

### ISSUE THREAD

**Issue by Cheeritup** [Skyrat-SS13/Skyrat-TG#11898]
## Round ID:
This happens a almost every round, rarely working

## Reproduction:
Set the frequency to a custom one, I use the lowest possible, unmute the sounds and mic and try to speak to it

**Comment by Zergspower** [comment]
Confirmed with an asterisk - I can do custom channels but some I cannot - this may be a feature

**Comment by Zergspower** [comment]
Resolved in current version
