### ISSUE TITLE
Command, Sec, Guards rolling antag.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#11942]
Reporting client version: 514.1575

## Round ID:
4686

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [production/fishing skills, forge/ceramics/glassblow cleanup](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11795)

**Comment by IsaacTheSharkWolf** [comment]
to be honest this does sound kinda fun, though security, bs , cap and rep probably shouldn't roll antag

**Comment by theselfish** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12246 Most likely fixed this.

**Comment by GoldenAlpharex** [comment]
This was fixed, and I'm glad it has been.
