### ISSUE TITLE
Parvise bug

### ISSUE THREAD

**Issue by EverothB** [Skyrat-SS13/Skyrat-TG#11972]
Reporting client version: 514.1557

## Round ID:
4699

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [production/fishing skills, forge/ceramics/glassblow cleanup](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11795)

## Reproduction:

I was forging with the new updates and I was checking what everything new did and how it worked. When I forged a Parvise shield, (The big two handed shield) it looked alright on the floor, it had no issues when holding it, but when I tried to put it on my back it worked and it showed like a big blob made out of pink and black squares as if it was missing textures, easy to reproduce. 
https://ibb.co/pht982J

Yes it works like normal, i took it off and back on again it still bugged, even when I reconnected it looked the same.

**Comment by YakumoChen** [comment]
It needs an onmob sprite assigned to it, easy fix
