### ISSUE TITLE
Xenobiological Slime Hybrids have body emissive on by default, with no visible option to turn off.

### ISSUE THREAD

**Issue by dekunutkid** [Skyrat-SS13/Skyrat-TG#11986]
## Round ID:
4711 at the time of writing, however issue has persisted for many rounds more.

## Testmerges: 
#11135 
#11509 
#10346 
#10823 
#11795

## Reproduction:
Create a xenobiological slime hybrid.
With no changes whatsoever, play as said slime hybrid.
Go into the darkness.
Watch as your body, and only your body, lights up for no reason in particular.
Images provided in order to quell any doubts of my fault.
![image](https://user-images.githubusercontent.com/43183074/157598178-402d27f3-573a-4ef8-a60a-1d8ee4d7345a.png)
![image](https://user-images.githubusercontent.com/43183074/157598190-d9a8a1d6-dd50-490b-9ce4-29325a11f7d1.png)
![image](https://user-images.githubusercontent.com/43183074/157598199-357c9f79-2523-4f5e-937a-2c5ce86fb97b.png)
![image](https://user-images.githubusercontent.com/43183074/157598212-89a57c25-b098-461c-bb8b-f12ef33044f4.png)
![image](https://user-images.githubusercontent.com/43183074/157598322-48d1f768-c15f-461b-8692-6db01eb6b4e5.png)

**Comment by YakumoChen** [comment]
Did you load the character while having a slot selected that did have emissives?

**Comment by dekunutkid** [comment]
> Did you load the character while having a slot selected that did have emissives?

No, none of my characters have emissives.

**Comment by YakumoChen** [comment]
It sounds intended but I cannot find any code supporting it

**Comment by dekunutkid** [comment]
> It sounds intended but I cannot find any code supporting it

Is there anything related to skin emissives? I'm not sure it's even an option, i've not seen anyone else with it to my knowledge.
