### ISSUE TITLE
Stasis beds do not prevent Live Surgery negative moodlet.

### ISSUE THREAD

**Issue by malleyeno** [Skyrat-SS13/Skyrat-TG#12045]
Reporting client version: 514.1575

## Round ID:
4736

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [Heretic Buffs, the Rebuffening](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[TM-ONLY] Disables speech circuit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)

## Reproduction:

Buckle a conscious patient into a stasis bed without anesthetic and perform brute fixing surgery on them. The patient will experience the negative moodlet for Live Surgery. 

(Note: This issue was not discovered by me, Andrani Evailos from this round ID experienced this.)
Adminhelps exchanged while this was being discovered suggest that this is not intended behaviour. Stasis beds should stop the moodlet as the beds stop time for patients, assuming they were properly buckled. Player experiencing issue confirmed from logs that they were buckled in while being operated upon.

**Comment by YakumoChen** [comment]
This is intended. On stasis you are conscious, it does not "freeze time", it just stops life ticks and numbs you.

**Comment by malleyeno** [comment]
Closing issue based on @YakumoChen's reply being accurate. 

Confirmed with testing that there are two levels of negative moodlets based on whether a patient is operated upon without numbing and with numbing, as [generic_negative_events.dm](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/datums/mood_events/generic_negative_events.dm) shows.
```
//SKYRAT EDIT START: Mainly surgery for now.
/datum/mood_event/mild_surgery
	description = "<span class='warning'>Even if I couldn't feel most of it, it feels wrong being awake while somebody works on your body. Ugh!</span>\n"
	mood_change = -1
	timeout = 5 MINUTES

/datum/mood_event/severe_surgery
	description = "<span class='boldwarning'>Wait, THEY CUT ME OPEN - AND I FELT EVERY SECOND OF IT!</span>\n"
	mood_change = -4
	timeout = 15 MINUTES

/datum/mood_event/robot_surgery
	description = "<span class='warning'>Having my robotic parts messed with while I was conscious felt wrong... if only I had a sleep mode!</span>\n"
	mood_change = -4
	timeout = 10 MINUTES
//SKYRAT EDIT END
```

[surgery_step.dm](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/modules/surgery/surgery_step.dm) demonstrates that the numbed trait is important for surgery mood since it can give the "mild_surgery" mood event.
```
/datum/surgery_step/proc/display_pain(mob/living/target, pain_message, mechanical_surgery = FALSE)
	if(target.stat >= UNCONSCIOUS) //the unconscious do not worry about pain
		return
	if(HAS_TRAIT(target, TRAIT_NUMBED)) //numbing helps but is not perfect - this is the tradeoff for being awake
		SEND_SIGNAL(target, COMSIG_ADD_MOOD_EVENT, "mild_surgery", /datum/mood_event/mild_surgery)
		return
	if(mechanical_surgery == TRUE) //robots can't benefit from numbing agents like most but have no reason not to sleep - their debuff falls in-between
		SEND_SIGNAL(target, COMSIG_ADD_MOOD_EVENT, "robot_surgery", /datum/mood_event/robot_surgery)
		return
	to_chat(target, span_userdanger(pain_message))
	SEND_SIGNAL(target, COMSIG_ADD_MOOD_EVENT, "severe_surgery", /datum/mood_event/severe_surgery)
```

Looking at [debuffs.dm](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/datums/status_effects/debuffs.dm), we can see that being put in stasis applies the numbed trait.
```
/datum/status_effect/grouped/stasis/on_apply()
	...
	ADD_TRAIT(owner, TRAIT_NUMBED, "stasis") //SKYRAT EDIT START - STASIS APPLIES NUMBING
	owner.throw_alert("numbed", /atom/movable/screen/alert/numbed) //SKYRAT EDIT END
```
