### ISSUE TITLE
Ghost Role Spawners Broke (Hard)

### ISSUE THREAD

**Issue by Ruediger4** [Skyrat-SS13/Skyrat-TG#12067]
## Testmerges:
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#11509: 'Heretic Buffs, the Rebuffening' by SpaceVampire at commit 76c81bd3c6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11509)
[#10346: '[NON-MODULAR]Fixes corrupt photo records' by nevimer at commit 7534a9947a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#12024: '[TM-ONLY] Disables speech circuit' by Zonespace27 at commit e04f6bac4d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
[#11860: '[HOST] [MODULAR] New character customization option, Headshots.' by Zonespace27 at commit 4e19938a77](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)

## Reproduction:
Bro just try to use ghost role spawners as anything but humans.
You can't spawn.
Door stuck.
![image](https://user-images.githubusercontent.com/57809136/158089037-f114faa6-925f-491e-8f98-dbca2f6578df.png)
This applies to **every** ghost role - Syndicate, PT, any ghost role. EVEN GOLEM SHELLS.

**Comment by Zonespace27** [comment]
Should be resolved now.
