### ISSUE TITLE
Prior link between Free Golem ORM and Station ORM leads to issues

### ISSUE THREAD

**Issue by EvilCrimsonWitch** [Skyrat-SS13/Skyrat-TG#12096]
Reporting client version: 514.1575

## Round ID:
4758

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[TM-ONLY] Disables speech circuit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)

## Reproduction:
So, a previous bug that has recently had its former issues closed has once again popped up. On Ice Box, as a free golem, for some reason the ORM begins linked to the stations silo. As a result Golems can pull all of stations resources if they so wanted, but most importantly, when building their own silo and linking it, it essentially removes their access to any materials they've previously placed inside. This leads to them either having to withdraw a large amount prior to linking, which may either cause some greed in digging into the stations resources or even taking each and every one of them, invalidating any work done by station shaft miners, or with the golems losing out on every single piece of ore they've deposited previously to get enough points to buy the liberators legacy.

Recreation should be easy, depending on what z level the golem ship starts on. 

Previously referenced in these issues: https://github.com/Skyrat-SS13/Skyrat-tg/issues/1881 and https://github.com/Skyrat-SS13/Skyrat-tg/issues/2929 so I'm a little disappointed to see them both closed. Whatever the case, it seems a prior link between the Golem's ORM and the stations is the cause, leading to both factions sharing the same pool of resources.

**Comment by Zergspower** [comment]
Odd - it was just tested - running a local server on the current branch replicated the issue - this should be a simple mapping fix

**Comment by Zergspower** [comment]
https://github.com/tgstation/tgstation/pull/65512 tossed it upstream

**Comment by Zergspower** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12149

**Comment by Zonespace27** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12149
