### ISSUE TITLE
Plasmaman race lacks gender options

### ISSUE THREAD

**Issue by EvilCrimsonWitch** [Skyrat-SS13/Skyrat-TG#12123]
Reporting client version: 514.1575

## Round ID:
4766

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[TM-ONLY] Disables speech circuit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [[SEMI-MODULAR] Medical Smartdarts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)

## Reproduction:
In character preferences, after selecting the Plasmaman race, the button to choose your characters gender from Male, Female or Other isn't available. I believe it defaults to the last selected gender of the character in that slot/the last gender chosen on a different race, as without the option, I spawned into the round with a female gender given all my equipment was prefixed wit 'She is' or 'She has'. 

I imagine this isn't intentional, as lacking the choice to change your gender or not being fixed into a 'They' option seems buggy.

**Comment by Zergspower** [comment]
Confirmed no gender option in the current build

**Comment by Zonespace27** [comment]
Intentional.

**Comment by Zonespace27** [comment]
small correction: plasmamen being forced to be "they" is intentional, not getting the "they" prefix isn't

**Comment by malleyeno** [comment]
Bug reproduced with testing. Plasmamen keep the pronouns of the last character to use the slot, including she/her and he/him.

I'm going to run through this and see if I can find where it happens. But for right now, a workaround would probably be to change the gender of a new character in a slot to Nonbinary, then select the Plasmamen race.

**Comment by malleyeno** [comment]
After stepping through the call stack bit by bit, I believe the part causing issue is in [gender.dm](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/modules/client/preferences/gender.dm). I have tried explicitly declaring gender in the Plasmamen species code as well as giving them the AGENDER species trait, but both get overwritten by character preferences. 

It could be possible to fix this issue by adding a species check to the gender.dm file. However, PR https://github.com/Skyrat-SS13/Skyrat-tg/pull/9884 did something similar and was reverted. This PR reverts code that would have required all species with Sexes=0/False (which plasmamen fall under) to use the Plural gender (which uses they/them on examines). On this revert, @GoldenAlpharex commented:

> We have genders available all the time, I'm not going to keep people from changing their gender if they want to.

This comment seems to suggest that gender selection should always be an available option. I am not sure on how to best proceed on my PR, so I am hoping I can get clarification on this.

**Comment by GoldenAlpharex** [comment]
> After stepping through the call stack bit by bit, I believe the part causing issue is in [gender.dm](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/modules/client/preferences/gender.dm). I have tried explicitly declaring gender in the Plasmamen species code as well as giving them the AGENDER species trait, but both get overwritten by character preferences.
> 
> It could be possible to fix this issue by adding a species check to the gender.dm file. However, PR #9884 did something similar and was reverted. This PR reverts code that would have required all species with Sexes=0/False (which plasmamen fall under) to use the Plural gender (which uses they/them on examines). On this revert, @GoldenAlpharex commented:
> 
> > We have genders available all the time, I'm not going to keep people from changing their gender if they want to.
> 
> This comment seems to suggest that gender selection should always be an available option. I am not sure on how to best proceed on my PR, so I am hoping I can get clarification on this.

This might very well be true, basically the genders *should* only matter for the sake of the `he, she, they`, if they can't set that, then that's unintended and would need to be fixed.

**Comment by tf-4** [comment]
Seeing as this was PR'd as a change and closed I think this is resolved.
