### ISSUE TITLE
Calling return as a bluespace tech with a synth character leaves battery 

### ISSUE THREAD

**Issue by MissFox0810** [Skyrat-SS13/Skyrat-tg#1215]
Issue reported from  Round ID: [65](https://scrubby.melonmesa.com/round/65) (/TG/ Skyrat 13)

Reporting client version: 513.1532

When calling return while bluespace tech as a synth. leaves behind a standard battery.
![image](https://user-images.githubusercontent.com/4310446/95524266-33fd8680-09d1-11eb-99df-c235b1fd744e.png)

**Comment by LimblessLayabout** [comment]
In this weekend's test, discovered that any randomized character (human, mammal, etc) generated by the bluespace tech spawn also leaves batteries upon Return. Which is cute but weird.

**Comment by unit0016** [comment]
It's not the synthchar that's the problem, it's the tablet computer in the BST's bag. Same happens if you cryo with a tablet, or are otherwise nuked with one in your inventory.
It's an upstream issue.

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/8145
