### ISSUE TITLE
Cyborg CI disappearing when damaged

### ISSUE THREAD

**Issue by Reco201** [Skyrat-SS13/Skyrat-TG#12170]
## Testmerges:
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#10346: '[NON-MODULAR]Fixes corrupt photo records' by nevimer at commit 7534a9947a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#11860: '[HOST] [MODULAR] New character customization option, Headshots.' by Zonespace27 at commit 9af030c5cb](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
[#11836: '[SEMI-MODULAR] Medical Smartdarts' by softcerv at commit 79fba5f40a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)
[#12126: 'Assault Operatives' by Gandalf2k15 at commit b3812768b2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12126)

## Reproduction:
Become cyborg
Activate combat indicator
Take damage or damage self

Ci disappears on cyborgs once damage is taken

**Comment by tf-4** [comment]
Is this still an issue?

**Comment by Reco201** [comment]
> Is this still an issue?

Yes its still a issue its not just damage seems to be whenever the sprite updates, will grab a list when I test.

**Comment by Reco201** [comment]
> 
Turning cyborg lights on/off 
Taking damage
Getting stunned 

All cause ci to dissapear
