### ISSUE TITLE
CharPrefs bug with Assistant deselection

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#12172]
## Bug
Turning Assistant to "Yes" will de-prioritize any other position, as Assistant is a YES or NO option.
If you attempt to re-prioritize a non-assistant job, however, it does not change Assistant to NO

## Expected Behavior:
Assistant should set to NO if you have any other job set to HIGH.
If I set HoS/MD/whatever to high I should not be spawning as an Assistant instead unless I have no other jobs set and the option enabled to force assistant if I didn't get my job selections. (I had mine to return me to the lobby if I didn't get my job choices)

## Reproduction:
Turn Assistant to YES
Watch as your highest priority job becomes Medium priority
Change that job back to High
Assistant stays YES, roundstart spawn still makes you Assistant.

**Comment by Tastyfish** [comment]
Upstream bug
