### ISSUE TITLE
[Bug] Zone error on IceBox

### ISSUE THREAD

**Issue by twilightwanderer** [Skyrat-SS13/Skyrat-TG#12206]
## Reproduction:

The station broke away from the planetoid and flew off to walk in space. 

![изображение](https://user-images.githubusercontent.com/88540658/159237457-edff54f5-9f34-4426-b63f-a0aa7654df71.png)
![изображение](https://user-images.githubusercontent.com/88540658/159237492-a862425e-ac6b-4893-94e6-27bd566da1cd.png)
![изображение](https://user-images.githubusercontent.com/88540658/159237522-2dbf61af-3536-4c88-85a5-537c3ae23530.png)

**Comment by Zergspower** [comment]
See you space cowboy

**Comment by Zonespace27** [comment]
Any reproduction steps?

**Comment by Jolly-66** [comment]
Since this is from March (while having numerous map resets since then) and I don't think anyone has seen/reported issues, I'll be closing this.
