### ISSUE TITLE
GPSes in space are automatically set to 'off'

### ISSUE THREAD

**Issue by weesnaw-ops** [Skyrat-SS13/Skyrat-TG#12218]
Round ID: 4825

Reproduction:
Go to any space ruins and look at their GPS's.

They are all automatically set to 'off' and cannot be found unless you.. find them. This doesn't seem intentional given the merges.

**Comment by SpaceVampire** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12260

Fixed.
