### ISSUE TITLE
Digitigrade Legs causing Suit-Layer sprite issues.

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#12244]
## Round ID: 
4839

## Testmerges:
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
[#10346: '[NON-MODULAR]Fixes corrupt photo records' by nevimer at commit 7534a9947a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#11860: '[HOST] [MODULAR] New character customization option, Headshots.' by Zonespace27 at commit 9af030c5cb](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
[#11836: '[SEMI-MODULAR] Medical Smartdarts' by softcerv at commit 7aad97cb4d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)
[#12126: 'Assault Operatives' by Gandalf2k15 at commit 710b46bb62](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12126)
[#12169: '[Semi-Modular] Oversized Overhaul (Overrated!)' by Nerev4r at commit 5a6d9af921](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12169)
[#11707: '[MODULAR] Overhauls how we handle taur sprites, adds a few pre-existing taur sprites to suits, and also a few new ones' by nikothedude at commit 0506b48a69](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11707)

## Reproduction:

Currently certain suit sprites are coming up with the placeholder suit-text sprite for species with Digitigrade legs.  Certain armor vests, jacket-type clothing and the ponchoes are nonfunctional in this manner.

Picture as evidence, character with digitigrade legs trying to wear the Red Poncho.
https://cdn.discordapp.com/attachments/640760727489085450/956285811144392714/unknown.png

To verify, tried with a normal character with normal legs and it worked fine with the poncho. Gave same character digitigrade legs, the issue emerged and the placeholder sprite came up.

**Comment by TetrakoHateThis** [comment]
Based on some very deft help from Kotoheck and a little rudimentary searching, I believe the issue is related to:

#11707: '[MODULAR] Overhauls how we handle taur sprites, adds a few pre-existing taur sprites to suits, and also a few new ones' by nikothedude at commit 0506b48a69

There are entries in it directly handling the suit layer items I've found issues with and I believe something has been botched there and needs reviewing and changing.

**Comment by nikothedude** [comment]
You were right, my PR was breaking it. I fixed it in the most recent commits.

**Comment by TetrakoHateThis** [comment]
Can confirm now the issue has been fixed. Will close now.
