### ISSUE TITLE
Incinerator Access Console repeatedly re-opens its UI unless walked away from entirely

### ISSUE THREAD

**Issue by aeronadf** [Skyrat-SS13/Skyrat-TG#12243]
Reporting client version: 514.1582

## Round ID:
4839

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [[SEMI-MODULAR] Medical Smartdarts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)
- [Assault Operatives](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12126)
- [[Semi-Modular] Oversized Overhaul (Overrated!)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12169)
- [[MODULAR] Overhauls how we handle taur sprites, adds a few pre-existing taur sprites to suits, and also a few new ones](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11707)

## Reproduction:
On IceBox and Meta, over two separate rounds, the airlock controller for the Ordnance Burn Chamber would repeatedly re-open the UI after being clicked once, regardless of how many times it was closed thereafter, with approximately a one-second delay. After walking away, this bug stops - but it seems to cause the switch inside the airlock ('airlock sensor') to stop functioning until the Access Console is clicked again. Video: https://dl.dropboxusercontent.com/s/embu5lmev0jc7gq/03-23-2022_133340.mp4

**Comment by Zergspower** [comment]
previous console no longer exists - safely assuming resolved
