### ISSUE TITLE
Quirks are broken

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#12257]
## Round ID: 

 literally any round

## Reproduction:

 So when i take my last quirk the points don't go from e.g. -8 to 0, they stay at -8 and when i reload the page it kicked that quirk back out. i can't fully use up my quirk points.

![Screenshot_3](https://user-images.githubusercontent.com/75141807/159966952-11606175-8c29-40a8-b0f3-8f13e235f72a.png)

**Comment by Mithrun** [comment]
![image_2022-03-24_174532](https://user-images.githubusercontent.com/75141807/159967510-b2b656dd-ead3-4d59-a499-49937fda0c71.png)
plus one from prosthetic arm.

**Comment by Mithrun** [comment]
Ok i just found out by removing my +1 surplus prosthetic arm i can take it to 0, but not with it on.

**Comment by Sigmar-alkahest** [comment]
a note this issue is still going on, had to do some experimenting but i'm preeeetty sure it's because the menu isn't counting the point from the prosthetic limb even though it displays having it?

**Comment by GoldenAlpharex** [comment]
> Ok i just found out by removing my +1 surplus prosthetic arm i can take it to 0, but not with it on.

That's normal, that's how the surplus prosthetics work.

They're a malus, so you can get a good quirk in exchange.

**Comment by GoldenAlpharex** [comment]
But, yes, if you still have this issue, I'd like to know what kind of stuff you have in the Augments+ tab.

**Comment by Zergspower** [comment]
Assumed resolved given the time gap
