### ISSUE TITLE
SEVA doesn't protect against ash storms or being on fire

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#12276]
SEVA is supposed to make you immune to ash storms. Sort of the whole point of it.

## Reproduction:

get a SEVA suit on
Stand out in an ash storm
Die

**Comment by YakumoChen** [comment]
It doesn't even protect you against fire!!! what the fuck

**Comment by ghost** [comment]
Was fixed by #15433
