### ISSUE TITLE
Spawning as an officer, jumpskirt option not working + the normal jumpsuit overrides your loadout preference

### ISSUE THREAD

**Issue by Cheeritup** [Skyrat-SS13/Skyrat-TG#12307]
Reporting client version: 514.1582

## Round ID:
Any round

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [[SEMI-MODULAR] Medical Smartdarts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)
- [Assault Operatives](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12126)
- [[Semi-Modular] Oversized Overhaul (Overrated!)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12169)
- [[MODULAR] Overhauls how we handle taur sprites, adds a few pre-existing taur sprites to suits, and also a few new ones](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11707)
- [ACTUALLY FIX RESTRICTED JOBS ROLLING ANTAGONIST](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12246)
- [[TM-ONLY] Revert "[MIRROR] [READY] Podperson hair (sprites by Shiets!)  [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12265)

## Reproduction:
Set highest priority to security officer
Set your preference to jumpskirt
Choose any clothing that should override your default jumpsuit in your loadout.
Set "move job to backpack"
Click ready and spawn in at round start.

1. No jumpskirt (even though there is one you can order via cargo, same stats)
2. Jumpsuit overrides your loadout preferences, even when "move job to backpack" is enabled.

**Comment by tf-4** [comment]
The lack of jumpskirt is intended. The overriding is not.
