### ISSUE TITLE
Ashwalkers unable to spawn from eggs

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#12333]
## Round ID: 4882

Ashwalker ghost role unable to be used

## Reproduction:

Try to spawn in as an ashwalker, eggs dont seem to register even from the ghost-spawn menu

1. Observe
2. Check ghost spawn
3. Try to use any Ashwalker egg
4. Cry tribal tears

**Comment by Zonespace27** [comment]
Worked on #4891
