### ISSUE TITLE
Pepperball Goody Case arrives empty

### ISSUE THREAD

**Issue by Aether217** [Skyrat-SS13/Skyrat-TG#12365]
Reporting client version: 514.1582

## Round ID:
4892

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

## Reproduction:
I've observed it in a previous round as well and simply wrote it off as someone likely stealing or messing up my order but once again the goody case arrives locked yet with no contents

https://prnt.sc/E5Lre3_RThiy

**Comment by tf-4** [comment]
Feature, return it with a denied manifest
