### ISSUE TITLE
Huge Air Scrubber is invisible

### ISSUE THREAD

**Issue by Inari-Whitebear** [Skyrat-SS13/Skyrat-TG#12392]
Huge Air Scrubber is invisible. This is due to Modular Skyrat files overwriting the icon path to one that doesn't have the huge air scrubber's icon_state. Might've been an oversight or the sprites for it just aren't done yet?

## Testmerges:

Has been going on for a while, but currently:

BYOND Version: 514.1560
Server revision compiled on: 2022-03-29T02:09:57+00:00
Master commit: [b25e58d01fcb1752b3a3534434cc13875e1cd090](https://github.com/Skyrat-SS13/Skyrat-tg/commit/b25e58d01fcb1752b3a3534434cc13875e1cd090)
The following pull requests are currently test merged:
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#12310: '[NON-MODULAR] Small MODsuits remaster' by KathyRyals at commit 99556d72bd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
[#11860: '[HOST] [MODULAR] New character customization option, Headshots.' by Zonespace27 at commit 824455e5ff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
[#11135: 'The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs' by GoldenAlpharex at commit d4d0e8deb0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

Local commit: af52c800550f6a260c5e9bb50878f5509aa66d57
TGS version: 4.15.7
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:

Look at any huge air scrubber.
![image](https://user-images.githubusercontent.com/1077971/160895106-2c0178da-564c-4adf-896c-9442732d1b59.png)
![image](https://user-images.githubusercontent.com/1077971/160895143-9b00abb2-0bf2-46e0-abf8-42cf0e5ad2ff.png)

**Comment by Quill-Weave** [comment]
Probably fixed! Notifying Alpharex.
