### ISSUE TITLE
Broken Sparring God Contracts

### ISSUE THREAD

**Issue by Krexah** [Skyrat-SS13/Skyrat-TG#12519]
## Reproduction:

Sparring god contracts regularly break, and cannot be activated. Reproduces just like that honestly. Can't start it but every other part works fine.

![image](https://user-images.githubusercontent.com/102912494/161433365-24214e5b-4b4f-40e3-9ae5-9e9117d16deb.png)

**Comment by Zergspower** [comment]
Unable to replicate and havnt heard of this in recent months
