### ISSUE TITLE
DNA Manipulator still missing from Botany

### ISSUE THREAD

**Issue by yorii** [Skyrat-SS13/Skyrat-tg#1252]
😢

**Comment by Hemlock32** [comment]
Plant grafting and cross pollination exist as a replacement

**Comment by yorii** [comment]
> Plant grafting and cross pollination exist as a replacement

It's not a good replacement.

**Comment by atakiya** [comment]
Closing, stale and not enough information.
in the future, please explain **why** a feature should be added and make sure it accounts for any balance changes properly.

If this is still relevant, please post a new issue with the missing information, thank you.
