### ISSUE TITLE
Cargo console bluescreen

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-tg#1256]
## Round ID:

 69, skyrat rebase test server

## Reproduction:

Open a supply console. It bluescreens and shows

[object Event]
   at undefined:undefined
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Zoom 3.6.0)
State: {"ckey":"tehsplintercell","interface":"Cargo","window":{"key":"[0x203ceec]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2525-2559

**Comment by Gandalf2k15** [comment]
Unable to reproduce.
