### ISSUE TITLE
EMP Grenade issue, broken, nearly unusable.

### ISSUE THREAD

**Issue by AzyreR** [Skyrat-SS13/Skyrat-TG#12592]
## Round ID:
4991

## Testmerges: 
Unsure if it was caused because of a testmerge but I'm filling it anyway for completition's sake.
#10823 YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED
#11860 Character Customization option, Headshots
#12310 Small MODsuits remaster
#12169 Oversized Overhaul
#11135 MODsuit Digital Revolution

## Reproduction:
Shouldn't be hard to reproduce as they should be broken at all times since I managed to do it three times in a row with the same result.

Priming a EMP Grenade in your hand will cause it to dissapear and blow up on the player's sprite as if it were placed inside one of their storages. Instead of the usual, the grenade being primed and in your hand, and you being able to throw it. The explosion of the EMP grenade worked as usual, just, entirely centralized on the player as if they were still holding it on their hand.

I'll list below what other implants and gear I had in case I'm just being stupid.
Implanted:
CNS Rebooter.
Anti-Drop Implant.
EMP Implant.

Wearing:
Contractor MODsuit.
Thermal chameleon goggles.

Holding: 
Anti-Drop Implanted Contractor Baton.
EMP Grenade.

**Comment by Zergspower** [comment]
Resolved in current version
