### ISSUE TITLE
Moth people have a glitched yellow skin face

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#12685]
Reporting client version: 514.1582

## Round ID:
5023

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)

**Comment by GoldenAlpharex** [comment]
This was fixed, thankfully. The moth skin color options are not fixed, however, but this isn't what it was about.
