### ISSUE TITLE
Port Tarkon atmospherics tanks not having their inlet/outlet vents

### ISSUE THREAD

**Issue by Winterflux** [Skyrat-SS13/Skyrat-TG#12719]
## Testmerges:
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#12310: '[NON-MODULAR] Small MODsuits remaster' by KathyRyals at commit 99556d72bd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
[#12702: 'More fixes' by Gandalf2k15 at commit 10da8dbc97](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12702)

## Reproduction:

- 1. On any map where Port Tarkon spawned observe as a ghost and jump to P-T Atmospheric Center
- 2. Gaze into the tanks and witness the lack of the the output inlets in every one of the tanks along with the lack of injectors for inputting into the tanks like the NT stations have

This started around when I think the main atmos tanks on the station didnt have them but I remember it being on icebox (I don't know the round ID) and I saw people having to break into the atmospherics tanks to add their own scrubbers and setup the scrubbers aswell so the air mix tank actually gave air to the station which was a huge problem on the main station but that has been fixed but port tarkon has had the same issue and it has not been properly reported yet.
Additionally in a round I noticed that when I had fixed the tanks manually by breaking into them I noticed they would eventually drain out fully I think which makes me believe the atmos miners were not working but I do not have enough knowledge on that yet.

(also when you break the windows to get into the plasma tank to add a scrubber make sure to use a holofan and also to not spark your RPD near the tank or you will set the whole thing on fire and gain hot plasma for the rest of the round)

**Comment by IsaacTheSharkWolf** [comment]
should be fixed if my PR merges, along with the incinerator not being broken.
