### ISSUE TITLE
Teshari Genitals not visible in game sprite.

### ISSUE THREAD

**Issue by ArcticDruid** [Skyrat-SS13/Skyrat-TG#12769]
Reporting client version: 514.1583

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [More fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12702)

## Reproduction: Be Teshari species, have genitals, in character preference but in game sprites have no genitals and they are not visible in examine. Simple bug in terms and its happening to everyone who plays the teshari race.
![Teshari evidence](https://user-images.githubusercontent.com/103701456/163493810-df00d8ba-37a5-4f3f-b9d1-e59ff93cc0f8.JPG)

**Comment by Zergspower** [comment]
Resolved
