### ISSUE TITLE
Taur Clothing clipping issue

### ISSUE THREAD

**Issue by Quill-Weave** [Skyrat-SS13/Skyrat-TG#12831]
## Reproduction:

Put on shoes as many species of taur. In fact, this applies to multiple articles of clothing. Tested with Synthetic Lizard and Drake. Requested by Zonespace in #11074

![image](https://user-images.githubusercontent.com/103809013/163691274-eac152b0-3d9e-4938-bb3d-ef908b4a0ea4.png)

**Comment by desertmote** [comment]
the shoes working is a nice option for some

**Comment by Quill-Weave** [comment]
> the shoes working is a nice option for some

Yeah, sometimes I even see naga dudes wearing shoes, it's kinda cute. But clothes are kinda glitchy in general right now.
