### ISSUE TITLE
Body tonage body marking is not visible.

### ISSUE THREAD

**Issue by Leudoberct1** [Skyrat-SS13/Skyrat-TG#12853]
Like the title says. This is on a human male. Round ID is 5078.

**Comment by ImHoppingMad** [comment]
yeah, I noticed a few of my characters body tonage marking have gone missing myself, it isn't working on the anthro race either.

**Comment by tf-4** [comment]
Dupe of the more general https://github.com/Skyrat-SS13/Skyrat-tg/issues/13188
