### ISSUE TITLE
Having medical HUD or robotics HUD hiding the "writing" and "emoting" icons

### ISSUE THREAD

**Issue by Cheeritup** [Skyrat-SS13/Skyrat-TG#12872]
Reporting client version: 514.1583

## Round ID:
5084

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [More fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12702)

## Reproduction:
Super easy to reproduce. Wear a medical HUD, write something - Boom no writing icon. Take it off - Its back!

**Comment by theselfish** [comment]
It's there. It's just the fact the huds share the same area as the indicator.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13297
