### ISSUE TITLE
Naga Taur issues regarding shoes and leg clipping

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#12901]
Reporting client version: 514.1575

## Round ID:
5093 (also since K-limb)

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [More fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12702)
- [[TM ONLY] Removes firelocks from windows](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12889)

## Reproduction:

Use Taur - Naga setting
Legs are not removed like how they were before update but are just somewhat hidden beneath the tail, the toes still poke out the front by a few pixels (see bottom right)
Shoes also appear over the tail as well from the legs existing

The issue becomes worse when using *turf as demonstrated. 
Usually the tail sprite is hidden/qdel and replaced with a static one of a coil (which could be pixel shifted away from, previously showing nothing below the waist)
Doing it now will reveal the legs fully and give you the appearance of a biped
![naga borked](https://user-images.githubusercontent.com/75050485/163995038-ebc8637e-a915-4b1c-a06b-65ad882e041e.png)

**Comment by desertmote** [comment]
Oh no my *turf emote... will look into this
