### ISSUE TITLE
Languages still bugged.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#12958]
Reporting client version: 514.1582

## Round ID:
5120

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Adds Gun Cargo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12632)
- [OG GUNSEC: Revelations](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12940)
- [Assault operatives now announce at 15 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12938)

**Comment by GoldenAlpharex** [comment]
It's now fixed.
