### ISSUE TITLE
Cargo orders can be randomly not delivered.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#12965]
Reporting client version: 514.1582

## Round ID:
5122

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Adds Gun Cargo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12632)
- [Heads of staff once again get their guns](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12940)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

**Comment by Quill-Weave** [comment]
Can you test ordering those three items again?

I've noticed that you can confirm orders while the shuttle is in transit, for some reason. This might be related to the bug. Other than that, ordering too many items per shuttle can sometimes break it. Which map did this happen on?

**Comment by theselfish** [comment]
If the crate and paper come through, but not the item. This is a feature. Mark the manifest as incorrect and send it back.

**Comment by tobjv** [comment]
> If the crate and paper come through, but not the item. This is a feature. Mark the manifest as incorrect and send it back.

there was no crate for any of these options, which usually means the person had not enough funds in their account but they did as the item cost 1086 cr and they had 2k in their bank.

**Comment by tobjv** [comment]
it is like once out of every 10 shifts rare. that's why it is hard to reproduce.

**Comment by Zergspower** [comment]
Given how long its been since we've heard of this problem - assuming it's resolved
