### ISSUE TITLE
Tablet Notepad Causes Action Lockout

### ISSUE THREAD

**Issue by Knouli** [Skyrat-SS13/Skyrat-TG#13000]
## Round ID:
275247

## Testmerges:
The following pull requests are currently test merged:
[#10823: 'YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ' by Gandalf2k15 at commit 58ec183702](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#12632: 'Adds Gun Cargo' by Zonespace27 at commit a89659aa24](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12632)
[#12949: 'Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types' by Iamgoofball at commit c9daa55dea](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit d416c5dfa5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

## Reproduction:
Open up the notepad in your tablet device.
Begin typing with an above average CPM.
Receive an action lockout and auto-report to the administration team.

![image](https://user-images.githubusercontent.com/25857923/164599583-a6f7367b-5c5a-4c39-86ba-111f38c3a57b.png)

If I had to guess, it has something to do with the form resubmitting itself with every character you type - but, that's pure speculation and gut instinct, I'm not privy to the intricacies of the systems in play here.

**Comment by Zergspower** [comment]
Resolved
