### ISSUE TITLE
Close this, please. Mis-report.

### ISSUE THREAD

**Issue by EvilCrimsonWitch** [Skyrat-SS13/Skyrat-TG#13036]
Woops, mis-report. Apologies. Close this.

**Comment by EvilCrimsonWitch** [comment]
I tried to report an issue, before realising I simply had got a setting wrong. But, true to my original report, I do think my characters eyes look a little... off? Not sure if a sprite has changed. 

![image](https://user-images.githubusercontent.com/75273306/164927497-cd6cfa68-2f12-4a1a-a529-fc1ae7c03fe9.png)

**Comment by Iamgoofball** [comment]
you should be able to close your own issue if you press the button next to comment
