### ISSUE TITLE
Hop/Captain ID missing ability to change job slots on ID console

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#13032]
Reporting client version: 514.1582

## Round ID:
5142

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Adds Gun Cargo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12632)
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

**Comment by Zergspower** [comment]
Issue was in relation to the big fat migration over to text based access vs numerics
