### ISSUE TITLE
Removing gigantism makes you smaller than you initially were.

### ISSUE THREAD

**Issue by SapphoQueer** [Skyrat-SS13/Skyrat-TG#13077]
Reporting client version: 514.1583

## Round ID:
5153

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

## Reproduction:
Step 1: Inject giganism
Step 2: Nullify it
Step 3: Repeat.

Edit: not sure if it's relevant, but my character is 1.08 size by default.

It's that simple.

This lets you be way smaller than intended, like only a few pixels tall.

![image](https://user-images.githubusercontent.com/94389951/164998531-6d655599-ea2c-459b-8e7b-26220e69604a.png)

**Comment by vinylspiders** [comment]
@Jolly-66 I fixed this in https://github.com/Skyrat-SS13/Skyrat-tg/pull/19418, must have somehow missed to link the issue.
