### ISSUE TITLE
Quartermaster erroneously lacks a gun permit

### ISSUE THREAD

**Issue by Draganfrukts** [Skyrat-SS13/Skyrat-TG#13102]
## Round ID: 
ANY

## Testmerges: 
ANY

## Reproduction:
Spawn as the Quartermaster, wear a permit HUD
Realize you don't have a gun permit despite spawning with a firearm in your very locker

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13306
