### ISSUE TITLE
Converting a text using the book binder adds formating tags to the text.

### ISSUE THREAD

**Issue by NEU-NEU** [Skyrat-SS13/Skyrat-TG#13127]
## Round ID:
5170

## Reproduction:
Printing a book from a paper sheet using the book binder messes up with the format tags and adds code like:
(span style="color:#000000;font-family:'Verdana';") (p)Blah blah blah(br)Blah blah blah.(/p) (/span).

(sorry i replaced "<>" by parenthesis or it would convert it here automatically)

Also, after using the pen to edit additional information, the book's content is missing, resulting in a blank book only showing the edited infos. (Book Title. Penned by author's name. Contents.)

**Comment by NEU-NEU** [comment]
![Untitled](https://user-images.githubusercontent.com/104406522/168468030-7ac0887b-2121-4609-86c4-7bf0b5238852.png)

**Comment by vinylspiders** [comment]
This has been fixed and may be closed. 

https://github.com/Skyrat-SS13/Skyrat-tg/commit/b1bd40e7606a51d8716ede9d4b2c938953030008 Most likely.

**Comment by SylvetteSylph** [comment]
This has not been fixed; instead of blurting out format, it just doesn't show any formatting at all, not even line breaks. It's better, but it still makes adding formatting a book entirely impossible.

**Comment by vinylspiders** [comment]
> This has not been fixed; instead of blurting out format, it just doesn't show any formatting at all, not even line breaks. It's better, but it still makes adding formatting a book entirely impossible.

Mmm, that's a different issue than the one reported here though, and an upstream one at that. I'd make a new issue report for it on TG as opposed to here.

**Comment by vinylspiders** [comment]
The issue described by the issue creator has been fixed, and the adjacent issue to this is going to be fixed by https://github.com/tgstation/tgstation/pull/74902.
