### ISSUE TITLE
Hair related items do not function properly.

### ISSUE THREAD

**Issue by WormOuroboros** [Skyrat-SS13/Skyrat-TG#13134]
Reporting client version: 514.1583

## Round ID:
5175

## Testmerges:
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

**Comment by Mithrun** [comment]
This is still an issue, +1

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13907
