### ISSUE TITLE
Owai's ~10-11 Missing Feature/Bug Report Mega"Thread"

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#1317]
## Missing Features
- ~~SSD Timers for Cryo Cells, and / SSD Examine Text. ZZZ Above heads for when someone is SSD~~
- ~~Star Symbol for Emotes (Runechat)~~
- ~~Radio Message Sound (For if you do `; :h`, ect.~~
- ~~Sprite Size Customization~~
- ~~Towels, Towel Bins, Colored Bedsheet Bins~~
- ~~Additional Alert Levels (Violet, Amber, Orange)~~
- ~~PDA Noises (Beeping when clicking through menus. Beeping on message sent. Possibly sounds for when a message fails to send?)~~
- Prize Machines / Tickets
- Hand Mirrors
- Some PDA Styles are missing. (Specifically, Holographic, unless they're just named different.) I don't think it can be changed midround either.
- Food Preferences
- Directional Falling seems to be missing.

(Apparently not being done?)
```
- Cloning is not fully implemented.
- Auto-Call/Extension Votes
- All the random ERP stuff.
```

**MEDICAL**
- Anesthetics / Painkillers (Anesthetic Tanks, Morphine, Miner's Salve, Vitrium Froth (For Ashwalkers)
- Blood Bank Generator / Synthblood (Possibly remake it so it has proper upgrade tiers for efficacy instead of doubling blood rounstart.)

## Possible Bugs
- Changeling Transformation Stings might not work correctly? (Don't know if it's just a TG feature or not.)
- Ghosting in Cryo doesn't immediately remove your body.
- Face Masks (At least for muzzle variants) don’t show properly when looking down
![image](https://user-images.githubusercontent.com/7543955/96075581-5849df00-0e79-11eb-82d0-baae209048d9.png)
- Pickpocketing things from someone will drop the item on the floor, making it pretty easy to tell you tried to nick their shit.
- ~~Same thing goes for buying things at vendors. Items kinda just drop out of the vendor.~~

## QoL Improvements
- ~~Alt-Click to select amount for Reagent Containers~~
- ~~CTRL Click Jumpsuit to max sensors.~~
- ~~Can't wear trash bags on belt.~~
- Food Crafting takes -forever- compared to Citcode.
- Ghost filtering of common messages.
![image](https://user-images.githubusercontent.com/7543955/96076378-37828900-0e7b-11eb-8290-0ac82c12f902.png)

## Straight up requests.
- Stuff to help prevent permakilling. IE: Gibber/Cremator spitting out brains, Fryer not allowing brains to be fried, brain cake removal. Reminders for both antags and security players that permakilling is a last resort, and assassination objective does not mean you can permakill people.
- Mutation Toxins and a spawnable bottle of them for each race. (For Easier TF Reversal, Citcode only had a few.)

## Stuff that probably doesn't matter or needs done upstream.
```
- Chat doesn't have a two-tone mode (Dark Top, Light Bottom)
- PDA Messages and Pointing count as "Unsorted" Messages. Could use some category?
- OOC and LOOC cannot be sorted seperately. I always want to see LOOC messages, but the chat sorts them both in the same category.
- Color Coding for Medipens (I might just do this upstream, 3 medipens look exactly the same. Epinephrine Medipen, Emergency First -Aid Autoinjector, Hypovolemic-response Autoinjector.)
- Polychromatic Clothing
```

## End Notes:
Some of these may have already been fixed, but I was urged to put these things on the github instead of a random google document that I don't look at all that much. I'll try to strike things off of this as they're fixed, and either open up a new thread, or make date-stamped addendums under this message.

**Comment by Gandalf2k15** [comment]
Cloning is not fully implemented. - Not doing.
Auto-Call/Extension Votes - Likely not doing.
All the random ERP stuff. - Github problems, keep this off the github.
Directional Falling seems to be missing. - Once fallen, you may move into which direction you want to.

**Comment by Gandalf2k15** [comment]
Alt-Click to select amount for Reagent Containers - https://github.com/Skyrat-SS13/Skyrat-tg/pull/1359

**Comment by Gandalf2k15** [comment]
CTRL Click Jumpsuit to max sensors. -https://github.com/Skyrat-SS13/Skyrat-tg/pull/1361

**Comment by Gandalf2k15** [comment]
Color Coding for Medipens (I might just do this upstream, 3 medipens look exactly the same. Epinephrine Medipen, Emergency First -Aid Autoinjector, Hypovolemic-response Autoinjector.) > do it upstream

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1362

**Comment by Owai-Seek** [comment]
When it comes to directional things, I don't mean moving while on the floor, I mean tipping over in the way that you're facing. I believe it was this PR on the prior codebase.

https://github.com/Skyrat-SS13/Skyrat13/pull/2713

**Comment by Spiriten** [comment]
Tesla coils can't be swapped to corona research coils. Usually it is just screwdriver use on the board. Even the tooltip says to use a screwdriver. But, alas it doesn't work.

**Comment by Spiriten** [comment]
Experienced an issue where I as a cargo tech, was unable to order HOS weapon crates. He ordered them. But I could not approve them. Unsure if that is because I was just a cargo tech. They appeared in the request menu, but with no approve or deny ability.

**Comment by Owai-Seek** [comment]
PDA Stuff addressed with this. https://github.com/Skyrat-SS13/Skyrat-tg/pull/1415
