### ISSUE TITLE
[Kapulimbs] Female clothing types broken.

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#13189]
HD advanced screenshot:
![image](https://user-images.githubusercontent.com/62520989/165664327-b6d27c07-3e3c-4a21-8c54-9c1ef8e6d7d8.png)
![image](https://user-images.githubusercontent.com/62520989/165664343-23309dda-9a0e-42b2-87e8-6cb366d2eb40.png)

## Reproduction:
open char creator/spawn in as a female, put on a jumpsuit or anything else that'd auto adjust, gawk.

**Comment by GoldenAlpharex** [comment]
I fixed it upstream ( https://github.com/tgstation/tgstation/pull/66646 )

**Comment by RatFromTheJungle** [comment]
fixed (see above)
