### ISSUE TITLE
[KAPULIMBs] Lizard sprites got re-darkened

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#13193]
what it says on the tin, previously fixed in
https://github.com/Skyrat-SS13/Skyrat-tg/pull/2500
and
https://github.com/Skyrat-SS13/Skyrat-tg/pull/2568

**Comment by Deek-Za** [comment]
Big annoyance. Managed to somewhat remedy this by applying plain markings to every part in the meantime. It's doubly bad that both the Leg and the Torso are colored by the same thing but the (Digi)legs aren't darkened, so you're basically forever mismatched if you run Digi
