### ISSUE TITLE
Agent ID's can have their forged job description be 2048 characters long

### ISSUE THREAD

**Issue by SapphoQueer** [Skyrat-SS13/Skyrat-TG#13197]
## Round ID:
5194

## Testmerges:

- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Blob Enhancements 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)

## Reproduction:
On a forged agent ID, you can add up to the character limit worth of text, there's no right reason for it to be this high of a character limit.

![image](https://user-images.githubusercontent.com/94389951/165815547-763221c2-c0bd-42a1-a077-c4028c966762.png)

**Comment by Zergspower** [comment]
most likely by design, but it would belong upstream otherwise
