### ISSUE TITLE
Radio chat tab filter includes examine text

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#13211]
## Testmerges:
Round ID: 5200
BYOND Version: 514.1583
Server revision compiled on: 2022-04-27T21:11:34+00:00
Master commit: [c7fdb03a17321c754454c8116d9aee2a3ad63567](https://github.com/Skyrat-SS13/Skyrat-tg/commit/c7fdb03a17321c754454c8116d9aee2a3ad63567)
The following pull requests are currently test merged:
[#12949: 'Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console' by Iamgoofball at commit 34a7f733fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 1fd8fd4009](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#12885: 'Blob Enhancements 1' by Zergspower at commit bba7e29752](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
[#13176: 'Disables time track profiling temporarily' by Gandalf2k15 at commit 8663ecb531](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)

Local commit: 84948114c49d54c251abc3a46add4ff2359acd5d
TGS version: 4.16.2
DMAPI version: 5.3.0

## Reproduction:
Create new chat tab with only Radio filter on. Examine someone

**Comment by KeptheKobold** [comment]
Upon further testing, it seems to only happen when you have a HUD active, like medical HUD, and it shows the buttons for extra actions

**Comment by YakumoChen** [comment]
have you tested it with other filters? Some messages are just immutable.

**Comment by KeptheKobold** [comment]
> have you tested it with other filters? Some messages are just immutable.

I just checked, and on talk filter atleast it doesnt show up

**Comment by YakumoChen** [comment]
likely an upstream issue then
