### ISSUE TITLE
Crates bought with Scientific budget unable to be opened.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#13251]
Reporting client version: 514.1582

## Round ID:
5222

## Testmerges:
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Blob Enhancements 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
- [Event voting system, prelude to event planner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11270)

**Comment by YakumoChen** [comment]
The RD's ID should have the access for it

**Comment by tobjv** [comment]
should, but didnt.

**Comment by Zergspower** [comment]
this is intended, dept budgets aren't tied to an ID And weapon armament crates are. The ones that can be unlocked by the department budgets would be the ones in the request console in your respective department

**Comment by YakumoChen** [comment]
@Zergspower problem is that you can order armament crates with budget through the Tablet program as a Head of staff
