### ISSUE TITLE
SignalCommander on Tablets Non-Functional

### ISSUE THREAD

**Issue by Knouli** [Skyrat-SS13/Skyrat-TG#13250]
Reporting client version: 514.1581

## Round ID:
5220

## Testmerges:
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Blob Enhancements 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
- [Event voting system, prelude to event planner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11270)

## Reproduction:
Download and attempt to open "SignalCommander"
Receive error message via chat: "flashes an error: "hardware\signal_hardware\startup.bin -- file not found"."
Attempt and fail to adjust the 'undefined' code and frequency. Neither manual input, nor 'click and drag' adjustment viable.

![image](https://user-images.githubusercontent.com/25857923/166137587-21d2c7e7-fe0c-41ed-917c-b82d6d826455.png)

**Comment by YakumoChen** [comment]
its getting removed upstream

**Comment by YakumoChen** [comment]
Not a bug
You need the signaler hardware in your tablet to use the program.
