### ISSUE TITLE
Guncargo DTR6 failed to deliver.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#13278]
Reporting client version: 514.1582

## Round ID:
5231

## Testmerges:
- [Goofsec 2.0 aka "I guess we're going back to bullets in Security": Security Pistol w/ 6 Ammo Types, Warden Dispatch Console](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12949)
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Blob Enhancements 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
- [Event voting system, prelude to event planner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11270)

**Comment by YakumoChen** [comment]
Needs more details.
 Did you reciece an empty crate or no crate at all? 
Could you reproduce this?

**Comment by tobjv** [comment]
was missing gun, had the paper and the case.

In that round, yes. in another round? Havent checked yet

**Comment by YakumoChen** [comment]
The case? As in, the gun was not present in the case?

**Comment by Zonespace27** [comment]
Not a bug. Cargo (not just guncargo) has a chance to make orders not appear, deny the manifest and send it back for a full refund (to the cargo budget)

**Comment by YakumoChen** [comment]
figured that was the case but I had to have the proper clarification
