### ISSUE TITLE
Synthetic races always have a white leg (cum??)

### ISSUE THREAD

**Issue by Lizzzard26** [Skyrat-SS13/Skyrat-TG#13298]
## Reproduction:
1. Make synthetic athropomorph or synthetic lizard
2. Now your leg is in the mess, bruh

![image](https://user-images.githubusercontent.com/102904016/166562120-6d530ed2-f4d9-469a-9190-1bfd17737db4.png)
![image](https://user-images.githubusercontent.com/102904016/166562143-a65156af-a2b8-441b-9299-3d8bcb04fe6c.png)

**Comment by Lizzzard26** [comment]
I can assume that for some reason the leg is repainted in 000000 color

**Comment by GoldenAlpharex** [comment]
Do you have any markings selected, when you try to do that?
