### ISSUE TITLE
Various pieces of security/department guard armor are broken for digitigrade.

### ISSUE THREAD

**Issue by gummardgumphrey** [Skyrat-SS13/Skyrat-TG#13322]
## Reproduction of issue one: Put on any of the following vests and watch as you get a beautiful pink and black coat! 

![image](https://user-images.githubusercontent.com/77675526/166830302-2149052d-e4d8-45b2-ad8a-505bbbbb161f.png)

Works (breaks) in all colors! 
![image](https://user-images.githubusercontent.com/77675526/166830877-87d4dc32-4bb6-49bd-a38c-7e0c0ea62f8f.png)

**Comment by tobjv** [comment]
[yeah the vest is broken too](https://prnt.sc/W3SKOgXwF2UY)

**Comment by gummardgumphrey** [comment]
Belts have since been fixed, I think. Issue one still perists. Might just edit this to reflect this update.
