### ISSUE TITLE
NO BOOPS!!!

### ISSUE THREAD

**Issue by Lizzzard26** [Skyrat-SS13/Skyrat-TG#13337]
## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 2e71538436](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#12885: 'Blob Enhancements 1' by Zergspower at commit bba7e29752](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12885)
[#13281: '[DNM] [NON-MODULAR] Early Mirror of New drink sprites aka Drink Desouling' by ErdinyoBarboza at commit 37f10beac5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13281)
[#13176: 'Disables time track profiling temporarily' by Gandalf2k15 at commit 8663ecb531](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)

## Reproduction:
1. Join the round
2. Boop someone's nose
3. *suicide due to depression*

**Comment by Lizzzard26** [comment]
there are no boops or no noses? god, what a horrible world we live in... NO BOOOOOOPS(

Ps: in case anyone doesn't understand or is too lazy to check the bug in the game: instead of booping, you pat your companion on the head

**Comment by tf-4** [comment]
probably due to https://github.com/Skyrat-SS13/Skyrat-tg/pull/13117

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13797
