### ISSUE TITLE
Item in suit storage slot are invisible if not placed inside while clothing toggle is open

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#13481]
## Testmerges:
BYOND Version: 514.1583
Server revision compiled on: 2022-05-08T23:56:10+00:00
Master commit: [4ed05d2d486e7287bfe826e24974b0ec1f0f5a17](https://github.com/Skyrat-SS13/Skyrat-tg/commit/4ed05d2d486e7287bfe826e24974b0ec1f0f5a17)
The following pull requests are currently test merged:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 54e6505406](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13176: 'Disables time track profiling temporarily' by Gandalf2k15 at commit 8663ecb531](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
[#13281: '[DNM] [NON-MODULAR] Early Mirror of New drink sprites aka Drink Desouling' by ErdinyoBarboza at commit 37f10beac5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13281)

## Reproduction:
Get a suit that allows you to place items into its storage.
Place item inside suit storage slot while the clothing toggle is closed

**Comment by Jolly-66** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/68008
