### ISSUE TITLE
Syndicate Modsuit modules underlay masks

### ISSUE THREAD

**Issue by Ebin-Halcyon** [Skyrat-SS13/Skyrat-TG#13488]
Reporting client version: 514.1583

## Round ID:
5303

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
- [[DNM] [NON-MODULAR] Early Mirror of New drink sprites aka Drink Desouling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13281)

## Reproduction:
What it says on the tin. The modules underlay mask sprites making it look a bit wonky.
What it should look like:
![image](https://user-images.githubusercontent.com/81479835/167513298-80c89c0e-f8e3-481f-9bbf-b5da72ff0e98.png)
![image](https://user-images.githubusercontent.com/81479835/167513306-84248a77-b81d-4d0c-b4eb-0d20baa82633.png)

What it looks like right now with a Syndicate mask:
![image](https://user-images.githubusercontent.com/81479835/167513354-59376cce-ae1a-4097-b748-03910d75fe7c.png)

Might be an upstream issue, not entirely sure.

**Comment by Zonespace27** [comment]
This was fixed upstream
