### ISSUE TITLE
[KAPULIMBS] Unable to reattach detached limbs to body

### ISSUE THREAD

**Issue by SarmentiCampbell** [Skyrat-SS13/Skyrat-TG#13506]
Reporting client version: 514.1582

## Round ID:
5318

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Disables time track profiling temporarily](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13176)
- [[DNM] [NON-MODULAR] Early Mirror of New drink sprites aka Drink Desouling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13281)

## Reproduction:
Unsure if it is only for some races, so for now i'll assume that it is every species

1. Grab limbs that were separated from the body
2. Do Prosthetic Replacement Surgery to reattach severed limbs
3. ???
4. Cry 
![unknown](https://user-images.githubusercontent.com/61919894/167654914-20c75a39-5772-47d4-9109-d60f800f3e5d.png)

**Comment by nevimer** [comment]
This is fixed now I believe.
