### ISSUE TITLE
Virology bounties no longer work, possibly other jobs too(?)

### ISSUE THREAD

**Issue by AtoriBirb** [Skyrat-SS13/Skyrat-TG#13541]
## Round ID: 
5333
## Testmerges:

Probably has to do with recent https://github.com/Skyrat-SS13/Skyrat-tg/pull/13504

## Reproduction:

When you try to generate bounties off of a virology ID, it fills the list with nulls and  locks up the ability to use it for bounties.
![](https://cdn.discordapp.com/attachments/610319137012580383/974027911227138108/unknown.png)
This is on the bank account's datum stuff. Just seems like someone didn't fully test that PR they mirror/merged.

**Comment by Zergspower** [comment]
confirmed working again
