### ISSUE TITLE
Ears not affected by 'Hide Mutant Bodyparts'

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-TG#13556]
pretty sure it may be an oversight...
## Reproduction:
use any kind of ear and if you look north east or west you can still see them even if you hide mutant parts, its at it's most obvious with larger ears, such as bunny ears (the ones that droop down alongside the head)

**Comment by YakumoChen** [comment]
Please elaborate. Were you using a hat that hides the hair?

**Comment by Tastyfish** [comment]
The hide mutant bodyparts logic is broken for some of the slots, I'm gonna make a PR for this.
