### ISSUE TITLE
Synthetic - No additional parts are showing

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#13622]
## Round ID:
N/A

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e2ed90f05b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13596: 'Transfer votes will no longer be available to be started by everyone' by GoldenAlpharex at commit ef7c1ab985](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13596)

## Reproduction:
Synthetic Humanoids specifically currently don't seem able to have extra parts like tails, ears, horns etc (including lewd bits also). Enabling Mismatched Parts doesn't make any difference and neither does swapping the part in the dropdowns. Augments seem unaffected by this. Image link is showing how a tail (cable tail) is selected but not showing on the previews and this also carries to ingame.

https://i.imgur.com/QRXgfGt.png

**Comment by Zergspower** [comment]
Resolved
