### ISSUE TITLE
Synths do not have their own language by default

### ISSUE THREAD

**Issue by Lizzzard26** [Skyrat-SS13/Skyrat-TG#13655]
## Testmerges: 
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e2ed90f05b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
But this problem predates the Kapulimbus, it all started somewhere around the redesign of the character editors a couple of months ago.

## Reproduction:
1. Create a synth, choose any language (but not Encoded Audio Language or Galactic Common), 
2. Click "forget" to Galactic Common. If you do right, your language menu will looks like this: 
![image](https://user-images.githubusercontent.com/102904016/168640025-b32b55b8-23b0-4e84-8754-f66c7f7bf772.png)
3. Cry, toaster. You don't even know your own language and you cant speak galactic common too, but understand it.

![image](https://user-images.githubusercontent.com/102904016/168637945-75dab3ba-3422-4d44-b62a-bb9827a014ff.png)
![image](https://user-images.githubusercontent.com/102904016/168640128-9f4dfd26-740f-429c-8f6d-fc058f1ea7fd.png)

**Comment by Lizzzard26** [comment]
And so, about the fix I'd like to see: give the synths these languages by default or 2 extra points in the language selection menu.
Why should synths have so many languages? -
At least it's logical, because they don't learn languages, they just download them.

**Comment by YakumoChen** [comment]
Not a bug

Nothing is stopping you from just taking whatever languages you want. Extra languages on a race are not an obligation.

**Comment by Zergspower** [comment]
While I agree racial languages should be there by default (and maybe even free) the only one that is set as a default is common

**Comment by Lizzzard26** [comment]
> Not a bug
> 
> Nothing is stopping you from just taking whatever languages you want. Extra languages on a race are not an obligation.

Synth, in addition to MUST select the galactic common (otherwise you can't speak it, only understand it), must also take its own language. Thus we get that Synth can only have one additional language, while organic has two.

And yes, this is **BUG** because previously synths had many languages, about 1/4 of the librarian knowledge (to be exact, a couple of months ago, before someone messed up the code once again).

I would like to remind you that the synth doesn't learn languages and accents for years, it just loads it into the voicebox. If the synth knows many languages, it is good for the RP. If synths know 2 more languages than everyone else, it won't turn gameplay upside down.

**Comment by YakumoChen** [comment]
I cannot recreate this "bug"

I opened a character slot in use, changed species to "synth lizard"

By default I had GalCom and EAL. They both use a language point each, like every other species, according to intended behaviour.

Deleting EAL and GalCom both refunded the points. Like every other species, you can choose to remove your species-default language (provided you have one) for a point back in return.

"Extra language points" is not a benefit of playing synth species.

> And yes, this is BUG because previously synths had many languages, about 1/4 of the librarian knowledge (to be exact, a couple of months ago, before someone messed up the code once again).

This is explicitly not the case in the code, knowing all the default species languages is for cyborgs and AIs.

**Comment by Lizzzard26** [comment]
> I cannot recreate this "bug"
> 
> I opened a character slot in use, changed species to "synth lizard"
> 
> By default I had GalCom and EAL. They both use a language point each, like every other species, according to intended behaviour.
> 
> Deleting EAL and GalCom both refunded the points. Like every other species, you can choose to remove your species-default language (provided you have one) for a point back in return.
> 
> "Extra language points" is not a benefit of playing synth species.
> 
> > And yes, this is BUG because previously synths had many languages, about 1/4 of the librarian knowledge (to be exact, a couple of months ago, before someone messed up the code once again).
> 
> This is explicitly not the case in the code, knowing all the default species languages is for cyborgs and AIs.

The description of the race features clearly states that the synths have these languages by default. And it really used to be, but another "coder" broke it all.

**Comment by YakumoChen** [comment]
> The description of the race features clearly states that the synths have these languages by default. And it really used to be, but another "coder" broke it all.

EAL and Galactic Common, yes. They both take up language points regardless. This is not a bug.

**Comment by YakumoChen** [comment]
The relevant code is here. Notice that it's commented explicitly for synth races to only know EAL and Galcom by default 

https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/master_files/code/modules/language/language_holders.dm

**Comment by Lizzzard26** [comment]
> The relevant code is here. Notice that it's commented explicitly for synth races to only know EAL and Galcom by default
> 
> https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/master_files/code/modules/language/language_holders.dm

By default there is only GalCom (only at understanding level), there is no EAL at all. These languages have to be selected manually and spend points on them, even though it is written even in the code that they have to know these languages without selecting them in the list.

**Comment by YakumoChen** [comment]
I haven't reproduced that problem. You would have to spend the points regardless, default languages still take up language points.

**Comment by tf-4** [comment]
Man I'm just closing all of your shit where you're so weirdly aggressive, learn to write issue reports without being an ass about it
