### ISSUE TITLE
Slimes wont eat

### ISSUE THREAD

**Issue by ReiannaWinters** [Skyrat-SS13/Skyrat-TG#13691]
Reporting client version: 514.1582

## Round ID:
5395

## Reproduction:

Xeno slimes do not want to eat even when forced in area with monkies and nutrition is going down

**Comment by Jolly-66** [comment]
Fixed in #13664

**Comment by YakumoChen** [comment]
Needs more details

**Comment by YakumoChen** [comment]
As far as I can tell unless there is more details, this is not a consistent issue. I can go into a round right now and probably view xenobiology operating just fine.

**Comment by RatFromTheJungle** [comment]
@tf-4 this stopped with the DDOS
