### ISSUE TITLE
You cannot change the layout of the markings

### ISSUE THREAD

**Issue by Lizzzard26** [Skyrat-SS13/Skyrat-TG#13726]
## Testmerges: 
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e2ed90f05b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

## Reproduction:
1. Head to character setup...
2. Now head to augments...
3. Cry
There is no button to move the marking up or down, you have to completely reselect the markings in the correct order.
Every server has such a function, but another "coder" decided to cram his creation in without completing it to the end - I'm talking about the new character editor that appeared half a year ago.
![image](https://user-images.githubusercontent.com/102904016/169313951-949ea0c4-154d-4ec3-abd8-2574c936d46d.png)

**Comment by tf-4** [comment]
Make this less weirdly hostile
