### ISSUE TITLE
"Body tonage" marking is missed

### ISSUE THREAD

**Issue by Lizzzard26** [Skyrat-SS13/Skyrat-TG#13724]
## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e2ed90f05b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)

## Reproduction:
1. Head to the character setup
2. Choose a body tonage
So, there is body tonage in the list, but it wont work. Choosing it will not change any pixel at your character.

**Comment by tf-4** [comment]
Dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/13188
