### ISSUE TITLE
Missing walls on Tram

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#13807]
Reporting client version: 514.1582

## Round ID:
5432

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction: In maintenance, there are 2 missing walls under arrivals, depicted in this image
![image](https://user-images.githubusercontent.com/59770685/169696383-40208e59-485d-4adf-8a28-bd31925ba7c0.png)

**Comment by tf-4** [comment]
Fixed in a map reset
