### ISSUE TITLE
Engineer PDA's Start with Ampcheck, but don't support it

### ISSUE THREAD

**Issue by CCorvet** [Skyrat-SS13/Skyrat-TG#13829]
Reporting client version: 514.1583

## Round ID:
5441

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:

As above. Engineering PDA's start with Amp check which makes sense, however when trying to open it that fails and message "A.R.I.D (Station Engineer) flashes a "Hardware Error - Incompatible software" warning." Appears.

**Comment by JohnFulpWillard** [comment]
fix is up https://github.com/tgstation/tgstation/pull/67245
