### ISSUE TITLE
Improvised shotgun sprites are borked

### ISSUE THREAD

**Issue by CCorvet** [Skyrat-SS13/Skyrat-TG#13833]
Reporting client version: 514.1583

## Round ID:
5443

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:
Craft/Spawn an improvised shotgun
Use eyes to see, than anything past the stock, is not there. Making the gun just a stock.

**Comment by vinylspiders** [comment]
@Jolly-66 This is also fixed, likely by https://github.com/Skyrat-SS13/Skyrat-tg/commit/af778bae0a4e57e2d450e561205dfe1941e59f2c

![image](https://user-images.githubusercontent.com/13398309/228651964-c4c65adc-2f58-4ba6-8c4e-b8f927629bf5.png)

Sorry for all the pings, I am just going through the issues and seeing what is and still isn't one. I am on a fool's errand to get the number of issues <100.
