### ISSUE TITLE
Silicon brains are deleted when body is destroyed by blobs

### ISSUE THREAD

**Issue by Cecily-C-Catherine** [Skyrat-SS13/Skyrat-TG#13851]
## Round ID:
5447.

## Reproduction:
When killed by a blob your body and brain are both permanently deleted.

**Comment by YakumoChen** [comment]
Not a bug. 

Blob attack Gibs dead borgs. Borg corpses would impede movement otherwise. Assuming if left behind a brain regardless it would be consumed by blob expand like any item.
