### ISSUE TITLE
Space ruins broke, they do not spawn.

### ISSUE THREAD

**Issue by Ruediger4** [Skyrat-SS13/Skyrat-TG#13874]
## Testmerges: 
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e2ed90f05b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13835: 'Familiar lobbyscreen' by Gandalf2k15 at commit 9e76315c8d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13835)
[#13820: '[NONMODULAR] [Test] Relegates Round Timer To Observers' by Nerev4r at commit 6d92c4a240](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13820)

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13928
