### ISSUE TITLE
QM no longer has command access, other skyrat access changes reset

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#13899]
## Round ID: 5471

#13751 touched our modular skyrat jobs.dm, and removed many changes in favor of giving heads only access_weapons
All CMO changes were removed in favor of access_weapons, as well as CE, head of personnel, and the entire removal of our atmos techs edit.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/76465278/170422461-79d55a52-d2ff-45eb-a3e1-290fa080292e.png)
What the actual fuck
(From the mentioned PR, [modular_skyrat/master_files/code/datums/id_trim/jobs.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13751/files#diff-1d5e267336edc8e88527e45466f21930bddee8af7d51883c4d4d9bada861dcbf))
There is ZERO reason for this to have happened to a modular file

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13955
