### ISSUE TITLE
Owai's 10-19 Rebase Test Missing Feature/Report Thread

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#1391]
**Annoyances/"Bigger" Issues.**
- ~~Lots of chat issues. Regular chat breaking, dead chat breaking.~~
- ~~Ashwalkers cannot breathe on lavaland and also spawn with plantigrade legs.~~
- **(Added 10-20)** Would kinda like a debug area (Ghost Cafe) spawn) to help test stuff as non-admin.
- **(Added 10-23)** Positronic (and possibly, Drone) Ghost-Ping Consoles for Robotics.
- Someone mentioned not being able to drag things across catwalks. (Such as the Janicart)
- Flavortext/OOC limit might be smaller on rebase. Needs testing/checked.
- Double clicking stairs as ghost doesn’t give option to go up or down (like ladders)
- Someone mentioned that they cannot adjust hypospray amount.
- Emote star seems to only show up on long emotes, but not short ones.
- Voting might be a tad broken? (It didn’t mention anyone not voting, and pushed all non-votes into one of the options)

**Mildly Unimportant.**
- Status tab does not list connected players.
- Different jobs. (Brig Phys, Synthetic Repairer, ect.)
- Someone mentioned the metric unit measurements for size.
- Some sound effects are a bit weird now. (Gasp, Cough, Sneeze, Sigh)
- Bluespace Techs drop Standard Batteries when they peace out.
- Some maps are missing cryo cells (Ice Box)
- Pubby Perma is SMOOOL.
- People take burn damage in metalstation freezer.
- **(Added 10-20)** Several Spraypaints are probably missing, such as paw prints, but I forgot to check.

**Possible Clothing Issues**
- People mentioning Polychromatic stuff is Donator Only
- Fishnet Stockings don’t exist. (Underwear/socks?)
- Requests for berets and departmental winter coats.
- Tennis Balls not on loadout.
- Nurse Outfit
- Jeans and Chaplain may not be working with digi legs.
- Egyptian Chaplain Clothes missing from vendor.

**Character Customization**
- ~~Angel / Dragon wings disappear when looking to side.~~
- **(Added 10-20)** Luminescent Eyes will turn back on by themselves if toggled off, if you move or change direction at all.
- Slime People apparently do not start with shapechange.
- Several Quirks are missing. (Synthetic, Monophobia, Coldblooded, ect.)
- Language Customisation Missing? (Was in last test.)
- Food Likes/Dislike Customisation
- Two mute perks. Mute (+2) Tongue-Tied (0)
- Everyone seems to get navigationally challenged trait, even if its turned off. Is it a pref hidden somewhere?

**Requests**
- **(Added 10-21)** It would be nice if the character preview showed floor tiles, or had a selectable backdrop that wasn't pure black.
- **(Added 10-21)** Someone mentioned that it would be cool for pepperspray to be more useful. As it stands now, using any eyewear basically nullifies it, even if it would (realistically) allow you to still get peppersprayed. (IE: Single Eye Medihuds, Eyepatches, ect.)

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1392
Regarding ashwalkers and wings
