### ISSUE TITLE
Borers can teleport around if they scoot under a door while in a host

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#13936]
Reporting client version: 514.1582

## Round ID:
5481

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NONMODULAR] [Test] Relegates Round Timer To Observers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13820)
- [Revert "[MIRROR] Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time) [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13885)
- [[WIP] [MDB IGNORE] [MODULAR] BlueShift Airlock Audit + More](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13888)
- [[TM ONLY] Hides ongoing vote count from non-admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13856)

**Comment by Erokusan** [comment]
Nevermind just tested, they can't do it to doors on screen

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13930
