### ISSUE TITLE
Stacking machine makes materials with numerical values (Iron, Glass, Gold), dissapear into thin air.

### ISSUE THREAD

**Issue by CCorvet** [Skyrat-SS13/Skyrat-TG#13977]
Reporting client version: 514.1584

## Round ID:
5494

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Revert "[MIRROR] Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time) [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13885)
- [[TM ONLY] Hides ongoing vote count from non-admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13856)
- [Fixes arrivals on all maps](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13965)

## Reproduction:

Put items containing these materials, or just materials in sheet form on the belt in front of the recycler.
Turn on the belt
Watch, as the materials get recycles by the recycling machine, but when they pass the stacking machine, they dissapear without a trace.
They are not visible in the stacking machine console.
Keep in mind, other materials that don't have numerical values and cant be inserted in autolathes/ore silo do not face this issue. Such as cardboard, monkey hide. So it is likely an issue with translating numerical material values into sheets in the recycler, and/or storing the numerical variables.

**Comment by GoldenAlpharex** [comment]
This actually isn't an issue, the stacking machine is simply directly connected to the Ore Silo, so everything that's compatible with it, is stored there automatically, through bluespace shenanigans. :)
