### ISSUE TITLE
Down-scaling a sprite fucks with emissive markings.

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-TG#14037]
The following is a series of screen snips i took of a character with Plain marking emissive's on every single limb in the augments menu with the sprite scale at 0.81 (0.8 flat is kinda bugged aswell and doesn't change the sprite at all from what i can tell)

Snips taken in the cave in the ghost cafe by the mini shuttle you spawn in at

![0 81 emissive left](https://user-images.githubusercontent.com/58378414/171331559-05d4932a-e629-4a51-b0a2-03b0ba86995e.PNG)
![0 81 emissive north](https://user-images.githubusercontent.com/58378414/171331560-22924162-0f8b-4a2b-9d14-a05f28658e9f.PNG)
![0 81 emissive right](https://user-images.githubusercontent.com/58378414/171331561-3b903016-3677-4f11-ad38-a80286d1c7fc.PNG)
![0 81 emissive south](https://user-images.githubusercontent.com/58378414/171331562-28441da9-522e-4e1d-a7b8-7583079bee6b.PNG)

**Comment by YakumoChen** [comment]
In other news, downscaling a sprite without actually changing the sprite resolution makes the downsized sprite look like shit in every single aspect.

More at 11.

**Comment by tf-4** [comment]
Yeah kind of see above, really. Downscaling generally looks bad. This is a much more generic issue than emissives.
