### ISSUE TITLE
High-vis armored vest can't hold the same items.

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#14077]
## Reproduction:

 The high vis armored vest can't hold things like disablers, batons or any gun for that matter, making it practically useless while being very fashionable. PLease fix.

**Comment by YakumoChen** [comment]
what's the item's full name?

**Comment by Mithrun** [comment]
High vis armored vest 
![HV](https://user-images.githubusercontent.com/75141807/171995437-8a5044b1-e459-46fc-bfcf-f2385a95898f.png)

**Comment by YakumoChen** [comment]
From the code, this seems intended. It does not have much in the way of functional armor.

Fashion over function I guess.

**Comment by Mithrun** [comment]
It renders it pretty much unusable. What can it even hold?

**Comment by YakumoChen** [comment]
Nothing. Small o2 tanks
 It's just a lightly armoured cosmetic suit

Try wearing a secbelt
