### ISSUE TITLE
Test round feedback, missing features, and bugs discovered from 10/19/2020

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#1408]
When I play test rounds, I take notes. Here's what I have for the most recent one.

Welcome screen is missing the character name. This might seem like a small thing, but it's nice to confirm you have selected the correct character you wish to spawn as.

Pixel shifting is missing, this is a much beloved feature.

Some functions of alt clicking a tile to list and interact with all items on it are not working. This is a major critical quality of life item. More testing is needed, as it seems to work partially but not the same was as on skyrat-cit.

Antag OOC would be nice to bring over.

Bug: security tech armor accidentally got ported over.

Voting is not working correctly. Every time I've attempted it, which is several test rounds on multiple days, it's not taken my vote. The links do not highlight to confirm selection, and the counters don't change, which leads me to believe it's not working. It obviously works for some people, but there are other reports of it not working.

Antag objectives... these need a major skyrat edit if TG is to become the new main. Many involve round elimination or highly disruptive activities. Some of them are in disagreement as well. In the ling round that had to be abandoned for a server restart, the changelings had a team objective, to replace an entire department with changelings. However, each changeling had a different department listed for their team to take over, and this would have been functionally impossible to achieve as a result. It also only put in three lings for an otherwise very crowded round, so antag scheduling probably needs a look at too.

**Comment by Owai-Seek** [comment]
As a note, pixel shifting exists, but the hotkeys for it are now different.

**Comment by ShadeAware** [comment]
>Security techarmor got accidentally ported over
Go fuck yourself.

**Comment by ShadeAware** [comment]
_Bug: security tech armor accidentally got ported over._

Don't try and be cheeky and think you're funny. If you have an issue, take it to me directly. Trying to be funny just makes you look like a cunt.

**Comment by SpookyTheFox** [comment]
> 
> 
> _Bug: security tech armor accidentally got ported over._
> 
> Don't try and be cheeky and think you're funny. If you have an issue, take it to me directly. Trying to be funny just makes you look like a cunt.

While that statement was intended for humor, it is an issue. On previous discussion, I was led to believe tech armor and other major balance failures would not be ported. Some of the issues with it are being thick material, having flash and sechud capability, and protecting limbs it's not supposed to, while not correctly applying things that would debuff armor of this grade, like insulation penalty and EMP vulnerabilities. The intended effect could have been achieved by giving security one of the many glove options with protection, instead of giving them something that lets them take thermal vision without penalty and negates all balance and mechanics behind buying more capable armor from cargo or obtaining it based on situation from the armory. It was clearly a mistake to bring tech armor to skyrat-cit, one I do not intend to repeat with skyrat-tg.

**Comment by ShadeAware** [comment]
> 
> 
> > _Bug: security tech armor accidentally got ported over._
> > Don't try and be cheeky and think you're funny. If you have an issue, take it to me directly. Trying to be funny just makes you look like a cunt.
> 
> While that statement was intended for humor, it is an issue. On previous discussion, I was led to believe tech armor and other major balance failures would not be ported. Some of the issues with it are being thick material, having flash and sechud capability, and protecting limbs it's not supposed to, while not correctly applying things that would debuff armor of this grade, like insulation penalty and EMP vulnerabilities. The intended effect could have been achieved by giving security one of the many glove options with protection, instead of giving them something that lets them take thermal vision without penalty and negates all balance and mechanics behind buying more capable armor from cargo or obtaining it based on situation from the armory. It was clearly a mistake to bring tech armor to skyrat-cit, one I do not intend to repeat with skyrat-tg.

A good half of these things are flat out lies. Im not going to dignify you with a response if you're going to lie about the capabilities of the armor. Good day.

**Comment by atakiya** [comment]
Closing because of stale, only left issue is 
> Welcome screen is missing the character name

That may be fixed soon. Feel free to open a separate issue for that if you want to as well.

Atomizing issues into one topic each is preferred to keep an overview over what is relevant.
Simply said, one issue per feature/bug.

Thank you for the feedback nonetheless.
