### ISSUE TITLE
Imperial Enclave Ship airlock doors have wrong access

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#14136]
Reporting client version: 514.1582

## Round ID:
5580

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Revert "[MIRROR] Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time) [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13885)
- [[TM ONLY] Hides ongoing vote count from non-admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13856)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)

**Comment by ghost** [comment]
Fixed by removal, Enclave is gone 🦀
