### ISSUE TITLE
Admins unable to send HM (headset messages) to silicon

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#14164]
Reporting client version: 514.1582

## Round ID:
5588

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Revert "[MIRROR] Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time) [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13885)
- [[TM ONLY] Hides ongoing vote count from non-admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13856)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)

**Comment by GoldenAlpharex** [comment]
I feel like that isn't a bug per say, since they indeed do not have headsets.

Regardless, it's an upstream issue, if anything.

**Comment by Zergspower** [comment]
Looks like Headset Message only checks for Human/Carbon rather than anything else
