### ISSUE TITLE
Sprite Graphical Bug, with Welding helmet and Atmospheric gas mask

### ISSUE THREAD

**Issue by Sethnov** [Skyrat-SS13/Skyrat-tg#1424]
New to GitHub, but I did find issues on the big rebase test, of the year of our lord October 19th, 2020.
Number one: as playing as a character with a big beak for their snout, the welding helmet or atmospherics gas mask will cause it to get removed. the red dude to the right. 
![bug 1](https://user-images.githubusercontent.com/64242857/96806524-52f11500-13e2-11eb-8434-d5382a07032c.PNG)

Number two: small issue, but the sprite preview on the character appearances are a bit off compared to the ingame sprite size character.

**Comment by Azarak** [comment]
Things that cover your face, remove your snout from rendering too, but instead use a different sprite for the clothing itself to make it seem like its fitted. You get issues this way or the other way. Some masks shouldnt cover your face, much like the welding one I guess

**Comment by Funce** [comment]
If this is still an issue let me know.
