### ISSUE TITLE
Lizard snouts don't seem to take color customization

### ISSUE THREAD

**Issue by Ebin-Halcyon** [Skyrat-SS13/Skyrat-TG#14263]
Reporting client version: 514.1583

As it says on the tin, don't seem to be taking custom colors.

How it should look:
![image](https://user-images.githubusercontent.com/81479835/173210934-35a8e492-b03a-4be3-af9f-82d35008ea24.png)

What it looks like currently:
![image](https://user-images.githubusercontent.com/81479835/173210945-8c0f493e-f409-4ec4-959f-602b2ad98373.png)

Most likely a result of the organ refactor TM

## Round ID:
5636

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Fleshmind [ALPHA]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[TEMP MIRROR] [DNM] Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14206)
- [[MIRROR] This tail refactor turned into an organ refactor. Funny how that works. [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14017)

**Comment by YakumoChen** [comment]
Fixed by #14017
