### ISSUE TITLE
Issue with Wings being Flesh Coloured

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#14275]
## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 30ce45112f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14023: 'Fleshmind [ALPHA]' by Gandalf2k15 at commit 90ec784c26](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)

## Reproduction:
Humanoid/Anthromorph and I would hazard any other species reliant on Mutant Colours for skin, wings used on those species appear to use the first mutant colour (colour of skin) instead of their own colour assignments. This appears to be erratic and affecting some wings (like harpy, feathered, fairy) but not others (like dragon wings).

**Comment by YakumoChen** [comment]
Fixed by #14017 unless server is not updated?

**Comment by YakumoChen** [comment]
@GoldenAlpharex

**Comment by TetrakoHateThis** [comment]
This issue only began after #14017 was merged, actually.
