### ISSUE TITLE
Vox Spine Options Not Showing

### ISSUE THREAD

**Issue by VeteranKyl** [Skyrat-SS13/Skyrat-TG#14308]
## Round ID:
Issue started on 6/14. Unsure of exact round ID.

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit eeec0a6cf8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14023: 'Fleshmind [ALPHA]' by Gandalf2k15 at commit f27d670488](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#13400: 'Vox version Beanyvox' by Gandalf2k15 at commit 4898294f26](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13400)
[#14138: '[NON-MODULAR] [CONFIG] Prisoners now scale based on the security population. Defaults to 2 Prisoners for every Security person, maximum of 12.' by Iamgoofball at commit f4fe9c3fbe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14138)

## Reproduction:

The option to add a colored tip, bands, or stripe to vox tails though the spines option of the character creator no longer works. Selecting any option doesn't show in the character preview or in game. In the example picture, the character should have a white tipped tail, but despite having that option and color selected, it doesn't apply to the sprite.

![Vox Tail](https://user-images.githubusercontent.com/27029989/173527687-f0408eb8-f2ea-44d6-96a9-e14c4d60bb3a.png)

**Comment by Zergspower** [comment]
Resolved
