### ISSUE TITLE
Doors For Science Guard Don't Work On Delta Station

### ISSUE THREAD

**Issue by SackThing** [Skyrat-SS13/Skyrat-TG#14347]
## Reproduction:

Science Guard doors do not open for Science Guard ID on Delta Station.
The door was replaced by actual Security doors for some reason, so now Science Guard doesn't have access to them. They have to be amended at HoP every round and it's tedious if there HoP is too busy for that during a round or there is no HoP.
![ShareX_2022-06-16_11-21-20](https://user-images.githubusercontent.com/69650263/174104416-a10f0fb6-92fa-42b8-9992-321fc9d0aa7d.png)

**Comment by Jolly-66** [comment]
Should be fixed with a few upstream PRs that occurred, and with some recent changes down here. Ping me otherwise if this isn't the case.
