### ISSUE TITLE
Digitigrade legs not working for species that don't inherently have the option

### ISSUE THREAD

**Issue by Sy-zz-nthe-zz-ticF-zz-ox** [Skyrat-SS13/Skyrat-TG#14367]
Reporting client version: 514.1583

## Round ID:
5683

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Fleshmind [ALPHA]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Vox version Beanyvox](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13400)

## Reproduction:
1. Open a character as any of these species:
human
ethereal
felinid
fly
mothman
plasmaman
podperson
dwarf
ghoul
skrell
xenomorph hybrid
ipc
synthetic humanoid

2.Turn on mismatched parts to attempt to select digitigrade legs as an option
3.See that the option is not there, despite mismatched parts being turned on

![see](https://user-images.githubusercontent.com/82522672/174160873-a00d53ee-7f44-4a5b-b262-cd53767a391f.png)

**Comment by desertmote** [comment]
is this a bug?

**Comment by Sy-zz-nthe-zz-ticF-zz-ox** [comment]
considering how this worked up until very recently, i'd hope so

**Comment by Sy-zz-nthe-zz-ticF-zz-ox** [comment]
> is this a bug?

Considering how this worked up until very recently, i'd hope so, cause it's a feature I know a lot of people use

**Comment by Zergspower** [comment]
Less a bug and more a feature, they'll just need the digi allowed flag added
