### ISSUE TITLE
Prefs menu felinids are Sphynx cats

### ISSUE THREAD

**Issue by Fikou** [Skyrat-SS13/Skyrat-TG#14376]
REPRODUCTION!!!
![image](https://user-images.githubusercontent.com/23585223/174201717-da42a926-0ec4-4dcb-a8ec-d1c684d5066b.png)
![image](https://c.tenor.com/b0GB8KqB68YAAAAS/bingus-bingus-cult.gif)

**Comment by dawsonkeyes** [comment]
terrifying

**Comment by tf-4** [comment]
feature
