### ISSUE TITLE
Default keybinding for IC radio and whisper are the same. (Y)

### ISSUE THREAD

**Issue by UntoldTactics** [Skyrat-SS13/Skyrat-TG#14382]
## Round ID:
5688

## Testmerges:
#12529 
#10823
#14023
#13400 

## Reproduction:
Reset to default keybinds. See that both whisper and IC radio share the same default keybinding. I suggest V for radio or something.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/commit/0428f4a19c98f2510c058368175680c3f24d1c63

This has been fixed
