### ISSUE TITLE
Size select bar goes to 0.8 size, but only actually allows you to change your size to 0.805

### ISSUE THREAD

**Issue by weesnaw-ops** [Skyrat-SS13/Skyrat-TG#14394]
## Reproduction:

Trying to set your character size to 0.8 does nothing, even though the slider goes that low. If you manually type out 0.805, that is the smallest you can go.

**Comment by Iamgoofball** [comment]
This was an issue I accidentally introduced when I made the selection go in increments of 0.5, I'll take a look at a potential fix.
