### ISSUE TITLE
Heterochromia eyes change side based on what way you are facing

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#14403]
## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14023: 'Fleshmind [BETA]' by Gandalf2k15 at commit 60a1461cb4](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#13400: 'Vox version Beanyvox' by Gandalf2k15 at commit b6f5d423c1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13400)
[#14290: 'Disables bureaucratic error' by tf-4 at commit b2c27333cc](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14290)

## Reproduction:
Use the heterochromia quirk. Face south. Left eye is colour X, right eye is colour Y. If you turn to face east, your sprite will show your visible right eye as Colour X. If you face west, your visible left eye eye shows Colour Y, meaning your eye colours flip when you face to either side.

https://i.imgur.com/p9WsAAd.png - Image example

**Comment by ghost** [comment]
Comedy. Easy fix, just needs the sides swapped to be correct.
God knows what .dmi its stored in tho

**Comment by nikita-chekistov** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/68730
