### ISSUE TITLE
alpha vox code moment

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#14450]
## Round ID: 
5740

## Testmerges:
 [#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit f0011870b2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14290: 'Disables bureaucratic error' by tf-4 at commit 735f7116da](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14290)
[#14431: 'Mutant touchups' by Gandalf2k15 at commit 2337f47b9d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14431)

## Reproduction:

Gib Alpha Vox to produce pink squares.

![image](https://user-images.githubusercontent.com/71103211/174933499-aaa34c1f-e1e5-4f45-ad97-8b5d478ea9db.png)

![image](https://user-images.githubusercontent.com/71103211/174933510-8993d6fd-8246-4a39-a843-31d39b662af2.png)

Putting said Vox through the SAD does not fix their body as well. Instead, it keeps it as a weird skinwalker human-skulldog thing.

Please don't fix this.

**Comment by Zergspower** [comment]
Resolved in current version
