### ISSUE TITLE
silver scale pirates don't have a shuttle covering???

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#14603]
## Round ID:
5808

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14501: 'ash ritual' by jjpark-kb at commit 1be6f7a64a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14501)
[#14431: 'Mutant touchups' by Gandalf2k15 at commit 2337f47b9d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14431)
[#13848: 'The Refactaur' by GoldenAlpharex at commit fa3bd0a1f8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14574: '[Half-Modular] Ashtongue for Ashwalkers' by Nerev4r at commit 1f1d2eda75](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14574)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)

## Reproduction: 
pirates went under the interlink shuttle on tram
comedy ensues

uncertain if this is because of the interlink shuttle or an oversight 
![image](https://user-images.githubusercontent.com/71103211/176247439-b37f8ff7-f674-496a-adf1-6830719d98dc.png)

**Comment by zeratino** [comment]
update: it's the interlink shuttle lol
![image](https://user-images.githubusercontent.com/71103211/176247759-f3f0a409-e24b-4c35-a736-4755e4227177.png)

**Comment by ghost** [comment]
This is probably good to close, the fools landed below a shuttle and had their roof stolen - a different issue than whats reported, AND an upstream one
