### ISSUE TITLE
Taur Sprites are Broken

### ISSUE THREAD

**Issue by StrangeWeirdKitten** [Skyrat-SS13/Skyrat-TG#14605]
## Round ID:

N/A

## Reproduction:

Wear anything taur related. It's no longer reading `SYLE_TAUR_ALL` on anything taur related sprite wise. Taur styles are no longer completely overwriting actual legs so there's going to be strange pixel overlapping. I _think_ taur styles are no longer actual legs.
 
![image](https://user-images.githubusercontent.com/95130227/176302635-ce9b5da8-4d70-49af-aebc-e157a051bc22.png)

**Comment by GoldenAlpharex** [comment]
The legs are fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848

**Comment by GoldenAlpharex** [comment]
That was fixed a little while ago.
