### ISSUE TITLE
Placing anything into the blade slot of a Crusaders Sheathe resets Ashwalker nightvision

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#14611]
## Round ID:

 5812

## Reproduction:

 When I place a Bone Knife or Bone Sword into the Sheathe, it just resets the nightvision, I dunno how else to say it.    EDIT: Taking things out also effects the nightvision

**Comment by ghost** [comment]
I--
How does this even happen, what?

Is this still happening as of 3 months since report? Does it happen with any storage item being quickdrawn?

**Comment by vinylspiders** [comment]
Not happening anymore from my testing.

**Comment by vinylspiders** [comment]
@lessthnthree Fixed upstream likely.
