### ISSUE TITLE
Abductors cannot Say emote

### ISSUE THREAD

**Issue by nevimer** [Skyrat-SS13/Skyrat-TG#14628]
## Testmerges:
The following pull requests are currently test merged:
#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7
#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899
#14501: 'ash ritual' by jjpark-kb at commit 1be6f7a64a
#14431: 'Mutant touchups' by Gandalf2k15 at commit 2337f47b9d
#13848: 'The Refactaur' by GoldenAlpharex at commit fa3bd0a1f8
#14574: '[Half-Modular] Ashtongue for Ashwalkers' by Nerev4r at commit 1f1d2eda75
#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe
#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430

## Reproduction:

Be an abductor and say emote as a test. `"jumps high and says*Hello!"` and `"jumps high!*"`- They will be replaced with the placeholder string "An interesting thing to say"

Try a me verb emote - works just fine.

**Comment by nevimer** [comment]
Is this fixed tho?

**Comment by Zergspower** [comment]
I think i misunderstood what you were implying - but it may be due to how their speech works as it's telepathy based and not an actual language. Just like how when you emote over a radio it will say 'An interesting things to say' over their head

**Comment by vinylspiders** [comment]
Confirmed still an issue, it is caused by this gross misuse of the tongue's `modify_speech` proc.

https://github.com/Skyrat-SS13/Skyrat-tg/blob/a9e4b404860353e04782e709f9a15fc915c4a37e/code/modules/surgery/organs/tongue.dm#L273-L290

If I ever fix this one, it'll be one of the last fixes remaining...requires rewriting abductor speech code from the ground up.
