### ISSUE TITLE
Bow (from Renaissance Crate) stops being able to be loaded with arrows.

### ISSUE THREAD

**Issue by Jezzared** [Skyrat-SS13/Skyrat-TG#14639]
Reporting client version: 514.1568

## Round ID:
5821

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [ash ritual](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14501)
- [Mutant touchups](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14431)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [[Half-Modular] Ashtongue for Ashwalkers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14574)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)

## Reproduction:
Trying to load an arrow into the bow will suddenly stop working. It's been happening across multiple rounds after using the bow and arrow for a while.

During this round, the bow of the Chaplain, Lizbeth Sunsong, stops being able to load arrows. Another member of the crew then attempts to load the bow, with no success. The other bow in the Vintage crate does not have this problem, and can load and shoot arrows fine. Something that happened between getting the bow and the point where an arrow was attempted to be placed into it must have broken the bow in some way.

**Comment by Zergspower** [comment]
Resolved in current version
