### ISSUE TITLE
Drider Taur Greyscale

### ISSUE THREAD

**Issue by Resreep** [Skyrat-SS13/Skyrat-TG#14638]
## Round ID:
34164182

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#14501: 'ash ritual' by jjpark-kb at commit 1be6f7a64a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14501)
[#14431: 'Mutant touchups' by Gandalf2k15 at commit 2337f47b9d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14431)
[#13848: 'The Refactaur' by GoldenAlpharex at commit fa3bd0a1f8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14574: '[Half-Modular] Ashtongue for Ashwalkers' by Nerev4r at commit 1f1d2eda75](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14574)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)

## Reproduction:
With a character with a drider taur body, the taur half will become entirely greyscale/white, rather than following the mutant colors. While on my original character, I was able to become entirely naked, including underwear, to temporarily fix the bug until certain clothing parts were adjusted, such as head and eye wear. On a new character though, the drider taur half was trapped in greyscale and didn't register the taur colors.

**Comment by GoldenAlpharex** [comment]
Is this still an issue you can encounter?

**Comment by vinylspiders** [comment]
Could not reproduce--was likely fixed with all the refactors. If this is still happening please let us know and provide some more details to help us reproduce the problem.
