### ISSUE TITLE
High luminosity eyes beam not following owner

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#14685]
## Round ID:
5842

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 360dfe72a7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13848: 'The Refactaur' by GoldenAlpharex at commit f26740d174](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#14625: 'Railroads' by jjpark-kb at commit 234abb4ffc](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 6d1a9d2338](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)

## Reproduction:
Equip high luminosity eyes, walk in a straight line, have the light not follow.

**Comment by kcrash201** [comment]
Heard rumors that Lavaland creatures that produce light have similar issue, unsure.
Connected to pAI light Issue

**Comment by kcrash201** [comment]
[MIRROR] Fixes tablet lights [MDB IGNORE] #13946
Has been suspected as a cause, however it is perhaps upstream?

**Comment by Zergspower** [comment]
Eyes seem to be working fine currently - though another lighting issue exists this particular one is gold

**Comment by kcrash201** [comment]
From my experience using eyes for the past months, it is not fine, unless it's another lighting bug that is effecting the eyes.
I will have to test myself later to see if a recent push had indeed fixed them without me realising.

**Comment by Zergspower** [comment]
Reconfirmed issue after checking - though i feel this may be an UPstream issue since i dont think these eyes are unique to us

**Comment by kcrash201** [comment]
If it's an upstream issue I really hope they fix it some day
