### ISSUE TITLE
skyrat action button missing

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-TG#14683]
## Reproduction:
1. Grab a Gun that have safety on it such as the laser carbine(/obj/item/gun/energy/laser)
2. No safety toggle button apper at top left corner of the screen
3. Attempt to fire the weapon only get "Safety on!" message

- gun firing mode toggle are missing
- the return button you get from spawning as a Bluespace Technician also missing
- more other action button
Possibly caused by #14666

**Comment by tf-4** [comment]
The server hasn't been updated since that was merged

**Comment by WitherVictor** [comment]
@tf-4 Ye, but we're local host, so we found that problem and report this like https://github.com/Skyrat-SS13/Skyrat-tg/pull/14168

**Comment by tf-4** [comment]
Ah gotcha
