### ISSUE TITLE
after a alt-clicking a tile, the new tab never leaves

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#14698]
what it says on the tin; made worse by the tab being open causing persistently growing lag

Round: 5484

## Testmerges:

#12529: '[MODULAR] Status Indicators with Preference' by nevimer 
#10823: 'Database revision revert' by Gandalf2k15 
#13848: 'The Refactaur' by GoldenAlpharex 
#14647: 'Update orbit.dm' by Gandalf2k15 
#14625: 'Railroads' by jjpark-kb 
#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 
#14607: '[NO GBP] Final adjustments to on-mob sprites for racks.'
## Reproduction:
spawn in; alt click the floor, walk away from it

**Comment by Zergspower** [comment]
Resolved and unable to reproduce - Line of sight plays a factor here too
