### ISSUE TITLE
lavaland plants arent harvestable

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-TG#14697]
## Testmerges: [#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e700c26a67](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13848: 'The Refactaur' by GoldenAlpharex at commit f315d27c8b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#14625: 'Railroads' by jjpark-kb at commit bdfcda0852](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14607: '[NO GBP] Final adjustments to on-mob sprites for racks.' by Ghommie at commit fcf0fa958f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14607)

**Comment by ghost** [comment]
ok uh is this happening upstream if so "oh no i fucked up"

**Comment by Jolly-66** [comment]
Upstream issue, see https://github.com/tgstation/tgstation/issues/68158
