### ISSUE TITLE
Ice box, Gas Miner Beacon not working in atmospherics area

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#14707]
Reporting client version: 514.1582

## Round ID:
5853

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
- [Railroads](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[NO GBP] Final adjustments to on-mob sprites for racks.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14607)

**Comment by Zonespace27** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/14711
