### ISSUE TITLE
Heretic's Flesh Stalker not working

### ISSUE THREAD

**Issue by Ruediger4** [Skyrat-SS13/Skyrat-TG#14732]
## Testmerges:
The following pull requests are currently test merged:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e700c26a67](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13848: 'The Refactaur' by GoldenAlpharex at commit a71747698b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#14625: 'Railroads' by jjpark-kb at commit bdfcda0852](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14679: 'Automapper - IMPORTANT, READ ME [MDB IGNORE]' by Gandalf2k15 at commit adde3feb0b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14679)

## Reproduction:
Be a Flesh Stalker (Heretic Flesh Path, Lonely Ritual)
You can't disguise. You can EMP, you can jaunt, but can't disguise which is the main point of interest of a Flesh Stalker.

I think it COULD be a Skyrat problem instead of TG's.

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/190931446-bc661210-5f0b-4593-82fb-d5f884c75121.png)
working in current version
