### ISSUE TITLE
Chemical Carpet bugged

### ISSUE THREAD

**Issue by Siefer21** [Skyrat-SS13/Skyrat-TG#14757]
Reporting client version: 514.1578

## Round ID:
5881

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
- [Railroads](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Automapper - IMPORTANT, READ ME [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14679)

## Reproduction:
The chemical Carpet seems to not be working at all from what I could tell from the round. My plan during the round was to use the lucky pill I started with to move to a bucket and mop around bridge with it. didn't work then. tried putting in cleaner bottle and spraying. also didn't work. then finally tried putting in smoke grenade and didn't work as well. Its been awhile since I've used it but it should have worked with at least one of these methods. here is the description straight from Tgstation wiki: Creates a carpet on the floor. Best used in a [smoke] machine/[grenade] or spray bottle. Ingredient in [Barber's Aid].
It usually just makes bog standard red carpet on the floor atop the tiles, and is something I have noticed not working on floors as well as space lube working like water lately but thats another thing I'm not sure is an issue.

**Comment by Zergspower** [comment]
fairly certain this is fixed, ping me if it's not
