### ISSUE TITLE
Tram Circuitry: Off The Rails

### ISSUE THREAD

**Issue by Resreep** [Skyrat-SS13/Skyrat-TG#14753]
## Round ID:
5879

## Testmerges:
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit e700c26a67](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
[#13848: 'The Refactaur' by GoldenAlpharex at commit a71747698b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#14625: 'Railroads' by jjpark-kb at commit bdfcda0852](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit fdd6a814fe](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14679: 'Automapper - IMPORTANT, READ ME [MDB IGNORE]' by Gandalf2k15 at commit adde3feb0b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14679)

## Reproduction:
Using circuitry, Tram Station's Tram Control console can be connected to a circuitry shell, allowing someone to send the tram through the shell to a pre-set destination, utilizing the preset Tram Landmarks, according to my understanding. The three set landmarks are West Wing, Central Wing, and East Wing, the same as the console states. But when in game, when sending the tram to the East Wing, and potentially the West Wing, the tram will simply drive through any existing obstacles to arrive at a destination different from the console's own three definitions of the landmarks. Both West and East landmarks were in space, along some scaffolding, almost as if it was an intentional place. I don't know code more than enough to vaguely look through the server files for a vague picture. The fact that the tram stopped at these spots rather than continue on indefinitely leads me to assume that it's due to the landmarks being improperly placed.

**Comment by Jolly-66** [comment]
Certified upstream issue.

Probably fixed by,
https://github.com/tgstation/tgstation/pull/68572

**Comment by Jolly-66** [comment]
Also noted upstream as well,

https://github.com/tgstation/tgstation/issues/68541
