### ISSUE TITLE
Tram interlink connection broken, does not land right

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#14799]
Reporting client version: 514.1582

## Round ID:
5904

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
- [Railroads](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14625)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Automapper - IMPORTANT, READ ME [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14679)

**Comment by Jolly-66** [comment]
This should be fixed whenever the server updates, but I'll leave this open just in case it isn't.

**Comment by Jolly-66** [comment]
I'm going to say this has been fixed, per my own testing. If this issue remanifests please ping me on Discord.
