### ISSUE TITLE
Barber(Fab-O-Vend) sprays and fur dyer are broken 

### ISSUE THREAD

**Issue by MaxStirlitz** [Skyrat-SS13/Skyrat-TG#14841]
## Round ID:
N/A

## Testmerges:
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#13848: 'The Refactaur' by GoldenAlpharex at commit b17fe20bf9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#12529: '[MODULAR] Status Indicators with Preference' by nevimer at commit 213469911e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)

## Reproduction:
Upon using on character: Quantum hair dye, Baldium spray, Barber's aid, Super barber's aid - nothing happens

Electric fur dyer does not update sprites after using it on character

**Comment by Jolly-66** [comment]
Might be an upstream issue?

May be fixed by
https://github.com/tgstation/tgstation/pull/68580

**Comment by MaxStirlitz** [comment]
Still an issue

**Comment by Zergspower** [comment]
Tested them all and seems resolved, here have an abomination 
![image](https://user-images.githubusercontent.com/22140677/193701738-40d16109-d216-41f5-b9f2-6a04b7272682.png)
