### ISSUE TITLE
Synthetic-Taurs have organic legs

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat-TG#14861]
## Testmerges: 
[#13848: 'The Refactaur' by GoldenAlpharex at commit b17fe20bf9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)

## Reproduction: 

Be a synthetic Lizard with Nagatuar, weld or cable coil your **legs**. You will burn yourself. 

further testing required, unknown if normal synthetics are affected. ( I assume not since this is first time hearing of this)

**Comment by GoldenAlpharex** [comment]
I guess that makes sense, they don't inherit the biotype of the mob they're attached to. I'll have to think of a good way to fix that.

**Comment by Strazyplus** [comment]
This bug still exists as of Christmas day 2022, **robo snek leg ouchies need medkit I want to weld my tail like a normal robot!**

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/19318 will fix this!
