### ISSUE TITLE
IPC parts selected to none still make you ijnvisible

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#14876]
Reporting client version: 514.1582

## Round ID:
5941

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)

**Comment by Zergspower** [comment]
Resolved in current version
