### ISSUE TITLE
Shuttle bug deleting crew

### ISSUE THREAD

**Issue by Microvolnovka19** [Skyrat-SS13/Skyrat-TG#14897]
The video says it's all. If a Shuttle Catastrophe happens when the emergency shuttle had already docked with the station, all of the crew on it dissapears.

Probably this event should be locked during evac.

https://user-images.githubusercontent.com/59139863/178948492-cac995ea-0070-4b4c-88cb-b56884a831f8.mp4

**Comment by Jolly-66** [comment]
I believe this is an upstream issue (and probably a dupe here?) 
I'll verify when I get time

**Comment by Iamgoofball** [comment]
Shuttle Catastrophe is blocked when the shuttle's already docked on stock /tg/. This might have something to do with the new events voting system down here instead.
![chrome_IWOByhRMFr](https://user-images.githubusercontent.com/4081722/179429784-3e3477e6-bfd8-4705-8318-8b19d1d4b9f9.png)

**Comment by Zergspower** [comment]
Resolved in current version
