### ISSUE TITLE
Issues with Jumpsuits and Misc. Under when playing female Naga

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#14925]
Reporting client version: 514.1583

## Round ID:
5976

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)

## Reproduction:

Be Naga Taur. Equip anything from the Misc. Under tab or some from even the jumpsuit tab and most clothing in the general vendor

One of two outcomes will happen.

1. The clothing will look like an atmos tech jumpsuit with the bottom half cut off (This is a green sweater)
![image](https://user-images.githubusercontent.com/75050485/179330531-ba12231c-b51a-401a-bce6-54d9152b2e1c.png)

2. The uniform becomes horribly cut off below the waist and the top becomes either a mess of colour or an entirely different top.
This is the common issue for suit skirts or just anything that has a skirt

This Example is equipping the red plaid skirt. Looks like it has taken the tutu design.
![image](https://user-images.githubusercontent.com/75050485/179329764-1c3bae2f-944a-450a-a85c-e5637fcc6e0a.png)
![image](https://user-images.githubusercontent.com/75050485/179329215-0d834958-a802-4773-9deb-249977241cc6.png)

As a side issue. Any Camo clothing worn will have no skirts while the top half works fine If its able to bypass these two issues
Tacticool was used in testing:
Real: 
![image](https://user-images.githubusercontent.com/75050485/179329633-6b7e709e-333c-4649-8951-ab8de52d9339.png)

Chameleon:
![image](https://user-images.githubusercontent.com/75050485/179329717-a98ec888-f741-4a85-a838-708bff4d3ca6.png)

**Comment by GoldenAlpharex** [comment]
I don't think I can fix the Chameleon issue right now, that'd have to be in a future PR, however, I'm looking into this issue at the moment, since I've had a few reports on it.
