### ISSUE TITLE
Dullahans unable to see emotes/looc

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#14940]
## Round ID:

5987

## Reproduction:
Title

**Comment by GoldenAlpharex** [comment]
I'm very curious to hear about how you've noticed this one, especially considering how we don't run those on Skyrat, except on Halloween, which is in three months and a half.

**Comment by PeriwinkleBuddy** [comment]
Dullahans are listed in the Pride's Mirror and Magic Mirror (Lavaland and Wizards Den respectively)

**Comment by vinylspiders** [comment]
@Jolly-66 

![image](https://user-images.githubusercontent.com/13398309/231323578-08fda379-9441-44a3-af9a-b4eb9305d2ed.png)
 
Not sure which PR fixed this exactly, but both LOOC and emotes seem to be working. Can be closed.
