### ISSUE TITLE
Can't use headset in mechs

### ISSUE THREAD

**Issue by weesnaw-ops** [Skyrat-SS13/Skyrat-TG#14970]
## Round ID: 

5990

## Reproduction:

caused by https://github.com/Skyrat-SS13/Skyrat-tg/pull/14440

Cannot use headsets in certain mechs, like Maulers. It might be all mechs I don't know. It gives you the same message as if you were handcuffed.

**Comment by YakumoChen** [comment]
likely an upstream issue

**Comment by weesnaw-ops** [comment]
this meant to go upstream shit lol

**Comment by Zergspower** [comment]
Resolved in current version
