### ISSUE TITLE
Deadmin commands throwing Action ignored.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#14977]
Reporting client version: 514.1582

## Round ID:
5993

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)

## Reproduction: Does not seem to effect Auto deadmin just manual verb deadmin

 [https://cdn.discordapp.com/attachments/963186069522776094/998278572621967360/unknown.png](https://cdn.discordapp.com/attachments/963186069522776094/998278572621967360/unknown.png)

**Comment by GoldenAlpharex** [comment]
Will get fixed by https://github.com/tgstation/tgstation/pull/68983.

**Comment by GoldenAlpharex** [comment]
Already fixed by now!
