### ISSUE TITLE
Engineer Borg - Light Replacer cannot be refilled

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#14972]
Reporting client version: 514.1584

## Round ID:
5991

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)

## Reproduction:

Empty Engineering borg light replacer.

Try to refill it.

No error messages, or notices. Simply nothing happens.

**Comment by YakumoChen** [comment]
What are you refilling it with?
Have you tried using glass on it, using a recharger, using it on glass or lights?

**Comment by Zergspower** [comment]
Broken glass still works to fill, potentially a one-off isssue
