### ISSUE TITLE
HUDS, Prescription HUDS, do not exist, nor can they be picked in loadout

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat-tg#1499]
What it says on the tin, you can't even get these via research, unlike on main where they're freely available.

**Comment by Sigmar-alkahest** [comment]
pretty sure it was a thing done by Citadel? if i am recalling correctly, it is simply a matter of waiting for someone to either port the code for it or to recode it themselves.

**Comment by atakiya** [comment]
Closing, was fixed by #1865
