### ISSUE TITLE
Owai's 10-27 to 10-28 Rebase Test Observations

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#1501]
Mostly minor stuff this time around. Might condense all of my existing feature requests/bug reports into a single issue post since a lot of of the issues/features have been restored/fixed.

**10-27**

- Metal chairs are off-center, and are really hard to drag yourself/buckle onto. Also, picking them up gives you the old chair sprite.
- Trashbags, when worn on belt, show an odd purple belt around your waist instead of a bag.
- Decomposing Garbage doesn't seem to have a purpose? I wasn't able to find a way to clean it.
- Prisoners cannot latejoin.
- ~~Dark mode is really weird when you rejoin. Your top half will be light mode, but chat will be dark. (Probably Upstream Issue)~~
- Lolipops still leave bullet pellets behind. (Probably Upstream)
- Carrying is really weird, some things being similar to what I reported here on Citadel. I wasn't able to test as much as I would have liked. https://github.com/Citadel-Station-13/Citadel-Station-13/issues/11901

**10-28**

- Crab 17 protocol drains money way too fast, i’ve seen it drain 7-15% of funds every ~15 seconds, which means you have almost no time to deal with it. Assuming you lose 10% of your money every time it goes off, you lose all of it in 3 minutes.
- ~~When dragging a borg, specifically, drake/dogborgs, their sprite becomes off-center until they use Rest to fix it.~~
- Cryo Cells Don't delete a large amount of items. Specifically, PDAs. (I think it deletes the internal ID though.)
- ~~Light replacer not in Equipment Tab (QoL, Upstream)~~ (PR Open Upstream)
- Magi-carp can 1-hit KO people and can be spawned via slime core.
- QM isn’t command and doesn’t have command comms.
- Can’t seem to approve some requests at cargo. Have to manually re-order.
- When making a large order at cargo, it doesn't add total together. QoL
- Cannot make satchels with cloth.
- Mold creature corpses should self decay, it leaves behind a huge mess.
- I heard taur clothing was being weird, but didn't test it myself.
- (Added 11-5-20) I -believe the mechanic where you can pick up/wear pets does not exist.

(Supplemental Info)
Xenobio Carp bad.
```
/mob/living/simple_animal/hostile/carp/ranged/xenobiology // these are for the xenobio gold slime pool
	gold_core_spawnable = HOSTILE_SPAWN
	allowed_projectile_types = list(/obj/projectile/magic/animate, /obj/projectile/magic/teleport,
	/obj/projectile/magic/door, /obj/projectile/magic/aoe/fireball, /obj/projectile/magic/spellblade, /obj/projectile/magic/arcane_barrage) //thanks Lett1

/mob/living/simple_animal/hostile/carp/ranged/chaos/xenobiology
	gold_core_spawnable = HOSTILE_SPAWN
	allowed_projectile_types = list(/obj/projectile/magic/animate, /obj/projectile/magic/teleport,
	/obj/projectile/magic/door, /obj/projectile/magic/aoe/fireball, /obj/projectile/magic/spellblade, /obj/projectile/magic/arcane_barrage)
```
Borg Offset
![dreamseeker_PmT43UJAzo](https://user-images.githubusercontent.com/7543955/97617865-aff95600-19f4-11eb-8f2b-78f521b1eadb.png)
Chairs
![dreamseeker_bt3Tkof6A7](https://user-images.githubusercontent.com/7543955/97617413-1d58b700-19f4-11eb-8322-2c1f66d50f7e.png)
![dreamseeker_j11iZEhnS9](https://user-images.githubusercontent.com/7543955/97618675-b3d9a800-19f5-11eb-850a-9f50664a2eeb.png)

**Comment by Sigmar-alkahest** [comment]
can partially confirm the taur clothing bit, certain bits of clothing don't seem to show a sprite when worn by a naga for example, such as the qipao. have not checked other taur types as naga is generally the only one i use.

**Comment by Gandalf2k15** [comment]
Cyborgs are fixed dont worry.

**Comment by Gandalf2k15** [comment]
Half-darkmode is fixed upstream.
