### ISSUE TITLE
sec-belt gun-draw bug

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#15069]
## Reproduction:

spawn in, put a gun in the sec belt, leftclick to open the storage, it causes the right-click to draw to activate, and adds an empty storage UI to your screen that can't be closed (somtimes), and elsewise, just refuses to let you open the storage until you draw the gun

**Comment by Jolly-66** [comment]
Smells like an upstream issue by chance

**Comment by Paxilmaniac** [comment]
secbelt disablers are us only im fairly sure

**Comment by Zergspower** [comment]
Unable to replicate in current version - assumed resolved
