### ISSUE TITLE
Hemophages who run low on blood being slowed (akin to being hungry) for the rest of the round, even after refilling to nominal levels

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15067]
## Round ID:

6022
## Reproduction:
Basically what the title says. If your a hemophage (or probably a vampire) and you run low on blood (I think around 300/2000) you get a stamina debuff akin to being hungry, exept if you refill on blood, even to max, you dont get your speed back. I have no clue how the stamina system works so if this is intentional then thats kinda wack.

**Comment by vinylspiders** [comment]
Could not reproduce. This does not seem to happen anymore, possibly after the hemophage refactor. https://github.com/Skyrat-SS13/Skyrat-tg/commit/8905d13d8216ec3e4f241e859800f352313b85ec

**Comment by vinylspiders** [comment]
@lessthnthree fixed.

**Comment by lessthnthree** [comment]
Fixed

**Comment by vinylspiders** [comment]
@Jolly-66 found another one that can be closed. Hemophages have been revamped since this was opened
