### ISSUE TITLE
AI Custom Hologram doesn't register lizards

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#15075]
Reporting client version: 514.1582

## Round ID:
6031

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Update orbit.dm](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

**Comment by GoldenAlpharex** [comment]
Is this only reproducible with lizard characters, or can you reproduce it with anything else?

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/193700724-98a8b092-4331-4824-ab05-04f9f4816f6b.png)
