### ISSUE TITLE
Liquids in shot glasses not lining up with new sprites

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15094]
## Round ID:

6038
## Reproduction:

![ScuffedBooze](https://user-images.githubusercontent.com/108144396/180238979-1ea161fa-b43b-4d82-823c-3bd28fbec979.PNG)

**Comment by Jolly-66** [comment]
Smells like an upstream issue.

**Comment by Jolly-66** [comment]
https://github.com/tgstation/tgstation/issues/68798
