### ISSUE TITLE
Burning off rust with a welder doesnt blind you

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15097]
## Round ID:
N/A (I forgor and it doesnt really matter)

## Reproduction:
Your using a welder to burn some rust away, its self explanatory.

**Comment by Jolly-66** [comment]
Smells like an upstream thing.

**Comment by ghost** [comment]
Upstream, but I'm not complaining. God damn rust.

**Comment by Jolly-66** [comment]
https://github.com/tgstation/tgstation/issues/68796
