### ISSUE TITLE
Pocket Protector, bugged inventory and enlarged sprite

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#15091]
## Round ID:
6037

## Testmerges:
[#13848: 'The Refactaur' by GoldenAlpharex at commit 422fdba628](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#15028: 'Disable spiders from rolling in events' by Funce at commit 3f13c6b110](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)

## Reproduction:
Have pocket protector
Use pocket protector
Have inventory stuck open
Relog
Pocket protector enlarges

**Comment by kcrash201** [comment]
Unable to recreate anymore, may of been a one time issue

**Comment by Jolly-66** [comment]
Closing due to the above comment. If you can't replicate an issue anymore, please help us by closing your issue.

If this remanifests, please let me know.

**Comment by kcrash201** [comment]
Seen remanifested, but its a freak occurance, unsure exactly how its caused

**Comment by Jolly-66** [comment]
It may be an issue with relogging. Have you tried re-relogging to see if the issue continues/gets worst?

**Comment by kcrash201** [comment]
Will test next time it happens
