### ISSUE TITLE
Unable to fold up Body Bags

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15107]
## Round ID:

6042
## Testmerges:

[#13848: 'The Refactaur' by GoldenAlpharex at commit 422fdba628](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14601: 'Temporarily reverts the recent bust changes as per request' by Gandalf2k15 at commit 8ef5431430](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#14647: 'Update orbit.dm' by Gandalf2k15 at commit 7ea07af42b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14647)
[#15028: 'Disable spiders from rolling in events' by Funce at commit 3f13c6b110](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
[#15092: '[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?' by tf-4 at commit edb327a39d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
[#15078: '[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior' by Jolly-66 at commit f1933cdde5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
## Reproduction:
Theres no click to drag prompt, and dragging it onto myself doesnt do anything.

**Comment by Jolly-66** [comment]
Not an issue. They were moved to right click.
Theres also a PR on TG now (or merged, not entirely sure) to add elements to the hud. 

https://github.com/tgstation/tgstation/pull/67893
