### ISSUE TITLE
Unable to grind things in mortar

### ISSUE THREAD

**Issue by Microvolnovka19** [Skyrat-SS13/Skyrat-TG#15164]
The mortar doesn't give you option to grind. It automatically juices the thing.
I tried to grind Korta into flour, but it gave me milk. 
![image](https://user-images.githubusercontent.com/59139863/180654718-95ba3811-feb5-478b-8d2c-03cf475cf5ab.png)

It doesn't matter if i right or left-click.

**Comment by nikita-chekistov** [comment]
fixed.  #15735
