### ISSUE TITLE
Portable Mechs A.K.A. bluespace crates

### ISSUE THREAD

**Issue by Microvolnovka19** [Skyrat-SS13/Skyrat-TG#15161]
You can put mechs in crates. That's it.
![image](https://user-images.githubusercontent.com/59139863/180653910-ca675e20-5c96-40df-ad95-f2b5ce726908.png)
![image](https://user-images.githubusercontent.com/59139863/180653913-f7f128cf-4e5a-44fb-ba78-efcd1157f0f9.png)

**Comment by YakumoChen** [comment]
upstream issue

**Comment by Jolly-66** [comment]
https://github.com/tgstation/tgstation/issues/68795
