### ISSUE TITLE
Event Triggering Out of Order

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#15172]
Reporting client version: 514.1584

## Round ID:
6064

-- Submitting In-Case it hasnt been Included already-- 
Trigger event seems to be bugged. it triggers it before confirming, then sends the 1-minute countdown but triggers way before then, then the UI pops up after the event triggers asking how you want to handle it

## Testmerges:
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:

Attempt to run any event. The event will trigger, then say it will trigger in one minute, then after the one minute is up, will ask you how you want to trigger the event.

**Comment by Zergspower** [comment]
Resolved in current version
