### ISSUE TITLE
Various Xenobiology Bugs

### ISSUE THREAD

**Issue by Krypandenej** [Skyrat-SS13/Skyrat-TG#15181]
## Round ID:
6067 (?)

## Testmerges:
None!

## Reproduction:
Two issues: One with the Stabilized Green extract restoring everything BUT the user's original appearance upon dropping the item (something that happened with multiple people and the same extract), and an issue with Reproductive extracts not taking any monkey cubes from backpacks; the game instead insists that the bag "has no monkey cubes".

For the first bug, simply pick up and put down the extract rapidly a few times. For the second, just try using a bio bag with monkey cubes on any reproductive extract - I think we used Grey and Dark Blue Reproducing extracts.

**Comment by YakumoChen** [comment]
upstream issue

**Comment by Jolly-66** [comment]
I would attempt to try and reproduce this upstream. I'm not seeing many issue reports up there that describe what you have here. This seems like a "them" problem than an "us" problem.
