### ISSUE TITLE
Xenobiology burning black extract bug

### ISSUE THREAD

**Issue by captainfrost20** [Skyrat-SS13/Skyrat-TG#15191]
Reporting client version: 514.1584

## Round ID:
6074

## Reproduction:

Burning black extracts cant be used as they require wizard robes. When I tried using it it just spammed "You don't feel strong enough without your robe!" at me until and an admin had to spawn me in wizard clothes which allowed me to use the ability and fixed the message spamming at me.

**Comment by YakumoChen** [comment]
upstream issue

**Comment by Jolly-66** [comment]
Upstream issue. Please make a report up there.
