### ISSUE TITLE
Disassembling Shutters is a one way process

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15194]
## Round ID:
6076

## Testmerges:
[#13848: 'The Refactaur' by GoldenAlpharex at commit 422fdba628](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
[#14023: 'Fleshmind [PRE-RELEASE FINAL]' by Gandalf2k15 at commit 66dd484dc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#15028: 'Disable spiders from rolling in events' by Funce at commit 3f13c6b110](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
[#15092: '[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?' by tf-4 at commit edb327a39d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
[#15078: '[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior' by Jolly-66 at commit f1933cdde5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
[#10823: 'Database revision revert' by Gandalf2k15 at commit 30f7853899](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:

Screwing open a shutter and prying out the airlock circuit doesnt allow you to replace the circuit, simple as that, none of the "deconstruction" steps are reversable
(Also adding a little tooltip when the shutters panel is screwed open stating that using a multitool can change the id would be nice)

**Comment by YakumoChen** [comment]
I believe shutters are a crafting menu thing? I am aware for certain you can deconstruct them and construct them both

**Comment by Jolly-66** [comment]
Upstream issue. Please make an issue report up there.
