### ISSUE TITLE
You can no longer directly dump seeds from plant bags into the seed extractor for storage.

### ISSUE THREAD

**Issue by TheNeoGamer42** [Skyrat-SS13/Skyrat-TG#15203]
Reporting client version: 514.1583

## Round ID:
6082

## Testmerges:
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:
1: Obtain plant
2: Shove plant into seed extractor to get seeds (Or skip 1 and obtain seeds in some other fashion.)
3: Pick up seeds using a plant bag/portable seed extractor
4: Try to put them into the seed extractor for storage purposes
5: Fail horribly.
6: Suffer as you have to manually put the 45984737 seeds the seed extractor made because Science upgraded it for once, into it one by one, by hand. Or just use a fridge but the seed extractor organizes seeds by their stats, making it a vastly superior storage option when you can actually put stuff in it.

**Comment by YakumoChen** [comment]
likely an upstream issue

**Comment by Jolly-66** [comment]
Upstream issue. Please make an issue report up there.
