### ISSUE TITLE
[RUNTIME REPORT] Runtimes in species.dm,49.

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#15236]
Reporting client version: 514.1584

## Round ID:
6092

Creating report to start tracking consistent runtimes between rounds. Looking for large generators, not minor ones. 

![image](https://user-images.githubusercontent.com/60765218/181393116-ab69ba17-d801-4531-81a1-7cc3166b1916.png)
![image](https://user-images.githubusercontent.com/60765218/181393367-7c5f4b9e-9651-4e0e-b9e4-c0b9b86444db.png)

[22:53:03] Skipped 371 runtimes in species.dm,49.
[23:22:51] Skipped 56 runtimes in species.dm,49.
[23:46:18] Skipped 61 runtimes in species.dm,49.

Error Report 

`proc name: handle mutant bodyparts (/datum/species/proc/handle_mutant_bodyparts)
usr: CKEY/(CKEY)
usr.loc: (start area (8,174,1))
src: Human (/datum/species/human)
call stack:
Human (/datum/species/human): handle mutant bodyparts(Player Name (/mob/living/carbon/human/dummy), null, 0)
Human (/datum/species/human): handle body(Player Name (/mob/living/carbon/human/dummy))
Player Name (/mob/living/carbon/human/dummy): update body(0)
Player Name\'s head (/obj/item/bodypart/head): drop limb(1, null)
Player Name\'s head (/obj/item/bodypart/head): drop limb(1)
the human head (/obj/item/bodypart/head): replace limb(Player Name (/mob/living/carbon/human/dummy), 1)
Human (/datum/species/human): replace body(Player Name (/mob/living/carbon/human/dummy), Human (/datum/species/human))
Human (/datum/species/human): on species gain(Player Name (/mob/living/carbon/human/dummy), Human (/datum/species/human), 0)
Player Name (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0, 0, /list (/list), /list (/list), /list (/list), 0, 0)
Player Name (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0, 0, /list (/list), /list (/list), /list (/list), 0, 0)
...
/datum/preferences (/datum/preferences): render new preview appearance(Player Name (/mob/living/carbon/human/dummy))
the character_preview (/atom/movable/screen/character_preview_view): update body()
/datum/preferences (/datum/preferences): create character preview view(CKEY (/mob/dead/new_player))
/datum/preferences (/datum/preferences): ui data(CKEY (/mob/dead/new_player))
/datum/tgui (/datum/tgui): get payload(null, 1, 1)
/datum/tgui (/datum/tgui): open()
/datum/preferences (/datum/preferences): ui interact(CKEY (/mob/dead/new_player), /datum/tgui (/datum/tgui))
CKEY (/mob/dead/new_player): Topic("src=\[0x3000021];character_set...", /list (/list))
CKEY (/client): Topic("src=\[0x3000021];character_set...", /list (/list), CKEY (/mob/dead/new_player))`

## Testmerges:
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

## Reproduction:
N/A

**Comment by Zergspower** [comment]
Resolved in current version
