### ISSUE TITLE
[RUNTIME REPORT] Chat Failure / Runtimes after chat stopped working. 

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#15238]
Reporting client version: 514.1584

## Round ID:
6092

![image](https://user-images.githubusercontent.com/60765218/181394986-8ca10908-b367-4fb3-bf79-f8b769f7f105.png)
![image](https://user-images.githubusercontent.com/60765218/181395352-1c04eed5-64d1-4fd9-8e2a-3d0cb0be6c75.png)

*A Player Reports that chat broke instantly after transforming into red drake using Mining Potion - Potentially unrelated

`[2022-07-28 00:20:41.728] runtime error: Cannot execute null.read preference().
 - 
[2022-07-28 00:20:41.728] runtime error: Cannot execute null.send message().
 - 
[2022-07-28 00:20:41.891] runtime error: Cannot read null.chat_toggles`

## Testmerges:
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

**Comment by Zergspower** [comment]
Resolved
