### ISSUE TITLE
[RUNTIME REPORT] Runtime in _element.dm, line 51

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#15247]
Reporting client version: 514.1584

## Round ID:
6097
Map: Tramstation

[14:43:56] Runtime in _element.dm, line 51: We just tried to add an element to a qdeleted datum, something is fucked
usr.loc: (Freighter Ship (123,113,12))
[16:37:24] Skipped 309 runtimes in _element.dm,51.

## Testmerges:
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15078)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)

**Comment by Zergspower** [comment]
Resolved
