### ISSUE TITLE
Mining satchels (of holding) broke in the middle of a round

### ISSUE THREAD

**Issue by KelpoTietaja** [Skyrat-SS13/Skyrat-TG#15309]
Reporting client version: 514.1585

## Round ID:
6114

## Testmerges:
- [Disables the pollution subsystem](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15281)
- [[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
- [[SEMI-MODULAR] FAMILIES 5.0: Modularized For Skyrat Edition](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15173)

**Comment by YakumoChen** [comment]
are you sure you didn't have the ore bag module in your MODsuit?

**Comment by KelpoTietaja** [comment]
> are you sure you didn't have the ore bag module in your MODsuit?

If the module comes with the suit and is toggled on by default, it's very likely that was the case after all.
