### ISSUE TITLE
The forms from the printer serving no paper-pushing value whatsoever

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15305]
## Round ID:
6114

## Reproduction:

![StupidFuckingPrinter1](https://user-images.githubusercontent.com/108144396/181934979-ce2b708b-80b1-4430-964e-ec4e5d8e5f73.PNG)
![StupidFuckingPrinter2](https://user-images.githubusercontent.com/108144396/181934984-189beb5d-f110-46ff-bb0c-3c7e29d61d47.PNG)

**Comment by YakumoChen** [comment]
known bug, fields in general do not work on any paperwork made.

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/issues/66679
upstream issue

**Comment by Jolly-66** [comment]
Paper code issue. Theres something upstream thats a complete rewrite of it, hopefully it'll rectify a lot of issues.
