### ISSUE TITLE
Security belt has 7 slots instead of 5

### ISSUE THREAD

**Issue by Hardly3D** [Skyrat-SS13/Skyrat-TG#15333]
## Testmerges:
[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit ad34ec0a54](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#15092: '[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?' by tf-4 at commit edb327a39d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
[#15028: 'Disable spiders from rolling in events' by Funce at commit 3f13c6b110](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#15173: '[SEMI-MODULAR] FAMILIES 5.0: Modularized For Skyrat Edition' by Iamgoofball at commit e3a40a0e71](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15173)
[#15330: 'Optimizes SQL logging and adds missing related default config entries' by GoldenAlpharex at commit 1977e0b9d2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15330)

## Reproduction:
Be security/blueshield, grab a security belt from your locker and notice how it has 7 slots instead of 5.

![dreamseeker_A14rJnL5LE](https://user-images.githubusercontent.com/66234359/182155728-2e7f40bc-eb7b-4d76-be77-4504b772d5c9.png)

I tried taking a short code dive and it appeared to also be set to 5 slots so I'm not really sure what could be causing the issue. 🤔

Webbing still has 6 slots, it's just the default security belt that has 7 slots for whatever reason. Not a upstream issue as I had tried hosting a private TG server shortly after this.

**Comment by Tastyfish** [comment]
It's because in `modular_skyrat\modules\goofsec\code\sec_clothing_overrides.dm` `/obj/item/storage/belt/security/Initialize()` is just overriden without setting any of the atom_storage vars so they're the default. The original init for the sec belt is unused.
