### ISSUE TITLE
Dragon Form spell breaks chat

### ISSUE THREAD

**Issue by Glyphee** [Skyrat-SS13/Skyrat-TG#15342]
## Testmerges:
[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit ad34ec0a54](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#15092: '[DNM][TM ONLY][MORE CAPITAL LETTERS] fixes lag?' by tf-4 at commit edb327a39d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15092)
[#15028: 'Disable spiders from rolling in events' by Funce at commit 3f13c6b110](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
[#14593: '[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"' by jjpark-kb at commit 5ef8933cb7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)
[#15173: '[SEMI-MODULAR] FAMILIES 5.0: Modularized For Skyrat Edition' by Iamgoofball at commit e3a40a0e71](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15173)
[#15330: 'Optimizes SQL logging and adds missing related default config entries' by GoldenAlpharex at commit 1977e0b9d2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15330)

## Reproduction:
Get the dragon form spell from the VV menu or the dragon's blood bottle. Using the spell removes your ability to see any runechat or local chat messages in the chat box. Having your z-level change such as being brought to CC fixes the issue for some reason, but it reappears once the spell is used again.

**Comment by YakumoChen** [comment]
needs tested upstream.

**Comment by Tailiik** [comment]
There also is apparently a shortcut to do the lava swoop attack special move set to EXAMINE + CLICK, making it so if you examine a player while in drake form you have a good chance of killing them just because you wanted to see what they looked like.

**Comment by Zergspower** [comment]
Resolved in current version
