### ISSUE TITLE
Specific Suits Not Working For Ashwalkers (Digis Moment?)

### ISSUE THREAD

**Issue by EerieDream** [Skyrat-SS13/Skyrat-TG#15366]
So recently tribal armor has not been working properly, even though they were before. These consist (so far) of the miner armor, bone armor, and goliath cloaks not working whatsoever and instead turning into that gross pink/black whenever sprites don't work.

Not entirely sure which PR would've broke it, but it was a recent update. It started at ROUND ID: 6147 if that's of any use. Not sure what to include for bug reports, but here's the screencaps of what I'm talking about.  As of now, the bug apparently has been active for 24 hours but randomly showed later on.

Last server deployment was yesterday as of August 2, from what I told.

![](https://i.gyazo.com/506c51aef4410dbb23b825859d9d961d.png)

![](https://i.gyazo.com/c9162ad5ad56a841fe9db06018377b7f.png)

![](https://cdn.discordapp.com/attachments/951151946516004906/1004178245513642054/unknown.png)

![](https://cdn.discordapp.com/attachments/951151946516004906/1004176698687889510/unknown.png)

**Comment by EerieDream** [comment]
UPDATE: It's working now, and likely just a mass accidental var edit.

**Comment by Jolly-66** [comment]
If your issues are rectified, and you cannot replicate them further, please close your issue.

Otherwise, if this remanifests, please let me know.
