### ISSUE TITLE
Mechs can continue drilling a wall/item/mob and walk away as long as they stay facing it.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#15384]
Reporting client version: 514.1582

## Round ID:
6157

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [Optimizes SQL logging and adds missing related default config entries](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15330)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)

**Comment by R9b1t** [comment]
I always assumed this as an intended feature. Like it's useful for the instances you're fighting mobs in a mech or are trying to break an airlock with a diamond drill. If instead the wall/item/mob is being moved away from the mech but is still in that 1x3 area thats bad.

**Comment by Zergspower** [comment]
Seems this is a mechanical feature, it'd be an upstream change if anything at all
