### ISSUE TITLE
Wagging snake (stripe) tail makes it vanish

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#15416]
Reporting client version: 514.1583

## Round ID:
6165

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disable spiders from rolling in events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15028)
- [Optimizes SQL logging and adds missing related default config entries](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15330)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)

## Reproduction:
Have a character with snake (stripe) tail
Emote  *wag
Watch the sprite disappear, only to return when you stop wagging the tail

**Comment by Jolly-66** [comment]
Probably missing an appropriate associated icon state

**Comment by N0th1ngn3ss** [comment]
Going to watch this c:

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/225356386-29bf56f1-2482-4ba5-8fe7-425fce821e67.png)

Sems resolved
