### ISSUE TITLE
Saints coat sprite invisible on digigrade lizards.

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#15439]
Reporting client version: 514.1583

## Round ID:
6179

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:
Put on a saints coat from loadout on a digigrade lizard. See that its a error message and not visible.

**Comment by Jolly-66** [comment]
Missing associated digi sprites probably

**Comment by ghost** [comment]
Fixed via Removal, TG has removed this item and it will be removed from the loadout via the PR marked as Closing this
