### ISSUE TITLE
Blood Deficiency quirk not working on Xenobiological Slime Hybrids

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#15447]
Reporting client version: 514.1583

As titled. 

## Round ID:
6180

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:

Take Quirk as Slime: watch as "blood" will not slowly fall to 80% as intended.
Cry as gimmick is ruined and there's no reason to keep drinking welding fuel.

**Comment by Floofies** [comment]
Looking into this one

**Comment by Floofies** [comment]
Ok, so this is a bit of a weird one I'll be fixing shortly.

Slimes have the `NOBLOOD` species trait, yet have blood. Weird snowflakeyness abounds. The quirk has a conditional which checks for that trait:
```
if(NOBLOOD in carbon_target.dna.species.species_traits) //can't lose blood if your species doesn't have any
	return
```

A quick comment in the `jellypeople.dm` yields this hint: "Slimes have both NOBLOOD and an exotic bloodtype set, so they need to be handled uniquely here.". I'll most likely create a Blood Deficiency optimization for slimepeople that drains their jelly properly.
