### ISSUE TITLE
Please please please for the love of god fix the damn table in downstairs xenobiology

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15440]
## Round ID:
6179

## Testmerges:
N/A

## Reproduction:
Its driving me crazy, it makes me want to eat a burger with no honey mustard.
![OhNoOurTableItsBroken](https://user-images.githubusercontent.com/108144396/183263978-0792f016-5581-45b4-ac32-5e48d0680e13.PNG)
(All in all, sorry for the shitty bug report but like.. come on.. its been like this for **MONTHS**, maybe even a year!

**Comment by Jolly-66** [comment]
Please specify the map.

**Comment by YakumoChen** [comment]
upstream issue but also it's IceBox

**Comment by PeriwinkleBuddy** [comment]
oh shit in the heat of the moment I forgot to specify it was icebox lol
