### ISSUE TITLE
Imperfect Mutation Toxin not effecting Hemophages

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15445]
## Round ID:
6180

## Reproduction:
Title, it doesnt matter if its 0.5u, 4u or 15u, nothing.

**Comment by N0th1ngn3ss** [comment]
I think the reason of this is for the Trait "VirusImmune" they had, so I don't know if can be a bug or just the trait itself. 
`inherent_traits = list(
		TRAIT_ADVANCEDTOOLUSER,
		TRAIT_CAN_STRIP,
		TRAIT_NOHUNGER,
		TRAIT_NOBREATH,
		TRAIT_VIRUSIMMUNE,
		TRAIT_CAN_USE_FLIGHT_POTION,
		TRAIT_LITERATE,
	)`
