### ISSUE TITLE
Please, bring back the ability to go back to line on subtler

### ISSUE THREAD

**Issue by Traitre** [Skyrat-SS13/Skyrat-TG#15453]
Subtle and Subtle anti-ghost were recently changed, and that changed as all but removed the ability to easily go back to line or create spaces for paragraph on posts, making it a nightmare for people who like to write a lot in them to do so in an easy to read manner. Using notepad can be used to circumvent it, but it is highly annoying... So please, give us back the ability to go back to line and create space in the posts to make them readable without having to use another thing entirely ? thank you.

**Comment by Tailiik** [comment]
Far too big of a nerf to erp just to have fancy windows 🥴
