### ISSUE TITLE
Subtle refactor issues

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#15471]
## Reproduction:
Related to #15453, but there are numerous issues with Subtle. 

-As stated in the previous PR, despite being a multi-line text box, you cannot format text in any way. It's been reduced down to, arguably, an even worse version than the old explorer text box or lack of formatting from enforced one-line subtlers.
-If you enter in subtler text and go to the target menu, there is a cancel option. However, the cancel option still posts the emote to your own chat instead of returning out of the full emote.

**Comment by tf-4** [comment]
Knock off the inflammatory attitude

**Comment by GoldenAlpharex** [comment]
Take a look at https://github.com/Skyrat-SS13/Skyrat-tg/pull/15713, it fixed the first half of this.

**Comment by Zergspower** [comment]
Formatting works fine in both Subtle and Subtler, /ME is not multiline
