### ISSUE TITLE
Headpats toggle wag instead of only setting wag on.

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#15470]
## Testmerges:

[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#13970: 'Disables progtots' by Zonespace27 at commit 1efdad809f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:

Headpats can turn wagging on and off instead of just making you wag. Considering Excitable is a Skyrat-only quirk it seems like strange behavior.

**Comment by Jolly-66** [comment]
This is no doubt how head patting is coded (or excitable). Its probably trigger the emote each time its applied.

The behavior wasn't always like this, so somewhere within the last month or two it was changed.
