### ISSUE TITLE
Slimes lose their ear organ on changing to "None", also lost the ability to wag tails

### ISSUE THREAD

**Issue by mcmeiler** [Skyrat-SS13/Skyrat-TG#15486]
## Testmerges:

[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#13970: 'Disables progtots' by Zonespace27 at commit 1efdad809f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

### Deafness on removing ears
* Be a slime
* Get new ears (For my instance it was Cat, but any other works the same)
* Remove your ears
* Become deaf

Did a tiny investigation and it seems the actual ear organ gets removed, without replacement, when you select "None".

### Inability to wag tails
* Be a slime
* Get a waggable tail (Cat, Fox, etc.)
* Try to use *wag
* \>Unusable emote '*wag'. Use '*help' for a list of emotes.

Did a quick check up the call chain and it _seems_ the tail organs given to slimes lack the `WAG_ABLE` bitflag, at least from my testing.

Noticed this today, but it's likely this was an accidental side effect of #14848 and #14017 ?

**Comment by vinylspiders** [comment]
@Jolly-66  I can say that this is now definitely fixed, possibly by https://github.com/Skyrat-SS13/Skyrat-tg/commit/702c3e2ce644a382ed79d497d9088b959d5a1308.


Tail wagging

![dreamseeker_es3bMUIUEx](https://user-images.githubusercontent.com/13398309/228671817-9433bc39-e942-4ca1-94fb-f52951fe5b16.png)

Ears hearing

![image](https://user-images.githubusercontent.com/13398309/228671851-b594920f-254b-4b72-8979-f3af415a0ff0.png)
