### ISSUE TITLE
Interdyne deck officer spawns with duplicated gear. (Sorry for formatting issues, first time github user).

### ISSUE THREAD

**Issue by Televisionary** [Skyrat-SS13/Skyrat-TG#15492]
## Round ID: 
6201

## Reproduction:
Issue should be able to be reproduced by spawning as a deck officer, in theory. More specifically though: I connected to the server, joined as an observer, and then used the spawner menu to become a deck officer. Then, I loaded a premade character profile rather than taking the randomized clownhuman that the game made for me.
Doing so resulted in spawning with two combat knives, two sec flashlights, two mining vouchers, and two mining scanners. Only one PKA and one beacon.

**Comment by YakumoChen** [comment]
This is a problem for all the interdyne roles, it is likely something to do with the custom spawning. I also play interdyne and the miners get duped gear also.

**Comment by Jolly-66** [comment]
Could've swore someone reported this before.

Must've been on the Discord.

**Comment by Zergspower** [comment]
Resolved in current version
