### ISSUE TITLE
Security Webbing has incorrect number of slots

### ISSUE THREAD

**Issue by OolongCow** [Skyrat-SS13/Skyrat-TG#15494]
## Round ID:
6204

## Testmerges:
N/A

## Reproduction:
Spawn as a security member. Buy a 400 credit security webbing from the equipment vendor. Open it. Open your security belt. Kanye stare. Weep for innocence lost.

The security webbing seems to have been caught in the crossfire of a fix for the security belt made in #15340 , or broken at some other prior point. The 400 credit item security can buy as a replacement for their security belts for extra storage now... No longer gives extra storage. The 140 credit one (peacekeeper webbing) still gives 7 slots.

**Comment by Plum-but-gayer** [comment]
I should be able to fix this, just wanna double check - is the 400 credit webbing supposed to have 7 slots like the cheaper peacekeeper one, or more?
