### ISSUE TITLE
SSD players can't be put in cryo until they've been ssd for 300 hours

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#15523]
## Reproduction: 
Find ssd player, drag their sprite into a cryopod, receive funne message about needing another 18,000 minutes to cryo them. I could seethis being intentional so players don't get put into cryo while experiencing connection issues, but I would think a timer closer to 10-15 minutes would be more reasonable. Had to ask an admin to remove a player after they had to unexpectedly leave, they had used an expose verb prior to that and I didn't want to leave the poor bean exposed for the rest of the round.

**Comment by GoldenAlpharex** [comment]
That's an interesting one, I'll get someone to look into it!

**Comment by Jolly-66** [comment]
@GoldenAlpharex 
I looked at it a bit and I believe its the logic here,
```
if(target.lastclienttime + ssd_time >= world.time)
					to_chat(user, span_notice("You can't put [target] into [src] for another [ssd_time - round(((world.time - target.lastclienttime) / (1 MINUTES)), 1)] minutes."))
					log_admin("[key_name(user)] has attempted to put [key_name(target)] into a stasis pod, but they were only disconnected for [round(((world.time - target.lastclienttime) / (1 MINUTES)), 1)] minutes..")
					message_admins("[key_name(user)] has attempted to put [key_name(target)] into a stasis pod. [ADMIN_JMP(src)]")
					return
```

Messing with `SSD_time` fiddles with the required time, but its still disproportionate to what we want (i.e 9000 min)
