### ISSUE TITLE
Blastoff interfered by new freerunning

### ISSUE THREAD

**Issue by Siefer21** [Skyrat-SS13/Skyrat-TG#15521]
## Round ID:
any (6205)

## Testmerges:
[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#13970: 'Disables progtots' by Zonespace27 at commit eb7006ccc8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:
drink Blastoff. Its a drug that forces your body to flip and launches you forward on the third flip. just gives the notification on the procs that you aren't able enough. rest of chem works fine though.

**Comment by Jolly-66** [comment]
@Zonespace27
