### ISSUE TITLE
Department Guards keep spawning without hair

### ISSUE THREAD

**Issue by brokenOculus** [Skyrat-SS13/Skyrat-TG#15533]
Reporting client version: 514.1585

## Round ID: 
6212

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Early mirror of #69106](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15527)

## Reproduction:
Join as a department guard, and your character will be bald. I've seen this from both the cargo department guard and engi guard, and your  character will spawn without hair. The only way to fix this issue is to use a SAD machine. I have tried using barbers aid, concentrated barber's aid, and scissors to fix to no avail. Cryoing and respawning does not fix the issue. After cryoing I have confirmed that my character settings are okay in the ghost hotel, respawn as the same character as a guard again, and again, no hair.

**Comment by Jolly-66** [comment]
Have you tried changing the hair in the prefs menu and respawning?

**Comment by Tailiik** [comment]
I believe this is a headwear related bug and not a department guard specific bug. I believe it can happen with any helmet that hides your character's hair, such as a modsuit helmet, winter coat hood, or mining armor hood. I've had it happen to me from modsuits, and I've never played as a guard.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/15687
