### ISSUE TITLE
Disease Outbreak - Broken

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#15548]
Reporting client version: 514.1584

## Round ID:
6217

Disease Outbreak officially appears to be broken, while it will apply a disease to a crewmember, the Disease never properly progresses and does not account for the values the disease was given. 

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Early mirror of #69106](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15527)

## Reproduction:

Trigger :Disease Outbreak.

Wait.

**Comment by Zergspower** [comment]
Had the pleasure of seeing Lily catch on fire with hers last night - assumed resolved
