### ISSUE TITLE
"Save chat log" button bluescreens TGUI

### ISSUE THREAD

**Issue by Pirill** [Skyrat-SS13/Skyrat-TG#15547]
Reporting client version: 514.1583

## Round ID:
6217

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Early mirror of #69106](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15527)

## Reproduction:
Click button. Receive error.

**Comment by Jolly-66** [comment]
Upstream issue.

**Comment by Jolly-66** [comment]
For reference:
https://github.com/tgstation/tgstation/issues/69097
