### ISSUE TITLE
Breaking Reinforced Plasma Glass Windows with a Fire Axe gives you normal glass shards

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15551]
## Round ID:
6219

## Reproduction:
Title, at least for directional windows

**Comment by Jolly-66** [comment]
Could be an upstream thing, could be an us thing

Would need to be tested first

**Comment by Zergspower** [comment]
Confirmed still an issue

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/212390739-7c1751a6-056d-47de-9628-637da920a856.png)
Upstream as well

**Comment by vinylspiders** [comment]
@lessthnthree I'm going to be pinging you for all the issues I've tested / that have upstream fixes that can be confidently closed.

Fixed by https://github.com/tgstation/tgstation/pull/73274

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/19357
