### ISSUE TITLE
Add the "Water breathing" species trait to Akulas and Aquatics

### ISSUE THREAD

**Issue by Traitre** [Skyrat-SS13/Skyrat-TG#15594]
Upon creating a new character, i hovered over the snailpeople traits and found, much to my shock, that while akulas and aquatics who are both supposed to be aquatic in nature lack the water breathing species trait, the snail people have it.

This is a simple request to have the trait added to both species, something that i'm sure makes sense.

**Comment by Glyphee** [comment]
There's a water breathing trait? That seems like the thing that would be made _**for**_ aquatics and akulas, not snail people

**Comment by Traitre** [comment]
> There's a water breathing trait? That seems like the thing that would be made _**for**_ aquatics and akulas, not snail people

There is, it's unique to the snail people for some unfathomable reason... the description even specifies that SNAILS can breathe underwater, wich is why i made this post here. it'd make sense for the two species to also get it.

**Comment by YakumoChen** [comment]
Snails were added afterward and this trait didn't exist until then

**Comment by nikita-chekistov** [comment]
Trait added to aquatics with https://github.com/Skyrat-SS13/Skyrat-tg/pull/16476
