### ISSUE TITLE
Tounge tied raising and lowering brow indicator stuck

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#15591]
## Reproduction:
Occasionally, the icon used to display eyebrows raising and lowering break. This causes issues, and one of the only solutions is to delete the character and respawn it. Ahealing doesn't work. Sometimes the display glitches out and goes missing a eye. Im not sure what particularly causes it but its been a persistent bug and has been happening to me on multiple occasions. Using the typing indicator just overlays ontop of it.

**Comment by Jolly-66** [comment]
Believe this an upstream issue, thought it was fixed? Probably wasn't
