### ISSUE TITLE
Character quirks being deleted with admin commands and SAD

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#15590]
Reporting client version: 514.1583

## Round ID:
6229

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

**Comment by Zergspower** [comment]
intended on the ctrl+shift, SAD Seems to have been fixed
