### ISSUE TITLE
Paint kit doesn't work on modsuits after a speed potion is applied

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#15629]
## Round ID:
6243

## Reproduction:
1. Build/buy/steal/admin spawn a modsuit.
2. Apply a speed potion from xenobiology (other clothes applicable potions might cause the same thing to happen as well)
3. Print a modsuit paint kit from an exofab
4. Right click the control unit, cry when you can no longer repaint it

**Comment by GoldenAlpharex** [comment]
Have you tried using a spraycan and coloring the suit white first?

**Comment by Tailiik** [comment]
> Have you tried using a spraycan and coloring the suit white first?

Not as in the color doesn't apply, as in the recoloring menu itself didn't even appear.

**Comment by Jolly-66** [comment]
> Have you tried using a spraycan and coloring the suit white first?

The problem is, at least to my knowledge, speed potions apply a hard red overlay color to things that I don't think we (as players) can remove or modify in anyway, without removing the speed potion properties. Probably a similar case with fire proof potions?

**Comment by ghost** [comment]
Is this an upstream issue? All factors are TG items

**Comment by kittysmooch** [comment]
> Have you tried using a spraycan and coloring the suit white first?

seconding this. set spraycan to white/FFFFFFF and spray each piece of the modsuit including backpack. then right click with the paint kit again. works as of a few days ago.

**Comment by Zergspower** [comment]
With how it's coded it applies a color var when you use a potion - which frankly i feel is a feature to signal you're buffed. Beyond that upstream
