### ISSUE TITLE
Some of our mappable objects lack icon sprites

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15620]
The biggest offender is the lust wish.

The other offenders are anything gags'd (namely the sex-related sprites).

**Comment by Paxilmaniac** [comment]
i personally enjoy not seeing sex objects in my object tree and would prefer if all of them were lacking icons

**Comment by Jolly-66** [comment]
> i personally enjoy not seeing sex objects in my object tree and would prefer if all of them were lacking icons

Pax the dildos have sprites I'm sorry to tell you

**Comment by ghost** [comment]
Unofficial Sprite-tainer
WNF sex-related sprites lacking mapping icons
GAGS sprites missing icons I'm going to blame on upstream, as the icons are only assembled in-game and thus can't be put together in the mapper. Technically can be fixed but I'd rather wait to see how/if TG fixes it

If any non-sex and non-GAGS sprites are missing though please inform me

**Comment by vinylspiders** [comment]
I am closing this for now, seems the consensus is that it is intentional for NSFW items--and for GAGs items this is an upstream limitation.
