### ISSUE TITLE
Issue with Syncing/AI connection 

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#15635]
Reporting client version: 514.1583

## Round ID:
6249

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:

"

After assumed tampering from both a Ninja and a robotists, borgs that were disconnected from the AI, and assumingly relawed. Had their laws resynced & AI connections reset but they were still not avaliable via AI connection and other menus related to AI -> Cyborg interactions.
![image_2022-08-14_213638286](https://user-images.githubusercontent.com/104115259/184568084-c9b90aa6-46ca-49cf-a912-484e0f9e187e.png)
![image_2022-08-14_213703608](https://user-images.githubusercontent.com/104115259/184568116-f93ccec3-4e2c-4811-bcd2-9e8e96f1fe1c.png)

**Comment by Zergspower** [comment]
Were they rebuilt completely ? if they were given a syndiejack or the Ninja override they lose their old shell basically
