### ISSUE TITLE
The sprite for the aerostatic suit is broken. 

### ISSUE THREAD

**Issue by Fresau** [Skyrat-SS13/Skyrat-TG#15676]
Reporting client version: 514.1585

## Round ID:
6263

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)

## Reproduction:
Putting on the aerostatic suit results in a broken pink-and-black sprite. 
Steps to reproduce: 
Put on the suit and rejoice. 
![billede](https://user-images.githubusercontent.com/109923724/184997689-137c5eb8-d7dc-445e-96a6-10fb9c3f8f76.png)

**Comment by ghost** [comment]
Caused by a modular duplicate of a TG item, our overwrite icon broke it all.
Should be fixed by #16072, but cannot confirm 100% so I'll ask you or someone else to verify once it's merged

**Comment by Zergspower** [comment]
Resolved in current version
