### ISSUE TITLE
Tg gunpoint mechanics that conflict with Skyrat policy re-enabled.

### ISSUE THREAD

**Issue by SingingSpock** [Skyrat-SS13/Skyrat-TG#15681]
Pull request #14954 ported from upstream a fix to tg's gunpoint mechanic. This mechanic activates on right-click with a gun, and holds someone at gunpoint. After 2.5 sec, if the target moves (or clicks on any world item if I read the code right, haven't tested much), they automatically shoot with a damage multiplier of 2. After another 7.5 seconds (total of 10 seconds), the damage modifier is increased to 2.5. Both stages also multiply the wound bonus of the attack by 5. We already have a modular version of this that has no damage modifier. It had the shoot-on-move capability, but that was removed by PR #12624 at the request of the host. We need to either disable or alter the tg gunpoint mechanics to fit within our server.

**Comment by YakumoChen** [comment]
Some key differences:
- requires being adjacent to work
- does not have a visual indicator aside from the initial one
- no options to disable or enable movement or item usee, either you engaged it or didn't 
- also keeps you in place

This mechanic is far more useful for the intended purpose of holding someone up at gunpoint. It is Obviously Mechanical but the situations where it benefits most (hostage taking and ambushing) generally do not require CI and it is beneficial to prevent anti-RP (like someone grabbing your hostage).

It shouldn't be used unless you already planned for mechanics to be engaged.

Skyrat gunpoint on the other hand is more useful as a visual indicator and was not very reliable for mechanics anyway (often it just backfired)

**Comment by SingingSpock** [comment]
> Some key differences:
> 
> * requires being adjacent to work

It just got patched to work at a 2 tile range
> * does not have a visual indicator aside from the initial one
> * no options to disable or enable movement or item usee, either you engaged it or didn't

These are bugs, not features on an RP server
> * also keeps you in place

> This mechanic is far more useful for the intended purpose of holding someone up at gunpoint. It is Obviously Mechanical but the situations where it benefits most (hostage taking and ambushing) generally do not require CI and it is beneficial to prevent anti-RP (like someone grabbing your hostage).

Gunpoint that is mechanical in nature requires CI before usage by Skyrat Action-RP rules, but it's a fuzzy enough area that it caused a lot of tickets according to the PR I mentioned that removed the Skyrat auto-shoot function. The "intended purpose" of holding someone up at gunpoint mechanically does not fit in our environment. If someone's grabbing your hostage without putting up CI, that's its own break of the Action-RP rules and should be ahelped.

> It shouldn't be used unless you already planned for mechanics to be engaged.
> 
> Skyrat gunpoint on the other hand is more useful as a visual indicator and was not very reliable for mechanics anyway (often it just backfired)

Skyrat gunpoint isn't for mechanics at all. That is deliberate and a necessary thing. It is effectively a visual indicator for an RP situation, showing that one character is holding another at gunpoint. It facilitates the RP of holding someone at gunpoint without making it a mechanical situation in which the person being held up has to react within 2.5 seconds of the initial action or face heavy mechanical consequences.

**Comment by YakumoChen** [comment]
> It just got patched to work at a 2 tile range

Revert it then

>These are bugs, not features on an RP server

Not a bug, it's an oversight at best, not intended for the feature at worst Adding a visual indicator of someone being held up would be dead-simple, especially if it was made distinct from the gun-pointing.

> Gunpoint that is mechanical in nature requires CI before usage by Skyrat Action-RP rules, but it's a fuzzy enough area that it caused a lot of tickets according to the PR I mentioned that removed the Skyrat auto-shoot function. The "intended purpose" of holding someone up at gunpoint mechanically does not fit in our environment. If someone's grabbing your hostage without putting up CI, that's its own break of the Action-RP rules and should be ahelped.

Ambush policy disagrees, ambushing does not require CI. Being able to jump out at someone and hold them at gunpoint is effectively the same as jumping out and shooting them to crit in an ambush, but with the added bonus of being able to facilitate an RP instead. Considering the risk and difficulty of getting adjacent or provoking retaliation (and per policy, the other party HAS to be aware you are a threat), I would say its a fair tradeoff.
If someone grabs your hostage without CI, that's Instant Mechanics anyway and subjects everyone involved to immediate combat.

> Skyrat gunpoint isn't for mechanics at all. That is deliberate and a necessary thing. It is effectively a visual indicator for an RP situation, showing that one character is holding another at gunpoint. It facilitates the RP of holding someone at gunpoint without making it a mechanical situation in which the person being held up has to react within 2.5 seconds of the initial action or face heavy mechanical consequences.

Yes, which is why it was removed. Ranged gun-pointing is better purely as a RP tool. Melee-range gun-pointing hold-up is far more fair, when used within the policies in place.

**Comment by Zergspower** [comment]
Working as intended downstream
