### ISSUE TITLE
Station goals not rolling round start

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#15691]
Reporting client version: 514.1582

## Round ID:
6279

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Reverts #11270 (Event Voter)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
- [[NO GBP] Fix Languages Being Reset if You Load in Early](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15680)

**Comment by ghost** [comment]
Seen quite a few as of recent, is this still a bug?

**Comment by tobjv** [comment]
> Seen quite a few as of recent, is this still a bug?

last time i was on the server they were working again

**Comment by Zergspower** [comment]
Issue unable to be replicated, could have been a station trait roll
