### ISSUE TITLE
Refreshing you character in any way (S.A.D, prides mirror, Unstable Slime Toxin, etc) removes all languages but Sol

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15705]
## Round ID:
6283

## Testmerges:
[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#13970: 'Disables progtots' by Zonespace27 at commit 3787d21fd0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
[#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f1c42f538b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
[#15680: '[NO GBP] Fix Languages Being Reset if You Load in Early' by RimiNosha at commit c076ca2678](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15680)

## Reproduction:
Title

**Comment by Zergspower** [comment]
Resolved in current version
