### ISSUE TITLE
H.E.C.K suit bugs on digi characters only when putting helmet up

### ISSUE THREAD

**Issue by mopcat** [Skyrat-SS13/Skyrat-TG#15733]
## Testmerges:
[#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
[#13970: 'Disables progtots' by Zonespace27 at commit 3787d21fd0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
[#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f1c42f538b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
[#15680: '[NO GBP] Fix Languages Being Reset if You Load in Early' by RimiNosha at commit c076ca2678](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15680)
[#14937: 'NSS Void Raptor [MDB IGNORE] [SEMI-MODULAR]' by LYNXEMS at commit 78b1fe1dd9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14937)

## Reproduction:
1. Spawn as a character with digitigrade leg type.
2. Kill bubblegum (or just spawn the suit in yourself)
3. Put helmet up
4. Look like you forgot to install CS: Source

**Comment by ghost** [comment]
sounds like the suit doesnt have a toggle version for digi

Is it the whole suit, the suit alone (helmet fine), or the helmet alone?

**Comment by Zergspower** [comment]
Confirmed issue, only the helmet appears but not the suit

**Comment by ghost** [comment]
> Confirmed issue, only the helmet appears but not the suit

definitely the suit missing a toggle-state in the digi dmi then. will update this whenever I finally get the time to touch suit dmis. Thanks for confirming <3
