### ISSUE TITLE
NRI equipment unable to be used by tesharis

### ISSUE THREAD

**Issue by Paxilmaniac** [Skyrat-SS13/Skyrat-TG#15746]
## Reproduction:
If you look at the code for NRI equipment you'll see that each piece of clothing has a species check for specifically teshari to be unable to put them on, which is funny but also a little annoying

**Comment by YakumoChen** [comment]
Probably because it lacks sprites

**Comment by tf-4** [comment]
While this is not a bug, and is in fact intended functionality, sprites provided for it will be accepted. So I'll leave this open.

**Comment by Erol509** [comment]
#17820 SOON

**Comment by Zergspower** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/17820
