### ISSUE TITLE
Uh oh! Rezadone doesn't dehusk.

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#15758]
Reporting client version: 514.1583

## Round ID:
6316

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Reverts #11270 (Event Voter)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
- [[NO GBP] Fix Languages Being Reset if You Load in Early](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15680)
- [NSS Void Raptor [MDB IGNORE] [SEMI-MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14937)

## Reproduction:
Rezadone doesn't dehusk!

Rescued a security officer from fire blob. they were husked. fixed all wounds [except the 20 toxins and 17 oxyloss] and had a borg  put in rezadone. 

At the time they had 10.72u of Forma into them, and 10u of rezadone
No dehusking
Borg chem purged, readded 10u of rezadone
Readded limb, fixed wounds again, just to be safe, purged chems, readded rezadone, no dehusking
Tried defibbing, said patient was husked [confirming its not a visual bug]
Added 100u of synthflesh and they finally got dehusked.

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/190575123-93b02fe8-ee15-4a0c-8ec5-64416d1dd9fc.png)
Most likely you were actually dealing with a changeling - was able to de-husk 5 in a row with only 5u.

Changeling husks behave differently and do require 200 Synthflesh and whatever mix Rez has (didnt test that)
