### ISSUE TITLE
Skyrat specific surgery (genitals/tail) doesn't work on synths

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#15775]
## Round ID: 
6322

## Reproduction:
1. Place synth on table
2. Cut open groin
3. Attempt to insert penis/balls/anus/tail
4. Fail

Had a synth come into robotics in like 30 pieces and I was unable to reattach their funtime simulation devices, they were upset. Had to use a SAD to regenerate bits. Doomba was saying they found the issue in looc but couldn't elaborate further without giving something away, but I'm posting this anyway because I didn't get a chance to looc them away from other players to find out if I should file a report or not. Said synth was obliterated by a skill cape pod, not sure if that is relevant to the issue.

**Comment by Zergspower** [comment]
Closing this out for now, synth surgeries will be worked over in their own right soon but since this has a solution with the SAD present already I think we can safely put it away
