### ISSUE TITLE
Public airlock sprites aren't consistent 

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15779]
They look like they may be windowed, but they're not. They're missing the inner pieces.

It looks, very off putting and wrong.

Public solid
![image](https://user-images.githubusercontent.com/70232195/186296053-493e1fcd-767f-4465-b822-4ef8be1b2d94.png)

Public glass
![image](https://user-images.githubusercontent.com/70232195/186296058-5a6aab80-9405-4610-a95c-b19401d50f3e.png)

**Comment by ghost** [comment]
Once upon a time I tried making a Fill, but it looked horrible. The door is definitely designed for the glass, the fact there's solids of this design is kinda trouble-causing
