### ISSUE TITLE
Admin triggered events don't execute

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#15793]
## Testmerges:
#15175: '[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!' by RimiNosha at commit e8efee6843
#13970: 'Disables progtots' by Zonespace27 at commit e4ec3ebc22
#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f1c42f538b
#15680: '[NO GBP] Fix Languages Being Reset if You Load in Early' by RimiNosha at commit c076ca2678
#14937: 'NSS Void Raptor [MDB IGNORE] [SEMI-MODULAR]' by LYNXEMS at commit 2533e915ff
#15773: 'Fixes SQL game logs throwing a bunch of SQL errors' by GoldenAlpharex at commit a5c4ea4b5a

## Reproduction:
Admin trigger an event such as Immovable Rod, Supermatter Surge, Brand Intelligence etc. It doesn't do anything.

**Comment by Jolly-66** [comment]
@Zonespace27

**Comment by lessthnthree** [comment]
It seems to be round specific. 6382 is the latest where manual triggered events don't fire.

**Comment by lessthnthree** [comment]
6588 also not working.

**Comment by lessthnthree** [comment]
Round isn't even over and we have 235k runtimes

![image](https://user-images.githubusercontent.com/83487515/192128147-7ceced0b-b562-4d89-ba8c-f6bba46de542.png)

**Comment by lessthnthree** [comment]
Round 6648

**Comment by lessthnthree** [comment]
Round 6657

**Comment by Zergspower** [comment]
Update to this: They seem to work at the very start of the shift but wont later on - we can force via the 'inject midround' but that messes with other timers

**Comment by Zergspower** [comment]
didnt mean to close that
