### ISSUE TITLE
Select Equipment is horribly not right

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15827]
Self explanatory.
The dummies are not reflective of either the character or the outfit being chosen.

![image](https://user-images.githubusercontent.com/70232195/186698314-58a2ba5f-137a-478f-91c0-441a9103e1d0.png)

**Comment by ghost** [comment]
I believeeee @GoldenAlpharex did a PR to change how player previews generate down here (for the sake of examines), I wouldnt know if that damaged this at all or if its a TG issue but it miiight be?

**Comment by Jolly-66** [comment]
This is an issue unique to us. Select Equipment works fine on TG
