### ISSUE TITLE
Ashwalkers can't plant anything on Ice Box

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#15874]
Reporting client version: 514.1582

## Round ID:
6350

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Reverts #11270 (Event Voter)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
- [NSS Void Raptor [MDB IGNORE] [SEMI-MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14937)
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [Modularize Crew Monitor, fixes health status](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15490)
- [[MIRROR] Makes the game start faster by optimizing round-start manifest injections [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15866)

**Comment by Tailiik** [comment]
Make an ash staff, dig in the lava turf, plant to your lizard heart's content.

**Comment by Zergspower** [comment]
Unable to reproduce or resolved, the ashland patch is able to dig a hole to be planted - this can be closed
