### ISSUE TITLE
Sterile mask and Medical gas mask look identical on the side profile

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15891]
Sterile mask.
![image](https://user-images.githubusercontent.com/70232195/187091743-6edc04e0-9867-4898-b1cd-985eb4a8c589.png)

Medical gas mask.
![image](https://user-images.githubusercontent.com/70232195/187091805-1f8c92c7-5f5c-42b3-a5e3-5f57bacda4fc.png)

For clarity, here's the regular gas mask.
![image](https://user-images.githubusercontent.com/70232195/187091831-c6b5e8fd-179c-429b-9bf1-1d4e3635e9ee.png)

**Comment by ghost** [comment]
I'll get to this whenever I sort the mask .dmi's if no one gets it in...
hmmh
~a month i guess~
this aged poorly. just give me time i have a real life to deal with abrhbrbr
