### ISSUE TITLE
Medical MOD (and presumably others?) mask clipping issue

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15890]
Title.
Mask sprite pokes out a singular pixel out of the MOD helmet. Tested using the general medical MOD.

![image](https://user-images.githubusercontent.com/70232195/187091670-3034118b-f0a9-4f5c-ace3-ff3496cdb619.png)

**Comment by ghost** [comment]
(Specifically an issue with Muzzles)
I'll be cleaning this with the mask spritefile cleanup in the coming months, if my motivation isnt shot

**Comment by Paxilmaniac** [comment]
modsuits really should be hiding masks so this problem doesn’t happen to begin with

**Comment by ghost** [comment]
> modsuits really should be hiding masks so this problem doesn’t happen to begin with

Should be fixed by an upcoming TG PR, keep an eye out for the mirror of https://github.com/tgstation/tgstation/pull/71199
