### ISSUE TITLE
Cybernetic hand sprite layering conflicts with some clothing, causing hands to disappear

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#15892]
## Round ID: 
6361

## Reproduction:
I'm not 100% certain what causes this, at first I thought maybe it had to do with character slots that were setup prior to the newer character creator merge that happened a while back, but after a bit of playing around in the editor I believe it has to do with sprite layering with certain outfits. At first I thought it was somehow only happening on the anthromorph race, but I believe it's more accurately just certain clothing items are layered strangely. 

While facing to the side and naked, the hand will show, and with some clothing such as the tactical hawaian outfits the hands will display properly, but with others such as the recolorable sundress they will be hidden. My experiments in the creator also found a weird thing where the void created by a missing hand will make a hole in a suit slot item that sees through to the clothing underneath, as shown in the screenshots below. I picked clothing, arm, and suit slot with high color contrast to make this easier to see.

This displays both in the character creator menu and in game, as far as I've seen. It was originally pointed out to me by a friend.

https://i.imgur.com/GW0cux7.png

**Comment by Jolly-66** [comment]
I think this may be a dupe issue, or I saw someone talking about it on the Discord.

**Comment by Tailiik** [comment]
I did a brief search on the issues tab and didn't find it, feel free to close this one if there is another report already. Or link them together maybe? Whatever is most helpful.
