### ISSUE TITLE
Centcom Kitchen and Bar Buttons for Shutters are in the wrong locations.

### ISSUE THREAD

**Issue by Reco201** [Skyrat-SS13/Skyrat-TG#15907]
## Testmerges:
[#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f83ec84088](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 71d1ca4de8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15842: '[Tram] New tram, new consequences. Tram collisions actually hurt.' by lessthnthree at commit 555409a216](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)

## Reproduction:
Go to centcom and head for the kitchen shutters and press the button
Observe the bar shutters opening

Go to centcom and head for the bar shutters and press the button
Observe the kitchen shutters opening

**Comment by Zergspower** [comment]
Given the change to the new map soon - i think we're good here
