### ISSUE TITLE
Coffee maker is invisible

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#15930]
## Reproduction:
/obj/machinery/coffeemaker

icon = 'icons/obj/medical/chemical.dmi'
icon_state = "coffeemaker_nopot_nocart"
base_icon_state = "coffeemaker"

We don't have a /medical/ folder in obj so it's invisible.

**Comment by Jolly-66** [comment]
Either something got skewed with Tattles organization somewhere, or we didn't get the sprites.

**Comment by lessthnthree** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/15951

**Comment by GoldenAlpharex** [comment]
> Either something got skewed with Tattles organization somewhere, or we didn't get the sprites.

(It totally wasn't my fault)
