### ISSUE TITLE
Error tab in Game Preferences, broken setting

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#15931]
The game preferences menu now has an ERROR tab next to ERP, with a single option.
cum_face_pref and it's angry that "...is not filled out properly!!!"

![image](https://user-images.githubusercontent.com/83487515/187416978-a6937d13-b76d-4d6e-bf5e-19051299908b.png)

## Testmerges:
[#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f83ec84088](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 71d1ca4de8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15842: '[Tram] New tram, new consequences. Tram collisions actually hurt.' by lessthnthree at commit 555409a216](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)
[#15898: 'the ash farming expands' by jjpark-kb at commit 651f001ec6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)

## Reproduction:
Open Game Preferences

**Comment by Jolly-66** [comment]
Try to keep the title a bit more SFW, granted, it is what the issue is.
Should the day come we can appeal to not be on GitHubs shit list, this'll make it easier.

**Comment by Jolly-66** [comment]
cc: @Zonespace27

**Comment by lessthnthree** [comment]
True. Sometimes being vague in bug reports is a good thing.

**Comment by ghost** [comment]
Should have been fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/16143, can you check on the server and verify this is cleared @lessthnthree?

**Comment by lessthnthree** [comment]
Yep, good to close.
