### ISSUE TITLE
Window airbags balloon alerts are weird

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15948]
They're ever double stacked, or the fact its so long, it causes it to be crunched. 

![image](https://user-images.githubusercontent.com/70232195/187765569-c301a138-a9a4-4923-b211-4eca31d73763.png)

**Comment by Tastyfish** [comment]
It's clashing with the "need to unscrew!" message from the simple_rotation component.
