### ISSUE TITLE
sweater jackets do not look like sweaters

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#16009]
## Reproduction:

![image](https://user-images.githubusercontent.com/10399117/188048970-ac923554-d108-4fe5-a59e-dd2a62fe5756.png)
Red is the jacket, black is under sweater. They have the same item sprite as well.

I would have expected sweater jackets to just look like... sweaters?

**Comment by ghost** [comment]
Not A Bug; TG added a "Sweater Jacket" item, we added the Cableknit Sweaters long ago - if anything, we'd best rename our Sweaters to Cableknit Sweaters, but the report itself is not a bug. @tf-4 this is good to close
