### ISSUE TITLE
The texture in black tiles and black + color tiles is not consistent (and possibly others?)

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#16008]
The color for the tiles "textured" bits are not the same.

![image](https://user-images.githubusercontent.com/70232195/188028432-bce86864-0cfa-4492-abeb-45c7e4ceb89a.png)

**Comment by ghost** [comment]
I tried I swear 😭

**Comment by Paxilmaniac** [comment]
this is what we get for not just using tg's tiles
