### ISSUE TITLE
IPC arms not appearing for clothes

### ISSUE THREAD

**Issue by Sy-zz-nthe-zz-ticF-zz-ox** [Skyrat-SS13/Skyrat-TG#16023]
Reporting client version: 514.1585

## Round ID:
6411

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [[Tram] New tram, new consequences. Tram collisions actually hurt.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [Fixes events happening too often and blobs being handled outside of dynamic](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15947)
- [Fixes being able to retract an active MODsuit's parts and still be able to use its modules](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15950)

## Reproduction:
1. Make an IPC with any of the chassis options
2. Select any loadout option that covers has a shirt/sleeves or the turtleneck shirt option
3. The side sprite on both sides has the hands missing
![arms4](https://user-images.githubusercontent.com/82522672/188254905-8ab03cf5-5f05-4443-ad24-103c6c789f37.PNG)
![arm1](https://user-images.githubusercontent.com/82522672/188254908-be63b203-073c-46c4-8739-add60fdd3199.PNG)
![arm2](https://user-images.githubusercontent.com/82522672/188254909-7ae4066d-f416-43a0-88e4-1cb0feb3c5c2.PNG)
![arm3](https://user-images.githubusercontent.com/82522672/188254910-9159d4f5-e192-4b92-9e07-81b2a6a9fadf.PNG)

**Comment by Fresau** [comment]
I'd like to add that this doesn't just apply to IPCs, to also applies to prosthetics in general, it mostly seems to affect newer sprites?

**Comment by Tailiik** [comment]
Related report: https://github.com/Skyrat-SS13/Skyrat-tg/issues/15892

**Comment by Ebin-Halcyon** [comment]
The issue here is Robotic limbs not having a 'hand' sprite in the spritesheet, so it has nothing to layer over the clothing sprites, i'll fix it in a bit.
