### ISSUE TITLE
High heels use digi sprite when worn plantigrade

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#16046]
## Reproduction:
It looks really scuffed
![image](https://user-images.githubusercontent.com/10399117/188297660-48f6edc1-2aca-4dc1-86c6-e7c42ffc88b5.png)

**Comment by glitchbow** [comment]
I would also very much like this fixed. It is using the digitigrade legs sprite on normal legs. This problem is only happening on colorable High Heels, Black Heels look and work fine and as-intended.
