### ISSUE TITLE
Elevated and lowered floor tiles have no sprites when placed

### ISSUE THREAD

**Issue by PatchyDragon** [Skyrat-SS13/Skyrat-TG#16062]
## Testmerges:

[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 9345fd0676](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15842: '[Tram] New tram, new consequences. Tram collisions actually hurt.' by lessthnthree at commit f422d0b8b8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)
[#15898: 'the ash farming expands' by jjpark-kb at commit 651f001ec6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
[#15947: 'Fixes events happening too often and blobs being handled outside of dynamic' by GoldenAlpharex at commit 32f1fbd611](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15947)
[#15950: 'Fixes being able to retract an active MODsuit's parts and still be able to use its modules' by GoldenAlpharex at commit 7bb8eab0ee](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15950)
[#15863: '[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos' by Paxilmaniac at commit cfa6fbfdd4](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)

## Reproduction:

While messing around with pool floors and the viability of making either a really deep pool or big aquarium on cafe, I discovered that Elevated Floor tiles do not properly show up when placed, instead appearing as a solid black space. While you can in fact crowbar them up and examine them still, due to the jank of the way clickdragging icons works, you cannot drag yourself to the tile to climb up it, breaking key functionality of the tile too. A bit more testing revealed that it's the same way with lowered tiles.

![image](https://user-images.githubusercontent.com/8277254/188334096-8a58b39d-b757-48dd-a863-ce949e40dcc9.png)

My current bet is something has gone wrong in the smoothing code, since it appears to name the right dmi and icon names in code, but I'm currently recompiling the latest version of the code to test further on a local server where I actually have varedit.

**Comment by PatchyDragon** [comment]
As an aside, pool/elevated/lowered tiles are currently made at a 1:1 ratio of iron to tiles, but when welded only return at a 1:4 ratio, requiring four tiles minimum per iron. I lost quite a few tiles and thus metal just to them autostacking with regular floor tiles... Uncertain if this is a bug.

**Comment by PatchyDragon** [comment]
Okay yeah, at runtime it's setting its icon_state to "elevated_plasteel" when it should be switching to something with a -0 or other numerical value at the end, similar to walls. This certainly smells like a smoothing code issue.

**Comment by vinylspiders** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/2f860507-067e-4349-bc72-83c61d525cdd)

Definitely the smoothing issue has been fixed. Though the smoothed icons look a bit interesting to say the least.

But they seem to be rendering as they're supposed in any case.
