### ISSUE TITLE
[UH OH] TGUI Sprites Are Completely Broken, But Only on Skyrat Main

### ISSUE THREAD

**Issue by RimiNosha** [Skyrat-SS13/Skyrat-TG#16074]
## Round ID:
6431, but has been happening for a couple of days now, ever since the last deploy, on the 3rd. (https://discord.com/channels/596783386295795713/661273195978162201/1015692711396909086)

## Testmerges:
#15802 
#15842 
#15898 
#15947 
#15950 
#15863 

## Reproduction:
Load into game, and open character prefs, boom, no images of anything at all, aside from your avatar.

Though anything that uses the spritesheet component for showing images in TGUI are just completely non-functional.

Only happens on SR Main, this does not happen on my local test server, which is running the latest commit as well as some upcoming PR code.

Looks like the spritesheet caches are corrupted on SR's side, though I'm not certain. Updating the server could also probably fix this, in case there's a bugfix PR that's been merged since.

**Comment by GoldenAlpharex** [comment]
I already know what the issue is, should hopefully be fixed from next round onward (and this is a duplicate issue anyway).

The assets were meant to be cached, but they weren't, which is what caused the issue.

**Comment by GoldenAlpharex** [comment]
It's still not fixed, grrrr
