### ISSUE TITLE
Character Pref Error, Icons not showing

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#16073]
Reporting client version: 514.1582

## Round ID:
6431

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [[Tram] New tram, new consequences. Tram collisions actually hurt.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [Fixes events happening too often and blobs being handled outside of dynamic](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15947)
- [Fixes being able to retract an active MODsuit's parts and still be able to use its modules](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15950)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)

## Reproduction: Atm the icons for Character PRef are not rendering. See pic. Will comment back if it happens next round. 
![Screenshot_5](https://user-images.githubusercontent.com/13283561/188475758-cb0f3037-74b4-4f21-bdec-74313f73fac3.png)

And yes people have cleared both caches and downgraded or upgraded byond, it is happening across multiple accounts and versions

**Comment by YakumoChen** [comment]
Reported before #16074 but that report is more concise

**Comment by GoldenAlpharex** [comment]
I already know what the issue is, should hopefully be fixed from next round onward (and this is a duplicate issue anyway).
