### ISSUE TITLE
Normal Operating Tables completely uninteractable and invisible

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#16095]
Reporting client version: 514.1582

## Round ID:
6437

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
- [Redoes bluesec clothing sprites to have a nicer, more consistent color palette, along with correcting alot of glaring mistakes.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16068)

**Comment by GoldenAlpharex** [comment]
Fixed in #[16096](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16096)
