### ISSUE TITLE
Breathing tube doesn't function properly in space

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#16160]
## Reproduction:
1. Either spawn with a breathing tube or get one implanted
2. Get a space suit (any flavor, from emergency to modsuit. Suit type doesn't matter)
3. Find an air tank
4. Turn the air tank on, do not equip a mask. The air supply will function normally in pressurized areas
5. Go into space, after a few seconds you will start to suffocate. Cranking the tank output will not fix this
6. Perish unless you put a mask on

**Comment by Tailiik** [comment]
Afterthought: I didn't test this in spicy air to see if the tank actually gives you the air in pressure actually...the issue might just be that the implant doesn't supply air to you but lets you turn on the tank and makes you think you're supplied.

**Comment by Tailiik** [comment]
UPDATE TWO: Breathing tube doesn't supply you with the contents of your tank at all currently. 

1. Set distribution pressure to 0kpa
2. Activate tank
3. Successfully breathe

**Comment by YakumoChen** [comment]
this is more than likely an upstream bug given the lack of code we have touching implants

**Comment by Zergspower** [comment]
I recall when this issue was being talked about in DChat, you all had been EMP'd to hell and back at the time

**Comment by Tailiik** [comment]
The first time I died because of it I don't believe I had been emped, but I've tested it in following rounds where I definitely wasn't emped and got the same result. I tried it earlier right after I spawned and it wasn't supplying any air.

**Comment by Tailiik** [comment]
I believe whatever was causing this has been fixed. It definitely wasn't working for a couple days but it's working again now.
