### ISSUE TITLE
quality of life improvements rebase test day 11/7/2020

### ISSUE THREAD

**Issue by Sethnov** [Skyrat-SS13/Skyrat-tg#1618]
I am listing what should be added for convenience, and just make life easier
1. Give atmospherics people engineering access, unable to access electrical Lockers
2. add mag boots to suit storage units in engineering,
3. the sprite for the jaw of life and hand drill seem too small to know if it's in drill or bolt mode, along with jaw of life cutter or pry mode.
4. make it faster to assemble and dismantle machines, pipes, walls, windows.
5. a little bit faster movement speed, in general, would be helpful in getting tasks done faster.
6. re add Gas miners, so i don't try to efficient all the time be nice.
 
this is it for now.

P.S avian species and avian legs are currently not in skyrat rebase, bird people would love to have those.

**Comment by Funce** [comment]
Issue lists are being closed. 
If any of these enhancements are still relevant, please add them into separate issues.
