### ISSUE TITLE
Plasmamen spawn into the cafe sans envirosuit

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#16195]
Reporting client version: 514.1582

## Round ID:
6492

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
- [Redoes bluesec clothing sprites to have a nicer, more consistent color palette, along with correcting alot of glaring mistakes.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16068)
- [Reworks microfusion guns to behave like energy guns that can be upgraded, not like ballistic guns that happen to fire lasers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16017)

## Reproduction:
Plasmamen spawn into the ghost cafe in nothing but a jumpsuit and immediately catch fire. Very funny, but it means they cannot utilize the cafe either for rp or for testing their racial mechanics, drip, and quirks.

Admittedly effects about three people.

**Comment by YakumoChen** [comment]
Skill issue

**Comment by kittysmooch** [comment]
so true bestie

**Comment by N0th1ngn3ss** [comment]
Gonna try fixing this!
