### ISSUE TITLE
Events Failing to Trigger again. 

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-TG#16198]
Reporting client version: 514.1584

## Round ID:
6493

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
- [Redoes bluesec clothing sprites to have a nicer, more consistent color palette, along with correcting alot of glaring mistakes.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16068)
- [Reworks microfusion guns to behave like energy guns that can be upgraded, not like ballistic guns that happen to fire lasers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16017)

## Reproduction:

Attempt to trigger any event either let the server random one, or force one. The event will not fire. 

Lowpop Round, Forced Extended enabled.

**Comment by lessthnthree** [comment]
#15793 is still open.

**Comment by Zergspower** [comment]
Closing due to duplicate https://github.com/Skyrat-SS13/Skyrat-tg/issues/15793
