### ISSUE TITLE
Suit sensors can be set to the names of nearby people.

### ISSUE THREAD

**Issue by Mintybea** [Skyrat-SS13/Skyrat-TG#16207]
## Testmerges:
This is possibly related to the new code that prevents you from changing suit sensors when dead or restrained.

## Reproduction:
I was fighting an EMP blob and went down about three times, and was restrained twice to get carried out of the fight. When I made sure to check my sensors after fighting the blob I noticed the normal sensors were not present, instead I could set my sensors to the names of people around me. Personally set my sensors to McGriff, and it appears that this carries to other unforms as well.
UPDATE: So I just realized this is a menu for adjusting the suit sensors of other people around me, when I click my own name it then allows me to change my suit sensors.

![image](https://user-images.githubusercontent.com/56327747/190019041-4cfb6649-d208-47d0-a3c4-368af39e8b93.png)

**Comment by lessthnthree** [comment]
Someone add the upstream tag, I'll post it there.

**Comment by lessthnthree** [comment]
Confirmed upstream, a PR is in.

**Comment by Floofies** [comment]
Fixed by #16231
