### ISSUE TITLE
Antag Pacifism

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#1623]
## Reproduction:
Antags do not lose pacifism when rolling antag.

This isn't too much of a problem on its own but for antags like changeling which generally *have* to murder someone to do their objective, it becomes a problem when they cannot fight at all.

**Comment by unit0016** [comment]
Lings lose their quirks when transforming into another identity and transforming back. They also lose a few things like digitigrade legs. Lings are just... wild in general, codewise.
