### ISSUE TITLE
SAD does not properly transfer brain traumas, leading to incurable ones.

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#16296]
## Round ID:
6530

## Testmerges:

n/a likely related to the SAD change that transfers conditions instead of being an aheal

## Reproduction:

SAD does not transfer brain traumas properly. It erases them, but keeps all the effects (likely the flags on the mob said traumas grant) because it does not properly remove the traumas, leading the the traumas being incurable without, say, giving them the traumas again and removing them.

**Comment by Zergspower** [comment]
I know why aheal was removed, but it sounds like the replacement wasnt great. Aheal removes even quirks which was the issue there

**Comment by YakumoChen** [comment]
> I know why aheal was removed, but it sounds like the replacement wasnt great. Aheal removes even quirks which was the issue there

As typical of giving players an inch and taking a mile, the aheal was abused for... being an aheal.
