### ISSUE TITLE
Bees that enter their apiary do not leave, effectively killing hive activity once maximum bees have been produced.

### ISSUE THREAD

**Issue by DerFlammenwerfer** [Skyrat-SS13/Skyrat-TG#16314]
Reporting client version: 514.1585

## Round ID:
6545

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
- [Revert "[MIRROR] Add Alt RMB and Ctrl RMB screentips (used for Simple Rotation) [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16298)
- [Adds several themed vending machines that can spawn in place of snack vendors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
- [Izhevsk Coalitioning](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)
- [[s] Maroon objective removal](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16307)

## Reproduction:

I have noticed while beekeeping that whenever bees end up returning to the Apiary they call home, they end up never coming back out, causing the apiary to essentially die out after it reaches the maximum number of bees and requiring the whole assembly to be replaced. To reproduce the issue, simply wait for enough bees to have been produced (15)

**Comment by YakumoChen** [comment]
Upstream issue, presumably

**Comment by Zergspower** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13805 is the last bee related PR I can find and it was upstream - i'd let them know

**Comment by out-of-phaze** [comment]
See upstream issue https://github.com/tgstation/tgstation/issues/69315

**Comment by vinylspiders** [comment]
Finally fixed upstream by https://github.com/Skyrat-SS13/Skyrat-tg/pull/22652 hooray
