### ISSUE TITLE
You can walk through the organ storage fridge on Delta

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#16323]
## Testmerges:
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 712341258d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15898: 'the ash farming expands' by jjpark-kb at commit ba7420a343](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
[#15863: '[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos' by Paxilmaniac at commit 1931c418df](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
[#16298: 'Revert "[MIRROR] Add Alt RMB and Ctrl RMB screentips (used for Simple Rotation) [MDB IGNORE]"' by tf-4 at commit 40b7024212](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16298)
[#16215: 'Adds several themed vending machines that can spawn in place of snack vendors' by Paxilmaniac at commit c901fcf1f1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
[#15696: 'Izhevsk Coalitioning' by Stalkeros2 at commit 74bcb9b472](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)

## Reproduction:
For some reason this organ fridge on Delta you can walk straight through back and forth like it's a normal floor tile.
![image](https://user-images.githubusercontent.com/83487515/191130160-786fd958-46e5-47fe-8333-f1703f92e5fe.png)

**Comment by Jolly-66** [comment]
Upstream issue, please reproduce/check upstream and push an issue.
