### ISSUE TITLE
Prisoners are able to roll traitor

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#16347]
## Testmerges:
BYOND Version: 514.1585
Server revision compiled on: 2022-09-19T14:35:26+00:00
Master commit: [de08bde842254dcb001b76b5b67bdd0d6f6dda0a](https://github.com/Skyrat-SS13/Skyrat-tg/commit/de08bde842254dcb001b76b5b67bdd0d6f6dda0a)
The following pull requests are currently test merged:
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 712341258d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15898: 'the ash farming expands' by jjpark-kb at commit ba7420a343](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
[#15863: '[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos' by Paxilmaniac at commit 1931c418df](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
[#16298: 'Revert "[MIRROR] Add Alt RMB and Ctrl RMB screentips (used for Simple Rotation) [MDB IGNORE]"' by tf-4 at commit 40b7024212](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16298)
[#16215: 'Adds several themed vending machines that can spawn in place of snack vendors' by Paxilmaniac at commit c901fcf1f1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
[#15696: 'Izhevsk Coalitioning' by Stalkeros2 at commit 74bcb9b472](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)

They rolled midround or latejoin traitor.

![image](https://user-images.githubusercontent.com/83487515/191419402-fd210900-b53a-4cde-a302-5e45b6200087.png)

**Comment by Lukaster42** [comment]
Actually that's pretty intresting, could be a good feature.

**Comment by YakumoChen** [comment]
Not a bug?

Prisoners being able to be antag is in fact intended.
