### ISSUE TITLE
Hardware cake seems to be impossible to craft at the moment.  "Circuit board" as an ingredient does not seem to exist in the game.

### ISSUE THREAD

**Issue by Rivernoodl** [Skyrat-SS13/Skyrat-TG#16385]

**Comment by Rivernoodl** [comment]
Note: The hardware cake was attempted using a pair of integrated circuits and a pair of fire lock circuits when this was discovered.

**Comment by nikita-chekistov** [comment]
> Note: The hardware cake was attempted using a pair of integrated circuits and a pair of fire lock circuits when this was discovered.

It is craftable. In order to get it you have to use actual machine circuitboards.
![image](https://user-images.githubusercontent.com/59139863/192491944-806be987-2ed6-4ce9-837f-499f1bee69ea.png)
