### ISSUE TITLE
Sprite Issue - Server startup warning: design /datum/design/plumbing_rcd_service with icon 'modular_skyrat/modules/aesthetics/tools/tools.dmi' missing state 'plumberer_service'

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#16383]
## Warning logged on private server startup
`## WARNING: design /datum/design/plumbing_rcd_service with icon 'modular_skyrat/modules/aesthetics/tools/tools.dmi' missing state 'plumberer_service'`

(Mostly made this report as a note for myself: @OrionTheFox)

**Comment by ghost** [comment]
@tf-4 is this fixed? never seen a PR for it, yet see the icon in-game 🤔 i can't see server logs so can't verify the warning being fixed on main

**Comment by tf-4** [comment]
yes I fixed this a while ago

**Comment by tf-4** [comment]
it was fixed in a commit to a mirror that's why you can't find the PR, and I forgot which mirror it was now
