### ISSUE TITLE
Invisible Drinking Glasses

### ISSUE THREAD

**Issue by TheLightorTheDark** [Skyrat-SS13/Skyrat-TG#16425]
Reporting client version: 514.1583

## Round ID:
6589

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [Adds several themed vending machines that can spawn in place of snack vendors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
- [Izhevsk Coalitioning](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)
- [[MODULARIZING] Partial Refactoring of Organic Interface Code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)

## Reproduction:
An unknown kind of drinking glass seems to be pulling from a sprite that is completely transparent, and is also completely lacking flavor text, with the name of "glass". This occurred on the Station with a Tram, though it may be reproducible on other Stations as well.

Step 1: Explore Maint tunnels until a green trash bin is located.
Step 2: Open green trash bin.
Step 3: Hope that the RNGods have decided to provide you invisible glass.

**Comment by ghost** [comment]
Did a bit of diving from what this report has - found the garbagelist of the green carts (`code\game\objects\effects\spawners\random\trash.dm` `line 14`)

The offender seems to be `/obj/item/reagent_containers/cup` itself; which has no icon state (code\modules\reagents\reagent_containers\cups\_cup.dm, `lines 1 - 20`
Is this a TG upstream issue? This item is a base type used for lots of reagent code, but it's in TG's trash spawner list

**Comment by Tastyfish** [comment]
It is indeed an upstream issue. That path is a base type. Appears it's supposed to be `/obj/item/reagent_containers/cup/glass/drinkingglass` but got clobbered in the cup PR a month ago. Making an upstream PR real quick.

**Comment by Tastyfish** [comment]
https://github.com/tgstation/tgstation/pull/70127

**Comment by Tastyfish** [comment]
Was fixed by #16454
