### ISSUE TITLE
Surgically removing a tongue does not appear to have the intended effect

### ISSUE THREAD

**Issue by SciDragon** [Skyrat-SS13/Skyrat-TG#16420]
## Testmerges:
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 3a2c288860](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#16215: 'Adds several themed vending machines that can spawn in place of snack vendors' by Paxilmaniac at commit 5c4d4b66a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
[#15696: 'Izhevsk Coalitioning' by Stalkeros2 at commit 977669db9c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)
[#16019: '[MODULARIZING] Partial Refactoring of Organic Interface Code' by RimiNosha at commit 726b12c8ec](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)

## Reproduction:
During this round, I was playing an OPFOR/Antag gimmick that allowed me to cast a spell, specifically Aggressive Spread from the Rust Heretic path. For RP purposes, I often use Terrum when speaking the chants/incantations. In order to stop my character from casting the spell, security and medical staff elected to perform tongue removal surgery. It appears this did not work as intended: My character could talk normally and indeed still cast his spells. Instead, Terrum was greyed out from my languages: I could no longer speak it, but I could still understand it.

To reproduce this issue, perform organ manipulation and remove the tongue of a patient. Check their languages tab after the surgery.

**Comment by SciDragon** [comment]
I used the thunderdome with Granite and was able to reproduce the issue. I similarly lost the ability to speak the third language my character knows, but otherwise removing the tongue did pretty much nothing.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/23766 looks like we can finally close this one, praise Melbert!
