### ISSUE TITLE
Reagent Forging Bench and Water Basin missing from crafting.

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#16448]
## Round ID:
6599

## Testmerges:
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 3a2c288860](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#16215: 'Adds several themed vending machines that can spawn in place of snack vendors' by Paxilmaniac at commit c31bb103bb](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215)
[#15696: 'Izhevsk Coalitioning' by Stalkeros2 at commit 977669db9c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)
[#16019: '[MODULARIZING] Partial Refactoring of Organic Interface Code' by RimiNosha at commit 726b12c8ec](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)
[#16433: '[NON-MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human' by Tastyfish at commit c6506607ea](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
[#16430: 'incompatible species for ghostroles, and character pref for black market dealer' by jjpark-kb at commit cb7965843e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16430)

## Reproduction:

Gather up some Wood Planks. Use them in-hand to get the crafting menu up. Notice that the Reagent Forging structures associated with wood (Water Basin and Forging Crafting Table) are missing from the list. This effectively prevents reagent crafting AND Skyrat Fishing from happening.

**Comment by TetrakoHateThis** [comment]
Found the problem PR:  #16173 
This PR removed the recipes for the two aforementioned items.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/16462
