### ISSUE TITLE
Can hear whispering through walls  / Yelling heard through walls is the same text size as normal conversations

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#1647]
## Reproduction:

If a wall separates you and another person, and you are within whispering range, you can hear the person whispering, albit with the wall you are two tiles from the source so you can see a partial message instead of the full one.  

Through walls, you can hear yelling/screaming, however the text is the same size as normal conversations vs smaller as it was on the older tg code.

To replicate either of these, just go into a room, put someone on the other side of that wall, and try whispering to replicate the first issue, or yelling to replicate the second issue.

**Comment by Azarak** [comment]
fixed
