### ISSUE TITLE
Possible N2 bug duplication again

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#16480]
Reporting client version: 514.1582

## Testmerges:
- [Izhevsk Coalitioning](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15696)
- [[MODULARIZING] Partial Refactoring of Organic Interface Code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)

## Reproduction:

Happened at roundstart and we deleted the crystal, cleared the pipes out, restarted and recovered atmos and replanted a new crystal and it functioned normally. Layout below but Nitrogen got to 294,000+ mols within the first 10 minutes of the shift sstarting.

![image](https://user-images.githubusercontent.com/22140677/192594567-258920b1-e496-4464-b00a-e42527932cbd.png)

**Comment by Zergspower** [comment]
unable to recreate locally - will see if it pops up again in the next few days

**Comment by nevimer** [comment]
Before it was a chance issue with valves. It was always a chance issue with valves when both sides = the same pipenet

Looking at the screenshot I see two valves connecting making it all a singular pipenet

**Comment by nevimer** [comment]
see this: https://github.com/tgstation/tgstation/pull/66093
as the last fix
