### ISSUE TITLE
Skyrat Escape Pod needs some reworking

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#16510]
As this is a mapping issue that's exclusive to SR and the roundID/testmerges aren't of use I'm adding my own section below
## Info:
**Issue type** - Mapping
**File path** - _maps\shuttles\skyrat\escape_pod_default_skyrat.dmm
**Priority** - Low (Visual issues but functionally 100%)

## Reproduction:
![image](https://user-images.githubusercontent.com/76465278/192730762-9ac37c92-33b9-42b6-a41a-a9bb0baa0554.png)

The new Escape Pod is having clipping issues with the surrounding fixtures when its placed, the rear engines' marker beacons are layered under and thus invisible, the front beacons are suffering from the fact that they're meant for the ground but we want them to be much more, the light fixture and locker share a wall, and the chairs' offset can make it clip through the wall when seen from this angle.
- [ ] Rear engines should fully share the tile with the wall, the same way the TG pod does it
- [ ] All marker beacons should just be cut out, they're hellish to work with. Could be worth making new assets for decorating these kinds of tiles, external lighting fixtures or the likes
- [ ] Chairs facing the window? The offset was a lesser issue, but will exasturbate the next solution;
- [ ] Move the light fixture off that wall, probably just to the opposite side
- [ ] Can the side engines be embedded in the walls at all? See point 2, perhaps RCS that's a wall-decoration could do well?

**Comment by Paxilmaniac** [comment]
We don't use these anymore since the escape pod rework so what it do baby
