### ISSUE TITLE
Modular Computers & Laptops

### ISSUE THREAD

**Issue by GypsumKobold** [Skyrat-SS13/Skyrat-TG#16518]
## Round ID:
6617

## Reproduction:
After building a modular laptop and computer frame, computer parts like the hard drive couldn't be inserted into them.

The modular computer frame also had an additional issue that it couldn't be deconstructed using tools, and required bullets to be shot at it to destroy it.

**Comment by Tastyfish** [comment]
Looks to be upstream https://github.com/tgstation/tgstation/issues/70135 .

**Comment by vinylspiders** [comment]
Modular computers have been gutted upstream for now. As far as I know a total rework is planned.

**Comment by vinylspiders** [comment]
I'm going to close this for now, there are whispers of a rework in progress upstream so stay tuned for that. They've been made deliberately nonfunctional for now from what I have gleaned.
