### ISSUE TITLE
camera sprites are WHACK

### ISSUE THREAD

**Issue by press-mark** [Skyrat-SS13/Skyrat-TG#16512]
## Round ID:

N/A
## Testmerges:
N/A

## Reproduction:
![image](https://user-images.githubusercontent.com/6972764/192755686-8f35ad23-a65b-4b80-8f7f-0ba51edad1d4.png)
This camera here on icebox is "floating" above the engine door frame.
![image](https://user-images.githubusercontent.com/6972764/192755764-3663fd4c-9fe7-4fcd-96ea-45d9671fa841.png)
Upstream, it's not a problem as it's just pixel shifted to the right BUT:
![image](https://user-images.githubusercontent.com/6972764/192755836-82c7b1fa-2008-46b4-bf9e-2f334b38a30e.png)
Our camera sprites are on the right hand side for some reason...

---
Pretty sure this falls under an overwritten sprite issue.

Could probably be solved by moving the camera sprite to the left, but I dunno if that'd mess up SR specific maps like Blueshift & Void Raptor.

**Comment by ghost** [comment]
You didn't ping me like I told you to :(

**Comment by press-mark** [comment]
@OrionTheFox
