### ISSUE TITLE
Golems cant speak their native tongue

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#16535]
## Round ID:
6624

## Reproduction:
![Why](https://user-images.githubusercontent.com/108144396/193123613-3d1aed19-59b1-45f2-aebc-5eb2359e9aaa.PNG)

**Comment by vinylspiders** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/4ac2c111-c874-4f26-b34e-8f896739de53)

Fixed upstream it would seem
