### ISSUE TITLE
Free Golem Ship doesnt appear on blueprints (In terms of expansion)

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#16534]
## Round ID:
6624

## Testmerges:
N/A

## Reproduction:
![Agony](https://user-images.githubusercontent.com/108144396/193115930-b9094445-0a34-4f7a-b490-09ef58eacb35.PNG)

**Comment by Zergspower** [comment]
This is due to it being an actual ship you can fly, it's just disabled here
