### ISSUE TITLE
Medical treat fabricator stays stuck on screen.

### ISSUE THREAD

**Issue by sargashC** [Skyrat-SS13/Skyrat-TG#16555]
Reporting client version: 514.1585

## Round ID:
6628

## Testmerges:
- [[MODULARIZING] Partial Refactoring of Organic Interface Code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)
- [Cyborg Model Advertisement Update, or How I Stopped Having To Guess If You're A Janitor Or A Miner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16468)

## Reproduction:
As a medical borg, when you get the treat fabricator upgrade, the old one stays on your screen permanently. Even when closing module selection.

Go to robotics and get your treat fabricator upgrade. You'll now have a permanent (and uninteractable) treat fabricator stuck on your screen in the middle.

**Comment by vinylspiders** [comment]
@Jolly-66 fixed by https://github.com/tgstation/tgstation/pull/74017 , can be closed.
