### ISSUE TITLE
Lights do not turn off when Nightmares strike players with light eater

### ISSUE THREAD

**Issue by GizkaFreechman** [Skyrat-SS13/Skyrat-TG#16583]
## Round ID: 6637

fighting against sec is now impossible due to a lighting bug that's been around for a long time, its the issue when lights from pda's (or other light sources) are switched off yet still generate light despite being "turned off"

because of this Nightmares cannot escape in the dark, because players now have a permanent light source emanating from them that cannot be removed  

## Reproduction:

i cannot replicate the exact nature of the lighting bug but it seems that switching your lights on and off over and over while facing certain directions fixes/causes it

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/issues/67676

**Comment by Zergspower** [comment]
Resolved

**Comment by YakumoChen** [comment]
> Resolved

Link the fix pr?

**Comment by Zergspower** [comment]
> > Resolved
> 
> Link the fix pr?

No fix needed, the code itself sets the lumins to 0.5 which is what happens in the game, it's working as TG has set it since 2021.
![image](https://user-images.githubusercontent.com/22140677/234399509-1ce4fd10-c355-449f-87ef-ddfbe22cba9f.png)
![image](https://user-images.githubusercontent.com/22140677/234399552-4d43192e-6119-494f-bc0c-538b03cca2c9.png)

**Comment by YakumoChen** [comment]
@Zergspower 
I don't think you seem to actually understand the issue
You also are not linking the file, screenshots do not give me context

This is regardless an upstream issue but you shouldn't pass this off as "fixed " by any measure when there is a confirmation of the bugged behavior from other sources and no clear fix pr

**Comment by YakumoChen** [comment]
Light eater is intended to disable lighting to a state where it does not impede their darkness-based abilities, any handheld devices immune to this are likely to be a bug, especially something as ubiquitous as a PDA.
