### ISSUE TITLE
Broken character preferences

### ISSUE THREAD

**Issue by FeenieRU** [Skyrat-SS13/Skyrat-TG#16592]
## Round ID:
NaN

## Testmerges:
NaN

## Reproduction:
After updating character redactor, we have some bugs in characters slots like broken language system (I can't choose more than one language after removing some languages) or broken body parts (naga tail, that can't be removed). I think, you should add "Reset slot" button in character preferences.

**Comment by DerFlammenwerfer** [comment]
Regarding the language issue, it may be fixable by adding and removing the linguist quirk.

**Comment by FeenieRU** [comment]
> Regarding the language issue, it may be fixable by adding and removing the linguist quirk.

It doesn't work

**Comment by RimiNosha** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/16608 should have fixed the last of the language issues.

For the mutant part, enable mutant parts, go to the part that you want to remove, and set it to None. This issue looks like it'll be fixed by #16433 at a glance.

**Comment by FeenieRU** [comment]
Well, it works. Thanks.
