### ISSUE TITLE
Observe (verb) not rendering any equipped items on target

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#16606]
## Round ID:
6657

## Testmerges:

#16019
#16468
#16290
#16574
#16472
#16553

## Reproduction:

see title. When observing players (per the verb), most of their equipped items do not have visible sprites. This makes observation a lot less useful in general.

**Comment by tf-4** [comment]
Plane cube TM issue, resolved now
