### ISSUE TITLE
Subtler No Longer Allowing Single Mob Selection

### ISSUE THREAD

**Issue by Knouli** [Skyrat-SS13/Skyrat-TG#16619]
## Testmerges:
#16019: '[MODULARIZING] Partial Refactoring of Organic Interface Code' by RimiNosha at commit e2faf98175
#16468: 'Cyborg Model Advertisement Update, or How I Stopped Having To Guess If You're A Janitor Or A Miner' by GoldenAlpharex at commit 1328ef9c31
#16290: 'Space hotel Tender loving Care (and more)' by Zergspower at commit e2ecff7ee6
#16574: 'Fixed species that don't have hunger, not having a stomach' by GoldenAlpharex at commit 53bfa3ab7c
#16472: '[MIRROR] Multiz Rework: Human Suffering Edition (Contains PLANE CUBE) [MDB IGNORE]' by SkyratBot at commit 6f1b2b31c6
#16553: 'forging using material items, not rods' by jjpark-kb at commit 9e5f09c392

## Reproduction: 
Attempt to post a subtler anti-ghost emote with another player within range - only to find that your options are limited to 'same tile' and '1-tile range'. This contrasts against the functionality of subtler as outlined in the original PR, as well as my own observation of its use in-game prior to this round.

![image](https://user-images.githubusercontent.com/25857923/193715876-bcaa4eff-5ebb-4488-8f1a-52048ad81001.png)

As this is the most recent PR I can see adjusting the verb, I'm quick to point blame at it: https://github.com/Skyrat-SS13/Skyrat-tg/pull/16305

**Comment by YakumoChen** [comment]
This was working a couple days ago for me, so I don't think the pr that completely changed it is at fault

**Comment by RimiNosha** [comment]
#15199 is **definitely** not at fault, considering that's the PR that added that functionality in the first place to begin with.

**Comment by Knouli** [comment]
AHEM - Rimi is right, and I made an error in the original bug report. Sorry about that.

The PR I was attempting to blame is thus: https://github.com/Skyrat-SS13/Skyrat-tg/pull/16305

**Comment by tf-4** [comment]
Yes I noticed the issue, didn't get around to fixing it yet but I know the fix
