### ISSUE TITLE
Lavaland bile worm and drakr spawns are to high

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-TG#16610]
About a week ago we got about 20-50 bile worms a shift with 0-3 ash drakes 

As of late its now 60-90 bile worms with about 11-14 ash drakes covering lavaland in a ton of threats

## Reproduction:

Keeps repeatedly happening shift after shift

**Comment by SpaceVampire** [comment]
Known upstream issue.
