### ISSUE TITLE
Supermatter Surge doesn't do anything

### ISSUE THREAD

**Issue by press-mark** [Skyrat-SS13/Skyrat-TG#16663]
Reporting client version: 514.1588

## Round ID:
6671

## Testmerges:
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [forging using material items, not rods](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16553)
- [[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)

## Reproduction:
Looks like https://github.com/Skyrat-SS13/Skyrat-tg/pull/16603 accidentally broke supermatter surges. If the event triggers normally or via an admin on a local server, it doesn't seem to affect the engine.

**Comment by nevimer** [comment]
Fixed upstream.
