### ISSUE TITLE
Opening interfaces in general is a miserable, RNG nightmare of white boxes and reconnects.

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#16667]
## Round ID:
6673

## Testmerges:
Current merges dont seem applicable, N/A

## Reproduction:
When I open say.. my PDA menu to message someone, the message menu (The box that lets you type in the message) appears as a white box, or say for instance I attempt to say something and happen to reconnect, I'm now stuck in place, unable to speak unless I use Say, and chat wont update, I have to actually close the game out and restart my game because the reconnect button wont help. I have the MODsuit menu open, I open a disposal pipe interface, white box. Other times I can have three different menus on my screen and its all sunshine and rainbows, reconnecting fixes some things and breaks others, icons dont load sometimes and sometimes they do! Wanna dispense some materials from a lathe? Hope you remember which is which!

**Comment by YakumoChen** [comment]
This kind of sounds like a client side issue. Is your BYOND up to date? How current are your hardware specs?

Have you tried clearing your byond cache?

**Comment by YakumoChen** [comment]
Have you tried turning your computer off and on again?

**Comment by Floofies** [comment]
I am considering using tcpdump or similar, if I encounter that issue. Using such packet capture software may show what is going on. I've always known TGUI to be hit-and-miss with the connections, but if there's an uptick in issues that's pretty interesting

**Comment by Zergspower** [comment]
Ensure you're properly updated to the current version, clear your cahce in both BYOND and IE
