### ISSUE TITLE
Adding Boiled Rice to a Custom Sushi Roll duplicates the bowl

### ISSUE THREAD

**Issue by W4rd3nn** [Skyrat-SS13/Skyrat-TG#16660]
## Round ID:
6671

## Testmerges:

- #16290
- #16553 
- #16433 

## Reproduction:
Add boiled rice to a custom sushi roll and then cut it with a knife. The bowl will be returned to you when you add the rice, and then four more bowls will spontaneously appear when the sushi is cut. Lets you duplicate bowls. Not really a high-priority issue, but it is funny.

**Comment by Jolly-66** [comment]
If this is still an issue, please post an issue report upstream.

VERIFY the issue is still there by using /tg/ code.
