### ISSUE TITLE
Baguettes have no Examination text

### ISSUE THREAD

**Issue by DonutWorm** [Skyrat-SS13/Skyrat-TG#16687]
Reporting client version: 514.1588

## Round ID:
6683

## Testmerges:
- [forging using material items, not rods](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16553)
- [[MODULAR] Fixes a bug where opening Game Preferences and then spawning causing you to be a random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
- [Fixes Skyrat Camera Icons [TM FIRST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16525)
- [[MODULAR] Prefs-Enabled Synth, IPC, and Cyborg Brains!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)

## Reproduction:
When you Examine a Baguette, it does not show you its Examine text - or it doesn't have any.

**Comment by Tastyfish** [comment]
Will be fixed when https://github.com/tgstation/tgstation/pull/70359 is pulled down.

**Comment by DonutWorm** [comment]
❤️
