### ISSUE TITLE
Bananium Meteors, whist being hilarious throw anchored things around that shouldn't be thrown around.

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#16695]
## Round ID:
6687

## Testmerges:
N/A

## Reproduction:

![Bwuh](https://user-images.githubusercontent.com/108144396/194473132-e057e4ad-e5d6-475f-a3eb-5dfbcf369365.PNG)
Its throwing Trees, Air Alarms, APC's and Light Fixtures, I feel like these things (Literally screwed, wrenched or in some cases even rooted) shouldnt even be moved around, also one time I **did** happen to see a bananium meteor throw actual force fields (Found in the ERT shuttle dock) around, there are some things that should be moved, and there are other things that shouldn't.

**Comment by PeriwinkleBuddy** [comment]
I'd also like to say that it moves wires, disposal pipes, and fluid pipes, however atmos pipes are unaffected.

**Comment by Floofies** [comment]
In my experience, by moving those wires it can really mess up the behavior of powernet. I would say this definitely causes a lot of bugs.

**Comment by Zergspower** [comment]
Is an upstream issue for sure, it uses the same system as if you did a 'get' on an item where it'll move the cable/pipe but retain the old placement - which as floofies mentioned is a definite issue
