### ISSUE TITLE
skyrat specific techfab designs aren't sorted

### ISSUE THREAD

**Issue by press-mark** [Skyrat-SS13/Skyrat-TG#16699]
## Round ID:
N/A

## Reproduction:
After the second tgui pr for the techfabs, all of the skyrat designs aren't sorted into the categories like the rest of the designs from tg.

(remind me to expand on this later i just didn't want to forget to report this)

**Comment by RimiNosha** [comment]
This means someone didn't use the defines, cause I went through everything that used the defines when fixing it up for merging.

For fucks sake.

**Comment by Zergspower** [comment]
> This means someone didn't use the defines, cause I went through everything that used the defines when fixing it up for merging.
> 
> For fucks sake.

Just the subcategories... all of them *cries* - oddly though there are a half dozen upstream ones i'll be fixing
