### ISSUE TITLE
Oversized characters are still capable of being headpat by regular-sized characters

### ISSUE THREAD

**Issue by zydras** [Skyrat-SS13/Skyrat-TG#16700]
## Reproduction:
Have a regular-sized character attempt to headpat an oversized character. The oversized character will still be headpat despite the smaller character not having arms long enough to do such. https://github.com/Skyrat-SS13/Skyrat-tg/pull/9264 seemed to have fixed it in the past, but the fix may have been broken by other refactors or the likes.

**Comment by nikita-chekistov** [comment]
fixed
