### ISSUE TITLE
Point cloud stucks forever with you. 

### ISSUE THREAD

**Issue by OrdinaryLife13** [Skyrat-SS13/Skyrat-TG#16706]
## Round ID:

6693

## Reproduction:

As you point at item in your hands, funny cloud appears above your head; but if in the same time you move on other z-level, it'll stuck with you forever. Cannot be fixed with admins I believe [only strip-respawn]. 
![dreamseeker_gAp42i9aAb](https://user-images.githubusercontent.com/50496521/194680650-fecd1f2a-06d3-4ff8-a699-9ad7857ca773.png)

**Comment by larentoun** [comment]
Trying to replicate the bug with lavaland shuttle, and fail to do so. Any more specific steps?

**Comment by OrdinaryLife13** [comment]
> Trying to replicate the bug with lavaland shuttle, and fail to do so. Any more specific steps?

It's been a thing on Ice Box, when we moved down on the other level via regular staircases. Might be only Ice Box issue, couldn't check it myself on local, but can do in few days only.

**Comment by Zergspower** [comment]
Resolved
