### ISSUE TITLE
Character previews are missing from examine+char creator

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#16747]
Reporting client version: 514.1583

## Round ID:
6709

## Testmerges:
- [forging using material items, not rods](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16553)
- [[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
- [Fixes Skyrat Camera Icons [TM FIRST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16525)
- [[MODULAR] Prefs-Enabled Synth, IPC and Cyborg Brains!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)

**Comment by ghost** [comment]
Not a Bug, need to update your Byond (I only just learned this, had the same issue)

**Comment by tf-4** [comment]
^
