### ISSUE TITLE
Command Vendor cannot be deconstructed

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#16749]
## Testmerges:
[#16553: 'forging using material items, not rods' by jjpark-kb at commit dc4109c242](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16553)
[#16433: '[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor' by Tastyfish at commit 0fab473a3b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
[#16525: 'Fixes Skyrat Camera Icons [TM FIRST]' by OrionTheFox at commit b9b992fb71](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16525)
[#16105: '[MODULAR] Prefs-Enabled Synth, IPC and Cyborg Brains!' by RimiNosha at commit 9332195fe1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)
[#16290: 'Space hotel Tender loving Care (and more)' by Zergspower at commit 331da63dfc](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)

## Reproduction:
Normal vendor deconstruction steps:
- Unscrew panel
- Pry out board/restock kit

Command vendor deconstruction attempt:
- Unscrew panel (Icon doesn't change either)
- Attempt to pry
- No fail message or anything, just doesn't pry

Assumed cause? No board? No restock type? The vendor's kind of evil code-wise.
Assumed Solution? Make a board and/or restock, make it buyable via cargo. The items inside are already locked to access, having command able to buy it on maps without or repair it should it be broken should be possible

**Comment by larentoun** [comment]
AFAIK a spriter is needed for restock boxy-thingy
