### ISSUE TITLE
AI camera lights don't work anymore

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#16763]
Reporting client version: 514.1588

## Round ID:
6717

## Testmerges:
- [[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
- [[MODULAR] Prefs-Enabled Synth, IPC and Cyborg Brains!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)

## Reproduction:
Play AI on any map. Attempt to turn on camera lights. They will not make any visible light despite the enabled/disabled message appearing in chat. Unfortunately, I have been quite busy latly and I can't recall when it started, but it was within the last week or two, I believe. May or may not be PR related, unknown. Not map or round specific.

![image](https://user-images.githubusercontent.com/98357253/194991609-d98c3732-298e-4c86-84dc-a447433f6f92.png)
![image](https://user-images.githubusercontent.com/98357253/194991621-4fb45a57-6e0d-4c0a-b34a-11314a8fb143.png)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/pull/70453

**Comment by Funce** [comment]
Fixed in #16818
