### ISSUE TITLE
AI camera search missing locations on some maps

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#16762]
Reporting client version: 514.1588

## Round ID:
6717

## Testmerges:
- [[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
- [[MODULAR] Prefs-Enabled Synth, IPC and Cyborg Brains!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)

## Reproduction:
Not version specific, not round specific, not PR specific. This is been going on for some time. In Ice Box (and possibly some other maps) it is impossible to automatically snap to Telecommunications or AI upload, for example, because they do not exist on the AI camera list under any name I can find. Most other places are fine and I can manually move the eye to see those places, but it makes it pretty difficult if I need to be there right away and I can't find it.

![image](https://user-images.githubusercontent.com/98357253/194988846-780e17ab-be3c-4a6c-85fc-876aa46f4c35.png)

**Comment by ShizCalev** [comment]
believe this is related to this runtime (since they're triggered when you open the list.)
https://github.com/tgstation/tgstation/issues/70329

**Comment by Tastyfish** [comment]
May be fixed by https://github.com/tgstation/tgstation/pull/70453 but we'll see.

**Comment by Sealed101** [comment]
the verb is set to only show cameras with ai's internal network, which is set to be ss13. telecomms and upload are not part of that network and thus do not show. should probably just bring the verb in line with the Jump to Network network sweep

https://github.com/Skyrat-SS13/Skyrat-tg/blob/4566c192c9a8e1eed2b646e7adae42f20849041d/code/game/machinery/camera/tracking.dm#L1-L15

**Comment by Zergspower** [comment]
resolved
