### ISSUE TITLE
(observation) Supermatter Surge not surging

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#16772]
Reporting client version: 514.1589

## Round ID:
6721

## Testmerges:
- [[MODULAR] Fixes bug where opening Game Preferences and then spawning causing you to be random human. Also SR bodypart prefs refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16433)
- [[MODULAR] Prefs-Enabled Synth, IPC and Cyborg Brains!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16105)

**Comment by tobjv** [comment]
Looks to be still broken, probably upstream

**Comment by tobjv** [comment]
ah some one pointed out that there was already a report. #16663

**Comment by tf-4** [comment]
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/16663
