### ISSUE TITLE
Combat defib cell is removable

### ISSUE THREAD

**Issue by Glyphee** [Skyrat-SS13/Skyrat-TG#16826]
Reporting client version: 514.1588

## Round ID:
6732

## Testmerges:
- [Hemophagus: The Hemophage Revamp, Part One: The Bloodthirst](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16757)
- [hammers dont damage, reagent weapons when imbued lose durability](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
- [Granite's Love pass 3 of X for ruins - DS-2 flavor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)

## Reproduction:

Infinite capacity cell can be removed from the combat defibrillator

Get a combat defib, and use a screw driver on it, the cell will come out.

**Comment by Tastyfish** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/70494
