### ISSUE TITLE
Loadout Hat Errors. Loadouts spawning and giving non-existent hats

### ISSUE THREAD

**Issue by Dreathtil** [Skyrat-SS13/Skyrat-TG#16870]
Reporting client version: 514.1585

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

While setting up your loadout, under the hat options for wearing/usage a majority of the hats (primarily costume hats such) show up as errors. This applies also to when you spawn with them in game, and it should be noted that some (or all I have not checked) still work properly in game, they can be spawned and/or acquired naturally. I'm aware as of the posting of this that there was an upstream problem in regards to repathing. I wonder if this issue is related. I have compiled a complete list (I hope this is all of them) of the hats affected in the hat section of loadouts.
Mail Cap
Bandana (Pirate Bandana from Costume Vendor)
Xenos Helmet
Pirate Hat
Rice Hat
Nurse Hat (Locked/Unavailable)
TMC Hat
PG Hat
Deckers Hat
Morning Star Hat
Fancy Hat

**Comment by ghost** [comment]
Should have been closed by #17260, I went through all the broken icons in Loadout on top of just the paths

**Comment by ghost** [comment]
Is this still happening?

**Comment by vinylspiders** [comment]
@Jolly-66 this one too--fixed
