### ISSUE TITLE
OpFor staff notifications not functional

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#16886]
Reporting client version: 514.1589

## Round ID:
6755

## Testmerges:
- [Hemophagus: The Hemophage Revamp, Part One: The Bloodthirst](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16757)
- [hammers dont damage, reagent weapons when imbued lose durability](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)

## Reproduction:
In the words of a Game Assistant through Admin PM, OpFor applications used to have an autonotification system that no longer works. It's quite awkward balancing the use of the update button with patience - I don't want to get on anyone's nerves, but it also might never be seen at all with the system not working properly.

**Comment by Zergspower** [comment]
currently functional 
![image](https://user-images.githubusercontent.com/22140677/200141621-a8192c18-cc46-4674-99fa-b8804b87cea5.png)
