### ISSUE TITLE
Taur Colors Not Working

### ISSUE THREAD

**Issue by Resreep** [Skyrat-SS13/Skyrat-TG#16883]
## Round ID:
6754, but this has been going on for much longer than that.

 

## Testmerges:
[#16757: 'Hemophagus: The Hemophage Revamp, Part One: The Bloodthirst' by GoldenAlpharex at commit 34e7f9d99b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16757)
[#16732: 'hammers dont damage, reagent weapons when imbued lose durability' by jjpark-kb at commit ca023e96bd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
[#16290: 'Space hotel Tender loving Care (and more)' by Zergspower at commit fad7f0a213](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
[#16447: 'Ghost Hotel Update' by Kush1Push1 at commit c6ad9421c3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)

## Reproduction: 

Secondary colors for taurs don't appear. This can be fixed by stripping your character completely naked, underwear included, and then reequipping all your equipment, but any equipment alterations with hats or other reasons I'm unaware of cause it to reset back to the secondary colors simply not appearing. There's at least one other report on this same issue.

**Comment by Innocent-Fire** [comment]
I posted this issue almost 2 months ago, doubt it will get fixed anytime soon. It was also a problem way before I posted it too.

**Comment by Zergspower** [comment]
Duplicate as mentioned above
