### ISSUE TITLE
Telescopic shield not having an in-hand sprite when extended

### ISSUE THREAD

**Issue by SmolGreenBuggo** [Skyrat-SS13/Skyrat-TG#16905]
Reporting client version: 514.1588

## Round ID:
6758

## Testmerges:
- [Hemophagus: The Hemophage Revamp, Part One: The Bloodthirst](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16757)
- [hammers dont damage, reagent weapons when imbued lose durability](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)

## Reproduction:

Take a telescopic shield, extend it. It does not have an in-hand sprite. It is a simple and easy reproduction.

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/200141392-10010af5-182c-4e98-ab64-c68a02f7155f.png)
