### ISSUE TITLE
Blind players unable to see footprints and text after changing z-levels

### ISSUE THREAD

**Issue by Dino36L** [Skyrat-SS13/Skyrat-TG#16900]
## Round ID:
6756

## Testmerges:
#16757 
#16732 
#16290 
#16447 

## Reproduction:
Playing as a blind character on Ice Box Station, when arriving you able to hear people talk and see footstep indicators on the floor. When going down a level, for example using the Botany stairs to switch Z-levels, one is only able to see the messages on the screen as a speech bubble when they are right next to the blind character, the same going for the footstep indicators. Messages still pop up in the chatbox, but one is unable to see from where someone is talking from. Issue fixes itself when going back up a Z-level, and return when going down a Z-level.

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/pull/70608 was fixed upstream

**Comment by vinylspiders** [comment]
@lessthnthree

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/17170
