### ISSUE TITLE
Security HUD Aviators might cause permanent HUD view

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#16920]
Reporting client version: 514.1589

## Round ID:
6761

## Testmerges:
- [hammers dont damage, reagent weapons when imbued lose durability](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Granite's Love pass 3 of X for ruins - DS-2 flavor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)

## Reproduction:
Equip Security HUD Aviators and use the 'Toggle Mode' button. After removing the HUD, the screen will still show an active HUD display and you will be able to view and set records by examining people. I managed to fix it once by wearing them, toggling the mode, and taking them off. When I did it a second time, the HUD was permanent.

![image](https://user-images.githubusercontent.com/98357253/196098078-c1ce2d99-3953-4d6a-9a28-45784d78be5c.png)

**Comment by Zergspower** [comment]
confirmed still a bug
