### ISSUE TITLE
Cortical Borer: Symbiote T2 Chemical Increase resets chemical storage

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#16921]
Reporting client version: 514.1589

## Round ID:
6763

## Testmerges:
- [hammers dont damage, reagent weapons when imbued lose durability](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Granite's Love pass 3 of X for ruins - DS-2 flavor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)

## Reproduction:
Play as a Cortical Borer. Inhabit a host and become stronger at least once, to boost your maximum chemical storage above 50. Once you select Symbiote T2 from the evolution tree, your max will be reset to 50 - for example, making it 90/50. After enough times growing stronger, you can make up for it once again.

![image](https://user-images.githubusercontent.com/98357253/196162376-adc8bbdd-75b7-4897-ab00-c5621730d5ea.png)
![image](https://user-images.githubusercontent.com/98357253/196162408-35fbbddb-b01d-40fc-94da-7613030d66ba.png)

**Comment by Zonespace27** [comment]
#16801
