### ISSUE TITLE
Modsuit Deletion upon hatted removal.

### ISSUE THREAD

**Issue by rudew** [Skyrat-SS13/Skyrat-TG#17033]
## Round ID: 6781

When I tried to take off my modsuit, mind you active, and thusly with the hat stabilizer active, it instead put the hat I had on the stabilizer into my hand, and deleted the modsuit, leaving the HUD icon of the recall module but it spitting the message "No attached suit", May perhaps be upstream, but I checked their issues & no one had reported anything like it, and I just feel like someone on TG woulda likely found it if it was, but im not sure.

[##] Testmerges:
[](url)https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290
[](url)https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769
[](url)https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447
## Reproduction:
Take off a modsuit while it is online, perhaps specifically with a hat stabilizer module and a hat inside.

**Comment by ghost** [comment]
This is most likely an us thing, TG can't mess with the modsuit while active. TG might appreciate the fix being pushed up there though as a redundancy

**Comment by nevimer** [comment]
![2crcNaB2lE](https://user-images.githubusercontent.com/77420409/200092536-55b5b256-ba77-437d-85bb-8850927b71d7.png)

**Comment by nevimer** [comment]
Equip modsuit. Put hat on suit. Retract suit. Drag modsuit off while worn.

**Comment by nevimer** [comment]
https://user-images.githubusercontent.com/77420409/200092648-e7551fb9-1620-4890-82f9-c1978951fa31.mp4
