### ISSUE TITLE
Cyborg NaN% RoboTact

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat-TG#17046]
## Testmerges:
[#16290: 'Space hotel Tender loving Care (and more)' by Zergspower at commit faff0f2e86](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
[#16447: 'Ghost Hotel Update' by Kush1Push1 at commit c6ad9421c3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
[#16769: 'Granite's Love pass 3 of X for ruins - DS-2 flavor' by Zergspower at commit 16cf91abe1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)

## Reproduction:
N/A Just opened RoboTact and it was all borked. cause unknown.

![image](https://user-images.githubusercontent.com/6706750/197030184-132812c3-2c53-4956-aca3-dd083f1608db.png)
roboTact is all NAN I tried to change my light power setting and it only made it worse!
![image](https://user-images.githubusercontent.com/6706750/197030199-dd5e6ec3-7ee5-4bf6-9f06-4cffcf9f58a8.png)
now I have no flashlight!

**Comment by Zergspower** [comment]
Just tried this, were you off station by chance? currently can use all the functions in robotact

**Comment by Zergspower** [comment]
tried on a few different shifts - this may have been a subsystem crash that we cant replicate until it happens again - closing for now
