### ISSUE TITLE
AI shell can't be controlled after teleporting to escape shuttle right before reaching CC

### ISSUE THREAD

**Issue by DannyBoy3642** [Skyrat-SS13/Skyrat-TG#17096]
Reporting client version: 514.1589

## Round ID:
6797

## Testmerges:
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Granite's Love pass 3 of X for ruins - DS-2 flavor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)

## Reproduction:
May or may not be reproducible. As AI, I extracted my core with an engineering shell using the MEKA design. The shuttle had already departed, so I set the AI satellite teleporter to escape shuttle, did NOT calibrate it, and pushed the core through, followed by the shell. Within a few seconds of arriving on the shuttle, I grabbed the core once again and attempted to pull it to find I had been put back in control of the core, all right before the shuttle docked with Central Command. Each time I tried to connect to the shell thereafter, I would be connected to it for roughly a quarter of a second before being returned to the core as if I had disconnected from the shell. Neither reconnecting nor manually selecting the shell from the list seemed to fix this.

**Comment by tobjv** [comment]
Can you try and reproduce this on other maps?
