### ISSUE TITLE
Magnate MODsuit deleting itself

### ISSUE THREAD

**Issue by SmolGreenBuggo** [Skyrat-SS13/Skyrat-TG#17123]
Reporting client version: 514.1588

## Round ID:
6807

## Testmerges:
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Granite's Love pass 3 of X for ruins - DS-2 flavor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16769)
- [[MODULARIZING] Removes Foreigner and Adds Quirk Sanitization](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16836)
- [new rituals](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16942)
- [change how ashwalker's revive + more](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16902)
- [[TM ONLY] Mirrors 70738](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17114)

**Comment by YakumoChen** [comment]
Duplicate issue

**Comment by Zonespace27** [comment]
#17033
