### ISSUE TITLE
Dep. guard outfit sprites are missing

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-TG#17146]
## Round ID:

N/A

## Testmerges:

N/A

## ummm sir you broke my drip

https://github.com/Skyrat-SS13/Skyrat-tg/pull/16922 deleted a lot of uniforms, including dep. guard stuff.
probably fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/16892 ?

**Comment by ghost** [comment]
definitely fixed by the mentioned PR, those are the only icons broken by the removals I SAID I WAS SORRY AGUGHBNGH
