### ISSUE TITLE
Internal radio gets set to 0 instead of 1 as AI, after being EMP'd several times in a shell

### ISSUE THREAD

**Issue by Vekzie** [Skyrat-SS13/Skyrat-TG#17219]
Reporting client version: 514.1589

## Round ID:
6846

## Testmerges:
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [[MODULARIZING] Removes Foreigner and Adds Quirk Sanitization](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16836)
- [new rituals](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16942)
- [change how ashwalker's revive + more](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16902)
- [Near complete refactor and rework of how forge crafting benches work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
- [Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)

## Reproduction:
The issue: After being EMP'd several times by a 'mold' in an engineering shell as AI, my command comms no longer worked, in or out of my shell.

Get into a shell as an AI, and have your shell get EMP'd multiple times. I was fighting the mold, which emp'd me repeatedly. Then, in shell or out of shell, try to talk into command chat, with telecomms working fine. You won't be able to see command chat at all. It flips the internal radio on my core to 0 instead of 1, after checking with admin Desminus.

**Comment by Vekzie** [comment]
To add onto it, it seems that it affected all the comms except for common.

**Comment by Zergspower** [comment]
Yeah that's normal - the Roboticist can repair it
