### ISSUE TITLE
Characters of a Blood Dependent Origin (Vampires, Hemophages) Unable to bat form during the Spooky Month

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#17221]
## Round ID:
6847

## Testmerges:

N/A
## Reproduction:
Hemophage is said, literally on the race menu that during halloween, they can turn into bats, I don't see no ability button (I assume that was just put there by golden and then not elaborated on any further :trollface:), and as for vampires, I Prides Mirror'd into one like.. a month ago to no avail, Still no bat form then, and still no bat form now

**Comment by Paxilmaniac** [comment]
Bat form was removed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/9636 and it is likely just a mistake that it still says they can

**Comment by PeriwinkleBuddy** [comment]
Wack.
