### ISSUE TITLE
Cyborg light sprites are not updating when light is turned on and off

### ISSUE THREAD

**Issue by Reco201** [Skyrat-SS13/Skyrat-TG#17255]
Reporting client version: 514.1588

## Round ID:
6863

## Testmerges:
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Near complete refactor and rework of how forge crafting benches work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
- [Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
- [Fix/Refactor: MOD tails, tails use defines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)

## Reproduction:
Spawn in as cyborg
Turn lights on
Notice how the sprite does not update
![image](https://user-images.githubusercontent.com/71794877/198909459-7de70d2e-2b38-491b-af78-96e7c98392b8.png)

Cyborg sprites don't seem to be updating when the light is turned on. The actual light still works but the sprite still appears in the off state.

**Comment by Sonic121x** [comment]
cause by this change:https://github.com/tgstation/tgstation/commit/3867fdeb85ac04bdb2a52fa734058b3d2022925d
