### ISSUE TITLE
Universal Tagger from #17212 is completely busted

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#17261]
## Testmerges:
[#16447: 'Ghost Hotel Update' by Kush1Push1 at commit c6ad9421c3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
[#17103: 'Near complete refactor and rework of how forge crafting benches work' by Paxilmaniac at commit 6cf4d5e14e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
[#17056: 'Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated' by Paxilmaniac at commit 11be36155f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
[#16778: 'Fix/Refactor: MOD tails, tails use defines' by larentoun at commit 760073b33f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)
[#17037: 'Gives the lavaland ashwalker den the same treatment I gave the icebox one' by Paxilmaniac at commit 5359bba113](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)

## Reproduction:
The Universal Tagger, a new item from #17212 serving to merge all the previous cargo tagging items into one, is completely busted. Lacks receipes in lathes to print out and the sales tagger sprite for it is completely invisible, making its functionality spotty at best and unobtainable to anyone besides QM and cargotechs.

**Comment by Tastyfish** [comment]
Sprite being fixed in https://github.com/tgstation/tgstation/pull/70926

**Comment by Tastyfish** [comment]
Oh note that in the meantime, the GrandArk Exporter app still works as a way to print barcodes.
