### ISSUE TITLE
Halloween Race: Dullahan 

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#17274]
## Testmerges:
[#16447: 'Ghost Hotel Update' by Kush1Push1 at commit c6ad9421c3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
[#17103: 'Near complete refactor and rework of how forge crafting benches work' by Paxilmaniac at commit 6cf4d5e14e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
[#17056: 'Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated' by Paxilmaniac at commit 11be36155f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
[#16778: 'Fix/Refactor: MOD tails, tails use defines' by larentoun at commit 760073b33f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)
[#17037: 'Gives the lavaland ashwalker den the same treatment I gave the icebox one' by Paxilmaniac at commit 5359bba113](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)

## Reproduction:
Play as a Dullahan and have someone try to talk to you with a /me or Looc, be unable to see both, but be able to talk in both

**Comment by YakumoChen** [comment]
upstream issue (dullahans are very broken in general)

**Comment by kcrash201** [comment]
Gotcha, figured it'd be, but made a post anyways
Alright just gonna get this closed coz it's upstream.
