### ISSUE TITLE
The Centcom Commander Cap is gone from the Command Clothing Vendor

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#17317]
## Round ID: 
All

## Reproduction: 

Look at the vendor 🗿

**Comment by SpaceLoveSs13** [comment]
There was never a Central Commander role?

**Comment by SpaceLoveSs13** [comment]
There is no central commander role. Rep's items werent changed in the commandrobe code recently and all paths seem fine.

**Comment by Mithrun** [comment]
well it's gone either way...
![image](https://user-images.githubusercontent.com/75141807/206254424-449ba0b7-e5f2-4d52-a169-6eb721ed960b.png)
used to be right here, looked like this
![image](https://user-images.githubusercontent.com/75141807/206254854-2c532b95-3ca7-4376-a78b-238a2f51b134.png)
/clothing/head/hats/centcom_cap

**Comment by Zergspower** [comment]
Since this isnt really an issue i'm going to close it out - though if you want to add it in feel free to do a PR with maybe a subtype for the NTRep
