### ISSUE TITLE
Enhanced Regeneration attempting to repair Cybernetic Damage

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#17316]
## Round ID:
6880

## Testmerges:
[#17290: 'Hemophagus: The Hemophage Revamp, Part Two: Blood Surge' by GoldenAlpharex at commit d97d2f9d13](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)

## Reproduction:
During an Enhanced Regeneration state, the tumor will attempt to repair cybernetic damage (to no avail) and still consume blood for the damage (not) repaired, don't know how else to say it other than: Blood is being consumed to repair damage it cant repair.

**Comment by GoldenAlpharex** [comment]
Thanks for the report, I probably would've never caught that otherwise!

**Comment by GoldenAlpharex** [comment]
Actually, since it's a test-merge related issue, I'll close it now, since it's technically resolved already!
