### ISSUE TITLE
Ashwalkers unable to get trophies

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#17328]
## Round ID:
6888

## Testmerges:

N/A
## Reproduction:

Title, dunno what else to say, but I can't seem to get any trophies through conventional means, I was pretty sure that for a while, ashwalkers killing things would have a chance to drop trophies

**Comment by Zergspower** [comment]
was able to get a goliath trophy with a spear, assuming resolved
