### ISSUE TITLE
Odd behavior with some tails and modsuits

### ISSUE THREAD

**Issue by Plythios** [Skyrat-SS13/Skyrat-TG#17340]
## Reproduction: 
![unknown](https://user-images.githubusercontent.com/3536787/199874920-980ddeb2-0584-4c77-b723-dbbd62198837.png)

For the past month or so, I have noticed that some tails are neutered or changed when wearing modsuits. I have seen other people having this issue and they too have confirmed the problem.

To reproduce this issue, I would recommend wearing the "Snake (Strip Alt)" and trying it out.

While this is being read, I'd like to also report another behaviour with snake tails in general. In that wagging them makes them vanish completely. Now, I'm not entirely familiar with the rules regarding valids, security and antagonists, but i imagine one  could probably disguise themselves quite easily by simply wagging their tail, and looking like someone completely different.

**Comment by YakumoChen** [comment]
For once test merges are relevant here and you should have checked them

Tails missing on wag is a separate issue (with a duplicate on the feed)

The orher point is no concern, there is a verb to hide animal parts in game

**Comment by Zergspower** [comment]
Resolved
