### ISSUE TITLE
Auto-Wash doesn't start properly as a janitorial cyborg

### ISSUE THREAD

**Issue by Vekzie** [Skyrat-SS13/Skyrat-TG#17410]
Reporting client version: 514.1589

## Round ID:
6915

## Testmerges:
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)
- [Hemophagus: The Hemophage Revamp, Part Two: Blood Surge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)
- [NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16043)
- [[MIRROR] Easy's Super Omega  "unarmed strike based species var moved to limbs" refractor, unarmed strike striking with specific body parts rather than it just being flavor, and brain based attacking limb selection extra chunky edition. And also bodypart traits. [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17306)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)

## Reproduction:
The issue: Can't start auto wash when a janitorial model as a cyborg. I have  water in the bucket, I have soap, everything there is fine. But when you start it, it immediately stops and wont continue. The request to report the issue was by Fluffy-Kun.

Steps to reproduce: Be a cyborg, activate a janitorial model, get water in your bucket, and try to activate auto wash.

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/issues/69018 upstream duplicate issue
