### ISSUE TITLE
Void Raptor Maint Tweaks and Fixes

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#17434]
## Round ID:
6934

## Reproduction:

Abandoned Robotics has extra Package Wrappers and Hand Labelers, the table they are on is partly reinforced.
Starboard Quarter Solars has a reinforced wall jutting out
Feels like theres a LOT of heaters and not enough Pacman units
Theres just.. some extra reinforced walls between the Night Club and the Vacant Office (why..?)
![WhyTheseGasPricesSoHighWawa](https://user-images.githubusercontent.com/108144396/200809145-75c8a773-4fc5-4647-8f8f-0ce1ab44e682.PNG)
Reinforced Walls on the south side of the Construction Area, no other reinforced walls on the other sides
Xenobiology Private Maint Room has a (by default) inaccessable curtain (Marked with blue), recommend making the curtains controlled by a button or move the dresser (Marked with red) (Also does that heater need to be there? Maybe make it a Personal Closet?
![OhMyLordyLordIsThatABANANA](https://user-images.githubusercontent.com/108144396/200810711-34b3832e-2799-4df9-a329-dba2865a19cd.PNG)
Theres no Security Warrant Console, woe be any assistants that get a fine and want to use a warrant console

**Comment by Zenitheevee** [comment]
So-
Believe it or not
The Abandoned Robotics Handlabeler + Package wrapping being 2 of each actually stems from Delta's Abandoned Robotics lab.
The only other maps that have these rooms (Meta and Kilo) lack these, except for meta which only had 1 hand labeler. 

But the Void Raptor Abandoned Robotics lab has another issue: Duplicated cyborg chargers on the same tile.
