### ISSUE TITLE
DS-2 Liaison is targeted by their own turrets.

### ISSUE THREAD

**Issue by Serrasaa** [Skyrat-SS13/Skyrat-TG#17452]
Reporting client version: 514.1589

## Round ID:
6979

## Testmerges:
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)
- [Hemophagus: The Hemophage Revamp, Part Two: Blood Surge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)
- [NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16043)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
- [New default laws for Silicon](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
- [Gun Cargo Rework: Now with 90% less gun and 100% more stuff the rest of the crew can actually use](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326)

## Reproduction:
Simply selecting to spawn as the Corporate Liaison aboard the DS-2 will cause all turrets both on the station, and down on the Interdyne to be aggressive towards you despite being a part of the faction.

**Comment by zydras** [comment]
Haha hey I might have caused that, thanks for reporting it!

I believe it may have been due to me trying to give the CL a lighter implant, of which i've removed in a recent commit. I've yet to test it, but I assume that is all that's keeping the slot from being not targeted.

**Comment by zydras** [comment]
From what it's worth, either it's simply something else in-round that caused it, or something i've missed.
![Screenshot (1703)](https://user-images.githubusercontent.com/39807808/201523282-8e56a01e-25f4-41c2-ac11-5a77f5dfda89.png)

**Comment by Serrasaa** [comment]
I'm not sure, it could just be me somehow. But every time I spawn as CL I get blasted the station turrets without fail, 3 rounds in a row now.

I've since spawned as something **other** than a CL and the turrets behave normally. But still, only whenever I'm not CL.

![dfa9798f0780b5e0bce46498c4f4f351](https://user-images.githubusercontent.com/117245104/201764991-4762dc1e-ea17-4a42-b6c6-3ce3f6245276.png)

**Comment by zydras** [comment]
Seems you still have the lighter implant, that might've been the cause but despite tests I can't seem to find *why* that occurs. Odd.

**Comment by Zergspower** [comment]
Faction is present now
