### ISSUE TITLE
Laser pointer circuits have no cool and can easily overload and crash tiles

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-TG#17525]
Feeding the output signal of a laser pointer into its own input to make a feed back causes a rapid fire of laser pointers every single frame it can, over loading tiles into errors while being fast enough for you to walk around while it destroys tiles if the target is you

![66d52545e3437ba0f52e9e8ca7608296](https://user-images.githubusercontent.com/69182855/202378704-3f8a16de-fc45-47c0-96d4-a813df1ba0e2.png)

**Comment by Tastyfish** [comment]
Probably an upstream issue since wiremod circuit stuff should be 100% stock tg.
