### ISSUE TITLE
Forge Oven Baking and Cheese Curd recipes broken

### ISSUE THREAD

**Issue by Rvali** [Skyrat-SS13/Skyrat-TG#17536]
Reporting client version: 514.1589

## Round ID:
7012

## Testmerges:
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)
- [Hemophagus: The Hemophage Revamp, Part Two: Blood Surge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)
- [NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16043)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
- [New default laws for Silicon](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
- [Gun Cargo Rework: Now with 90% less gun and 100% more stuff the rest of the crew can actually use](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326)

## Reproduction:

Forge Baking:

In the making bread in a forge, an oven tray is needed, but when dough is inserted into the forge with the tray, it burns instead. This was done in a lit forge, with both wheat dough and rootdough.

Cheese Curd:

Curd Cheese is made as one normally would, and then put into the microwave. One is put in only. What comes out is a burned mess.

**Comment by Rvali** [comment]
An update: Even with the Microwave not going boom when added new parts, the Cheese Curd recipe is still broken.

**Comment by Paxilmaniac** [comment]
Did you leave the dough in the oven too long, that tends to make food burn

**Comment by Rvali** [comment]
It instantly burns, so no, I don't think that's the issue.
