### ISSUE TITLE
pAIs cannot use radio while folded in

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#17547]
## Testmerges: 
[#17037: 'Gives the lavaland ashwalker den the same treatment I gave the icebox one' by Paxilmaniac at commit a22f66b85d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)
[#17290: 'Hemophagus: The Hemophage Revamp, Part Two: Blood Surge' by GoldenAlpharex at commit f9449a40e4](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)
[#16043: 'NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink' by Jolly-66 at commit 2228d01bf0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16043)
[#17229: '[MODULAR] Complete DS2 remap + 2 new syndicate spawners' by zydras at commit 1feb1d28aa](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
[#17269: 'New default laws for Silicon' by Zergspower at commit 52fbb5af6c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
[#17326: 'Gun Cargo Rework: Now with 90% less gun and 100% more stuff the rest of the crew can actually use' by Paxilmaniac at commit 4d4adc67f9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326)

## Reproduction:
1. Get downloaded as pAI
2. try to use radio and notice its saying you cannot reach the radio
3. fold out and use radio again and have it work

**Comment by vinylspiders** [comment]
@Jolly-66 fixed, see referenced PR
