### ISSUE TITLE
Microwave duplication 

### ISSUE THREAD

**Issue by CrazyMoth** [Skyrat-SS13/Skyrat-TG#17543]
## Round ID: 7013

 

Map: Delta Station

## Testmerges:

Not sure.

## Reproduction:

When building a microwave;
1. Build the machine frame and put wires in.
2. Unsecure the frame, move it at least 1 tile then secure it again.
3. Put in the essentials, do NOT use screwdriver to finish it.
4. Unsecure the frame again and move it 1 tile at least, then secure it.
5. Finish the microwave with a screwdriver. ( In my case the microwave was on the floor. )
6. All the required parts spawn inside the microwave. 
7. Use eject option and you get all the parts required refunded, except the iron for the frame.

**Comment by YakumoChen** [comment]
upstream bug, already being worked on

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/pull/71087 Fixed, can be closed.

**Comment by vinylspiders** [comment]
@lessthnthree

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/17482
