### ISSUE TITLE
Vox clown does not get clown mask

### ISSUE THREAD

**Issue by UntoldTactics** [Skyrat-SS13/Skyrat-TG#17560]
## Testmerges: 
[#17229: '[MODULAR] Complete DS2 remap + 2 new syndicate spawners' by zydras at commit a716619db7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
[#17269: 'New default laws for Silicon' by Zergspower at commit 677e05aa15](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
[#17326: 'Gun Cargo Rework: Now with 90% less gun and 100% more stuff the rest of the crew can actually use' by Paxilmaniac at commit 5f9e92b4f8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326)

## Reproduction:
Join the job 'Clown' as the species 'Vox' (new vox to be very specific)
Spawn with vox gas mask in mask slot opposed to clown mask.

**Comment by Tastyfish** [comment]
In terms of alternate clown outfits, I think we might only account for plasmamen and not either vox, yeah.
