### ISSUE TITLE
Ashwalkers getting draconic language instead of ashtongue

### ISSUE THREAD

**Issue by boniblade** [Skyrat-SS13/Skyrat-TG#17599]
Reporting client version: 514.1589

## Testmerges:
- [New default laws for Silicon](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
- [Gun Cargo Rework: Now with 90% less gun and 100% more stuff the rest of the crew can actually use](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)

## Reproduction:

Being an ashwalker gave me the draconic language instead of ashtongue, which everyone else has. I think it's because my character was made in an older version. I can't change the languages they can understand.

**Comment by YakumoChen** [comment]
Might be a save file issue, contact a keyholder like Golden
