### ISSUE TITLE
PDAs don't imprint job titles from their inserted IDs.

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#17719]
## Round ID:
N/A

## Testmerges:
- [New default laws for Silicon](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
- [[TM-ONLY] Fixing PDAs - Early mirror of #71467](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17691)
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)

## Reproduction:
Inserting an ID with a different name or job title into a previously imprinted or roundstart PDA doesn't enable the imprint key in the UI. Roundstart PDAs also don't reflect alternate titles anymore, spawning instead with the default title. Happens consistently across rounds, easily reproducible.

**Comment by ghost** [comment]
@GoldenAlpharex 
I know you're working with PDA's on https://github.com/tgstation/tgstation/pull/71467, did the early Testmerge of [#71467](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17691) slip off?

@kittysmooch this bug is one of the cases where Testmerges is a section that actually needs to be filled out, we've got stuff touching PDAs test merged

**Comment by kittysmooch** [comment]
> @GoldenAlpharex I know you're working with PDA's on [tgstation/tgstation#71467](https://github.com/tgstation/tgstation/pull/71467), did the early Testmerge of [#71467](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17691) slip off?
> 
> @kittysmooch this bug is one of the cases where Testmerges is a section that actually needs to be filled out, we've got stuff touching PDAs test merged

Updated with today's TMs. The PDA bug is still present, so it seems fine. Sorry for the lag, been pretty busy.

**Comment by Zergspower** [comment]
believe we resolved this as i can imprint a few ID's
