### ISSUE TITLE
Feathery wings are missing

### ISSUE THREAD

**Issue by FireGriffin32** [Skyrat-SS13/Skyrat-TG#17720]

**Comment by Zergspower** [comment]
Can you elaborate on the conditions here? Is it only with modsuits?

**Comment by FireGriffin32** [comment]
I think it has been fixed now. I noticed them reappear a few days ago. And
no it was just missing fully if I had any clothes on. It started when the
MODs where enabled to show mutant parts so I figured something from that
might have caused it.
