### ISSUE TITLE
Lawyer's loadout gets overwritten twice.

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#17782]
## Reproduction: 
I spawn in with my loadout set to move job items to bag and i get two pieces of clothing in the bag, jumpskirt and shoes and then a different set of jumpskirt and jacket to replace my loadout.
![image_2022-11-27_121140095](https://user-images.githubusercontent.com/75141807/204132126-6c335dad-22c6-4773-8a48-5bf2ed2a56d4.png) My actual loadout
![image](https://user-images.githubusercontent.com/75141807/204132134-738efe40-7857-42f6-90fa-f3529bd74c86.png)
 vs what i gets what i get

**Comment by vinylspiders** [comment]
Is this happening still? I was trying hard to reproduce it while in the loadout code and was not able to.

Furthermore I checked for the most likely causes and could not find any, so it seems to me like it may have been fixed.

**Comment by vinylspiders** [comment]
@Jolly-66 this one can be safely closed I think. I've tried to reproduce it and no luck, and from the not insignificant amt of time I've spent in loadout code I'm sure it's since been fixed by something.
