### ISSUE TITLE
berzerker armor for ashies still missing sprites

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#17784]
Reporting client version: 514.1589

## Round ID:
7089

## Testmerges:
- [New default laws for Silicon](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17269)
- [[MODULAR] Complete DS2 remap + 2 new syndicate spawners](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17229)
- [[TM-ONLY] Fixing PDAs - Early mirror of #71467](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17691)
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)

**Comment by Erol509** [comment]
#17861
