### ISSUE TITLE
Ice Box Interdyne Rampant Brand Intelligence bug

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-TG#17797]
## Round ID:
7093

## Date and Time of Issue:
21:04
Sunday, 27 November 2022

## What Map did this Issue occur on:
Ice Box

## Testmerges (If Applicable):
N/A

## Reproduction:
-Not sure if this issue happens if Interdyne is located on the lowest Z-level; this would have to be tested. For now we'll assume that it only happens when Interdyne is on the middle Z-level (the lower level of the station)
-Initiate the 'Rampant-Brand Intelligence' random event
-Vending machines in Interdyne are somehow able to be affected by the random event, including mining point redeemers  

## Possible Screenshots of the Issue in question:
![interdyne bug](https://user-images.githubusercontent.com/88389357/204176622-5763fba3-f5a0-4056-8a48-5f1b82c0cf7a.PNG)
Here is a screenshot of a poor ID operative being put into crit after fighting the Rampant vending machines.

**Comment by Quink-Fix** [comment]
It's also worth noting that station cleanliness affects Interdyne on Ice Box too - some tiles are missing, which leads to irreplaceable decals being destroyed round-start.

**Comment by Zergspower** [comment]
Issue reported upstream

**Comment by tf-4** [comment]
? where is it reported
