### ISSUE TITLE
Fancy Heels do not account for Digi legs.

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-TG#17808]
## Round ID: 
past 20 or so rounds atleast.

## Date and Time of Issue: 
ongoing.

## What Map did this Issue occur on: 
clothing sprite issue, does not apply

## Reproduction: 
add Fancy Heels to a digitigrade leg'd character.

## Possible Screenshots of the Issue in question:
![issue](https://user-images.githubusercontent.com/58378414/204388737-db7c615b-4a2e-46b6-9e50-0f2b0b3eba84.png)

**Comment by ghost** [comment]
@tf-4  can this get a Sprite tag
