### ISSUE TITLE
Forked xeno tongue issues unlocking uplink

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#17804]
## Round ID:
7098

## Reproduction:
Xeno tongue can't unlock their traitor uplink. For example, they have to say 'x-ray' but their tongue pronounces 'ecks-ray.' This might impact other tongues, but the xeno is the one experienced in this round.

**Comment by Tastyfish** [comment]
hilarious

**Comment by YakumoChen** [comment]
Based and xenophobepilled

**Comment by YakumoChen** [comment]
Also this might be an upstream issue since I imagine lizards would have the same trouble with some words + not our code

**Comment by Zergspower** [comment]
works if you just swap to an alt language - probably intended but defo upstream
