### ISSUE TITLE
DS-2/Interdyne Spawner Issues

### ISSUE THREAD

**Issue by BriareosBlue** [Skyrat-SS13/Skyrat-TG#17849]
## Round ID: 
7114

## Reproduction:

DS-2 and Interdyne ghost role players do not spawn in having the Codespeak language known. Furthermore, when they spawn in, their loadouts are given to them repeatedly, overwriting character loadouts and overflowing their storage.

**Comment by YakumoChen** [comment]
Relevant code:
https://github.com/Skyrat-SS13/Skyrat-tg/blob/878be38209a0189c5a116e7565894734dad7070b/modular_skyrat/modules/mapping/code/mob_spawns.dm#L74
