### ISSUE TITLE
Interrogation room eating logs

### ISSUE THREAD

**Issue by FeenieRU** [Skyrat-SS13/Skyrat-TG#17859]
## Round ID:
--

## Testmerges:
--

## Reproduction:
Any logs, that was written in interrogation room in brig can be eaten by bluespace. Nobody see your log as you.

**Comment by Zergspower** [comment]
Can add a bit more detail here? Logs? as in game logs? Chat logs?

**Comment by FeenieRU** [comment]
> Can add a bit more detail here? Logs? as in game logs? Chat logs?

Chat logs

**Comment by Tastyfish** [comment]
This was likely a one-off spatial grid issue unless somebody can recreate it as somehow being specific to the interrogation room.

**Comment by Zergspower** [comment]
yeah i wasnt able to see what it is, and i've seen interrogation chat since then
