### ISSUE TITLE
Ashwalker Tendril reviving dead without actually healing them.

### ISSUE THREAD

**Issue by Nechronom** [Skyrat-SS13/Skyrat-TG#17882]
Reporting client version: 514.1589

## Round ID:
7123

## Testmerges:
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)

## Reproduction:
When the corpse of an ashwalker is brought next to the tendril that which they spawn from and their entire antagonist role is based around, they do not explode and create another Ash Walker egg, the corpse is instead put inside of a different egg called an Occupied Egg. Normally this would revive you and, along with a message stating that the tendril is having mercy on you and to be patient, attempt to return you to health.
At the moment it seems unable to do this. when an ashwalker corpse is currently placed next to the tendril, it will put your corpse into an egg, sure, and even briefly revive you as if you had been defibrillated! But it will not attempt to heal you, it would seem. The longest I lasted while inside an egg is when my fellow ashwalkers had used surgery to repair most of my bruise and burn damage before bringing me to the tendril. It revived me at light crit, and I lived for about half a minute before the messages regarding my slow bleeding built up and my screen eventually became whiter and whiter. Eventually killing me.. and then I began the much more regular experience of slowly being made into an egg. dying. being released from the egg. and then repeating the cycle over and over. At this point, the message stating that '.You have died. Barring complete bodyloss, you can in most cases be revived by other players. If you do not wish to be brought back, use the "Do Not Resuscitate" verb in the ghost tab.' and all that it includes being posted literally right above the message of 'The tendril has decided to be merciful and revive you within a minute, have patience.' and repeating each time your body is brought in to a new egg.

![image](https://user-images.githubusercontent.com/63927284/205269290-264a67f3-9aea-43fb-9fd3-d3e70673d56c.png)

**Comment by Zergspower** [comment]
I cant replicate this so the assumption is it's resolved

**Comment by Nechronom** [comment]
What do you mean you can't replicate this? Just go into crit as an ash
Walker next to the tendril.. It very much is still an issue
