### ISSUE TITLE
3 Instances of Normal Meteor Wave in admin event panel

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#17884]
## Round ID:
Private Test Server
Checked and non-existent on TG

## Testmerges:
N/A

## Reproduction:
Be Admin
Open Event window
Type Meteor

Peep the horror

![image](https://user-images.githubusercontent.com/76465278/205287808-e739ed0e-6268-4f28-a7c1-96563964ad5b.png)

**Comment by GuiltyNeko** [comment]
In modular_skyrat/modules/event_vote/code/event_chaos_system.dm there's a /datum/round_event_control/meteor_wave/major_dust which doesn't exist as a real subtype. My master is slightly outdated so it's likely there's others that exist somewhere.

For reference major dust was made into a space dust subtype.
