### ISSUE TITLE
Syndicate posters designed to demoralize crew spawn with randomgen

### ISSUE THREAD

**Issue by CenkTheRaptor** [Skyrat-SS13/Skyrat-TG#17956]
Reporting client version: 514.1589

## Round ID:
7154
 it affects all rounds since #15262 was merged

## Testmerges:
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)

## Reproduction:

 Start the round, syndicate posters will spawn on walls with randomgen posters.

**Comment by CenkTheRaptor** [comment]
first noticed this was the case at the interlink: [https://i.gyazo.com/14e4fef1894e74d86be0a97e142a7a92.png](url)

**Comment by E231kei500bandai** [comment]
> https://i.gyazo.com/14e4fef1894e74d86be0a97e142a7a92.png

![image](https://i.gyazo.com/14e4fef1894e74d86be0a97e142a7a92.png)

**Comment by E231kei500bandai** [comment]
Does this effect the actual station or just that place. I dont recall this bug ever happening on TG

Edit: So I looked at the posters right after the round starts and this is indeed a bug. I guess I just wasn't paying enough attention to the posters before now. I just never noticed a syndicate poster spawning roundstart.

**Comment by ghost** [comment]
Is this still happening?

**Comment by Jolly-66** [comment]
I wanna say this is a /tg/ issue due to the random spawners.

Maybe not.

**Comment by E231kei500bandai** [comment]
I think it could be because the spawn place is off the station z-level so the posters are acting like they're on the syndicate z-level. but thats just a guess maybe they just put the wrong type of posters there,

Edit: Nevermind I'm dumb it actually happens on TG I just never noticed it
