### ISSUE TITLE
Medieval Helmet sprite mismatch

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#17976]
## Testmerges:
Master commit: [33e1d22d983e91ce2afb3e2644e02a7c363b3cf5](https://github.com/Skyrat-SS13/Skyrat-tg/commit/33e1d22d983e91ce2afb3e2644e02a7c363b3cf5)
The following pull requests are currently test merged:
[#17372: 'MOD Hardlight (Refactors how sprite accessories handle MODs)' by theOOZ at commit f4ab3d8318](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)
[#17813: 'Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors' by Paxilmaniac at commit 7d417f3cc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
[#17455: 'Fairly large assault operatives changes' by Paxilmaniac at commit 08cc744978](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)

## Reproduction:
Wear any Medieval Helmet from the Vintage Crate
![Helmets](https://user-images.githubusercontent.com/36179195/206158121-a858273c-de62-4190-8e37-e0ffd378f343.png)

Muzzles seem to not match when facing east or west, tried on difference species for examples shown

**Comment by Tailiik** [comment]
I'm the goober on the left, snout used is Mammal, Long for reference.

**Comment by ghost** [comment]
This will be fixed in the "inevitable" sprite cleanup for the relevant file
Soon:tm: meaning whenever I can be assed to do it

@tf-4  can this get the Sprite tag ?

**Comment by Jolly-66** [comment]
@OrionTheFox you can ping me on Discord for tagging issues :)
