### ISSUE TITLE
Bluespace RPD Remote Piping doesn't work.

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#17970]
Reporting client version: 514.1589

## Round ID:
7156

## Testmerges:
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)

## Reproduction:

 It says alt click to toggle remote piping. You alt-click, nothing happens.

**Comment by vinylspiders** [comment]
@Jolly-66 fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/17980

<details>
<summary>works</summary>

![dreamseeker_7vaRwOjQwc](https://user-images.githubusercontent.com/13398309/229267825-5fe25f33-b513-498d-96dd-c7ddfb2ffa29.gif)

</details>
