### ISSUE TITLE
Can only pull items from containers from the second slot.

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-TG#17990]
## Round ID:7166

Pretty much as said in the title, when a bag or box is filled, one can only take out items from the second slot, nessesitating the constant taking out and replacing of items until the right item is in the slot that you wanted to take out in the first place

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: N/A

## Testmerges:

[#17813: 'Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors' by Paxilmaniac at commit 7d417f3cc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
[#16967: '[99% MODULAR] Synth and IPC Unification and Extended Customization!' by RimiNosha at commit c3f0864094](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16967)

## Reproduction:
Don't know how to reproduce but maybe just, play an armalis vox and have a bag, fill the bag and try to take items out? Works with boxes and belts too.

**Comment by ARandomAlien** [comment]
Also randomly seems to fix itself, its just, all around a weird bug, restarting or relogging did not help

**Comment by Jolly-66** [comment]
Ignore that. I misunderstood what you said.

If you keep running into this please keep a track log of rounds so we may investigate.

**Comment by Zergspower** [comment]
> Also randomly seems to fix itself, its just, all around a weird bug, restarting or relogging did not help

Given im seeing it more and more - this is 99% probable a window issue. 

Next time it happens, hover over the icon on your task bar, then hover over the popup that comes up - no need to click anything. Do that until the slot 'opens up'
