### ISSUE TITLE
Void raptor distro readout.

### ISSUE THREAD

**Issue by trefoils** [Skyrat-SS13/Skyrat-TG#18010]
Reporting client version: 514.1588

## Round ID:
7172

## Testmerges:
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [[99% MODULAR] Synth and IPC Unification and Extended Customization!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16967)

## Reproduction:
The issue is only on void raptor. The distro on the computers never reads right. I am unsure what it is reporting but it can't be distro as it always seems to report waste gases like carbon dioxide or some such thing.  be a qol thing mostly to get those computers working and help atmos and engineering better monitor conditions on the station.

**Comment by Zergspower** [comment]
could you clarify which computer? I'm not able to see this

**Comment by trefoils** [comment]
> could you clarify which computer? I'm not able to see this

stations atmospheric monitoring.. it reads something but that something is clearly never distro. though recently almost every station no longer has a working atmospheric monitoring for distro

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/19086 Fixed I think?

If not please say so and I'll reopen. Trying to get rid of some of these older ones.
