### ISSUE TITLE
mail_goodies var given with quirks like clown enjoyer & mime fan don't work

### ISSUE THREAD

**Issue by desertmote** [Skyrat-SS13/Skyrat-TG#18043]
Reporting client version: 514.1589

## Round ID:
7178

## Testmerges:
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [[99% MODULAR] Synth and IPC Unification and Extended Customization!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16967)

## Reproduction:

For example these two quirks are supposed to give you more stuff to get in the mail, which doesn't happen.

![Code_VyrdzEHhcg](https://user-images.githubusercontent.com/77534246/206797123-f111af08-4fa0-482b-93d4-1678180c13ab.png)
![Code_adEE6ppC2U](https://user-images.githubusercontent.com/77534246/206797125-c100a468-621a-4db4-b585-a730e35e9043.png)

**Comment by Jolly-66** [comment]
Wonder if this is bugged on /tg/ by chance.

**Comment by vinylspiders** [comment]
It's not a guarantee, one item is picked randomly from the list in the screenshot above, and then that one random item is picked from the weighted list. So it's actually a fairly low chance to get any given item from the quirk goodies.

https://github.com/Skyrat-SS13/Skyrat-tg/blob/f7c26bbf2592b92034ba1ede42cf1797b1324024/code/game/objects/items/mail.dm#L166-L173

@lessthnthree I think this one can be closed, not a bug but a misunderstanding of the feature.
