### ISSUE TITLE
Morphling can turn completly see through

### ISSUE THREAD

**Issue by Sgt-Solid01** [Skyrat-SS13/Skyrat-TG#18068]
Reporting client version: 514.1583

## Reproduction: As an morph, turn into something one Z-level below the current one while in a vent, when coming out you turn invinsible, works for carbons, npcs and objects,  on the map Icebox, in a vent be outside chapel and above science, you can see one Z-level down chap when looking inside of there, from here turn into anything down there and once you come out the vent you are completly see through.

turning invinsible is not Good.

**Comment by YakumoChen** [comment]
upstream issue

**Comment by Jolly-66** [comment]
If this is still an issue, please post an issue report upstream.

VERIFY the issue is still there by using /tg/ code.
