### ISSUE TITLE
Split Personality doesn't return original person back into their body

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#18096]
Reporting client version: 514.1589

## Round ID:
7189

## Testmerges:
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [[99% MODULAR] Synth and IPC Unification and Extended Customization!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16967)
- [Add: Cybernetic Tongue & Augments Tweak](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17561)

**Comment by Floofies** [comment]
This happened to me once! I had the brain tumor quirk which gave me the brain trauma.

**Comment by Jolly-66** [comment]
If this is still an issue, please post an issue report upstream.

VERIFY the issue is still there by using /tg/ code.
