### ISSUE TITLE
Compact AI Circuit (Posibrain reskin) creates broken ghost prompt on spawn)

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#18120]
## Testmerges:
[#17813: 'Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors' by Paxilmaniac at commit 7d417f3cc0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
[#17561: 'Add: Cybernetic Tongue & Augments Tweak' by Floofies at commit 74f0f4c2c1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17561)
[#16967: '[99% MODULAR] Synth and IPC Unification and Extended Customization!' by RimiNosha at commit d86e83c1ad](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16967)

## Reproduction:
- Have 1 player set cyborg posibrain pref to Compact AI Circuit
- Have them late-join as Cyborg
- Have ghost in dchat at time of late-join; ghost should see prompt that `Compact AI Circuit created in ___!`
- If ghost clicks prompt, they'll be sent to the Debug room in a duplicate brain. The cyborg player is unaffected.

![dreamseeker_tAnfBLvwVU](https://user-images.githubusercontent.com/76465278/207219320-d2e200d7-6b22-4642-9842-391da3c1edbe.png)
![dreamseeker_xHkSmh05S4](https://user-images.githubusercontent.com/76465278/207219327-4235885d-8fa6-4e8f-83b7-4703485a48b8.png)
![dreamseeker_bRBXLaqnl3](https://user-images.githubusercontent.com/76465278/207219337-8f41aba3-4497-4f5a-a1ef-579e9da4b331.png)

**Comment by vinylspiders** [comment]
Unable to reproduce with the steps described--it seems fixed now.
