### ISSUE TITLE
Stray pixels on Astolfo hair sprite

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#18158]
## Reproduction:

1. Select a character slot, existing or empty
2. Equip the 'Astolfo' hairdo close to the bottom
3. Rotate and observe the strange collection of black pixels on your ass
4. https://i.imgur.com/45CY60c.png

**Comment by Gofawful5** [comment]
thats the astolfo bow

**Comment by Jolly-66** [comment]
It would've been preferred if you didn't use the Union Jack as your underwear.

**Comment by vinylspiders** [comment]
![image](https://user-images.githubusercontent.com/13398309/219757761-24d92ba4-da90-482e-ba2e-0a005fff0157.png)
No stray pixels on this sprite, the black pixels are the bow that comes with it as someone mentioned. @lessthnthree

**Comment by lessthnthree** [comment]
Not a bug

**Comment by Jolly-66** [comment]
If you're going to apply the "Not a Bug" label please fix the labels accordingly.
