### ISSUE TITLE
capacitators are fucked

### ISSUE THREAD

**Issue by markjsls** [Skyrat-SS13/Skyrat-TG#18174]
Reporting client version: 514.1588

## Round ID:
7226

## Reproduction:
Whenever I try to do the "Advanced Scanning Modules Calibration" and try it with the BEPIS 3point experiment, it says the BEPIS doesn't work with the experiment even though I used the right tier for the scan. This also happened with the booze dispensers, because I tried to upgrade them with T4s but it didn't work. The machine had T2s and it wasn't letting me replace them with the T4s. 

1. Get T4s in a BRPED 
2. Build a machine frame, wire, card with BEPIS
3. add the parts to it and construct
4. select advanced scanning modules calibration and it doesn't work when trying to scan bepis
5. cope

1. get T4s in BRPED
2. try to upgrade booze dispenser/soda dispenser 
3. it doesn't replace the T2 parts inside the machine
4. cope

**Comment by markjsls** [comment]
step 6-9 are unrelated to 1-4 (1-4 is bepis and 6-9 is booze dispenser)

**Comment by YakumoChen** [comment]
upstream issue (known already)

**Comment by ghost** [comment]
Is this still happening?

**Comment by Jolly-66** [comment]
If this is still an issue, please post an issue report upstream.

VERIFY the issue is still there by using /tg/ code.
