### ISSUE TITLE
Ancient machines require "s" as part

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#18187]
## Round ID:
7231

## Testmerges:
Master commit: [35726f300551d199b01e92e9b8821018d3771460](https://github.com/Skyrat-SS13/Skyrat-tg/commit/35726f300551d199b01e92e9b8821018d3771460)

## Reproduction:
Attempt to build any Ancient Machine (Interdyne for example)

**Comment by kcrash201** [comment]
Apparently "s" is beakers

**Comment by ghost** [comment]
TG upstream issue, will be fixed in #18204

**Comment by Tastyfish** [comment]
Should have been fixed by #18204
