### ISSUE TITLE
Modsuit helmet sprite funkiness

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#18182]
## Reproduction:

Certain parts of modsuit helmets seem to always appear over your head while the modsuit is active, even if the plating is retracted. I didn't test them all, but I first noticed it with the rave visor module. The medical helmet without the rave visor works fine, but the little gas mask tubes on the engineering helmet have the same issue where they show up while the suit is active and helmet [retracted.](![modsuit sprites](https://user-images.githubusercontent.com/71854016/208220608-9ef81d35-6074-49c7-a9e5-531ea026c06a.png))

**Comment by YakumoChen** [comment]
this has been a long-standing issue stemming from the fact MODsuits are not designed to be retracted when active. Almost all modules have a visible sprite which always show on the overlay even when the suit is retracted.

**Comment by ghost** [comment]
Not a "sprite" issue, this has to do with code not removing overlays. Is there a better label @Jolly-66?

**Comment by Jolly-66** [comment]
We don't have many issues labels
