### ISSUE TITLE
Interdyne Headset Broken?

### ISSUE THREAD

**Issue by LuciliusMothboy** [Skyrat-SS13/Skyrat-TG#18197]
Reporting client version: 514.1589

## Round ID:
7236

## Reproduction:

For some reason, when I attempt to use the Interdyne frequency on Interdyne headsets, I am completely unable to. This problem has persisted for my entire time playing the game, and persists across all rounds. No one else appears to experience this issue. My ckey is LuciliusMothboy. I have tried using the .w, .h, :w, :h prefixes multiple times, on multiple rounds. It always treats it as if my headset does not have the frequency. When the headset is given to others, they are able to use it normally, and are unable to reproduce the bug entirely. When I am given a different headset, the bug persists, including with both normal Interdyne and Command headsets. This issue does not occur with any other type of headset, only Interdyne. Restarting my client, updating my client, restarting my computer, resetting my router, etc, have not fixed the issue. I am unsure what causes the issue, or how others may reproduce it. It's a major roadblock in my gameplay. I don't know if fixing this is even possible, but I really do need it fixed. No amount of explanation in LOOC seems to make other players understand my issue, and it negatively impacts my interactions in game, and makes my time playing less enjoyable.

**Comment by YakumoChen** [comment]
Needs more information. Lists of quirks and augs, species, languages used, if you've tried this with other character slots, if you're doing anything weird with the headset like trying to use radio with the device in your hand

**Comment by Zergspower** [comment]
> Reporting client version: 514.1589
> 
> ## Round ID:
> 7236
> 
> ## Reproduction:
> For some reason, when I attempt to use the Interdyne frequency on Interdyne headsets, I am completely unable to. This problem has persisted for my entire time playing the game, and persists across all rounds. No one else appears to experience this issue. My ckey is LuciliusMothboy. I have tried using the .w, .h, :w, :h prefixes multiple times, on multiple rounds. It always treats it as if my headset does not have the frequency. When the headset is given to others, they are able to use it normally, and are unable to reproduce the bug entirely. When I am given a different headset, the bug persists, including with both normal Interdyne and Command headsets. This issue does not occur with any other type of headset, only Interdyne. Restarting my client, updating my client, restarting my computer, resetting my router, etc, have not fixed the issue. I am unsure what causes the issue, or how others may reproduce it. It's a major roadblock in my gameplay. I don't know if fixing this is even possible, but I really do need it fixed. No amount of explanation in LOOC seems to make other players understand my issue, and it negatively impacts my interactions in game, and makes my time playing less enjoyable.

since we cant replicate this, unless it's still happening or more info is required i'll have to close it
