### ISSUE TITLE
Monkey cube boxes are invisible

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#18195]
As it's current, game is looking for monkeycubebox in modular_skyrat\modules\aesthetics\storage\storage.dmi

Since it's missing, box is invisible. This may be impacting other boxes in addition to monkey cube.

## Reproduction:
Spawn monkey cube box

**Comment by Sonic121x** [comment]
seems like a recent change in "modular_skyrat/modules/aesthetics/storage/storage.dm" cause it

**Comment by lessthnthree** [comment]
Yes, and as per https://github.com/Skyrat-SS13/Skyrat-tg/pull/18186 someone will need to fix the structure to match upstream.
