### ISSUE TITLE
the entire cargo system is broken (actual pretty critical)

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-TG#18256]
## Reproduction:

go to cargo
make a request for anything at any price
get it shipped for free  
unlimited guns, sm shards, and gas miners 
![image](https://user-images.githubusercontent.com/69182855/208871217-7653dd2d-2e01-46e0-a6f1-24520a422414.png)
![image](https://user-images.githubusercontent.com/69182855/208871526-d0027308-9499-45ce-8303-341e21565aad.png)
![image](https://user-images.githubusercontent.com/69182855/208871275-200c88d8-de23-4b31-a0f5-c6144dc62730.png)
last was in my hands

**Comment by StrangeWeirdKitten** [comment]
#17852 touched supply.dm code last month and it's skipping the entire block of code that actually charges an account on purchase. 

![image](https://user-images.githubusercontent.com/95130227/209585730-7d80e367-6b50-49a8-a68b-858b63806b8b.png)

charge_on_purchase is being set to null

**Comment by StrangeWeirdKitten** [comment]
Fixed by #18353

**Comment by Zonespace27** [comment]
#18353
