### ISSUE TITLE
Voidraptor AI Sat Power Issues

### ISSUE THREAD

**Issue by nevimer** [Skyrat-SS13/Skyrat-TG#18251]
## Testmerges:

None

## Reproduction:

The AI can be killed on voidraptor by smashing a single glass window. 
![dreamseeker_4PhuHfsJr2](https://user-images.githubusercontent.com/77420409/208797413-ea154ab2-d811-4463-80e3-d557a21432f3.png)
This glass window here will put you into a tube to the AI sat, where you will see an SMES.
![StrongDMM_kNnqUdX2i6](https://user-images.githubusercontent.com/77420409/208798319-37c86999-75a8-49af-b550-74e72aacc1f1.png)

![StrongDMM_r4gn2slxxL](https://user-images.githubusercontent.com/77420409/208797960-0902a383-4c50-42f6-b56a-ae66ac99835a.png)
This SMES here, powers everything by default on the AI sat, including the AI itself. One only had to discretely turn off the output and wait two minutes for the AI to die, due to a wiring issue further south. The placement itself is bad, but, it's further compounded by this issue.
![StrongDMM_8EycKUxOIX](https://user-images.githubusercontent.com/77420409/208798114-c10e5887-7386-496f-b14d-9eaec019f4f7.png)

The AI's own SMES is connected it ITSELF, acting as a power sink if you have no idea how wirenets or powernets work (and believe me, nobody fucking knows unless you are coder brain, it is very obtuse.)

**Comment by Zergspower** [comment]
Nice.
