### ISSUE TITLE
Mail can sometimes stop running mid-shift.

### ISSUE THREAD

**Issue by BriareosBlue** [Skyrat-SS13/Skyrat-TG#18279]
## Round ID: 
7265

## Reproduction:
On this round, there were 2-3 mail crates that had arrived on the cargo shuttle. After that, there stopped being mail crates. I have also noticed that, every shift after that, mail does not seem to be arriving on cargo shuttles anymore.

**Comment by BriareosBlue** [comment]
Had this incident repeat on another round, as well. ID for that is 7313.

**Comment by vinylspiders** [comment]
Is this still happening?
