### ISSUE TITLE
Security and possibly other armor no longer stows forged weapons

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#18286]
Reporting client version: 514.1589

## Round ID:
7273

## Reproduction:

Forged reagent weapons used to attach to security and other armor vests as of last night, but do not as of sometime today. As there's no corresponding pr and the only change seems to be Christmas maint loot, it seems like unintended behavior. Forged cuirasses hold reagent weapons as expected.

**Comment by YakumoChen** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/blob/e74462deb12a5bcf735e53fc8a45b43631aee3c2/code/__DEFINES/inventory.dm#L212-#L228

Demonstrably untrue.

**Comment by kittysmooch** [comment]
> https://github.com/Skyrat-SS13/Skyrat-tg/blob/e74462deb12a5bcf735e53fc8a45b43631aee3c2/code/__DEFINES/inventory.dm#L212-#L228
> 
> Demonstrably untrue.

*edit* vests were holding reagent weapons literally the night before last, do not know what to tell you lmfao

**Comment by kittysmooch** [comment]
Closing as it seems that security vests holding reagent weapons at all was the unintended behavior lmao
