### ISSUE TITLE
Universal Recorder Not Recording Anything

### ISSUE THREAD

**Issue by TypeVar** [Skyrat-SS13/Skyrat-TG#18295]
## Round ID:

7279

## Testmerges:

No active test merges during round
## Reproduction:

The universal recorder does not seem to be recording any lines, and instead counts up from 1 to the duration of the recording. 

**Steps to reproduce bug:**

1. Insert a tape into a universal tape recorder
2. Prepare to say something
3. Begin recording on the recorder
4. Say something
5. End recording on the recorder
6. Play recording on the recorder

**Expected Result:**
This should record anything that was said. This is what the result had been up until recently.

**Actual Result:**
The universal tape recorder does not record anything, and instead just counts up from 1 to the duration of the recording.

I believe this is a recent issue, so I suspect something that was merged affecting the universal tape recorder is causing this. I assume this is a problem, as this effect does not seem intentional.

![image](https://user-images.githubusercontent.com/100787466/209422889-e87f07cc-a4ea-405e-8a83-25894157ab37.png)

**Comment by vinylspiders** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/18915
