### ISSUE TITLE
Ashwalkers cannot get trophies from non-megafauna kills

### ISSUE THREAD

**Issue by Zonespace27** [Skyrat-SS13/Skyrat-TG#18313]
## Reproduction:

Found via code, but

- Kill lots of fauna
- See not a single trophy

**Comment by Zonespace27** [comment]
This broke when crusher loot was elementized, since the code didn't carry over

**Comment by YakumoChen** [comment]
Upstream issue?

**Comment by Zonespace27** [comment]
It's an us issue

**Comment by YakumoChen** [comment]
Ah, I didn't know we changed something about that

**Comment by vinylspiders** [comment]
Ahh I understand-fix is up.
