### ISSUE TITLE
Round removed due to being a synth

### ISSUE THREAD

**Issue by kcrash201** [Skyrat-SS13/Skyrat-TG#18330]
## Testmerges:
[00dd09a11a2f2909a82942f17a4516a6329a2734](https://github.com/Skyrat-SS13/Skyrat-tg/commit/00dd09a11a2f2909a82942f17a4516a6329a2734)

## Reproduction:
Get gibbed as synth, get torso dusted, get brain destroyed in process

Synths can be round removed where as an organic would not in the case of their body suddenly combusting.
I see this a bit unfair as synths are punished for what race they are.

**Comment by YakumoChen** [comment]
Gibbed or dusted? There's an important distinction here.
Needs more information on the how and why.

**Comment by kcrash201** [comment]
The body was dismembered, limbs and head detached, leaving the brain in the torso where the toso dusted after a few minutes and brain with it.

I used the term gibbed wrong

**Comment by YakumoChen** [comment]
Sounds like not a bug, I believe all body parts can ash from fire.
Especially in lava.

Being round removed from dusting explicitly is intended behaviour.

**Comment by nevimer** [comment]
Not intended behaviour. Fire causes other organs to throw randomly when the parent one is deleted.

**Comment by kcrash201** [comment]
I thought so, the Synth/Ipc brain gets destroyed with the torso when the torso dusts in this situation

**Comment by RimiNosha** [comment]
Yea, when the head ashes, it drops the brain. Brains are meant to be undeletable for the most part.

I have a good idea on what needs to be done to fix that issue though.
