### ISSUE TITLE
oppsoing_force_equipment 'nukiemod' ID authorization mismatch

### ISSUE THREAD

**Issue by desertmote** [Skyrat-SS13/Skyrat-TG#18346]
Reporting client version: 514.1589

## Round ID:
7291

## Testmerges:
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)

## Reproduction:

I  gained `/obj/item/mod/control/pre_equipped/nuclear` from the opfor selection `/datum/opposing_force_equipment/clothing/nukiemod` as roundstart traitor and wasn't authorized to use the modsuit

**Comment by YakumoChen** [comment]
Traitors do not get syndicate access, no.

Not bug

**Comment by nevimer** [comment]
This is a bug, things are intended to work. It is like buying a product and finding out it doesn't include vital components.
