### ISSUE TITLE
Broken chat after leaving someone's hands as simple mob

### ISSUE THREAD

**Issue by Oxotnak** [Skyrat-SS13/Skyrat-TG#18363]
## Round ID:
Not at Skyrat, last update 26 December

## Reproduction:
Be a simple mob, let someone pick up you, move from his hands, have a broken local, LOOC and radio chats, maybe something else too. Chat tab settings were checked, problem not in them
![Screenshot_393.png](https://user-images.githubusercontent.com/107066254/209656739-45a308ce-a5c4-48be-a03c-1a140c4dafbc.png)
![image-2.png](https://user-images.githubusercontent.com/107066254/209656771-3b06dcff-3d2b-4af6-85a9-4f7c980c9078.png)

**Comment by Erol509** [comment]
It is with us few months already, this is probably a upstream issue.

**Comment by vinylspiders** [comment]
Was fixed by https://github.com/Skyrat-SS13/Skyrat-tg/commit/ec2aad19d2f739857c3d101376ddf506ab9d47e9

**Comment by vinylspiders** [comment]
@lessthnthree

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Skyrat-SS13/Skyrat-tg/commit/ec2aad19d2f739857c3d101376ddf506ab9d47e9
