### ISSUE TITLE
QOL suggestions

### ISSUE THREAD

**Issue by Eclipse-Presence** [Skyrat-SS13/Skyrat-tg#1836]
Issue reported from  Round ID: [42](https://scrubby.melonmesa.com/round/42) (Skyrat SS13 - /TG/ Anthro-Friendly Roleplay Server [Apply on Discord, Weekly Events])

Reporting client version: 513.1532

I'm not a coder, just a player that noticed a few things, so take these with a grain of salt.

-Movement seems too slow, and is a drastic shock compared to what it used to be. I do like the sanity and mood affecting speed, but the base speed still seems almost unbearable.
-The switch from chems having little to no side-effects to suddenly being confronted by the entire list of horrendous effects and organ damage is wildly complex, and I feel as though items like cigarettes and alcohol will become more obsolete in the long run as people stop using them as roleplay items, because of their horrendous mechanical effects. I'll also miss the Fermichems, if only because it was fun to wander around with a glowing red voice, as well as daring people to chug kegs of aphrodisiac.
-Being able to remove underwear is probably something you've already heard complained about, but re-adding the underclothes system would be awesome.
-Certain cosmetic items like the messenger bags were fun options, and I think it'd be neat if they were added back. Also, the old PDAs looked fantastic, and I hope they get swapped back to.
-Coloured runetext and extra character languages were awesome, please add those again if possible.

**Comment by Eclipse-Presence** [comment]
Well, I thought this was a suggestions page, not an issues page, and now I don't know how to delete it. My bad.

**Comment by Gandalf2k15** [comment]
Speedwise, make sure you're not wearing a dufflebag, they slowdown A LOT

**Comment by Azarak** [comment]
@Eclipse-Presence Issues is fine for suggestions, dont worry

**Comment by Azarak** [comment]
`-Being able to remove underwear is probably something you've already heard complained about, but re-adding the underclothes system would be awesome.` You can remove them with a verb in the IC tab

**Comment by Funce** [comment]
This suggestion list is being closed. If any of these suggestions are still relevant, feel free to open new issues for them.
