### ISSUE TITLE
Welding mask + Inactive Retinal projector Meson HUD makes you blind temporarily

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#18379]
## Testmerges:
[#17455: 'Fairly large assault operatives changes' by Paxilmaniac at commit d14745ce56](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)
[#18292: 'Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood' by GoldenAlpharex at commit c9cfe2a9e0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)

## Reproduction: 
Put on a welding helmet that is angled down, next get either retinal projector mesons or aviator mesons, turn them off and put them on

**Comment by dawsonkeyes** [comment]
Seems to be intended behavior besides the retinal projector - glasses darken your vision against flashes, and the bug is that retinal projectors share this quality. Being blinded by wearing sunglasses with a welding mask is intended otherwise

**Comment by Zonespace27** [comment]
Retinal projectors are buggy and broken as shit
