### ISSUE TITLE
Security has an crematorium on Voidraptor

### ISSUE THREAD

**Issue by nevimer** [Skyrat-SS13/Skyrat-TG#18392]
Round ID: 7312
BYOND Version: 514.1589
Server revision compiled on: 2022-12-27T21:38:40+00:00
Master commit: [70e28b33c26f98f75164d4fbb279049a7a6fa417](https://github.com/Skyrat-SS13/Skyrat-tg/commit/70e28b33c26f98f75164d4fbb279049a7a6fa417)
The following pull requests are currently test merged:
[#17455: 'Fairly large assault operatives changes' by Paxilmaniac at commit d14745ce56](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)
[#18292: 'Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood' by GoldenAlpharex at commit c9cfe2a9e0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)

Local commit: 8e78d3a009d0ed93223e1299fd0bf2f35c86fac8
TGS version: 4.19.1
DMAPI version: 5.3.0

## Reproduction:

On Voidraptor, in the security department there lies an crematorium and a morgue. Typically, access to an crematorium is a two party system - the AI and security - the Chaplain and security - The Captain and security - an Engineer and security, and other combinations to round remove / destroy objects. 

Security should not have such an easy method of destroying anything in the game out of convenience. For matters that *require* such things, the balances in place are completely bypassed in this case. 

No other currently running map gives security such a thing, and the only historical map that ran like that was pubbystation (very small old map)

**Comment by Jolly-66** [comment]
Me and Paxil have both rectified when this came up in the past that this is a non-issue.
