### ISSUE TITLE
Slimes can't shapeshift.

### ISSUE THREAD

**Issue by SpaceVampire** [Skyrat-SS13/Skyrat-tg#1851]
Slimes are no longer able to use the shapeshifting menu, additionally taking mutation toxin to turn into another type of slime will reset all of your colors and make you look ugly with no way to fix it. If there way a way to make both of those handled like it was pre-rebase, I think it would be an improvement. It was a really fun RP tool.

**Comment by Azarak** [comment]
I'll be adding the shapeshift ability soon, and I'll look into the mutation thing
