### ISSUE TITLE
Honorbound chaplain sect "declare evil" broken

### ISSUE THREAD

**Issue by kylecorn1996** [Skyrat-SS13/Skyrat-TG#18511]
## Reproduction:

Pick honorbound sect as a chaplain. 

the declare evil spell is what allows you to attack someone in a protected "class", such as roundstart medical staff or secoff. without declare evil, you will be UNABLE to lay a finger on these protected classes, as if you were pacified or paxxed. this even counts for HERETICS who start as these honorbound-protected roles. the spell to declare a person evil is entirely broken with three identified issues. 

Issue 1: the icon and name for the spell is incorrect/broken. the icon is a magic scroll, when it used to be a claymore. the name of the spell is "Spell" and the subtext is "A wizard spell". I remember the spell used to be called "Declare Evil" but I don't remember what the subtext was.

Issue 2: attempting to cast the spell  is impossible if your null rod is in your hands or slots. Declare evil is not supposed to be blocked by antimagic. it never did before.

Issue 3: the spell fails stating that you need a wizard robe to cast it. I feel like I don't need to explain this one.

**Comment by ghost** [comment]
Would have been fixed by missed mirror of https://github.com/tgstation/tgstation/pull/72484; manually mirrored now
