### ISSUE TITLE
Chat history too short.

### ISSUE THREAD

**Issue by SpaceVampire** [Skyrat-SS13/Skyrat-tg#1852]
The current chat system is unable to hold a full rounds worth of stuff. Maybe add an option allowing people to choose how much stuff is saved on their end, along with an option to delete the current logs, like the old pre-rebase server? It would also be nice if you could export logs that are just the logs of the filters you were using in question, instead of the whole thing, but that is less important than the above two.

**Comment by tf-4** [comment]
This breaks things quite badly when you turn it up
