### ISSUE TITLE
Drake Horns causes sprite to turn into an Error Sign

### ISSUE THREAD

**Issue by avimour** [Skyrat-SS13/Skyrat-TG#18608]
## Testmerges:

https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292

## Reproduction:

1. Have emissive Drake horns (probably regular drake horns too)
2. Try to hide your underwear
3. Turn into a red error sign
4. Desperately try to fix your texture, only for it to never be fixed again. (Get made fun of by everyone in LOOC.)

![image](https://user-images.githubusercontent.com/92401911/211237981-4f92c5d3-ab81-4bc9-a542-a433a2f4da43.png)
![image](https://user-images.githubusercontent.com/92401911/211238092-853aea1c-b5b0-45e3-aae1-be5008d6bf20.png)

**Comment by Tailiik** [comment]
I have the same problem, I also use drake horns. I thought it was a cursed character slot and started rebuilding in a new slot but now I think I might wait if it's somebody fucking it up with a pr.

EDIT: It is indeed the drake horns causing it for me, not a cursed character slot

**Comment by Zergspower** [comment]
Are either of you using heterochroma eyes? I'm not able to replicate this locally or in the current server (or it's fixed)
![image](https://user-images.githubusercontent.com/22140677/212492256-c705c1c2-b426-404d-870b-a53b1d55e432.png)

**Comment by avimour** [comment]
I have the nerve staple perk, but besides that nope. I checked on the live server and it still causes an error.

**Comment by avimour** [comment]
Okay!! I tried it again and for me it seems to be purely emissive related, ie the amount of emissives I was using. I only had ears, horns, spines, eye, and penis emissives on, and turning penis & eye emissives off seems to have fixed it! Not sure if the other guy was using emissives as well.

**Comment by Tailiik** [comment]
> Are either of you using heterochroma eyes? I'm not able to replicate this locally or in the current server (or it's fixed) ![image](https://user-images.githubusercontent.com/22140677/212492256-c705c1c2-b426-404d-870b-a53b1d55e432.png)

![error](https://user-images.githubusercontent.com/71854016/213992515-68c47298-ed1a-435b-920d-ef871adbf268.png)
I put the drake horns back on and this still happens, I have no emissives enabled. I can show you all my settings if that helps, or if you feel like digging through all the character files I have two slots named Tailiik Gemwing, the second one is the one I use and the one that experiences this bug. 

No emissives, no heterochromatia, only happens with drake horns on and after I take off and put back on a piece of clothing. Your local test may not have had the issue show up if you didn't do the step of adding/removing clothes. When I first spawn in everything looks normal.

**Comment by vinylspiders** [comment]
@Jolly-66 This one can probably be closed. 

There's been a lot of work done on overlays lately and it's probably been fixed by one of them.

I have been testing with a stupid amount of emissives (including drake horns) and cannot seem to reproduce this no matter what.

<details>
<summary>testing footage, warning - nsfw</summary>
 

![dreamseeker_JVQNhykDuC](https://user-images.githubusercontent.com/13398309/229030858-6a135be8-2d35-4da3-b1b3-3df961db2c90.gif)

</details>
