### ISSUE TITLE
Runtimes relating to LINDA_TURF and DOG AI_Controller

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#18619]
Reporting client version: 514.1589

## Round ID:
7401

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [At Long Last, Towels](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Fixes screenshots properly this time + bonus fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18596)

## Reproduction:
just let the game run, specifically dog subsets of simplemobs and lindaturfs in hyperspace are contributing to millions of runtimes currently.

![image](https://user-images.githubusercontent.com/22140677/211438708-153bb67e-e8ad-435b-b7a3-80cee68e5a4f.png)

![image](https://user-images.githubusercontent.com/22140677/211439052-48811c61-7eac-4b8f-bd29-a196b6d18c27.png)

![image](https://user-images.githubusercontent.com/22140677/211439057-d13961e3-6b55-4123-a4ff-5091fe0b4dff.png)

**Comment by theselfish** [comment]
I assume this is related to https://github.com/Skyrat-SS13/Skyrat-tg/pull/17930

I am most likely incorrect, though. It's merely my best guess.

**Comment by Zergspower** [comment]
yeah that's a thought since we had 2 dog PR's but it looks like that part was fixed - the LINDA Spam appears to be erratic however and affects space maps
