### ISSUE TITLE
DNA infusions work on synthetics.

### ISSUE THREAD

**Issue by kylecorn1996** [Skyrat-SS13/Skyrat-TG#18615]
## Reproduction:

place synthetic character into DNA infuser with valid DNA source such as carp, goliath, or mouse corpse. perform exploratory surgery after the infusions and you will see that their organs do, in fact, get replaced with mutant organs like an organic player. this seems to cause no harmful effects or instant death, even if it replaces their brain and/or heart.

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/pull/72688
