### ISSUE TITLE
They took my beer battered sausage.

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-tg#18689]
Reporting client version: 514.1589

## Round ID:
7427

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [At Long Last, Towels](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

Making beer battered sauages will merge them into one pile, deleting the other sausages in a pile.

**Comment by ghost** [comment]
Does this happen Upstream as well?

**Comment by theselfish** [comment]
> Does this happen Upstream as well?

Considering Battered Sausages are a Skyrat invention, I doubt it.

**Comment by vinylspiders** [comment]
The issue is that one of the ingredients for beer-battered sausages are plain sausages. 

And beer-battered sausages are a subtype of plain sausages so they count as a valid ingredient. 

So you can in essence keep crafting them from themselves, wasting your batter and recrafting the same ones.
