### ISSUE TITLE
Public Mining Shuttle MIA

### ISSUE THREAD

**Issue by Knouli** [Skyrat-SS13/Skyrat-TG#18731]
Reporting client version: 514.1589

## Round ID:
7436

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [At Long Last, Towels](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

## Reproduction: 
As per the title. Attempt to summon the missing public mining shuttle via station-side console - only to find it reporting the shuttle missing at an unavailable destination.
![image](https://user-images.githubusercontent.com/25857923/212502262-189e13b8-0104-476d-b14a-0542e24d5467.png)

**Comment by Zergspower** [comment]
this was mostly like not a bug but rather a disabled by admin deal, we're currently having a hyperspace issue that's spamming millions and millions of runtimes

**Comment by Jolly-66** [comment]
Please specify the map if you can remember.
