### ISSUE TITLE
Frogs have no cooldown on HNNNNGGG, and are being abused to spam horrible deafening noise.

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat-tg#1873]
Reporting client version: 513.1536

## Round ID:
[53](https://scrubby.melonmesa.com/round/53)

## Testmerges:
- [[NON-MODULAR] The 30TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1744)
- [[SEMI-MODULAR] Ambitions v2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1743)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[SEMI-MODULAR] [TESTMERGE ONLY] Configurable spawners for event use for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1786)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[Modular] Ports over our old chemicals.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1864)

## Reproduction:
Spawn /mob/living/simple_animal/hostile/retaliate/frog, get two or three crew to walk back and forth across the tile repeatedly.
**HHHNNGNGGG**
_HRNNNGGGG_
_**HHHNNGNGGG**_

Sound effect should have volume normalized and trigger needs a short cooldown.

**Comment by Gandalf2k15** [comment]
Issue with upstream

**Comment by atakiya** [comment]
Fixed on our side by #2193 by disabling the sounds entirely. Closing therefore.
