### ISSUE TITLE
Cargo NIF order stuck on console

### ISSUE THREAD

**Issue by Yuzunari** [Skyrat-SS13/Skyrat-TG#18745]
Reporting client version: 514.1588

## Round ID:

7440

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [At Long Last, Towels](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

## Reproduction:

When ordered Standar NIF's over the cargo console by a crewmember, aparently when ordered more than 3, it will get one of the three orders completely stuck in the cargo console, no matter how many travels we make it do, it will stuck there and charge the crewmember and when cancel the order it wont be refunded, but it never arrives on the shuttle, late on the shift, someone ordered a Cerulean type NIF and it was delivered completely fine, and after all the shift, the same crew ordered a Standar Type NIF and it arrived properly

**Comment by Jolly-66** [comment]
@softcerv
