### ISSUE TITLE
Humonkeys and the SAD

### ISSUE THREAD

**Issue by LtBytes** [Skyrat-SS13/Skyrat-TG#18757]
When a player's brain/head is placed into a hu-monkey and then put into the SAD they get a "primal look in their eyes" and start attacking players wildly, apparently this seem to be a quite a bug since it only works on the hu-monkey bodies.

**Comment by LtBytes** [comment]
Oh yeah Round ID is 7445

**Comment by GoldenAlpharex** [comment]
Fixed!
