### ISSUE TITLE
[Minimum Information] Z-Level Transition Failing

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#1876]
Reporting client version: 513.1536

## Round ID:
[57](https://scrubby.melonmesa.com/round/57)

## Testmerges:
- [[NON-MODULAR] The 30TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1744)
- [[SEMI-MODULAR] Ambitions v2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1743)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[SEMI-MODULAR] [TESTMERGE ONLY] Configurable spawners for event use for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1786)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[Modular] Ports over our old chemicals.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1864)

## Reproduction:
I've always known z-level transitions were rather busted, but this takes the cake. While travelling z-level 6, we moved towards the western edge and manage to hit coordinate 1 - and be stuck there. Something that isn't normally possible. I have no idea what caused this, but my only guess is because me and someone else were holding each other by grabbing? I have no idea, honestly. We broke out after a bit of struggle and a few wasted credits.

**Comment by Gandalf2k15** [comment]
Unable to recreate this.
