### ISSUE TITLE
Chaplain weapon not visible.

### ISSUE THREAD

**Issue by Mufi87** [Skyrat-SS13/Skyrat-TG#18787]
Reporting client version: 514.1589
Round ID: 7456
Issue: Chaplain weapon will not be visible if put on the storage suit slot if you have a boatcloak equipped. (As a teshari, in case it works with other races, I haven't tested.)
Reproduction:
So when you put the weapon onto the storage slot while You have a boat cloak on it is simply not going to be visible, if You unequip the boatcloak and put the weapon onto the slot then it is visible even if you equip the boatcloak after as long as you don't get the weapon in hand and put it back in which case the bug occurs again.

**Comment by vinylspiders** [comment]
![image](https://user-images.githubusercontent.com/13398309/213885824-ddcd3fd2-f0b3-4ed9-a221-170cb2df278a.png)

![image](https://user-images.githubusercontent.com/13398309/213885833-285822f0-b934-4608-83c8-4adf120363dd.png)

Seems like the cloak is just covering the part of the suit it is attached to. Looks right to me.

**Comment by Mufi87** [comment]
> Seems like the cloak is just covering the part of the suit it is attached to. Looks right to me.

it works if you put the cloak on while you already have it on your suit as said, but If You take the weapon out and then back, You will notice not only the needed parts are "covered".
![test1](https://user-images.githubusercontent.com/122923057/213915196-58e5a374-dc29-4108-9b99-7f800cef77a1.png)
![test2](https://user-images.githubusercontent.com/122923057/213915226-46f10274-186c-4e77-bbda-d5ce18c84fc7.png)
![test3](https://user-images.githubusercontent.com/122923057/213915232-27ad8609-47b6-4a09-9303-1a64febd81b3.png)

**Comment by vinylspiders** [comment]
Ah yeah I see what ya mean. Working on a fix as we speak.
