### ISSUE TITLE
DWARF RACISM. DWARVES HAVE NEGATIVE THROW STRENGTH

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#18789]
Reporting client version: 514.1589

## Round ID:
7456

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

## Reproduction:

Through reproduction I was able to reproduce this by taking a BRAND new character slot that had to have the big red and green text processed, and it still was present

Even with varediting from staff I had no hopes at throwing past the tile I was standing on

https://files.ratchtnet.com/v/f8e925

**Comment by MaSvedish** [comment]
AFter some help, its certain items that I cant throw. 

Books, donator items, batons, etc I cant throw, the above file happens

Dice, containers, bottles, hats, etc I can throw fine, and throw as expected

**Comment by lessthnthree** [comment]
Upstream.
https://github.com/tgstation/tgstation/issues/73448
