### ISSUE TITLE
Limb Grower not functioning at all

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#18794]
Reporting client version: 514.1589

## Round ID:
7457
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18734 fits the timeframe of it being broken

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

**Comment by lessthnthree** [comment]
https://github.com/tgstation/tgstation/pull/72853
