### ISSUE TITLE
Markus cannot be revived with Lazurus injector

### ISSUE THREAD

**Issue by Reco201** [Skyrat-SS13/Skyrat-TG#18792]
Reporting client version: 514.1589

## Round ID:
7457

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

## Reproduction:
Spawn markus
Kill Markus
Attempt to use Lazurus to revive
![image](https://user-images.githubusercontent.com/71794877/213029911-9f754cf1-175a-4285-aa9a-e59368522305.png)

**Comment by Tastyfish** [comment]
Redundant to the broader #18949
