### ISSUE TITLE
Ranged NPC mobs aren't firing anything and just wander around like an angry toddler having a tantrum

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#18795]
Reporting client version: 514.1589

## Round ID:
7457
Basically any mob that fires a gun is affected

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [Teshari sprite pack (2) security boogaloo](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

**Comment by Jolly-66** [comment]
Potentially /tg/ related issue. I recall seeing a fix PR upstream, not sure if it was merged.

Report back if this issue keeps persisting.
