### ISSUE TITLE
Skating fucks with prosthetics

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-tg#1880]
![disabled](https://user-images.githubusercontent.com/75141807/100481600-dba35500-30f4-11eb-89b3-726aabb40ae9.png)
Reporting client version: 513.1524

## Round ID:
[58](https://scrubby.melonmesa.com/round/58)

## Testmerges:
- [[NON-MODULAR] The 30TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1744)
- [[SEMI-MODULAR] Ambitions v2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1743)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[SEMI-MODULAR] [TESTMERGE ONLY] Configurable spawners for event use for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1786)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[Modular] Ports over our old chemicals.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1864)

## Reproduction:

 Sometimes when i go on the holodeck skatepark and grind enough times it disables my prosthetic arm, causing my character to scream and giving the message 'YOU LOSE CONTROL OF YOUR PROSTHETIC RIGHT ARM' it doesn't always happen but it doesn't cause any damage either, just disables it.

**Comment by Owai-Seek** [comment]
Without looking at the code of it my first thought is that maybe the sparks (from grinding) somehow disable the limb?

**Comment by Zergspower** [comment]
Unable to recreate - potentially fixed given the age of the report
