### ISSUE TITLE
company req's menu causes NTOS-bluescreen

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#18831]
## Testmerges:
[#18349: '[MOSTLY MODULAR] NIFs' by softcerv at commit 224721134c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 43fff10d10](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#18292: 'Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood' by GoldenAlpharex at commit f1516bc58d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
[#18395: 'Teshari sprite pack (2) security boogaloo' by Ebin-Halcyon at commit 7eecc832b3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18395)

## Reproduction:
 try to open it
![image](https://user-images.githubusercontent.com/62520989/213599067-f48dd772-efb5-4f3d-a43a-0e40da0b610e.png)

**Comment by GoldenAlpharex** [comment]
Caused by https://github.com/Skyrat-SS13/Skyrat-tg/pull/18594, it seems.
