### ISSUE TITLE
Ion Rifle has no sprite on chest slot

### ISSUE THREAD

**Issue by H0gberg** [Skyrat-SS13/Skyrat-tg#1889]
Reporting client version: 513.1536

## Round ID:[63](https://scrubby.melonmesa.com/round/63)
63

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[SEMI-MODULAR] [TESTMERGE ONLY] Configurable spawners for event use for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1786)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[NON-MODULAR] The 30TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1744)
- [[SEMI-MODULAR] Ambitions v2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1743)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)

## Reproduction:

I equipped an ion rifle on my chest and I had no sprites

**Comment by SpookyTheFox** [comment]
Energy carbine seems to be missing it as well when in the belt slot.

**Comment by tf-4** [comment]
Ion rifle is fine. Ion CARBINE has a broken on mob suit storage icon. Energy carbine has no on mob belt slot icon.

**Comment by Zergspower** [comment]
Confirmed bug still exists - sprite links correctly to strap across the chest when put on the belt slot but not when wearing in the armor vest slot for the Energy Combine
