### ISSUE TITLE
AI is unable to Jump to Network

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#18913]
Reporting client version: 514.1589

## Round ID:
7499

## Testmerges:
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [[modular] alot of Company Requisitions price changes + return of the rave-visor and anomaly-modules](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18460)

**Comment by vinylspiders** [comment]
This has been allegedly fixed, closing
