### ISSUE TITLE
Ashwalker character/village issues

### ISSUE THREAD

**Issue by ZakuroTheGreat** [Skyrat-SS13/Skyrat-TG#18932]
Reporting client version: 514.1589

## Round ID:
5169

## Testmerges:
- [At Long Last, Towels](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18391)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [[MODULAR] Fix IPCs and Synths with Non-Default Brains Not Being Properly Inserted into Ghost Roles and Fixes Item Duplication and Also Fixes Ghost Cafe Boxes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18001)
- [[MOSTLY MODULAR] NIFs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18349)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Adminhelps into mentorhelps converting.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17788)

## Reproduction:

Issue related to ashwalkers and the mapping of ashwalker village on lavaland. 
Legion cores cannot be revitalized from a decayed state anymore through the nest tendril, although it always was possible. 
Move the village gate one tile down, you can walk through its sides due to how hitbox is made for it.
(Issues happened on TheFluffyFrontier, which uses up-to-date skyratTG code)

**Comment by SpaceVampire** [comment]
The legion core thing is intentional.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18035

**Comment by vinylspiders** [comment]
@Jolly-66 see above comment, not a bug.
