### ISSUE TITLE
Cell chargers no longer available from science circuit printer

### ISSUE THREAD

**Issue by Helios7-1** [Skyrat-SS13/Skyrat-TG#18937]
## Reproduction: Research advanced engineering. Cell chargers will be available from the generic circuit imprinter but not the science subtype circuit imprinter
https://cdn.discordapp.com/attachments/909136661978443777/1067496717328588870/image.png

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/214882371-83550646-864e-4007-bf5c-73428056ca86.png)

multi-cell was granted its category to match the cell charger (which upstream is just engineering too), let me look a little closer to see if my upstream PR undid a potential SR Edit

**Comment by Zergspower** [comment]
intended
