### ISSUE TITLE
Dog's can no longer be Lazarus Injected

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#18949]
Reporting client version: 514.1589

## Round ID:
7513

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Hemophagus, The Hemophage Revamp, Part Three: A Taste For Blood](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18292)
- [[NON-MODULAR] Fix vox with normal legs shoes, fix edge case birb/snout clothing rendering](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18914)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/pull/72440

**Comment by Jolly-66** [comment]
Linked TG issue, closing this.
