### ISSUE TITLE
Carpet foam and smoke does not work

### ISSUE THREAD

**Issue by HoodMilk** [Skyrat-SS13/Skyrat-TG#18969]
Reporting client version: 514.1588

## Round ID:
7523

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[NON-MODULAR] Fix vox with normal legs shoes, fix edge case birb/snout clothing rendering](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18914)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)

## Reproduction:

Create a smoke of the carpet chemical and you will see that it does not convert floor tiles to carpet like it is supposed to, same issue with foam.

**Comment by vinylspiders** [comment]
Edit--nevermind, this could still be an issue
