### ISSUE TITLE
No public mining shuttle on delta

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#19020]
Reporting client version: 514.1589

## Round ID:
7539

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[NON-MODULAR] Fix vox with normal legs shoes, fix edge case birb/snout clothing rendering](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18914)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes the game-alert message for the start of a new round also display the round ID](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18975)

## Reproduction:
Map issue: Delta doesn't have a public mining shuttle. It does not exist. Gone. Nadda. 

I have no idea if this is the same issue upstream as I don't play upstream

**Comment by Jolly-66** [comment]
Probably related to the template override used. Shouldn't be too hard to fix.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21303 will fix this.
