### ISSUE TITLE
PAI health hud software resets when changing z levels

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#19147]
Reporting client version: 514.1589

## Round ID:
7578

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[NON-MODULAR] Fix vox with normal legs shoes, fix edge case birb/snout clothing rendering](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18914)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)

## Reproduction:
I observed PAIs health huds reset everytime they changed z levels. This was spotted on icebox, however I dont know if it changes for other stations.!

**Comment by Jolly-66** [comment]
Most likely similar to the HUD issue.

There's a mirror open that is supposed to fixed this, please keep an eye out in the future if this issue keeps occurring, pending the PR is merged then.
