### ISSUE TITLE
Radiation Visual Bug (Green Glow)

### ISSUE THREAD

**Issue by Sethnov** [Skyrat-SS13/Skyrat-tg#1919]
While being Heavily Radiated, such as being in a trit fire or next to the HFR reactor, and putting your things in a shower to remove the green glow, the green glow is removed, but the rads are still existing, slight inconvenience to knowing the possible source of radiation.

**Comment by Azarak** [comment]
Could the rads be inside a content in your inventory? ie. pen inside PDA, key inside radio?

**Comment by Sethnov** [comment]
not only that, but the power cell in your hardsuit and jetpack upgrade even get contaminated, and I also believe rads need to be possibly nerfed a little, as a contamination level of 40 rads will make you irritated very fast and others around you 
![image](https://user-images.githubusercontent.com/64242857/100553145-0eb32900-325a-11eb-8213-b22d277d2d29.png)

even when everything is washed, check every inch you still have some rads somewhere, and somehow, even ten rads on yourself are deadly but does decay at a decent rate.
