### ISSUE TITLE
Delam counter is not counting delams

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#19366]
## Round ID:
7664
## Reproduction:
Delam the SM (plz not on the live server)

Only happens on SR, TG's counter is fine.

**Comment by Cyprex** [comment]
It works fine on our downstream too I believe, most likely this is an issue with whatever's used to keep track of this not being included in gamestaticfiles correctly

**Comment by lessthnthree** [comment]
Not a bug, we actually had >99 shifts without a delam.
