### ISSUE TITLE
[MINOR] Poutine has no nutrient content and is consumed instantly.d

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#1940]
## Reproduction:

1. Make Poutine

2. Try to eat it, you eat it in a single bite and it doesnt provide any nutrition to the person, even though the fries, gravy, and cheese have nutrient in it (the pre-cursors to make it)

**Comment by tf-4** [comment]
This is probably something that will be fixed with this https://github.com/tgstation/tgstation/pull/55207

**Comment by Funce** [comment]
The Poutine Recipe is no longer present in tgstation code, likely after the aforementioned PR. PRing it upstream would be best. 
Check tgstation/tgstation#50010 for the recipe
