### ISSUE TITLE
Station ransom event takes money but spawns antagonists regardless. 

### ISSUE THREAD

**Issue by ApplePlastic** [Skyrat-SS13/Skyrat-TG#19427]
## Testmerges:
[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 6c4ce6648f]
(https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#17248: 'You can no longer see the icon of languages you don't know' by Zonespace27 at commit ac46e46d56](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
[#19248: '[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes' by Useroth at commit 1bdef665f1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
[#19308: '[TM ONLY] Disables Sideplane, Makes the Game Playable' by RimiNosha at commit dde0fb7070](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
[#19349: '[TM-ONLY] Makes the Twin Nexus spawn every round for Valentine's Day' by GoldenAlpharex at commit e7a471e8b8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19349)

## Reproduction:
Should be rather easy. Admin-spawn a station ransom event with 100,000 credits in the budget, and pay it. It will act as if there wasn't enough money in the budget, but the credits will be gone, and the antagonist ship will spawn regardless of paying.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/blob/b9eeb21a49c2b77e7dadf3dde2c43f93074baac5/modular_skyrat/modules/contractor/code/datums/contract.dm 

Are you talking about this event? Could you be more specific as for the steps to how to trigger this please. 

I only know of the pirate events and they all seem to ask for 20k credits, and from my testing those work fine.

**Comment by ApplePlastic** [comment]
No, I'm talking about pirates. The only way to properly counteract pirates is to completely ignore the ransom altogether, otherwise it will act like command paid money, take said money, then proceed to spawn pirates anyway. 

This has been an issue for weeks and I don't really know how to properly explain it.

**Comment by Zonespace27** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20167
