### ISSUE TITLE
Tram signal Central-NE malfunctioning

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#19439]
https://user-images.githubusercontent.com/83487515/219933291-db8eb746-0839-47ec-8e01-b140758b2ee4.mp4

## Round ID:
7690

## Reproduction:

Watch the light

**Comment by Jolly-66** [comment]
Not sure if a bug, or mapping issue.
We just reser the maps, so if this isn't occurring anymore, please close this issue.

**Comment by lessthnthree** [comment]
Yeah, the reset fixed it.
