### ISSUE TITLE
NRI pirate spawns cannot access their own turret controls

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-TG#19462]
## Testmerges:

Not relevant.

## Reproduction:

Spawn in as the NRI police/audit/whatever patrol for the pirate event. Be unable to unlock and configure your own turrets from the turret control wall mount device. I am unsure if this applies to the variants or not. Station-cyborgs can access it, as well as the various doors, but that's a separate issue.

**Comment by vinylspiders** [comment]
![image](https://user-images.githubusercontent.com/13398309/232569432-c1cb97db-d648-4a69-9a0b-59dbdbe4dd2d.png)

@Jolly-66 upon testing this is no longer an issue. the panel has the correct access, and I was able to unlock it by hitting it with a NRI id and adjust all the settings that way.
