### ISSUE TITLE
HUD overlay breaking when players switch Z-levels

### ISSUE THREAD

**Issue by MDIPurple** [Skyrat-SS13/Skyrat-TG#19538]
Reporting client version: 514.1589

## Round ID:
7743

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)

## Reproduction:
Wear any HUD glasses. Switch z-levels. Observe error.
![image](https://user-images.githubusercontent.com/82527483/221391494-dcdd332d-c2a8-488e-8ce9-533e327c69b4.png)
![image](https://user-images.githubusercontent.com/82527483/221391499-766fd211-2ddc-492b-81da-f77e725e629a.png)

**Comment by ghost** [comment]
Will be fixed by #19447

**Comment by Jolly-66** [comment]
Fixed in aforementioned PR
