### ISSUE TITLE
Glasses layer over everything on non human species (Except moths for some reason)

### ISSUE THREAD

**Issue by Ebin-Halcyon** [Skyrat-SS13/Skyrat-TG#19556]
Reporting client version: 514.1589

## Round ID:
7745

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)

## Reproduction:

Make anthromorph/lizard character, put on glasses, put on hat, watch as glasses layer over everything.

Shown with jamjar glasses to show how apparant it is.

![image](https://user-images.githubusercontent.com/81479835/221410535-a65b680d-9e62-449f-96c8-cc6d7d670d04.png)
![image](https://user-images.githubusercontent.com/81479835/221410541-4c3e9f1c-daae-4fa6-9d37-1bf88e95d934.png)

most definitely caused by: #19530

**Comment by vinylspiders** [comment]
Oh no, The pain...yes that is definitely the cause.

I have come up with a hopefully adequate solution. The issue came from trying to fix a bug with the (Top) versions of snouts. 

I have since fixed the glasses layering over hats and also made the fix only affect the (Top) versions where it's needed.
