### ISSUE TITLE
Ghost roles on crew manifest

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#19569]
## Round ID:

7750

## Testmerges:

#19248
#19308
#18110
#17248
#19489
#19078
#19536
## Reproduction:

![image](https://user-images.githubusercontent.com/10399117/221463582-7bc194e1-9b16-4032-b2b7-2e38bc63f5fb.png)

**Comment by GoldenAlpharex** [comment]
Yeah that's fixed already.
