### ISSUE TITLE
Contractor: No Contracts

### ISSUE THREAD

**Issue by ToneWyld** [Skyrat-SS13/Skyrat-TG#19567]
Reporting client version: 514.1589

## Round ID:
7749

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)

## Reproduction:

(I'm just a user and have not taken steps to reproduce this error, I was asked to explain by an Admin. Please forgive me if I add excessive information or leave out an imperative.)

I spawn in as a Contractor, open my PDA and choose a Contract. Wait about five minutes, while I'm outside the station, organizing.

I get an alert in large red text, "Contract target out of reach. Contract rerolled." 
![image](https://user-images.githubusercontent.com/126434060/221460497-fe11539e-70bd-4b5b-abb8-4f7538bc629f.png)

I check my PDA, my contract remains. I activate my Contract Pinpointer, and it gives me a directional signal.
I get this alert maybe three more times, before I realize the Pinpointer is blank. I check my PDA, and my contracts section is empty, but I still seem to have a Dropoff Locator sending me to the position I was supposed to extract my original contract.
![image](https://user-images.githubusercontent.com/126434060/221460591-67876dcb-e5f7-4d57-b72a-35730eda24b3.png)
An admin attempted a number of ways to fix me be re-applying contractor status, and re-spawning before applying it again. In all cases my contract list didn't update.
Both before and after this, I attempted to use the three 'Free Rerolls', that come with the Contractor options. None of them seemed to change the list.

**Comment by Jolly-66** [comment]
@Zonespace27

**Comment by Gyrandola** [comment]
Had this happen to me aswell. Basically if you abort your contract or they "get out of reach" it will be removed from the list, so if you for example select and abort every single contract you have you'll be left without any. (if you reroll you're rerolling 0 contracts at that point so it changes nothing).
