### ISSUE TITLE
Ashwalkers spawning without language

### ISSUE THREAD

**Issue by Trigillass** [Skyrat-SS13/Skyrat-TG#19575]
Reporting client version: 514.1589

## Round ID:
7755

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)
- [[MIRROR] Refactors crew records (#72725) + Medical/Security records now use the max/min age. [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19078)
- [fixes ghost cafe sleepers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19536)

## Reproduction:
When spawning in from observation to an Ashwalker, they sometimes appear without a language. This can occur several rounds in a row or may only occur once every few rounds. The only known way to fix this issue in-game is to have an admin add back the language manually per round. 

A hypothesis presented is that it has to do with using a character loadout since in the character creation, Ashwalkers cannot select any languages.

**Comment by vinylspiders** [comment]
Are they spawning without Ashtongue?

Or just without Sol? Because if it's the latter it's coded to remove common and grant ashtongue, even in spite of char prefs.

If they aren't spawning with -any- language then there's probably a runtime associated with this.

Edit: nevermind, I am able to reproduce it. You have to set additional languages in a species that is capable of doing so, then switch to ashwalker in your prefs, without removing the extra languages. That will cause the bug to crop up every single time. I will try to add a fix in my dsi/ nri spawner language PR.

**Comment by Trigillass** [comment]
They are not spawning with Ashtongue but after using a fix recommended by another player - creating a new character - the language stuck. It is to be seen if this is consistent. 

Also, the linked pull request does sound like the main issue at hand so this thread can likely be closed.

**Comment by vinylspiders** [comment]
> They are not spawning with Ashtongue but after using a fix recommended by another player - creating a new character - the language stuck. It is to be seen if this is consistent.
> 
> Also, the linked pull request does sound like the main issue at hand so this thread can likely be closed.

Yeah. I was able to isolate and reproduce the bug, the fix for it is in the linked PR. In the meantime that should work as long as you don't change the new character's language prefs and then swap to ashwalker.
