### ISSUE TITLE
Shapeshifted taur parts have visible shoes and modsuit legs when character created do not.

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#19609]
Reporting client version: 514.1589

## Round ID:
7770

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)
- [fixes ghost cafe sleepers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19536)

## Reproduction:
Before: spawned in as slime with taur set in character creation, shown below is boots worn by the character but hidden on the model as intended

![image](https://user-images.githubusercontent.com/75050485/222273634-6951a5a4-da86-4157-bf6e-9163149d03df.png)

Replication of issue:
Alter form any taur part, legs are deleted and replaced but in a strange way? Character falls over for a moment and problems arise with shoe clipping.
Shoes and modsuit legs are now visible.

![image](https://user-images.githubusercontent.com/75050485/222274803-20c66915-56dd-4abc-b35d-a36800ae123f.png)

![image](https://user-images.githubusercontent.com/75050485/222275723-d1dce85a-4d33-444b-b2b6-c090399d7c42.png)

![image](https://user-images.githubusercontent.com/75050485/222276283-fbe73b22-dcc9-4d80-af38-b8409b7a4d32.png)

Images of modsuits tested on local host:

Normal taur:

![image](https://user-images.githubusercontent.com/75050485/222276678-69c3c8ef-bbe8-4d74-8271-128313fbfb71.png)

shapeshifted taur:

![image](https://user-images.githubusercontent.com/75050485/222276873-4da9ff32-a723-4150-8263-09caffcc7e7b.png)

**Comment by Jolly-66** [comment]
@GoldenAlpharex

**Comment by Syrox25** [comment]
Round 7847: Test merge of the refactor

![image](https://user-images.githubusercontent.com/75050485/224524627-fd015afd-6ce3-4e01-9e0c-2d17cbf16c94.png)

Initial testing seems promising. Slime taur spawns with transparency by default rather than normal opaque which is appreciated :> Modsuits should work fine aswell seeing as shoes are hidden.

![image](https://user-images.githubusercontent.com/75050485/224524798-9d45f70f-b447-4c0d-9f90-4e289a7d78d9.png)

changing taur legs still has the same issue unfortunately but should come up even less often now.

![image](https://user-images.githubusercontent.com/75050485/224524868-4860e84a-5486-4240-80f5-6f58fc7848da.png)
