### ISSUE TITLE
Bots no worky on newTram

### ISSUE THREAD

**Issue by John-Peppercorn** [Skyrat-SS13/Skyrat-TG#19626]
Reporting client version: 514.1585

## Round ID:
7781

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)
- [fixes ghost cafe sleepers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19536)

**Comment by vinylspiders** [comment]
I believe that bots need a beacon to be on the map in order to be able to patrol. https://github.com/Skyrat-SS13/Skyrat-tg/blob/6d63672d4b2636eeaf0a925f87845af95edadbc0/code/game/machinery/navbeacon.dm

It's probably related to that. If there isn't a beacon they'll just not work.

**Comment by Jolly-66** [comment]
Unfortunately the greater problem is most likely not an us issue. 
However, we did just reset thr maps, so if this issue persist after a week, please let us know.
