### ISSUE TITLE
Game fucking crashes when I examine literally anything

### ISSUE THREAD

**Issue by Socialistion** [Skyrat-SS13/Skyrat-TG#19720]
Reporting client version: 514.1589

## Round ID:
7817 (Many others I've tested as well)

## Testmerges:
- [[TESTMERGE CANDIDATE] [SEMI-MODULAR] AI and hologram QoL stuff + misc bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Makes CMGs in the armory spawn as gunsets that include both non-lethal and lethal magazines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19489)
- [Removes modular random event/event vote system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [[MODULAR] Adjust Moldies Random Event](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19352)

## Reproduction:
Step 1: Open Skyrat on my Computer apparently
Step 2: Hold the shift key
Step 3: Try to examine something
Step 4: Watch as the client stops responding and crashes

I have no idea what is causing this but the issue appeared after I moved about 2 months ago (End of December 2022) so either y'all merged Anti-Soshy (me) code during that time or some fucky wucky is making shit go fucko boingo

**Comment by Jolly-66** [comment]
This is most likely, unfortunately, a you issue. I'd recommend talking to the coders in the code channel for help.
