### ISSUE TITLE
Flipped table sprites are no longer consistent

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#19769]
Its probably not a big deal, but consistency is nice to aim for. 

The flipped table is based off the OLD tables before they got Imaginos'ed.
You know, the rounded edged ones. The ones that were baby proof.

![image](https://user-images.githubusercontent.com/70232195/224460101-e6d3d411-b809-4278-b948-b8b77da8504e.png)

**Comment by OrionTheFox** [comment]
Oh god fricking frick
