### ISSUE TITLE
Psyker can't see where their ship is going

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#19795]
Reporting client version: 514.1589

## Round ID:
7850

## Testmerges:
- [Removes modular random event/event vote system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Total refactor of the way we handle and draw mutant_bodyparts (+ missed mirrors that motivated me to do this)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635)

**Comment by Jolly-66** [comment]
![image](https://user-images.githubusercontent.com/70232195/224730026-f5531627-17a6-4fc4-8813-0ca40a46fc47.png)
