### ISSUE TITLE
Taur genitals are incorrectly placed

### ISSUE THREAD

**Issue by wivernshy** [Skyrat-SS13/Skyrat-TG#19803]
Reporting client version: 514.1589

## Round ID:
7851

## Testmerges:
- [Removes modular random event/event vote system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Total refactor of the way we handle and draw mutant_bodyparts (+ missed mirrors that motivated me to do this)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635)

## Reproduction:

Related to https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635. Showing genitals on a taur character will place it at the front of the body, as if they're bipedal, rather than at the back of the taur body. The incorrect placement is the same for all taur bodies, and enabling "Penis Taur Mode" also doesn't fix the issue.

**Comment by GoldenAlpharex** [comment]
Good catch, I forgot to handle that condition.

**Comment by GoldenAlpharex** [comment]
Should be fixed next server restart.
