### ISSUE TITLE
Mold mobs aggro to one another

### ISSUE THREAD

**Issue by LovliestPlant** [Skyrat-SS13/Skyrat-TG#19801]
Reporting client version: 514.1589

## Round ID:
7851

## Testmerges:
- [Removes modular random event/event vote system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Total refactor of the way we handle and draw mutant_bodyparts (+ missed mirrors that motivated me to do this)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635)

## Reproduction:
Electric mosquitos spawned by mold attacked one another when within range (looked to be 6 or 7 tiles). Other observers reported seeing oil shamblers attacking the core on previous rounds.

**Comment by Zergspower** [comment]
Sadly this bug takes a lot of the bite out of molds
