### ISSUE TITLE
plasteel gloves not upgrading with goliath/polar bear hide

### ISSUE THREAD

**Issue by Minuspurple** [Skyrat-SS13/Skyrat-TG#19831]
## Round ID:
7860

## Reproduction:

all i did was make a pair of plasteel gloves and try to upgrade them with goliath/polar bear hide, no error messages or glitches it just wouldnt apply the hide to the gloves

**Comment by Trigillass** [comment]
I've had this issue on multiple occasions and I believe it's the gloves themselves. Supposedly, it's meant to use the same upgrade amount as the boots but it isn't formatted correctly.
