### ISSUE TITLE
Melee not damaging simplemobs, at all, it seems

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#1984]
Reporting client version: 513.1536

## Round ID:
[88](https://scrubby.melonmesa.com/round/88)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Zombie balance changes [TESTMERGE & DNM]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1974)

**Comment by Funce** [comment]
Fixed in #1998
