### ISSUE TITLE
Cyborg: Upgrades no longer accessible and appear disable to players. 

### ISSUE THREAD

**Issue by Tessi12** [Skyrat-SS13/Skyrat-tg#1989]
Reporting client version: 513.1536

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TESTMERGE-ONLY] [DNM] Stack traces on some things](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1848)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Zombie balance changes [TESTMERGE & DNM]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1974)

**Comment by Gandalf2k15** [comment]
It was fixed.

**Comment by atakiya** [comment]
> 
> 
> It was fixed.
