### ISSUE TITLE
pistol magazine (9x25mm) seems to be missing a icon

### ISSUE THREAD

**Issue by AquillaF** [Skyrat-SS13/Skyrat-TG#19905]
Reporting client version: 514.1589

## Round ID:
7879

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [Total refactor of the way we handle and draw mutant_bodyparts (+ missed mirrors that motivated me to do this)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

Pulled the magazine out from the Makarov as black market dealer, and there was no icon for the magazine.

**Comment by AquillaF** [comment]
![Magazinewithnoicon](https://user-images.githubusercontent.com/88289697/225705325-a42b1c80-7010-4955-8bf7-07113cf9995c.png)
also have a picture I guess

**Comment by AquillaF** [comment]
turns out it only happens when its empty or full

**Comment by HoodMilk** [comment]
Saw this as a comms agent too.
