### ISSUE TITLE
0.8 char size is a valid value for sprite scaling but has no effect

### ISSUE THREAD

**Issue by nikothedude** [Skyrat-SS13/Skyrat-TG#19939]
Reporting client version: 514.1589

## Round ID:
7887

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

Step 1. Enter 0.8 into the character size box
Step 2. See as the preview doesnt change
Step 3. See as when spawning in, it acts as if your scaling is at 1

Better seen when going from say 0.9 to 0.8.

**Comment by vinylspiders** [comment]
Duplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/14394, TG upstream issue that hasn't been fixed yet

**Comment by Jolly-66** [comment]
Duplicate issue.
