### ISSUE TITLE
Blood deficiency drain rate doesnt seem to be working as intended.

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#19991]
Reporting client version: 514.1589

## Round ID:
7903

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

I found an issue with blood deficiency itself while writing up an issue regarding its recent addition for slimepeople

While trying to figure out why slime jelly drain rate was so quick during testing, I done some code diving and naturally came across the deficiency code and I think I know whats going on with it...

Blood Regen rate of a human is 0.25
deficiency rate is 0.025

and the part of the code that handles both of these numbers I found this line

> var/blood_deficiency_drain_rate = BLOOD_REGEN_FACTOR + BLOOD_DEFICIENCY_MODIFIER // slightly above the regen rate so it slowly drains instead of regenerates.

If the comment is correct as to how its meant to work then in practice blood drain should be:
[regen_factor - (regen_factor + deficiency_modifier]
Person regenerates 0.25cl of blood, then in the same tick also loses 0.275cl. Net total loss of 0.025cl as it should be (?)

However in testing it seems that blood regen is fully disabled for those with the quirk. So instead of losing 0.025cl per life tick, the actual drain rate is (regen_rate + 0.025)

In human (adjacent) this comes to 0.275, which checks out in practice:

![image](https://user-images.githubusercontent.com/75050485/226249382-facb52df-da2b-4fb1-a3cd-9238799b1fc1.png)

However.. Slimes have a regen rate 6 times that of humans at 1.5
meaning that slimes lose 1.525cl per tick:

![image](https://user-images.githubusercontent.com/75050485/226249728-90e2568d-429c-4df9-b06e-23d8f0d22d2a.png)

Kinda negligable for normal organics as theres not much penalty for sitting at 80% but has been super crippling for slimes as a constant infusion of 4 different toxins is required to offset a drain of 1.5 in order to keep it above 100% in order to not starve.

Thats what I managed to find and understand but what I cant figure out is why that 0.25/1.5 regeneration stops

**Comment by vinylspiders** [comment]
Not an issue. This is intended. See https://github.com/tgstation/tgstation/pull/73866

No matter what way you do it, if a slime's blood volume is any bit less than the amount 100%, they will lose 1.25 nutrition along with regenerating blood. The reason why slimes regen at a rate 6x humans is because of that.

It's not the regen rate that is the issue, it is the fact their blood regen is tied to a need to consume meat. Which is kind of how slimes work. I noted this in my PR linked above.

If it's too penalizing, perhaps I can add a check that lowers it slightly--but this is intentional. Negative quirks are supposed to be negative. Blood deficiency says in its description that it requires constant blood infusion just to keep you alive. It should actually work that way imo.

I did note that if you can keep blood volume over the 560 threshold then you will effectively not suffer the hunger effects.

**Comment by Syrox25** [comment]
No no... I understand that... Its just that if im reading this correctly then drain rate should only be 0.025cl per tick, no? Even on non-slime characters the rate is 0.275cl. 11 times greater than what I believe is intended. 

> I did note that if you can keep blood volume over the 560 threshold then you will effectively not suffer the hunger effects.

In a normal round this is practically impossible... Without having an IV drip of 4 different toxins (Toxin, welding fuel, pest killer, weedkiller) the drain rate is still higher... As demonstrated... every tick the blood volume is draining by 1.525cl
61 times greater than the drain:

> /// Determines the rate at which humans lose blood when they have the blood deficiency quirk. The default is BLOOD_REGEN_FACTOR + BLOOD_DEFICIENCY_MODIFIER.
#define BLOOD_DEFICIENCY_MODIFIER 0.025

**Comment by vinylspiders** [comment]
> No no... I understand that... Its just that if im reading this correctly then drain rate should only be 0.025cl per tick, no? Even on non-slime characters the rate is 0.275cl. 11 times greater than what I believe is intended.
> 
> > I did note that if you can keep blood volume over the 560 threshold then you will effectively not suffer the hunger effects.
> 
> In a normal round this is practically impossible... Without having an IV drip of 4 different toxins (Toxin, welding fuel, pest killer, weedkiller) the drain rate is still higher... As demonstrated... every tick the blood volume is draining by 1.525cl 61 times greater than the drain:
> 
> > /// Determines the rate at which humans lose blood when they have the blood deficiency quirk. The default is BLOOD_REGEN_FACTOR + BLOOD_DEFICIENCY_MODIFIER.
> > #define BLOOD_DEFICIENCY_MODIFIER 0.025

Ah perhaps it isn't clear in the language. But yes, as you noted. The drain rate is 0.275. The regen rate is 0.25. The way it is coded, the regen happens alongside the drain so you must subtract the regen + a modifier to get a net loss.

**Comment by Syrox25** [comment]
apparently it does not. The 0.25 is not added before the 0.275 is removed, meaning you just lose the full ammount

Screenshots provided was me spamming health analazyer on a mothman and a slime, those are only 1 update (tick*) appart from each other.

**Comment by vinylspiders** [comment]
So if I understand what you are saying, you say that is that it is not possible to IV drip faster than the regen rate for slimes, but for humans it works?

This is how regen works for humans. They will gain blood each tick from this, .25 * `nutrition_ratio`, per Life() tick, and then 

it gets removed by the quirk's `process()` for a net loss. That is the idea, anyway. It could be possible that the quirk subsystem process() fires more frequently than Life() which would be unintentional. I didn't code that, I simply went with what was already there when I made that PR.

So the issue in this case is that you are unable to keep blood volume over the 560 threshold for slimes in order to stop the hunger?

**Comment by vinylspiders** [comment]
In other words, if I were to sync up the process() with Life() such that the amount does not fluctuate back and forth and always is -0.025 net loss, would that solve the issue? (aka I would rather skip pulling out the IV drips if I know it works) : )

**Comment by Syrox25** [comment]
Slimes gain blood from drinking something toxic, cant find exactly what those rates are but i believe its to do with damage values

I had to drink 4 constantly in order to get blood above 100% due to losing 1.5cl a tick..

Looking at the code... yeah that seems correct in theory.. but in practice something goes wrong..

Right... I think I get it.
so slimes (and in general?) dont process nutrients into blood unless below 560
I knocked "JELLY_REGEN_RATE +" out of:
> blood_deficiency_drain_rate = JELLY_REGEN_RATE + BLOOD_DEFICIENCY_MODIFIER

It drained at a rate of 0.025cl which then hits the threshold of 560 and the rest of the code kicks in and instantly pushes it back up above it. which seems alot more stable

I think its just an issue with the rate of drain then due to how slimes differ from other organics...

Slimes arent meant to go below 100% at all so having a drain of 1.5cl is super crippling and is hard to offset manually.
whereas humans dont seem to turn nutrients into blood. It just looks at the nutrition level to determine rate and are safe to fall as low as 80% without being starved instantly. (blood.dm)

Alright. my appologies... seems to be working as intended, I do believe that drain is way too high then. Lets see... Hemophage rate is 0.125cl per second... I think anything below 0.25 should be alot more managable? Ill go test that..

**Comment by vinylspiders** [comment]
>Alright. my appologies... seems to be working as intended, I do believe that drain is way too high then. Lets see... Hemophage rate is 0.125cl per second... I think anything below 0.25 should be alot more managable? Ill go test that..

No it's fine--you are right that the way it is done is a bit wonky. I don't know why TG did it that way but the drain and regen happen asynchronously, so that is something that can and probably should be fixed. 

I appreciate the testing, I had a suspicion that it might be -too- crippling with the way the nutrition loss is added in for slimes' regen. But as for solving that, I guess I pictured there being a reasonable way to get the blood levels to remain over 560 (so as to avoid the hunger) and if that isn't possible then I will work on a solution.

**Comment by Syrox25** [comment]
> I pictured there being a reasonable way to get the blood levels to remain over 560

Still doable, I think the only number that needs to change is "blood_deficiency_drain_rate ="

I thought that slimepeople still regenerated blood in the same way as humans but then had a boost when going below thresholds but well.. regeneration stops above 100 and starts below it... so that balancing act is pretty awful when being drained of nutrients.

an alternative (or even a synergy) I guess would be lowering the regeneration to 80% when using the quirk so that blood is only regenerated  if blood is actually lost. Meaning to manage it would only require external toxins rather than a constant fight with nutrient regeneration. Same result I guess. Altho its a shame (and maybe a blessing?) that slimes can starve to death anymore. Results of testing back soon

**Comment by Syrox25** [comment]
Ah. alright I think i got it. 
Welding fuel, no matter how much you consume regenerates blood at a rate of 1cl
This is the most accessible substance and what i used alot in testing.
Toxin adds 1.5cl

So... easy enough then... 1 point of damage = 1cl of blood... hmm..
why did I struggle to gain blood when using toxin/welding fuel blends.... lemme go see

**Comment by vinylspiders** [comment]
>I thought that slimepeople still regenerated blood in the same way as humans but then had a boost when going below thresholds but well.. regeneration stops above 100 and starts below it... so that balancing act is pretty awful when being drained of nutrients. 

Yeah, slimepeople do their own thing with blood in `spec_life()`. They still technically enter the human `handle_blood` proc but there is an early return because of a check for `TRAIT_NOBLOOD` so nothing actually happens in there. It's all in `spec_life()`.

I tested after syncing the quirk's loss in `process()` with the gain given in `spec_life()` and this is the result of spamming the health analyzer (Note: it's not exactly 0.025 because of delta_time).

![image](https://user-images.githubusercontent.com/13398309/226446100-514b8f3e-b061-4aa6-b345-43bda71ddada.png)

edit: the amt got even smaller when I noticed it was being called twice.

**Comment by vinylspiders** [comment]
Another thing I noticed with slimes in particular--if your nutrition is BELOW `NUTRITION_LEVEL_STARVING` (which is 150 nutrition) then slimes will not regen at all. So suddenly that small amount of 0.05 picks up to +1.55/life tick.

**Comment by Syrox25** [comment]
mm... alright. back to using "blood_deficiency_drain_rate = JELLY_REGEN_RATE + BLOOD_DEFICIENCY_MODIFIER"

and results are... not what they should be?.. in theory I should be regenerating 2.5cl each damage update from drinking toxins while losing 1.5cl but.... no.. im still losing blood

 
![image](https://user-images.githubusercontent.com/75050485/226446908-83b50b16-2ce4-4ad3-a9ff-197c32ced829.png)


Wait.... hang on... 3.5 constant toxin damage offsets it... Is the drain rate 2 times faster than recieving damage updates from poison?

**Comment by vinylspiders** [comment]
> Is the drain rate 2 times faster than recieving damage updates from poison?

It could be, yes. On the version you are using the drain takes place in the quirks subsystem which fires at a different rate (possibly more frequently) than Life() proc does. I have fixed that in my version however.

And see above comment about nutrition, which also could be a factor. If your nutrition is below 150 then you will not regen at all as a slime.

**Comment by vinylspiders** [comment]
Okay, I didn't want to have to do it but I spose it I have to at this point.

On my version where I fixed the issue of the procs syncing up, this is how it works.

![image](https://user-images.githubusercontent.com/13398309/226450001-ef02e65e-ca21-4b78-b1d5-afac7c89597d.png)

You need to transfer 0.03 or higher for the toxin to not be ignored by the liver and so it gets metabolized, and then you get the effect of gaining blood.

If you have multiple toxins in the same mix then I suspect the amount might be getting diluted and so each individual toxin gets ignored. That's just how it works unfortunately. So if you had two toxins I think you would have to do 0.06 and so on.

On top of that, when you reach 560 it jumps back to 556 for some reason. I'm going to look into that, but a simple fix would be to not subtract nutrition unless you are at 550 or so blood volume. That way if you are hooked up to an IV with welding fluid at a transfer rate of 0.03 you will never suffer the hunger effects. But they will still start pretty early on if you aren't, making it necessary to take care of around roundstart.

How does all of this sound?

**Comment by Syrox25** [comment]
> If your nutrition is below 150 then you will not regen at all as a slime.

natural regeneration no... but manual regeneration using toxins is still doable.. and personally I believe that a single toxin should JUUST about offset or equal it. so an effective rate of between 0.75 and 1.5?

I tested that 3.5 toxin damage while starving but should be the same if above 100% aswell... So in theory reducing the code value to 0.50 should be a fair balance for welding fuel alone and 0.75 would require multiple or something stronger to get blood above 100% consistantly. requiring 3+ constantly seems a bit much...

![image](https://user-images.githubusercontent.com/75050485/226451020-f125b07f-aca4-4e22-afb0-348b7384fd25.png)

**Comment by Syrox25** [comment]
bleh, sorry for all the trouble. It might not be nessisary to go that far. still in the middle of tweaking rate values in jellypeople.dm directly. Nothing seems to stop you just.... setting it to a specific value... Little worried its jank code and might break something elsewhere

**Comment by vinylspiders** [comment]
> bleh, sorry for all the trouble. It might not be nessisary to go that far. still in the middle of tweaking rate values in jellypeople.dm directly. Nothing seems to stop you just.... setting it to a specific value... Little worried its jank code and might break something elsewhere

Naw, it's fine. It shouldn't break anything else. I think I have a solution at this point. In my solution as long as you don't let nutrition reach 150, if you get an IV with one toxin hooked up to you your blood will regenerate faster than it drains. And no hunger loss once you get to 550 blood.

So you might have to eat a little bit around roundstart to hold yourself over but otherwise it shouldn't be an issue. And if you manage to get to below 150 hunger you can temporarily eat to get yourself over that point. Does that sound ok?

If we start getting into checking for multiple toxin blends and stuff then the code will get very jank very quickly. It will however work if you have 3 toxins going at 0.09/s I think but it is far easier to just get your nutrition up than go through that to get the natural rate back.

**Comment by Syrox25** [comment]
yup... Confirmed... slime toxin regeneration only happens at half the rate

I made it "blood_deficiency_drain_rate = 1.5" and tested with that

Taking 2.5 toxin damage from metabolising caused blood to only drain at a rate of 0.5cl constistantly with no rounding errors, meaning that in order to offset the drain using toxins alone you need to take 3 damage constantly.

I could just override the whole line for a static number equal to half of what a reasonable toxin damage should be.

I still think a drain rate 6 times higher than that of a human is a little unreasonable... 20 minutes is all you get after chugging a tank of welding fuel and an entire cheesecake before blood and hunger is fully drained and thats even while afk.
It should affect nutrition but only if you fail to keep on top of it and at current rate it doesnt seem reasonable to manage, sorry :/

**Comment by Syrox25** [comment]
Suggesting static value of 0.75.

Welding fuel alone cannot out regenerate this number but reduces drain to 0.5cl

Would need to aquire a second toxin from somewhere or eat slightly more frequently than normal. 
Two at most is managable due to how abundant welding fuel is and how slowly it metabolises (0.32), only requiring one other to offset fully.

**Comment by vinylspiders** [comment]
I'm in the midst of working on a PR for this, I suggest waiting a little bit until I put it through

**Comment by Syrox25** [comment]
Ah.. Alright, sorry for all the trouble. Was only meaning that as an alternative if you didnt want to do your method. You sounded reluctant to try it.

Thank you <3

**Comment by vinylspiders** [comment]
> Ah.. Alright, sorry for all the trouble. Was only meaning that as an alternative if you didnt want to do your method. You sounded reluctant to try it.
> 
> Thank you <3

No problem! I've had it coded in already, but I am just working out a weird kink with humans now.

**Comment by vinylspiders** [comment]
It should be done now, feel free to download my branch if you wanna test it yourself. How it works now is described in the PR body.

**Comment by Syrox25** [comment]
Had to test as transformed human so there may be skewed results but seems alot better.
being fed and drinking welding fuel is keeping it from going below the new threshold. staving off blood drain with a constant minor toxin intake is what I had in mind for it so im happy.

slow increase to 560 then drops down below 558. With no intervention it ticks down at a rate of 0.05cl
Nutirent drain of 2.5 starts below new threshold

Thank you <3
