### ISSUE TITLE
Ashwalker eyes don't work

### ISSUE THREAD

**Issue by Mrsteak123** [Skyrat-SS13/Skyrat-TG#20009]
Reporting client version: 514.1589

## Round ID:
7916

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:
I spawned in as an Ashwalker, and the ashwalker eyes didn't work. The HUD icon was there, but clicking it did nothing, The age ceremony didn't change anything either. After ahelping, the admin said that they tried giving me new eyes but that it didn't work, possibly due to the age ritual? Or maybe TG's new nightvision update broke the eyes. I've got no clue, but ashwalkers are near unplayable without them.

If anyone wants to try reproducing this, try spawning in as an ashwalker and see if the eyes work. Or maybe spawn as a normal character and give yourself ashwalker eyes, and then test it. I'm unsure if the issue is with ashwalkers or just the eyes, but I'm betting it has something to do with the nightvision update.

**Comment by vinylspiders** [comment]
Duplicate, I've had a fix open for this for the past week.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/19897

Whenever someone merges that it will be fixed.

**Comment by Mrsteak123** [comment]
Alright, I wasn't sure if I was the only one having this bug or not. Hopefully that gets merged shortly.
