### ISSUE TITLE
[MINOR] No ghetto analogue for food-cutting implements.

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#2017]
## Reproduction:

1. Try to cut bread, flat-dough, cheese-wheels or any food item that requires it with an object that isn't a knife.  You are unable to, it seems food items have to be cut with a knife now and ghetto analogues no longer work (scalpels, saws, broken glass, etc.).

2. Im unsure if this is working as designed or a bug, if its as designed then please close.

**Comment by Owai-Seek** [comment]
More than likely an upstream issue with the food reworks. Eeeee.

**Comment by Zergspower** [comment]
Food rework seemed to have resolved this bug - PDA pen works as well on Cheese-wheels. Though dough has a few unusable points but with how cheesewheels are interacting I think this is a design feature since dough is soft.
