### ISSUE TITLE
Pride Pins don't spawn from loadout

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#20214]
Reporting client version: 514.1589

## Round ID:
7992

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

Have a pride pin in loadout > no pride pin at roundstart or on spawn. dire bug. pls fix.... 

*EDIT* Actual bug/stealth nerf is that gear harnesses no longer allow you attach accessories, such as pride pins. Clearly a mistake bcuz gear harnesses are mad gay.

**Comment by Gyrandola** [comment]
Tried to replicate but no luck

**Comment by vinylspiders** [comment]
Me neither--more information would be helpful to figure out the cause. What is your full loadout and what were you trying to spawn as @kittysmooch?

**Comment by kittysmooch** [comment]
> Me neither--more information would be helpful to figure out the cause. What is your full loadout and what were you trying to spawn as @kittysmooch?

sorry for the lag, got busy. i was spawning in as a security officer with my pin set to spawn on my gear harness. could be harnesses not letting pins get attached but i haven't checked yet, i'll try to troubleshoot it a little more if i get time tonight.

**Comment by kittysmooch** [comment]
yeah its the gear harness not accepting accessories anymore. gonna update the main post.

**Comment by vinylspiders** [comment]
> yeah its the gear harness not accepting accessories anymore. gonna update the main post.

Awesome, thank you!
