### ISSUE TITLE
tier 4 scythe crate contains nothing

### ISSUE THREAD

**Issue by kylecorn1996** [Skyrat-SS13/Skyrat-TG#20216]
## Round ID:
7994

## Reproduction:
purchase the tier 4 scythe crate from service orders. open the crate. behold, nothing.

you may want to check the tier 3 crate while you're at it. it's possible that both service order scythe crates are empty, though I haven't had the opportunity to check.

**Comment by Gyrandola** [comment]
I tried ordering tier3/4 scythes and even spawning them but couldn't get to replicate the bug. They always had their content.

**Comment by vinylspiders** [comment]
I also tried to replicate this and could not. 

![image](https://user-images.githubusercontent.com/13398309/229267162-42f76b3d-634f-42ab-a427-ffb7216c285c.png)

Could you provide more details, like were other people able see the scythe missing from the crate? Perhaps it's a local client side thing, may want to update byond to the latest and all that and see if it still is happening. Same goes for the #20214. I'd like to get to the bottom of this!

**Comment by kylecorn1996** [comment]
I can't replicate it either. when I order them inround now, they show up with the scythe in it. not sure what to say. I suppose this can be closed?

**Comment by vinylspiders** [comment]
> I can't replicate it either. when I order them inround now, they show up with the scythe in it. not sure what to say. I suppose this can be closed?

Yeah, it is hard to say what was going on without seeing runtime logs and such.

Is the pride pin thingy still going on too? I will not suffer homophobic bugs.

Most likely it's a corrupt cache issue, that can cause things to become invisible. @Jolly-66 doesn't seem to be an issue on our end.

**Comment by Jolly-66** [comment]
Gonna assume its a tg issue then (woe is all)
