### ISSUE TITLE
Spawner menu blank

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-TG#20267]
## Testmerges:

Master commit: [359db16cb5b628df27d7afe3622e43cb810fcaa1](https://github.com/Skyrat-SS13/Skyrat-tg/commit/359db16cb5b628df27d7afe3622e43cb810fcaa1)
The following pull requests are currently test merged:
[#19505: 'Replace Chaos Event System with ICES - Intensity Credit Event System' by lessthnthree at commit 09537c9fe3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit b0f1f2f099](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#19308: '[TM ONLY] Disables Sideplane, Makes the Game Playable' by RimiNosha at commit dde0fb7070](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
[#19820: '[TM-ONLY] Prevents the psyker pirate variant from rolling' by GoldenAlpharex at commit b337b1a9a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
[#18364: '[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)' by Paxilmaniac at commit ba7530a265](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)
[#20232: '[DNM][MODULAR] Investigation Auxilium' by softcerv at commit b5cc22bd08](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20232)

Local commit: d561dc3320398ec583c39f040a4a9d0ee400a1a0
TGS version: 4.19.1
DMAPI version: 5.4.0

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:

idk click on the spawn menu.

For whatever reason the spawn menu has not been properly filling out in some rounds, and has instead been completely blank. For a day or two I have noticed it for every round I've hit on it for, but I also haven't been going to it religiously. A few people in ghostchat has chimed in with it being a sometimes thing. Couldn't say for certain! 

The sleepers and other such spawners all still work if you find them manually.

![image](https://user-images.githubusercontent.com/121744141/229329280-0f80fb2b-9c14-4489-8a07-e959d17fca7f.png)

**Comment by Gyrandola** [comment]
Can confirm

**Comment by ghost** [comment]
Can Confirm

**Comment by burgerenergy** [comment]
It was fixed for a bit, but now it's back on as of round ID: 8055.

**Comment by StarHorder** [comment]
CAN CONFIRM

**Comment by vinylspiders** [comment]
Ahh the server just hasn't been updated with the fix yet. It's an intermittent issue so it was never actually working on live, It must have just not cropped up yet in the round where it was working.

It should pop up in the changelog when it's actually been fixed.
