### ISSUE TITLE
Humanoids Can't Wear Jumpsuits

### ISSUE THREAD

**Issue by gamermomentum** [Skyrat-SS13/Skyrat-TG#20276]
## Testmerges: 
[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 80c6624a9e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#19308: '[TM ONLY] Disables Sideplane, Makes the Game Playable' by RimiNosha at commit dde0fb7070](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
[#19820: '[TM-ONLY] Prevents the psyker pirate variant from rolling' by GoldenAlpharex at commit b337b1a9a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
[#18364: '[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)' by Paxilmaniac at commit ba7530a265](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:
 Be a humanoid. Wear basically any jumpsuit(SOME work and show up as normal but like 95% of them I've tested don't work) Be inexplicably naked(underwear)

**Comment by Gyrandola** [comment]
I ran into the same problem today after the new update. Seems it somehow corrupted a lot of people's caches. So yes, the solution to invisible clothing is clearing the cache. BYOND > Cogwheel > Preferences > Games

**Comment by gamermomentum** [comment]
SO true. I'm goofy as hell and haven't had that caching issue in like 4 years so I didn't consider it lol
