### ISSUE TITLE
Spawner's Menu is showing nothing

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#20270]
Reporting client version: 514.1589

## Round ID:
8010

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)
- [[DNM][MODULAR] Investigation Auxilium](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20232)

**Comment by ghost** [comment]
Can confirm.

**Comment by Jolly-66** [comment]
Dupe of #20267
