### ISSUE TITLE
`regenerate_organs` proc is turning screenshot test green

### ISSUE THREAD

**Issue by desertmote** [Skyrat-SS13/Skyrat-TG#20284]
## Reproduction:

the `regenerate_organs()` proc used in our `/datum/species/prepare_human_for_preview()` proc is turning screenshot test characters green.

without the proc
![old](https://user-images.githubusercontent.com/77534246/229392629-3552a03d-dc8e-4299-9754-17ed8025bd91.png)

with the proc
![new](https://user-images.githubusercontent.com/77534246/229392662-60e3a90c-de3f-4741-830f-85dc5b2c0831.png)

**Comment by Jolly-66** [comment]
Green is the base mutant color that upstream uses, by the way.
