### ISSUE TITLE
Light tubes have wrong inhand sprite

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#20301]
## Round ID:

8020
## Reproduction:

Hold a light tube. It brown.

![image](https://user-images.githubusercontent.com/83487515/229593440-1e41f97e-416e-4a78-8486-502713a3b1f1.png)

**Comment by vinylspiders** [comment]
I've made a fix for this, just waiting on my other light inhand PR to get merged first because I don't feel like dealing with the conflict.
