### ISSUE TITLE
Strange sprite glitch when equipping pickaxe in explorer equipment slot

### ISSUE THREAD

**Issue by Dr-0range** [Skyrat-SS13/Skyrat-tg#2034]
## Round ID: 
[115](https://scrubby.melonmesa.com/round/115)

## Testmerges:
not applicable

## Reproduction:
When slotting a pickaxe into the equipment slot of the explorers suit a strange pink belt shows up on the player sprite. 
Tested with both diamond and regular pickaxe.
![image](https://user-images.githubusercontent.com/61362684/101103778-f2045180-35c9-11eb-880a-8d81d73bf426.png)

**Comment by Draganfrukts** [comment]
Upstream issue from one of their updates, it's a placeholder sprite.

**Comment by tf-4** [comment]
No longer an issue
