### ISSUE TITLE
Text cut-off on OPFOR panel

### ISSUE THREAD

**Issue by Ember16** [Skyrat-SS13/Skyrat-TG#20421]
Reporting client version: 514.1589

## Round ID:
8054

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)
- [Engineering Event - Wall Eating Mushrooms!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20264)
- [[SEMI-MODULAR] Lighting Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20269)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:

I opened the OPFOR panel and copy-pasted a copy of my application into the panel. When I changed the tab (swapping to the weapon selection screen then back) a majority of the contents included in the 'Backstory' and Objective 'Title' sections has been cut off and seemingly deleted. Nonetheless, I submitted the application as is and the admins didn't seem to notice anything wrong, so I'm guessing it is a glitch on the sender's side of things. It is not strictly visual however (such as the text being turned invisible), because I cannot click on or edit anything after the cut-off point. On my end it just seems like it was simply deleted.

**Comment by Zergspower** [comment]
Could you remember how large your post was? I'm wondering if here was a character limit breach

**Comment by vinylspiders** [comment]
It's 100% a character limit issue. The cap is 1000 chars for the background and 500 for the rest. It's not a bug. I do feel as though it's a bit too low though, I'll see if we can double it as well as put it in the tooltips mentioning that there is a limit.
