### ISSUE TITLE
Boots only being able to hold 1 item despite description saying it can hold 2.

### ISSUE THREAD

**Issue by Raxraus** [Skyrat-SS13/Skyrat-TG#20431]
Reporting client version: 514.1589

## Round ID:
8057

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:

Try and place two epipens into jackboots or dark jackboots, it will say that there is no space after one item is placed in it.

**Comment by Jolly-66** [comment]
Upstream issue unfortunately, I share your pain.

**Comment by vinylspiders** [comment]
The fix is already made upstream, just trying to get it reviewed and merged.
