### ISSUE TITLE
Spray Painted Windows not opaque

### ISSUE THREAD

**Issue by blaberface** [Skyrat-SS13/Skyrat-TG#20468]
Reporting client version: 514.1589

## Round ID:
8066

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)
- [Brings the CIN's *surplus* firearms to be a bit more modern than an ak-47](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20432)
- [[SEMI-MODULAR] APC/Air Alarm lighting and functionality](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20323)

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20288
