### ISSUE TITLE
Dying (To a cosmic heretic? maybe??) replaces the FOV fog of war with space

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#20529]
Reporting client version: 514.1589

## Round ID:
8086

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)
- [Brings the CIN's *surplus* firearms to be a bit more modern than an ak-47](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20432)
- [[SEMI-MODULAR] APC/Air Alarm lighting and functionality](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20323)

## Reproduction:

Died, got revived, saw the void instead of shadows where my view is occluded.

![image](https://user-images.githubusercontent.com/105110468/231673902-737c5983-f302-4ee2-b2bc-7f359d1af7dc.png)

**Comment by kittysmooch** [comment]
note while i'm wearing a night vision sechud here it persists even without it

**Comment by Jamarkus127** [comment]
this actually happens quite a bit. its never game breaking though, its some weird graphical issue. only place its disorientating is on icebox.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22791 This may be fixed by this. If it's still happening please let me know.
