### ISSUE TITLE
Eherals dont get hunger bar but get overcharge/overfed notice

### ISSUE THREAD

**Issue by Vynellin** [Skyrat-SS13/Skyrat-tg#2053]
## Round ID:

IRound id doesnt matter but 135

## Testmerges:

Current test merge unknown what we are on.

## Reproduction:

Plan a etheral.

**Comment by atakiya** [comment]
Tip:
> Current test merge unknown what we are on.

You can always check that by going to `OOC -> Show Server Revision` or typing `show-server-revision` into the commandbar

![image](https://user-images.githubusercontent.com/6952402/101296173-486bcd00-3822-11eb-807a-3c171898b73e.png)

**Comment by Vynellin** [comment]
![Screenshot 2020-12-07 145054](https://user-images.githubusercontent.com/67445899/101398213-bb655a00-389b-11eb-97e9-74d8c3d57c1a.png)

**Comment by tf-4** [comment]
You get a battery indicator when low.
![image](https://user-images.githubusercontent.com/8881105/151587595-319c792d-1a33-4ffe-a713-fb1c3cc0cf73.png)
