### ISSUE TITLE
The syrup bottles you can buy from cargo to add to coffee's don't work

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-TG#20615]
Reporting client version: 514.1589

## Round ID:
8120

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:

Buy the crate from cargo that is the coffee syrup crate.  With or without the pump on the bottle try to add the contents of the bottle to a cup or any other container.  It doesn't work.

**Comment by lessthnthree** [comment]
You click the coffee cup or other container on the syrup pump, not the other way around.
