### ISSUE TITLE
Slime Bones

### ISSUE THREAD

**Issue by Resreep** [Skyrat-SS13/Skyrat-TG#20677]
## Round ID:

8142, though this bug goes back much farther than that. Over a month, if not more than that.

## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 64f88e3e09](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#19820: '[TM-ONLY] Prevents the psyker pirate variant from rolling' by GoldenAlpharex at commit b337b1a9a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
[#18448: '[MOSTLY MODULAR] Time Clock' by softcerv at commit 95618085cd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:

Xenobiological Slime Hybrids, at least the roundstart version, seems to have bones. Slime characters are suffering wounds they shouldn't, such as broken bones and lacerations. Slimes are not meant to have wounds like this.

Wounds can be caused by any numbers of sources, but taking the cursed quirk is a quick way to bring it up. Or get shot, stabbed, or anything.

![image](https://user-images.githubusercontent.com/108446208/233516587-9c8d579a-f3ae-4171-abf5-56c3e116c98d.png)
![image](https://user-images.githubusercontent.com/108446208/233516599-b6809cb3-83b5-4e5e-adbc-5d0659e7038b.png)

**Comment by GoldenAlpharex** [comment]
For anyone looking into this, slime people should be immune to fracture wounds. The other wounds are fine for them to have, in my opinion, but fractures obviously make no logical sense on them.
