### ISSUE TITLE
Potential Disease Bug

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#2069]
Reporting client version: 513.1536

## Round ID: 
Round ID: #147

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Not Modular] Defibrillates bonus ore from the ORM. ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1913)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)

## Reproduction:

While playing on the server, an admin event gave me a disease, as well as presumably a few others. The disease however was bugged in some way as while the symptoms progressed, going from slightly hot to constant messages of feeling hot and my blood feeling like it was boiling. Despite this no damage was being done, and it would not show on sensors. This in the end required admin intervention as the messages came in too often to ignore.

**Comment by YakumoChen** [comment]
Intended, there are false alarm diseases that have exactly these effects and cause you to hallucinate symptoms for a few minutes.

**Comment by Funce** [comment]
Let me know if this still an issue.
