### ISSUE TITLE
Minebots have safety on their ranged attack which they cannot turn off

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#2071]
Reporting client version: 513.1536

## Round ID:
[148](https://scrubby.melonmesa.com/round/148)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Not Modular] Defibrillates bonus ore from the ORM. ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1913)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)

**Comment by tf-4** [comment]
No longer an issue
