### ISSUE TITLE
Bluespace miner board has two (machine board)

### ISSUE THREAD

**Issue by Zonespace27** [Skyrat-SS13/Skyrat-TG#20733]
## Reproduction:
- get bluespace miner board
- see two (machine board)s

**Comment by vinylspiders** [comment]
You mean like ordering it from cargo? I just tried and wasn't able to get it to happen locally. 

![image](https://user-images.githubusercontent.com/13398309/234057677-79aa7163-1149-4c61-acbc-c56e9cf1a2c6.png)

You sure there's not like a chance to get an extra item as a shipping error or something?

EDIT: Lol I see what you mean now.
