### ISSUE TITLE
Layer Shifting doesn't work for borgs, and cannot be used laying down.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#2077]
## Related PR:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1943
## Reproduction:

Be a degenerate, be around borg, be unable to layer shift with the borgo.

Great feature though!

**Comment by Zergspower** [comment]
Layering issue seems to be fine when engaging in degeneracy - resolved most likely over time
