### ISSUE TITLE
Spreading Prosthetic Limb Quirk

### ISSUE THREAD

**Issue by syntax1112** [Skyrat-SS13/Skyrat-TG#20791]
## Round ID:
8226

## Reproduction:

I believe something about the Prosthetic Limb Quirk is causing it to "spread" to other characters when selecting them in the creation menu. One of my characters has the prosthetic Limb quirk on, and when I select her and then switch to other characters, her quirk spreads to them. The quirk doesn't seem to show up in their Quirk selection window, but it applies to the character. And it isn't cosmetic: if I spawn in at that state, the prosthetic is there in-game. 

And I think, since the Quirk sets a RANDOM limb it keeps spreading until all the limbs of all my characters are gone if I continuously switch back and forth. The bug seems to go away if I close and reopen the creation window, but it will continue to spread again if I select the quirk'd character and back again. Removing the quirk entirely from the character and reloading the creation window seems to stop it from spreading.

![image](https://user-images.githubusercontent.com/104675450/234655083-1244b24d-4520-4fcc-9dd9-e74e6c999b3b.png)
Pictured is an unaffected character before selecting the character with Prosthetic Limb 

![image](https://user-images.githubusercontent.com/104675450/234655358-21e765d2-e340-4a04-aefa-113bc0097491.png)
This character has the quirk and it applied to their left leg.

![image](https://user-images.githubusercontent.com/104675450/234655553-e0044e4c-2c65-4eee-b35e-84c4ba3ed1d1.png)
Now switching back to the previously unaffected character shows that the left leg prosthetic copied over to them somehow.

**Comment by syntax1112** [comment]
I can't seem to consistently show that the bugged prosthetics apply when spawned in game. It happened before, but now that I'm trying to get it to happen for a screenshot, the issue seems to not persist into spawn.

**Comment by vinylspiders** [comment]
@GoldenAlpharex  could this be related to https://github.com/Skyrat-SS13/Skyrat-tg/issues/19935 ?

**Comment by vinylspiders** [comment]
confirmed upstream issue
