### ISSUE TITLE
Sometimes, Chat eats messages.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#2079]
## Reproduction:

Literally no idea what causes it, but, on (my side) a message didn't appear in chat, while it appeared for others. I've also noticed peoples messages disappearing sometimes when I see their runechat, but don't see what they said in the chatbox. It isn't when they're far away either, the person was sitting right next to me.

OOC: WFTWP: Xyel
OOC: WFTWP: You cant have dinner
**_Missing Message:_** OOC: WFTWP: We don't have vore yet.
OOC: StarHorder: yet

Time/Panel Stats:

![image](https://user-images.githubusercontent.com/7543955/101422205-2460c800-38c4-11eb-99bb-88446d119978.png)

**Comment by atakiya** [comment]
Probably upstream issue
https://github.com/tgstation/tgstation/issues/54692

**Comment by bobbah** [comment]
yes it is
