### ISSUE TITLE
Expand module broken

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#2084]
## Testmerges:

Master commit: bd29550b77a0b004f3f8e3580f32b118a0cdf7e5
The following pull requests are currently test merged:
#948: '[TESTMERGE] Makes icon2html not work' by Azarak at commit a7a3accaf5
#1783: '[DNM] Cryo on core maps [TESTMERGE ONLY]' by KathrinBailey at commit 2893082286
#1285: '[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity' by Azarak at commit 19015e17f1
#1913: '[Not Modular] Defibrillates bonus ore from the ORM. ' by ShadeAware at commit d3a493a2f3
#2030: '[TM] Disables sentient disease - pending rebalancing/tweaks' by Azarak at commit 113ea79ebe

## Reproduction:

Take expand module, install into borg. causes shrink, uninstall module, reinstall module shrinks further

**Comment by atakiya** [comment]
Should be fixed by #2083
