### ISSUE TITLE
permament stamina damage

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#20898]
Reporting client version: 514.1589

## Round ID:
8287

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [Peacekeepers Episode Two: Return of the Civil Disputes Officer](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20762)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)

## Reproduction:
I've seen this be observed several times, but basically taking any sort of stamina damage from slipping, shoving, or most commonly punches doing stamina damage.

Under VV no stamina damage will be in any values but your stamina bar will be yellow and you'll be slow. 

https://gyazo.com/f497b584f136ffd6fb5313d624175002

It seems to be a random chance, while entirely low, given I only see ahelps regarding this bug about once per week

**Comment by kittysmooch** [comment]
i got this and was able to recover with the usual things like coffee, if u need a temp fix for yr ahelps

eta: i also got the perma stamina damage from drinking catnip tea so it affects other sources too

**Comment by Samarai** [comment]
From my experiences, this bug 'fixes' itself when you're healed, but can also be triggered consistently with boxing gloves and/or punching yourself. Even just healing brute via sutures allows your stamina to regen and your movespeed to return to normal. Additionally, putting yourself in stamcrit can fix it, so a quick temporary-fix is to just... punch yourself until you can't move.

**Comment by vinylspiders** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/20992
