### ISSUE TITLE
👮 Head of Security -1/1

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#20913]
Reporting client version: 514.1589

## Round ID:
8288

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [Peacekeepers Episode Two: Return of the Civil Disputes Officer](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20762)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)

## Reproduction:

Get a load of this shit:
![image](https://user-images.githubusercontent.com/105110468/235822692-17397116-074b-4226-926e-178e122f75ab.png)

I was sitting in the lobby so aside from telling you that a HoS DNR'd I got nothin'

**Comment by vinylspiders** [comment]
Wow, they must have been bad at their job! 😆 

Do you know if anyone else saw it like that? I'm wondering if it's a ui glitch. 

I know that if you try to set them to a negative number via admin commands it just makes the amount infinite. Very interesting.

**Comment by tf-4** [comment]
DNR empties the jobslot so maybe they somehow cryoed *and* DNR'd?  Or they DNR'd and a confused admin cryoed them? That would be my guess.

**Comment by kittysmooch** [comment]
> Wow, they must have been bad at their job! 😆
> 
> Do you know if anyone else saw it like that? I'm wondering if it's a ui glitch.
> 
> I know that if you try to set them to a negative number via admin commands it just makes the amount infinite. Very interesting.

i didnt get anyone else to check, sorry!

**Comment by Thlumyn** [comment]
I saw the bug as well, and the HoS did DNR iirc
