### ISSUE TITLE
Birdshot perma observation has orderly locker despite being a sec area

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-TG#20937]
## Round ID:
8302

![image](https://user-images.githubusercontent.com/8881105/236331725-d3d74fdd-57cd-4529-b82c-67e5c94af7f3.png)

**Comment by press-mark** [comment]
![image](https://user-images.githubusercontent.com/6972764/236707678-1db993c3-24fe-43cc-9164-ca88b644cbc5.png)
upstream :-)

**Comment by Jolly-66** [comment]
Please close upstream issues :nooo:
