### ISSUE TITLE
GPS arrows stuck pointing North

### ISSUE THREAD

**Issue by LovliestPlant** [Skyrat-SS13/Skyrat-TG#21025]
Reporting client version: 514.1589

## Round ID:
8330

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
- [GPT API Integration + Use cases](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20958)

## Reproduction:
On Birdshot: the distance finder on GPS's always points North, regardless of the actual orientation of the point in question. GPS coordinates are still accurately displayed. Issue persists across multiple GPS's.

**Comment by Glyphee** [comment]
This happened to me on maps other than Birdshot as well.

**Comment by Paxilmaniac** [comment]
This seems to not be happening anymore
