### ISSUE TITLE
CMG fires on safety

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#21116]
Reporting client version: 514.1589

## Round ID:
8361

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
- [GPT API Integration + Use cases](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20958)

## Reproduction:
The CMG ignores the gun's safety state when firing. This bug does not seem to affect other guns that I've had the chance to test.

**Comment by vinylspiders** [comment]
Duplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/21059

This issue actually is affecting all guns that have the autofire component, working on a fix.
