### ISSUE TITLE
Changeling fake death stays faking death and cannot be revived

### ISSUE THREAD

**Issue by Syilumi** [Skyrat-SS13/Skyrat-TG#21156]
## Round ID: 
NULL

## Reproduction: 
as a changeling fake your death and wait till you can revive then attempt to revive whenever i do so the 'feign death' popup appears and if i click yes it just states that im already faking my death without reviving me

https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/b36ee623-69a5-492b-bbb0-a4a2c7b9c217

video of how it do

**Comment by softcerv** [comment]
I can confirm that this is a skyrat issue. I tested TG code and the same issue was not present

**Comment by Syilumi** [comment]
oh yea this is my first time posting a bug report thingy so uh i hope im not messing up in anyway

**Comment by Syilumi** [comment]
the revive function does work if the player dies

**Comment by softcerv** [comment]
> oh yea this is my first time posting a bug report thingy so uh i hope im not messing up in anyway

Nah, you aren't messing up in a way that matters. I was able to replicate the bug on my machine using your instructions, that's the most important thing. 

Thank you for making this issue.

**Comment by Syilumi** [comment]
woo!

> > oh yea this is my first time posting a bug report thingy so uh i hope im not messing up in anyway
> 
> Nah, you aren't messing up in a way that matters. I was able to replicate the bug on my machine using your instructions, that's the most important thing.
> 
> Thank you for making this issue.

woo! glad i do dis right
