### ISSUE TITLE
Carded Ai was wiped and still able to use their abilities in dead chat.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#2118]
Reporting client version: 513.1525

## Round ID:
[178](https://scrubby.melonmesa.com/round/178)
<!--- **INCLUDE THE ROUND ID**

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Not Modular] Defibrillates bonus ore from the ORM. ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1913)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)

## Reproduction:

Card AI, wipe AI, have AI use abilities in dead chat.

**Comment by Zergspower** [comment]
Unable to replicate bug - potentially resolved over time
