### ISSUE TITLE
Forked Tongue doesn't work as intended?

### ISSUE THREAD

**Issue by trazodont** [Skyrat-SS13/Skyrat-TG#21226]
Reporting client version: 514.1589

## Round ID:
8381

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)

## Reproduction:

From my understanding, the forked tongue agument is supposed to give your character the same speech mannerisms as lizardpeople but I have yet to experience it actually working.

I have the augment on a character, but I have actually not seen it work.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/97755577/913d027f-b8e0-41e5-8d78-3e7d8de96d45)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/97755577/e993c79c-ee62-4af7-8920-0822630a2943)

He doesn't get the extra ssss or even does the ks for x.

**Comment by YakumoChen** [comment]
Its because you're using the dog quirk

**Comment by YakumoChen** [comment]
Good on you for using screen shots but reproduce the bug on a trait-sterile human character next time

**Comment by Jolly-66** [comment]
Not really a bug per se, but more of a miscommunication with traits/quirks we have that should be clarified.
