### ISSUE TITLE
"/list" announcement bug

### ISSUE THREAD

**Issue by sciira** [Skyrat-SS13/Skyrat-TG#21312]
Reporting client version: 514.1589

## Round ID: 
8436

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
- [Clockwork Cult: Research](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20696)

## Reproduction:

Use of /obj/item/device/traitor_announcer produced a captain's announcement with "/list" as its contents. Issue seemingly only present on the main server, as attempting the same methods via a test server produces the proper announcement. A fellow admin tells me this is likely a test merge issue.

**Comment by vinylspiders** [comment]
Bug from the upstream new TTS feature it would appear.
