### ISSUE TITLE
Getting Spun and Flipping sets your sprite scale to 1.0

### ISSUE THREAD

**Issue by avimour** [Skyrat-SS13/Skyrat-TG#21311]
## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 43b43b8f04](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#20792: 'Re-adds MCR cell swapping' by Gandalf2k15 at commit 714600875f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
[#20576: '[Like 99% Modular] Soulcatchers' by softcerv at commit d14afbab56](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
[#20696: 'Clockwork Cult: Research' by Zonespace27 at commit 9e2778b1bf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20696)

## Reproduction:

If you get spun by an admin and decide to flip while being spun and fumble the flip, your sprite gets set to 1.0 and it doesn't get fixed with an aheal or the SAD. Very weird bug. Only modify size fixes it.

1. Get spun by an admin.
2. Flip while being spun, possibly mess up said flip.
3. Observe

**Comment by vinylspiders** [comment]
That is weird, I'm guessing one of those things is resetting the transform matrix.

Does it only happen if you fail to flip? Or does it do it on success too? Also, if possible can you find out what the admin did to make you spin? There are a number of things that can make you spin. I was trying to reproduce it and just wasn't able to.

**Comment by avimour** [comment]
The admin was Sciamach, and it does it without the flipping actually. Once the spinning is removed it just resets the sprite to 1.0 for some reason. It's very weird, honestly!

**Comment by sciira** [comment]
Okay I got the cause of the issue wrong: Its the "stop all animations" VV dropdown option

when doing so, any characters with their body size modified in prefs get set back to the default 1.0

Is this intended behavior for this function?

Also: Issue title probably needs to be modified, Im not sure Avi even knew I was using the stop animation function so that's my b for not communicating that.

**Comment by Zonespace27** [comment]
"Stop All Animations" stops any currrent `animate()` in addition to nulling your `transform`, which is what the sprite scale uses to modify a sprite's height.

**Comment by vinylspiders** [comment]
> "Stop All Animations" stops any currrent `animate()` in addition to nulling your `transform`, which is what the sprite scale uses to modify a sprite's height.

Ahh thought it was something like this, but I couldn't find the proc that was actually doing it. Will have a fix once I get home
