### ISSUE TITLE
Can't hide moth wings using ModSuit function to hide mutant parts.

### ISSUE THREAD

**Issue by Nonplayer775** [Skyrat-SS13/Skyrat-TG#21363]
If you wear a modsuit as moth and want to hide moth wings you click the button to do so visibly the wings don't get hidden. Antennas work fine but with wings you can't hide them, been an issue ever since I believe the refactoring of mutant parts. Also wearing spacesuits or other covering clothing items it seems to not hide the wings at all by default making them clip through.

**Comment by vinylspiders** [comment]
@GoldenAlpharex

**Comment by YakumoChen** [comment]
I think this is intended so moth players can see their wings all the time?

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/pull/60142
