### ISSUE TITLE
Detective's holster

### ISSUE THREAD

**Issue by FeenieRU** [Skyrat-SS13/Skyrat-TG#21381]
## Round ID:
--

## Testmerges:
idk

## Reproduction:
Empty your holster. If you did that - congratulations! You can't put speed loaders in holster, buuuuuuut! You can put pistols and make peace'n'democracy in green alert!

![изображение](https://github.com/Skyrat-SS13/Skyrat-tg/assets/62373791/f7993f2f-a15e-45fa-b27c-8ecf6ef4e636)

**Comment by YakumoChen** [comment]
Follow the format, this isn't a shitposting forum

The title needs to summarise the issue, and the description needs to have detail and steps to reproduce, preferably with screenshots.

**Comment by FeenieRU** [comment]
> Empty your holster.

> You can't put speed loaders in holster

> You can put pistols

**Comment by FeenieRU** [comment]
![изображение](https://github.com/Skyrat-SS13/Skyrat-tg/assets/62373791/8fc3d94f-f985-4b64-ba22-d116a8765b5f)
![изображение](https://github.com/Skyrat-SS13/Skyrat-tg/assets/62373791/00aa5980-f40d-40b5-8d37-a8097ea7af9d)
![изображение](https://github.com/Skyrat-SS13/Skyrat-tg/assets/62373791/4571b7d9-a9dc-4798-80a1-e43f0125a6b7)
![изображение](https://github.com/Skyrat-SS13/Skyrat-tg/assets/62373791/f3d8cfe9-fb22-4fad-8b86-22f1b0fbd842)

**Comment by YakumoChen** [comment]
The holster is intended to hold multiple types of pistols. The ammo issue will need investigating.

**Comment by FeenieRU** [comment]
> The holster is intended to hold multiple types of pistols. The ammo issue will need investigating.

Multiple types of pistols is not the problem. I think, _**four**_ pistols shouldn't fit in one holster.

**Comment by YakumoChen** [comment]
You have not indicated or shown the number of pistols that can be contained to be an issue

**Comment by YakumoChen** [comment]
Regardless of the UI the holster is coded to hold a maximum of three items, so you will have to prove it can hold four. Given it doesn't discriminate between ammo or gun (disregarding the ammo issue), holding several guns would be intended behaviour.

**Comment by ghost** [comment]
This isn't a professional bug-writing application, let them have fun and stop being a toxic ass. That's how you get people to NOT make bug reports. The bug was plenty easy to understand from the meme alone.

The title could have been more helpful, but said the exact item with the issue at least (something lots of bugs dont)
@FeenieRU Thank you for the report, and I personally think the meme was hilarious.

**Comment by vinylspiders** [comment]
I'm going to go ahead and preemptively close this one as a fix is up in #21386 . 

Thanks for fixing it, and remember you can link the PR so it auto-closes by doing "Fixes" before the issue #!
