### ISSUE TITLE
Soda Synthesizer Output

### ISSUE THREAD

**Issue by trazodont** [Skyrat-SS13/Skyrat-TG#21420]
Reporting client version: 514.1589

## Round ID:
8482

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
- [TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
- [[MIRROR] JSON Logging Take Two [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21329)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)

## Reproduction:

Essentially the soda synthesizers that come from the service plumbing tool have a weird output issue compared to the medical plumbing tool. When using the medical plumbing tool for botany, realistically you only need two/three chemical synthesizers with +5 water to keep the botany trays full of water for a whole round, even when the trays get upgraded by science. But when using the soda synthesizers from the service plumber, they struggle to output water at +5 and having **7** of them laid down is still not enough to feed the trays, which makes no sense.  

The picture included has **7** soda synthesizers, all connected to the plumbing and trays and yet, there are still trays struggling for water.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/97755577/a639d146-3f03-41cd-a87c-2cdc67910cce)

**Comment by YakumoChen** [comment]
send this upstream
