### ISSUE TITLE
There is no bolting sound when the corresponding button is pressed

### ISSUE THREAD

**Issue by AyIong** [Skyrat-SS13/Skyrat-TG#21510]
## Round ID:
LocalHost

## Reproduction:
Press the bolt control button. 

<details>
<summary>Video (With sound)</summary>

https://github.com/Skyrat-SS13/Skyrat13/assets/69762909/b7cbbfbd-827f-4a4b-aebf-ad97caa54f4b

**Comment by out-of-phaze** [comment]
Upstream issue, fix coming soon.
