### ISSUE TITLE
Green Ungenerated Turf on Icemoon + Telecomms Syndie Agent Improperly Mapped

### ISSUE THREAD

**Issue by John-Dang** [Skyrat-SS13/Skyrat-TG#21595]
Reporting client version: 514.1589

## Round ID:
8536

Hey so, I was in the icemoon map, blasting the rocks inside the runed metal giant box, and I hit gibbonite. It blew up and blew up the cult airlocks, leaving green ungenerated turf tiles below. I think the engraved floor tiles blew up really hard and the game didn't know what to replace them with, maybe? Also the telecomms syndicate agent ruin map is broken, both versions of it. the airlock needs to be nudged 1 tile east for both of them, its improperly mapped. Thought I'd include that too.

<img width="914" alt="image" src="https://github.com/Skyrat-SS13/Skyrat-tg/assets/38540951/6fba8737-7996-4339-951e-8804f4e1b6a6">

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [[Semi-modular] (The big) Akula species revamp](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
- [[SEMI-MODULAR] Ports config-based flavor text requirements from TaleStation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21063)
- [[SEMI-MODULAR] [TEST MERGE ONLY] General baton rework 2: Electric Boogaloo, batons-don't-suck edition (Now with OVERCLOCKING)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20893)

## Reproduction:
Go to icemoon, go to the boxed in piece of lavaland that has "the last dragon" in the middle of it. This particular one had no tendrils or anything, a few goliaths around it and just the boxed up dragon. Blow up gibbonite near the cult airlocks and blow them up.

**Comment by Jolly-66** [comment]
This is a base /tg/ issue with multi-z maps unable to assume a base turf in some situations, more commonly seen on the bottom most layer.
