### ISSUE TITLE
Detective holsters can't hold ammo

### ISSUE THREAD

**Issue by BriareosBlue** [Skyrat-SS13/Skyrat-TG#21613]
Reporting client version: 514.1589

## Round ID:
8559

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [[Semi-modular] (The big) Akula species revamp](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
- [[SEMI-MODULAR] Ports config-based flavor text requirements from TaleStation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21063)
- [[SEMI-MODULAR] [TEST MERGE ONLY] General baton rework 2: Electric Boogaloo, batons-don't-suck edition (Now with OVERCLOCKING)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20893)

## Reproduction:
Upon removing the speedloaders from the detective holster, they cannot be put back into the holster. It only seems to be able to carry pistols.

![ss (2023-06-04 at 01 17 24)](https://github.com/Skyrat-SS13/Skyrat-tg/assets/119547987/9a857d7c-0082-4be1-8d94-52b7d4a7e185)
![ss (2023-06-04 at 01 17 49)](https://github.com/Skyrat-SS13/Skyrat-tg/assets/119547987/ddccaaa6-87fd-479e-91eb-356eb3023e96)

**Comment by vinylspiders** [comment]
There is a fix for this already, it just has not been merged and updated to the server yet. 

See [https://github.com/Skyrat-SS13/Skyrat-tg/issues/21613](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21386)
