### ISSUE TITLE
IPC screens cannot be changed in-game via ability

### ISSUE THREAD

**Issue by SylvaraWasTaken** [Skyrat-SS13/Skyrat-TG#21685]
## Round ID: 
8578

## Testmerges: 
[Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
[TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
[[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
[[Semi-modular] (The big) Akula species revamp](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
[[SEMI-MODULAR] Ports config-based flavor text requirements from TaleStation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21063)
[[s] Custom away mission code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21682)

## Reproduction:
1. Select Synthetic Humanoid race, presumably any gender but tested as male
2. select any head appearance, any body appearance
3. select any IPC screen
4. enter the game as character
5. use ability "Screen Change", any option

**Comment by out-of-phaze** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/21702.
