### ISSUE TITLE
Blob is now considered Mold

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2185]
Reporting client version: 513.1538

## Round ID:
[223](https://scrubby.melonmesa.com/round/223)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)

## Reproduction: Become a blob, have great defenses like strong blob tiles, the crew ignores the fact your tiles aren't suppose to be walked over and casually kills your core
In laments term, its come to my attention that Mold tiles and Blob tiles are now considered the same, and it took the worse of the two traits by being walk able over the tiles

**Comment by Weblure** [comment]
#2199 Possible fix?

**Comment by Azarak** [comment]
fixed
