### ISSUE TITLE
Brand Intelligence can Target Icecat Wardrobe

### ISSUE THREAD

**Issue by sqnztb** [Skyrat-SS13/Skyrat-TG#21918]
## Round ID: 8666

See title.  Probably not great that this can be targeted since the station has basically zero chance to stop it.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/28007787/d90dbe66-c2a9-4c5b-a1b0-56c13c7e6bd7)

## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 375f1f67c1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#21296: 'TTS usage check' by Gandalf2k15 at commit 7a7aecd2be](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
[#21360: '[TM] (Maybe) fixes enormous RSC bloat' by AffectedArc07 at commit bb8672d33e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
[#20131: '[Semi-modular] (The big) Akula species revamp' by theOOZ at commit 01f61730d2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
[#21546: 'Increased alcohol/nicotine tolerance' by lessthnthree at commit e542493a70](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21546)
[#21777: '[test] more clarity for rails, make rails take longer to connect' by jjpark-kb at commit 1273b526d7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21777)
[#21708: 'restrict imbuing to ashwalkers & icecats' by jjpark-kb at commit a29140e56d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
[#19908: 'Makes Podpeople Hair Recolorable 3-D: The Revenge' by Nerev4r at commit 0b2661ef69](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19908)

## Reproduction:

I guess spam Brand Intelligence event until it targets this vending machine.

**Comment by tf-4** [comment]
This is an Icebox issue that we don't currently have a solution to down here. Would need fixing upstream. Not a hard fix.
