### ISSUE TITLE
Arrows are Invisible + Can't Forge More

### ISSUE THREAD

**Issue by avimour** [Skyrat-SS13/Skyrat-TG#22267]
## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 375f1f67c1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#21360: '[TM] (Maybe) fixes enormous RSC bloat' by AffectedArc07 at commit bb8672d33e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
[#21708: 'restrict imbuing to ashwalkers & icecats' by jjpark-kb at commit a29140e56d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
[#22045: '(testmerge only) Makes jetpacks work again' by Stonetear at commit bc9eebea54](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22045)
[#21991: '[MIRROR] SPECIES NUKING 2023: Refactors a bunch of species traits into flags for the head bodypart [MDB IGNORE]' by SkyratBot at commit bf9464fe90](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21991)

## Reproduction:

All arrows are invisible & whenever you try to craft more arrows via forging you just end up creating an 'arrow spawner' which gives you bullet casings.

1. Get an arrow somehow.
2. Notice that it's invisible.

&

1. Forge an arrow head
2. Place it on a workbench to finish it.
3. Stare in wonder as you get bullet casings instead.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/92401911/6b210409-9b21-4c4f-8763-baf5e2ab0781)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/92401911/3191c884-9877-4b90-97a6-68fb3d52880e)

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/pull/76565 will fix the invisible arrows.
