### ISSUE TITLE
Milking Machine doesn't collect fluids.

### ISSUE THREAD

**Issue by Drayco84** [Skyrat-SS13/Skyrat-TG#22273]
## Round ID: 8830
Was actually a few days ago, was hoping to give it some more testing but the device needs two players to work/test.

## Testmerges:
[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 375f1f67c1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#21360: '[TM] (Maybe) fixes enormous RSC bloat' by AffectedArc07 at commit bb8672d33e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
[#21708: 'restrict imbuing to ashwalkers & icecats' by jjpark-kb at commit a29140e56d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
[#22045: '(testmerge only) Makes jetpacks work again' by Stonetear at commit bc9eebea54](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22045)
[#21991: '[MIRROR] SPECIES NUKING 2023: Refactors a bunch of species traits into flags for the head bodypart [MDB IGNORE]' by SkyratBot at commit bf9464fe90](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21991)

## Reproduction:
Milking machine doesn't collect any fluids from the character locked inside. Lactation on the character was enabled, character was naked with everything exposed, unable to test male parts but neither breasts nor fem-parts had their fluids collected when those parts were enabled. (Probably should also allow multiple parts to get harvested at once instead of just one or another.) This happened with former chem bottles, beaker, large beaker, and BS beakers in the device.
Also, the UI is overcrowded and the buttons/text are over top of other text.

**Comment by vinylspiders** [comment]
I fixed both of these the other day. Just give it a little bit to get merged and for the server to update. See:

https://github.com/Skyrat-SS13/Skyrat-tg/pull/22222

https://github.com/Skyrat-SS13/Skyrat-tg/pull/22221

**Comment by Drayco84** [comment]
Oh, thank you very much!

**Comment by vinylspiders** [comment]
> Oh, thank you very much!

Welcome!
