### ISSUE TITLE
Camera Failure Event

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2230]
Reporting client version: 513.1539

## Round ID:
[249](https://scrubby.melonmesa.com/round/249)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)

**Comment by tf-4** [comment]
It only breaks a small number of cameras, it's likely just not noticeable. It also doesn't leave an admin log when it runs, in the same manner as space dust.
