### ISSUE TITLE
Detective's revolver reload issue.

### ISSUE THREAD

**Issue by BobertRoberts** [Skyrat-SS13/Skyrat-TG#22316]

**Comment by vinylspiders** [comment]
Confirmed upstream issue

**Comment by Iamgoofball** [comment]
can you link the /tg/ issue report then

**Comment by vinylspiders** [comment]
> can you link the /tg/ issue report then

Had not created it, yet.

**Comment by vinylspiders** [comment]
Fixed https://github.com/Skyrat-SS13/Skyrat-tg/pull/22762
