### ISSUE TITLE
You can suplex people through walls and windows.

### ISSUE THREAD

**Issue by miniusAreas** [Skyrat-SS13/Skyrat-tg#2231]
## Details
You can suplex people into walls and windows. Balance machine broke.

## Reproduction:
Suplex with your back facing a wall. Surprise, person is now inside wall.

**Comment by H0gberg** [comment]
oh no he's found da glitch

**Comment by tf-4** [comment]
this is fixed afaik

**Comment by tf-4** [comment]
> this is fixed afaik

@Funce
