### ISSUE TITLE
Elevators are incorrectly labelled

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-tg#22340]
## Round ID: 
N/A: tested locally

## Testmerges:
N/A

## Reproduction:
The z-levels on Skyrat are offset from the tg version. This has lead to the elevator buttons on the North Star being incorrectly labelled.

i.e. instead of:
-Command (lvl 4)
-Service (lvl 3)
-Medsci (lvl 2)

it has become

-Floor 5 (lvl 4) // Presumably a default descriptor for '5th z-level' on elevator buttons
-Command (lvl 3)
-Medsci (lvl 2)

I believe the same issue also applies to the Tramstation elevators, which are similarly strangely labelled.

**Comment by vinylspiders** [comment]
Duplicate, see https://github.com/Skyrat-SS13/Skyrat-tg/issues/19343
