### ISSUE TITLE
[Feature request] Armor removing kit

### ISSUE THREAD

**Issue by atakiya** [Skyrat-SS13/Skyrat-tg#2234]
Doing this in place for T-StalkerZero

## Description of the feature
Add an item that can remove armor protection classes (see image below) from clothing.
Could be available as a crate bought at cargo.

![image](https://user-images.githubusercontent.com/6952402/102646730-d91ca400-4164-11eb-95ee-53d5a5f572a7.png)

## Reason
Could be used so amor could be worn as a cosmetic item, without being at risk IC or OOC wise for powergaming or similar.

**Comment by Azarak** [comment]
Visual armor should be indicative of protection from damage.
