### ISSUE TITLE
Cryogelidia will permanently freeze you until next round

### ISSUE THREAD

**Issue by Lutowski** [Skyrat-SS13/Skyrat-TG#22392]
## Round ID: 
Uncertain, which I'm aware isn't helpful. 

## Reproduction: 
Try to make cryogelidia repeatedly and have it fail and freeze the tiles around you. The recipe I used was: 
30u Nitrogen
30u Water
Cool to 0k
30u Stable Plasma

Aheals, restarts and coffee or other heating chemicals hasn't fixed it. You're just permanently stuck until the next round. You can still interact with anything nearby you, such as buckling yourself to a chair, but you can't move with WASD. Body temperature was normal during this. I'm not sure what's causing it - if you're stuck in an invisible ice cube, or you're so ridiculously cold that the game can't even register it.

**Comment by xXPawnStarrXx** [comment]
I've just been testing this offline; it's either a serverside issue or an issue caused by a check skipping. It's never lasted longer than the reagents processing time.

**Comment by vinylspiders** [comment]
I also just recently fixed some potential issues with this reagent upstream. Haven't been able to reproduce it either! Either way, it's an upstream issue. Or, was. I think it's fixed now.
