### ISSUE TITLE
New generic Status Readout modsuit module does not properly play death sound

### ISSUE THREAD

**Issue by W4rd3nn** [Skyrat-SS13/Skyrat-TG#22423]
## Testmerges:
#18110 
#21360 
#21708 
#22113 

## Reproduction:
1. Grab dude with modsuit.
2. give them the generic status readout module
3. shoot the fuck out of them until dead
4. cry when there's no dead space flatline sound

My guess is this is an issue with the mirror as it works correctly on TG.

**Comment by vinylspiders** [comment]
This was an upstream bug, fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/22445 . I -just- merged it today.

It may take a couple days to reach the live server.
