### ISSUE TITLE
Crafting Menu Button duplicating

### ISSUE THREAD

**Issue by Samarai** [Skyrat-SS13/Skyrat-TG#22462]
Reporting client version: 514.1589

## Round ID:
8899

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [The Illusive Language Re-Flavor PR ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22113)
- [[IDB IGNORE] [MDB IGNORE] The grand Skyrat un-poojening, AKA Halcyon hates Citadel sprites and old Digitigrade sprites.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20399)

## Reproduction:
After accidentally disconnecting from the game mid-round, I reconnected only to find that my crafting menu button wasn't working. I tried reconnecting, refreshing TGUI, and restarting the game fully multiple times in order to try and fix it. It was only when I shift + right clicked on the button that I saw whatever the fuck is going on here: 

![Screenshot (3859)](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5153958/81eeb80d-2af9-4f97-b3de-02af408bbbae)

I'm not sure if there's some weird combination of the things I did to try and make the menu work again that caused this, or if it will just happen upon reconnecting to the game, but now every time I reconnect to the server a new unusable button is added to the stack.

**Comment by vinylspiders** [comment]
In the meantime while this is sorted out someone in the linked issue said they were able to fix it by enabling fancy tgui in the game prefs.

**Comment by vinylspiders** [comment]
Most likely related to https://github.com/Skyrat-SS13/Skyrat-tg/issues/21932

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22700 Should be fixed now by this. If the issue persists after the server updates please let me know and I'll reopen.
