### ISSUE TITLE
Hemophage Oxygen Loss from Low Blood

### ISSUE THREAD

**Issue by GypsumKobold** [Skyrat-SS13/Skyrat-TG#22468]
## Round ID: 
8900

## Reproduction:
After talking with some hemophage friends of mine, we have done some testing and discovered that hemophages are taking oxygen damage from having low blood.

Testing has shown that low blood warning occurs on a health analyzer at around 84%, or 460ish blood. When this happen, they start taking a minor amount of oxygen damage, but due to how hemophages work, they don't recover this damage naturally and it stacks up really quickly.

Additional testing shows that a hemophage still cannot be choked, and doesn't drown in water. When they pass out from oxygen loss however, another person is unable to perform CPR and will instead simply attempt to shake them.

We have also found that chemicals that heal oxygen damage work in the hemophage to counter the loss from blood.

**Comment by GoldenAlpharex** [comment]
Yeah, I noticed that, it should be fixed soon, bundled in another mirror. Hopefully by tonight.

**Comment by GoldenAlpharex** [comment]
Should be fixed next server update.
