### ISSUE TITLE
All Skyrat-added species don't have preferred tastes

### ISSUE THREAD

**Issue by Samarai** [Skyrat-SS13/Skyrat-TG#22487]
Reporting client version: 514.1589

## Round ID:
8911

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [[MDB IGNORE] The grand Skyrat un-poojening, AKA Halcyon hates Citadel sprites and old Digitigrade sprites.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20399)
- [[s] Custom away mission code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21682)

## Reproduction:
Tin. Anthromorphs don't like raw meat and grains anymore, and every other Skyrat species lacks their preferred food tastes. Almost definitely related to the species trait overhaul/removal.

**Comment by SovietSpaghetti** [comment]
The same applies to roundstart slimes, and basically every other species added by skyrat. I was going to make an issue about the slimes not having preferences but found this.

**Comment by GoldenAlpharex** [comment]
The issue should be coming from using custom tongues.

**Comment by GoldenAlpharex** [comment]
To further comment on this: What I mean by "Custom tongues" is having a tongue that's different from the "Default" option in the "Augments+" tab. If you have "Default" selected, you should be having those liked foods.

Slime tongues were a genuine bug, they just had the wrong tongue set for whatever reason.
