### ISSUE TITLE
Surgical caps delete hair + more

### ISSUE THREAD

**Issue by BlindPoet** [Skyrat-SS13/Skyrat-TG#22489]
The new change to surgical caps does not look good. Not only does it not look like tucked hair, but rather your character being made bald, it also removes elements of your sprite that would not be tucked under a cap; such as large anthro ears, horns, frills and more. This change will simply mean nobody will wear the cap, anymore, with the end result being LESS people wearing appropriate medical garments than there were before. 
![Screenshot 2023-07-16 092604](https://github.com/Skyrat-SS13/Skyrat-tg/assets/115703586/500db21b-2f1a-4ee3-894e-84fe7a1ca1af)
![Screenshot 2023-07-16 092619](https://github.com/Skyrat-SS13/Skyrat-tg/assets/115703586/f486e2a3-5e4f-4cea-8506-2adec169f6ba)
![Screenshot 2023-07-16 092623](https://github.com/Skyrat-SS13/Skyrat-tg/assets/115703586/4baae913-96ac-4db9-922d-30756e47884d)

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22090
