### ISSUE TITLE
Eye Emissives are broken on non-normal sprite sizes

### ISSUE THREAD

**Issue by John-Peppercorn** [Skyrat-SS13/Skyrat-TG#22553]

**Comment by vinylspiders** [comment]
It looks like they're broken on every mob size. The species nuking PRs likely are the culprit...

**Comment by vinylspiders** [comment]
Update: eye emissives working again, unfortunately the scaling issue persists. It's been an issue since before the recent refactors and is a known issue, see: https://github.com/tgstation/tgstation/issues/62442
