### ISSUE TITLE
Weird Smoothbore Disabler Bug

### ISSUE THREAD

**Issue by Nerev4r** [Skyrat-SS13/Skyrat-TG#22605]
## Testmerges:
[#21360: '[TM] (Maybe) fixes enormous RSC bloat' by AffectedArc07 at commit bb8672d33e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
[#21708: 'restrict imbuing to ashwalkers & icecats' by jjpark-kb at commit a29140e56d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
[#22363: '[MANUAL MIRROR] Reworks Duffel Bags (Zippers)' by softcerv at commit 91247557dc](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22363)
[#22326: 'Fixes Hemophages having lungs' by GoldenAlpharex at commit cf60588bf7](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22326)

## Reproduction:

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/f580e2ea-7b35-4a8b-be32-13e1a39f77d5)

I wish I could embed a trollface right now but forreal this is wildly unintended.

**Comment by vinylspiders** [comment]
This is caused by the fact that they are a subtype of disablers, and disablers here get a super-capacity power cell.  https://github.com/Skyrat-SS13/Skyrat-tg/pull/22617
