### ISSUE TITLE
IRS Pirates failed to spawn

### ISSUE THREAD

**Issue by MortoSasye** [Skyrat-SS13/Skyrat-TG#22603]
Reporting client version: 514.1589

## Round ID:
8948

## Testmerges:
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [[MANUAL MIRROR] Reworks Duffel Bags (Zippers)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22363)
- [Fixes Hemophages having lungs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22326)

## Reproduction:

- IRS Report asking for credits to not visit triggers.
- IRS didn't get paid: so deadchat got a popup to join as pirates.
- Wait... keep waiting. The pirates never spawn.

If it helps any, the solar flare event triggered shortly after.

**Comment by Plum-but-gayer** [comment]
Also occurred in round 8963 - same steps for reproduction as above. Warning came up, station didn't pay, ghosts got the popup, then nothing.

**Comment by EmilyFontaine** [comment]
Happened again at the end of round 8966, same circumstances as Plum described. Definitely seems to be a recurring issue.
