### ISSUE TITLE
markings overwrite each other's colors

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#22646]
Reporting client version: 514.1589

## Round ID:
8970

## Testmerges:
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [these are some REAL tentative numbers trust me - ammo material rebalance (mainly for the ammobench)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21934)

## Reproduction:
applying multiple markings on a single limb in the character creator results in some buggy behavior, including markings deleting each other and sharing any changes in color, which makes layering colors on one limb impossible. does not seem to effect torso markings.

ETA: the bug appears to fix itself. I went back to the character creator after writing this and can change marking colors as usual. very bizarre, but similar to the way in which the character creator has been giving mutant instead of skin tones lately. ETA pt 2: and then it broke itself again, lol. lmfao.

**Comment by vinylspiders** [comment]
Have you checked if clearing the byond cache clears this up? (byond client->preferences->game tab)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/cd543a32-3c4c-4fb1-a62f-7378efc6bbd6)
Could be a corrupt cache causing it potentially.

Otherwise this might be related to the species refactors from TG.

**Comment by kittysmooch** [comment]
> Have you checked if clearing the byond cache clears this up? (byond client->preferences->game tab) ![image](https://user-images.githubusercontent.com/13398309/255441471-cd543a32-3c4c-4fb1-a62f-7378efc6bbd6.png) Could be a corrupt cache causing it potentially.
> 
> Otherwise this might be related to the species refactors from TG.

This did work. I'm gonna close this issue unless it crops up again.

**Comment by vinylspiders** [comment]
Glad to hear it!!
