### ISSUE TITLE
.38 revolver still looses capacity with each reload

### ISSUE THREAD

**Issue by okey2365** [Skyrat-SS13/Skyrat-TG#22769]
Reporting client version: 514.1589

## Round ID:
9012

## Testmerges:
- [[SEMI-MODULAR] Roundstart delam panic button](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22145)
- [[MODULAR] Dynamic threat/midround calculation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22409)
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [[MIRROR] Removes TTS voice disable option (Skyrat: Actually makes a functional "None" voice option this time) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22283)
- [[MANUAL MIRROR] Robotic organ and disease improvements](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22631)

## Reproduction:
Reload the 38 multiple times and it starts to lose capacity, I know the PR said it fixed it but it did not

**Comment by vinylspiders** [comment]
Yeah, the fix is not live yet. It was just merged 18 hours ago. Just need to wait to see it pop up in the changelog.

**Comment by okey2365** [comment]
My apologies I thought merged meant it was live, I'll close it when I test it IG

**Comment by vinylspiders** [comment]
No worries!

**Comment by okey2365** [comment]
It's still a bug after the PR was live

**Comment by vinylspiders** [comment]
Grrr. It should be fixed for real now after the linked PR goes live.

**Comment by okey2365** [comment]
thanks for the quick fix
