### ISSUE TITLE
Deviant tastes on humanoid characther gives disgusts to almost all foods

### ISSUE THREAD

**Issue by okey2365** [Skyrat-SS13/Skyrat-TG#22767]
Reporting client version: 514.1589

## Round ID:
9012

## Testmerges:
- [[SEMI-MODULAR] Roundstart delam panic button](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22145)
- [[MODULAR] Dynamic threat/midround calculation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22409)
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [[MIRROR] Removes TTS voice disable option (Skyrat: Actually makes a functional "None" voice option this time) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22283)
- [[MANUAL MIRROR] Robotic organ and disease improvements](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22631)

## Reproduction:
Eating anything but burgers, pizza,  fruit, veggies will give you disgust.

**Comment by vinylspiders** [comment]
Are you using a custom tongue?

https://github.com/Skyrat-SS13/Skyrat-tg/pull/22664

will fix that if so. It's not live yet, though, watch for the changelog.

**Comment by okey2365** [comment]
ah, I'll close this then

**Comment by okey2365** [comment]
Fixed it for humanoid chars too
