### ISSUE TITLE
Bonfires are borked

### ISSUE THREAD

**Issue by John-Peppercorn** [Skyrat-SS13/Skyrat-TG#22779]
Reporting client version: 514.1589

## Round ID:
9017

## Testmerges:
- [[SEMI-MODULAR] Roundstart delam panic button](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22145)
- [[MODULAR] Dynamic threat/midround calculation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22409)
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [[MANUAL MIRROR] Robotic organ and disease improvements](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22631)
- [Hemophagus, The Hemophage Revamp, Part Four: Blood Depravity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22625)
- [[MODULAR] Robust Adult Pref Checking](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22522)
- [[MOSTLY MODULAR] NIFSoft HUDs ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22063)

## Reproduction:

Be on ice moon
Create bonfire
Try to light it
Fail
(Taac even tried varediting one of these bad boys to be on fire, and no dice.)

**Comment by vinylspiders** [comment]
![dreamseeker_CMUGgv2YYr](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/7b54b800-a78e-4ea5-8b9f-09ba071fe34a)

![dreamseeker_JgBDg6NgTG](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/05b73c63-bdce-408d-9fab-960b8f8f26fa)

I am not able to reproduce this...I tried in several different spots on the Icemoon including underground in the caves and on the surface during the new 'Forever Storm' station trait.

**Comment by vinylspiders** [comment]
I am going to assume this is good now, if it's still happening and you can reproduce it just let me know.
