### ISSUE TITLE
Blob spawns on lowpop

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-TG#22797]
## Round ID:
9026

## Testmerges:
N/A

## Reproduction:
This has been a reoccurring issue, and ruined more than one round, especially with blobs that play to win despite the low player count meaning the odds are already stacked in their favour.
1. Have a game with more than 40 players online but less than 40 people alive (or spawned, but dead).
2. Wait for midroll to roll blob based on playercount rather than alive players
3. Witness the station get steamrolled because they don't have the population to fight a blob, especially if it's found late.

**Comment by lessthnthree** [comment]
Dynamic config.
