### ISSUE TITLE
Cargo Tech Jumpsuit seems to have no digigrade version.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#2288]
## Reproduction:

Spawn as a lizard with digigrade legs. Be cargo tech. Jumpsuit gives the `SUIT` state.

**Comment by ghost** [comment]
This has been fixed and no longer shows the `SUIT` state, issue can be closed
https://gyazo.com/89edef727a98b5ba3719259a6e448af7

**Comment by tf-4** [comment]
above
