### ISSUE TITLE
You can hear borg comms from several tiles away, and even through walls. Including Syndicate ones.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#2289]
## Reproduction:

Be like, 3 tiles away from any borg.

**Comment by SpookyTheFox** [comment]
I've noticed that whispers also can be heard from very far away, like 4+ tiles. Borg radio leaking out has always been an issue, lots of traitor AI players do not realize that all their shells will have the syndicate channel by default, and it plays rather loudly for everyone in the room, even if the AI is not controlling that shell.
