### ISSUE TITLE
Corrections officer missing from most security loadout strings

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-TG#22962]
## Testmerges:

Unlikely to be relevant, but;
[#22097: '[MODULAR] Adds the option for missing a limb to the prosthetics menu' by lessthnthree at commit 75a798ce01](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
[#22828: 'Makes certain organs properly unremovable' by GoldenAlpharex at commit e8ac78e582](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22828)
[#22679: 'NRI/CIN Precursor Food Replicator' by Stalkeros2 at commit 2646fef369](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22679)
[#22933: '[MODULAR] Modularized Interlink Loading' by CliffracerX at commit 50f2089b32](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22933)

## Reproduction:

The loadout requirements for the various security gear - for example, the security armband which everyone in the department can get - do not include the corrections officer. This oversight almost certainly comes from the fact the job is a Skyrat special and just never got added. Weirdly, all the guards have their department-wide digs still. Poor COs, no one loves them. 

edit: Alright armband isn't a great example, there's a security deputy one and I'm a blind bimbo, but it's true for uniforms, coats, and so on.

**Comment by ghost** [comment]
Intentional iirc. CO's are not officers and do not need officer gear.

**Comment by Zergspower** [comment]
i see no issue with them getting an armband so probably oversight no one decided to address, i'd make a PR if you'd wish to see em added
