### ISSUE TITLE
Arrows disappear after firing

### ISSUE THREAD

**Issue by Azlier** [Skyrat-SS13/Skyrat-TG#23103]
Reporting client version: 514.1589

## Round ID:
9141

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)

## Reproduction:

Fire an arrow at a simple mob, a wall, an object, just about anything really. It will strike, then promptly vanish from reality without dropping to be reused. This defeats the point of a bow and arrow completely in addition to making no logical sense. Life as an ash walker or ice cat is now even more difficult than it was before.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/23217 Fixed here, when the server updates this will be fixed
