### ISSUE TITLE
Manifold Progresses Even During Death

### ISSUE THREAD

**Issue by lowpowermia** [Skyrat-SS13/Skyrat-TG#23107]
Reporting client version: 514.1589

## Round ID:
9141

## Reproduction:

Be Manifold Sickness Type Beat

Die

Be dead, get slowly treated for Death.

Disease progresses unto stage 5, where they get erased from the timeline.

No Profit!

**Comment by vinylspiders** [comment]
Not a bug I'm afraid. 

https://github.com/Skyrat-SS13/Skyrat-tg/blob/f3d75f907078887ff9ce9aadd00656ad3498f173/code/datums/diseases/chronic_illness.dm#L8

This is one of those diseases that intentionally keeps progressing regardless of your living status. You can try proposing a change to that line upstream if you wish but that's a feature change request.
