### ISSUE TITLE
Interlink Double Door hitbox and visuals opposite ways

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#23145]
Reporting client version: 514.1589

## Round ID:
9164

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [SQL-Based Player Ranks and Player Ranks Subsystem](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)

Related to https://github.com/tgstation/tgstation/pull/77537 and/or https://github.com/Skyrat-SS13/Skyrat-tg/pull/22933

## Reproduction:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/40c84f64-a2a9-4c1d-9d6a-4fb470b8d71c)
Image shows the interlink door to the smokes room. Double door appears to be visually vertical, but in function it is horizontal. The lower tile of the door and the tile to the right of it are both door tiles. Bumping into one _or clicking it_ visually opens the door, and allows passage on both tiles.
The north tile of the visual door is solid and cannot be passed while the door is closed. Walking into it blocks your movement, like it were a wall, and clicking on it does not open the door. When the door is open, however, that tile is passable.

**Comment by vinylspiders** [comment]
Fixed (see linked PR)
