### ISSUE TITLE
Birdshot Turbine Failure

### ISSUE THREAD

**Issue by Abureaucrat** [Skyrat-SS13/Skyrat-TG#23200]
Reporting client version: 514.1589

## Round ID:
9186

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [SQL-Based Player Ranks and Player Ranks Subsystem](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)
- [NRI/CIN Precursor Food Replicator](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22679)

## Reproduction:
Trying to use the standard turbine setup on Birdshot results in zero RPM regardless of input. Nothing seemed to make it work, so it is my guess that it may be a mapping issue of some sort.

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/issues/75590 Probably related
