### ISSUE TITLE
GAGS Accessories from the loadout do not get their greyscale colors applied correctly

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#23214]
## Round ID:
9198

## Testmerges:
[#22097: '[MODULAR] Adds the option for missing a limb to the prosthetics menu' by lessthnthree at commit 34bc88e2e6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
[#23099: 'SQL-Based Player Ranks and Player Ranks Subsystem' by GoldenAlpharex at commit 92e3cbb1a9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)
[#22679: 'NRI/CIN Precursor Food Replicator' by Stalkeros2 at commit 7ed5ab1811](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22679)

## Reproduction:
Equip an accessory with greyscale in the loadout
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/76465278/edc5315d-74b4-4f40-b740-672785884e2d)

Spawn with that loadout
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/76465278/7655b723-5690-4a40-856e-8df811bdaade)

---
_If I had to hazard a guess, something about accessories being **attached** to the uniform probably makes the loadout code really upset._

---

**Comment by vinylspiders** [comment]
Oh so it's only accessories? interesting
