### ISSUE TITLE
Fluid Ducts are broken for hydroponic trays

### ISSUE THREAD

**Issue by Rvali** [Skyrat-SS13/Skyrat-TG#23224]
Reporting client version: 514.1589

## Round ID:
9207

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [SQL-Based Player Ranks and Player Ranks Subsystem](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)
- [NRI/CIN Precursor Food Replicator](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22679)

## Reproduction:

Fluid Ducts are broken with the chemistry plumbing gun, and all other guns as well. They will not connect to hydroponic trays.

You just simply need to put the pipe down and they will not connect even if the orination is correct.

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/issues/77795 Known upstream issue

**Comment by vinylspiders** [comment]
Should be fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/23241 on next update

**Comment by vinylspiders** [comment]
Is this fixed now?
