### ISSUE TITLE
Arrows are qdeleted at point blank

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-TG#23259]
## Round ID: 
9221

## Testmerges:
N/A

## Reproduction:
1. Acquire a bow.
2. Knock an arrow and draw back the string.
3. Fire at something (wall, mob, doesn't matter) at point black range. (Adjacent tile.)
4. Watch as your arrow vanishes into nothing.

**Comment by Elli-Skala** [comment]
Known TG issue dealing with imbeds

**Comment by Quink-Fix** [comment]
Upstream moment
