### ISSUE TITLE
Ashen arrows (and presumably bronze arrows) don't apply extra damage to some fauna

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-TG#23260]
## Round ID: 
9221

## Testmerges:
N/A

## Reproduction:
1. Acquire a bow, some regular arrows, and some ashen arrows.
2. Fire regular arrows at a legion; it takes 2 to kill it.
3. Fire ashen arrows at a legion; it takes 1 to kill it. This is standard behavior.
4. However, fire regular arrows at a watcher; it dies in about 4-5 arrows.
5. Fire ashen arrows at a watcher, and it takes around 10!
This renders ashen arrows largely obsolete and is not the intended behavior of the ammunition.

**Comment by Elli-Skala** [comment]
100% from the mobs going from simple to basic mobs

**Comment by vinylspiders** [comment]
> 100% from the mobs going from simple to basic mobs

Yep! You are correct

**Comment by vinylspiders** [comment]
Fix is up for this, however another upstream bug with arrows (all kinds, not just ashen ones) now exists. Hopefully a fix will come for that soon.

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/issues/77893 The mentioned unrelated issue.
