### ISSUE TITLE
Unable to Order MK-58 Magazine reloads.

### ISSUE THREAD

**Issue by Drayco84** [Skyrat-SS13/Skyrat-TG#23289]
## Testmerges:
[#22097: '[MODULAR] Adds the option for missing a limb to the prosthetics menu' by lessthnthree at commit 34bc88e2e6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
[#23099: 'SQL-Based Player Ranks and Player Ranks Subsystem' by GoldenAlpharex at commit 92e3cbb1a9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)
[#23244: 'Guncargo 2023 : I love the free market : No interest, no buying companies, no money down! : Cheaper literally everything' by Paxilmaniac at commit 40f131b9f0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23244)
[#23050: '[IT'S READY NOW!] [MODULAR] Razor Claws Augment' by Nerev4r at commit 50099b9811](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23050)

## Reproduction:
Neither of the MK-58 magazines are available from the Nanotrasen-Bolt Personal Defense Coalition store/menu despite the pistol itself being available from there, only the standard .45 and GK-17 lethal and non-lethal.

**Comment by ghost** [comment]
Dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/23338
