### ISSUE TITLE
MK-58 Magazines cannot be purchased from Bolt Defense

### ISSUE THREAD

**Issue by Samarai** [Skyrat-SS13/Skyrat-TG#23338]
Reporting client version: 514.1589

## Round ID:
9253

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [SQL-Based Player Ranks and Player Ranks Subsystem](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23099)
- [Guncargo 2023 : I love the free market : No interest, no buying companies, no money down! : Cheaper literally everything](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23244)
- [[IT'S READY NOW!] [MODULAR] Razor Claws Augment](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23050)

## Reproduction:
Tin. You can buy a MK-58 from Bolt Defense in the Company Imports section, but you cannot buy more MK-58 magazines than the one loaded in the gun. Considering extra magazines can be purchased for the GK-17, and they do not fit in the MK-58 (despite the mags having identical calibers and identical sprites, making me wonder why the MK-58 is even purchasable), this is probably not intended.

**Comment by Paxilmaniac** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/dd060880-f6f7-4e69-8a39-98c8d29acdba)
I forgot to add something onto the path at the end which results in them not showing up and getting overriden by eachother and then the 1911 magazine. It'll be fixed whenever the testmerge is next updated.
