### ISSUE TITLE
Sickle Nul Rods aren't sharp(?)

### ISSUE THREAD

**Issue by Mufi87** [Skyrat-SS13/Skyrat-TG#23410]
Reporting client version: 514.1589
Round ID: 9282
Issue: The Chaplain Sickle Nul rods (both) are unable to butcher, cut or be sharpened. Issue been present since around the respriting and addition of new nul rods.(sorry for the late report)
Reproduction: Simply select one of the two sickles to test for yourself.

**Comment by vinylspiders** [comment]
Are you talking about these? https://github.com/Skyrat-SS13/Skyrat-tg/pull/4885

They have never been able to do that. But they should. I'll make a PR for it.
