### ISSUE TITLE
Synthetic Humanoids and the Razor claws Augument cannot recharge at all.

### ISSUE THREAD

**Issue by GLDoS** [Skyrat-SS13/Skyrat-TG#23456]
## Testmerges:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/23050

## Reproduction: 

Be a Synthetic Humanoid.

Get the dual 8 point claws of death from the augments+ menu.

Spawn in.

Suddenly you lack the ability to recharge at any recharging station or Using the port to connect to an APC.

Proceed to struggle as you can't walk at max speed, Or do much of anything.

**Comment by Nerev4r** [comment]
you can recharge off welding fuel/plasma

**Comment by ghost** [comment]
Do the claws remove the charging cable implant? Is that intended?

**Comment by GLDoS** [comment]
Seems so. I don't think it IS intended, However, It can be annoying at times, Seeing as that's the easiest way to recharge, Without /eating/ something. Probably ruins some characters that don't really 'eat' things.

**Comment by Zergspower** [comment]
If you choose to override your charging port with an augment that's kinda on you - this really isnt an issue as you can drink welding fuel for food. Keep it to 1 claw and you'd be fine probably
