### ISSUE TITLE
Hearthkin/Ice Cats Ættmál

### ISSUE THREAD

**Issue by Asternox** [Skyrat-SS13/Skyrat-TG#23575]
## Reproduction:
Ever since the hearthkin got uncommon language replaced with Siik'tajr, language issues started to arise.(Most lack the main language Ættmál ) Some ice cats have uncommon and Siik'tajr. Some have only Ættmál , in other cases some have only Siik'tajr. Supposedly it has to be Ættmál  (Main language) and Siik'tajr (secondary/ trade language).

**Comment by MortoSasye** [comment]
Still bugged!
