### ISSUE TITLE
Chemical Grinder eats materials, does not produce

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#23749]
Reporting client version: 514.1589

## Round ID:
9428

## Testmerges:
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [Adds the ability to make calls from outside the server to modify player ranks live](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23521)
- [[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)
- [[MIRROR] [TEST-MERGE FIRST] Wound refactor number two: Full synthetic support [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23601)
- [[FOR A TEST-MERGE] Fix muscle scars causing "general disfigurement"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23630)

## Reproduction:

Use Science plumber to make a Chemical Grinder, wrench it down.
Throw a sheet of Plasma into it (from the direction it accepts input, Throw the sheet at or past the grinder.)
Expected: the plasma sheet disappears, the grinder has 20 units of liquid inside.
Observed: the plasma sheet disappears, the grinder has 0 units of liquid inside.

Test the above with Iron sheets too, because that's also supposed to grind and be liquid.

also while you're in there, the description of the Chemical Grinder, when examined, is just "chemical grinder." so that's 2 for 1.

**Comment by vinylspiders** [comment]
I believe https://github.com/Skyrat-SS13/Skyrat-tg/pull/23760 fixes this, can you confirm once the server has been updated with it?

**Comment by vinylspiders** [comment]
I'm just going to assume the lack of reply means it's probably fixed
