### ISSUE TITLE
Tower-Cap is bugged af

### ISSUE THREAD

**Issue by trazodont** [Skyrat-SS13/Skyrat-TG#23770]
Reporting client version: 514.1589

## Round ID:
9435

## Testmerges:
- [Adds the ability to make calls from outside the server to modify player ranks live](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23521)
- [[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)

## Reproduction:

Just place some tower-cap in a botany tray and watch it. When you harvest it without adding perennial growth to it, it will stay active in the tray, you can harvest it as many times as you want, the sprite will appear black (i think this is specific to multi-z level maps as the first time I saw this was on North Star, the same happened on Delta station but it did not have the solid black sprite). You cannot pick up the harvested logs unless you drop other things on it and pick it up in a plant bag, you cannot grab it from the plant bag, you cannot get it in your hand at all. You can dig it up, oitherwise, it doesnt work.

**Comment by trazodont** [comment]
Additionally, it seems this also affect bamboo.

**Comment by trazodont** [comment]
FURTHER update, shrubs also affected :)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/97755577/d892e659-7d24-43b5-80f8-994681634b4d)

**Comment by vinylspiders** [comment]
Known upstream bug

**Comment by vinylspiders** [comment]
https://github.com/tgstation/tgstation/issues/78375

**Comment by vinylspiders** [comment]
Should be fixed now, if there are still issues let me know
