### ISSUE TITLE
RCD Directionals and Grilles

### ISSUE THREAD

**Issue by TripleShades** [Skyrat-SS13/Skyrat-TG#23788]
## Testmerges:
N/A

## Reproduction:
As of https://github.com/Skyrat-SS13/Skyrat-tg/pull/23400 it is impossible to repair any round-start directional window + grille setups (unless it is purely one directional and a grille) with an RCD due to directional windows not accepting grilles as acceptable to be placed on. Additionally, it's also now impossible to RCD multiple directional windows on a single tile.

Steps:
1. Find or try to create a directional window setup such as 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6299921/58dd4aaf-0a1c-408e-8e16-c8de4b1daf36) on the left.
2a. Use your RCD to put down a directional window.
2b. Use your RCD to put down a grille.
3a. Try to use your RCD to place down a grille. You cannot, as the turf is blocked.
3.b Try to use your RCD to place down a directional window. You cannot, and if you alt+click the tile to try and place it down anyways, the turf is blocked.

You can construct a grille manually on the tile that contains the directional window, however this still prevents you from repairing it fully in cases like the example screenshot above.

Solutions:
Revert the QoL of the pr.
Fix the QoL to account for different mapping.
Remap maps that use these window spawners.

**Comment by ghost** [comment]
Upstream issue? They really shouldn't block RCDing windows if they didn't previously... if TG has the same issue it's likely unintended from the PR, if they DON'T have the issue then we've got something weird going on.
