### ISSUE TITLE
Gender/body type based clothing shaping appears to be wonky.

### ISSUE THREAD

**Issue by sergeirocks100** [Skyrat-SS13/Skyrat-TG#23899]
## Round ID: 
I first noticed it on ID 9493, but it's possible that it's been going on for longer.

## Testmerges:

[#23424: '[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related' by Paxilmaniac at commit 938068186f](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)
[#23521: 'Adds the ability to make calls from outside the server to modify player ranks live' by GoldenAlpharex at commit 609132ff94](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23521)
[#23733: '[SEMI-MODULAR] [TEST-MERGE FIRST] Adds synth wounds and resets synth limb damage to 1x, other synth changes' by nikothedude at commit 928dea7d99](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23733)
[#23796: '[MODULAR] Persistent NIFSofts' by softcerv at commit d3ad433d4e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23796)

## Reproduction:

1: Set your body type to something different from the gender default.
2: Watch as the underwear sprites fail to switch to the appropriate variant (IE; A shirt sprite will render with the female gender shaping if your gender is set to female, even if your body type is set to male.).

![Screenshot_90](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31294280/07463062-c115-4afa-94ed-34ea675116fc)

In this screenshot, i have the gender set to female, and the body type set to male. As you can see, chunks of the underlying body are poking through the shirt, because it's using the female sprite shape on the male body.

While i was figuring out things for the report, i also discovered that jumpsuits (and possibly other uniforms with gender-specific shaping) also have buggy gender-specific shaping, and don't work properly if you have digitigrade legs selected (For example, jumpsuits will render their female gender shaping fine if the legs are set to normal, but it reverts to the male shaping if it's set to digitigrade.):

<details>

<summary>Comparison</summary>
Normal:

![Screenshot_91](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31294280/04ab57c5-1217-4d9d-af28-a157e0771306)

Digitigrade:

![Screenshot_92](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31294280/978ba0e4-0086-4f46-8318-4f41f100dd6a)

Both screenshots had the gender set to female, and the body type set to female.
</details>

I've done some testing on /tg/, and i failed to notice either of these bugs, so i believe that these are on the downstream side.

If it matters, my BYOND version is 514.1589.

Apologies if the issue is a little large, i'm willing to split it in two if requested.

**Comment by vinylspiders** [comment]
Half-fixed, see other linked PR

**Comment by RatFromTheJungle** [comment]
@sergeirocks100 jumpsuits don't work with "female_uniform_full" or whatever the equivalent is, because it's applied before(?) or elsewise conflicts with(?) what changes the suit to digitigrade, for reference: try a jumpskirt (female_fitted_top or w/e) then try a jumpsuit, and you can see that the skirt is the only one that changes:

for another EX, on local, you can set everything to female_fitted_full (or w/e it is again) and now nothing will adjust for digigrade

(pinging you mostly for if you wanted to add it to the desc)

**Comment by vinylspiders** [comment]
> @sergeirocks100 jumpsuits don't work with "female_uniform_full" or whatever the equivalent is, because it's applied before(?) or elsewise conflicts with(?) what changes the suit to digitigrade, for reference: try a jumpskirt (female_fitted_top or w/e) then try a jumpsuit, and you can see that the skirt is the only one that changes:
> 
> for another EX, on local, you can set everything to female_fitted_full (or w/e it is again) and now nothing will adjust for digigrade
> 
> (pinging you mostly for if you wanted to add it to the desc)

That is true for upstream (and _was_ for here too)... but I found that with the way our icons (aka, we actually -have- digi icons for most things) are set up we can actually have it both ways. At least far as I can tell...I haven't found any ill effects yet.

![8TnpN86lQm](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/f0c8a718-25de-47ac-93a4-2221a455587d)

![7Bf4MruRV4](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/6983fc3c-f67a-47a6-aafe-136c799b34e0)

See https://github.com/Skyrat-SS13/Skyrat-tg/pull/23988 .
