### ISSUE TITLE
fire chaplains are doused!

### ISSUE THREAD

**Issue by Rad-Paperstock** [Skyrat-SS13/Skyrat-TG#23929]
## Reproduction:

So the sect of the pyre for the chaplain's Alter of Gods is not accepting lit candles for faith anymore. Ya just burn the alter, and not in a holy way! You can try this too, just pick the pyre path for the alter of the gods as a chaplain and watch as the gods refuse your offerings of lit red candles. Truly this is the dark times of our faith... May Space Jesus be merciful upon us.

**Comment by vinylspiders** [comment]
I think this should be fixed by https://github.com/tgstation/tgstation/pull/78542, which I am just noticing hasn't gone through yet. So just wait for that for the time being.

**Comment by vinylspiders** [comment]
Is this fixed?
