### ISSUE TITLE
Legion Corpse Radio

### ISSUE THREAD

**Issue by TripleShades** [Skyrat-SS13/Skyrat-TG#24008]
Reporting client version: 514.1589

## Round ID:
9523

## Testmerges: N/A but
- [[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)
- [[SEMI-MODULAR] [TEST-MERGE FIRST] Adds synth wounds and resets synth limb damage to 1x, other synth changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23733)
- [[MIRROR] Feature: bitrunner, a new supply role (READY) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23865)
- [[Modular] HotFix for Crew Monitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24006)

## Reproduction:
Fight a Legion (regular fauna.)
Die/become crit.
Become subsumed by a Legion (regular fauna.)
Wait for them to talk over Radio because oooh new mechanic.
Become filled with despair because it isn't working.
Cry.

As of https://github.com/Skyrat-SS13/Skyrat-tg/pull/23964 Legion have a new mechanic introduced that allows them to use the consumed corpse's radio to be spooky over while it holds onto you.
I have been told that, because of Skyrat-specific code, this is not possible due to needing hands to use your radio.
As you are very very dead/incapacitated during this state, and Legion do not have hands (that I know of), neither of these allow for it to do so.

**Comment by nikothedude** [comment]
IIIIIIIIIII dont think this is true. AT all. I tested it locally. They speak over radio. Its very cool.

**Comment by ghost** [comment]
Worth investigating even if it's not 100% - there might be a case in code in which Legion still has something keeping the radio blocked.

**Comment by TripleShades** [comment]
Closing because it resolved itself.
