### ISSUE TITLE
Bitrunner den on void not connected to power grid

### ISSUE THREAD

**Issue by Thlumyn** [Skyrat-SS13/Skyrat-TG#24007]
Reporting client version: 514.1589

## Round ID:
9523

## Testmerges:
- [[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)
- [[SEMI-MODULAR] [TEST-MERGE FIRST] Adds synth wounds and resets synth limb damage to 1x, other synth changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23733)
- [[MIRROR] Feature: bitrunner, a new supply role (READY) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23865)
- [[Modular] HotFix for Crew Monitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24006)

## Reproduction:

Bitrunner den on void not connected to power grid

**Comment by vinylspiders** [comment]
@Paxilmaniac

**Comment by vinylspiders** [comment]
Update --fix will be included with https://github.com/Skyrat-SS13/Skyrat-tg/pull/23865
