### ISSUE TITLE
Ashwalker respawns don't work

### ISSUE THREAD

**Issue by Quink-Fix** [Skyrat-SS13/Skyrat-TG#24107]
## Round ID:
9567

## Testmerges:
#23424 
#23733 
#24051 

## Reproduction:
#24028 supposedly fixed sacrifices, allowing Ashwalkers to gain respawns by sacrificing bodies - but unless this is limited to player bodies, which I couldn't confirm, this mechanic does not work in practice.

1. Sacrifice fauna/legion corpses
2. Nothing happens (save for the body being gibbed and its various organs/drops liberated, as well as eggs being produced)

**Comment by vinylspiders** [comment]
It's supposed to be a 40% chance to get your respawn back according to the code, how many times did you try it?

The other thought I had is it looks like it uses the `fingerprintslast` of the mob being sacrificed to identify the sacrificer as a member of the ashwalkers. 

Were you wearing gloves or something? Or maybe for some other reason your prints were not added.

**Comment by Quink-Fix** [comment]
After having it explained and testing locally, it seems to be working as intended. Apologies for jumping to conclusions!
