### ISSUE TITLE
the personal space quirk does not work 

### ISSUE THREAD

**Issue by zeratino** [Skyrat-SS13/Skyrat-TG#24186]
## Testmerges:[#24058: 'Cargo Engineering Content Part 1 | My little machines that go wwwhrhhhr | Die of CO2 poisoning' by Paxilmaniac at commit 447f885e2e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24058)
[#24068: 'URL Clickabillity. OOC Notes/Flavor Text/Species lore' by AnywayFarus at commit 2da0af6ca6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
[#23604: '[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]' by W4rd3nn at commit d78008cb3e](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)

## Reproduction: put on the personal space quirk, which is supposed to prevent ass slapping

have someone slap your ass anyways

**Comment by nikothedude** [comment]
If you were handcuffed or unconcious, it doesn't work, so that could be why

**Comment by nikothedude** [comment]
yeah it works for me

**Comment by zeratino** [comment]
fucked up, i was handcuffed yes
