### ISSUE TITLE
Sec IDs are missing trimline and job icon background colors

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#24201]
Title. Simple to fix, really.

Compare to other IDs.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/70232195/ebe1181e-db2b-4c54-9ebf-a03f2293f05d)

**Comment by ghost** [comment]
Likely caused by us having overrides for Security.... oh boy.

**Comment by ghost** [comment]
Found it. The sec blue sprites were silently removed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/24128, leaving their gray backgrounds (It was blue on gray before)
