### ISSUE TITLE
blueshift aux base doors don't use aux base access

### ISSUE THREAD

**Issue by Paxilmaniac** [Skyrat-SS13/Skyrat-TG#24237]
## Reproduction:
Be a job like curator that's supposed to have aux base access
Try to get in
Fish fail . mp4

**Comment by W4rd3nn** [comment]
boowomp

**Comment by W4rd3nn** [comment]
teehee it used construction access. so silly. This is fixed now with the latest push

**Comment by vinylspiders** [comment]
Resolved so I will close this!
