### ISSUE TITLE
xenoslime hybrids can't speak slime

### ISSUE THREAD

**Issue by dankmemerino147** [Skyrat-SS13/Skyrat-tg#2424]
## Round ID:

[382](https://scrubby.melonmesa.com/round/382) when noticed

## Reproduction:

step 1: play slime
step 2: open language menu
step 3: see "Slime: Can understand. Cannot speak."

**Comment by tf-4** [comment]
@Funce Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/3598
