### ISSUE TITLE
recolorable Maid Outfits  [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-TG#24265]
none of the maid outfits have any form of recolorability, this being changed would be nice.

**Comment by ghost** [comment]
Resolved by https://github.com/Skyrat-SS13/Skyrat-tg/pull/24566
(Recolorable maid outfit is now in-game! Yippee!)

@vinylspiders Issue is resolved and ready to close out.

**Comment by vinylspiders** [comment]
Thank you for letting me know!
