### ISSUE TITLE
Attempting to defibrillate as a cyborg causes negative effects as if they were synthetic as per #23923

### ISSUE THREAD

**Issue by dekunutkid** [Skyrat-SS13/Skyrat-TG#24271]
## Round ID:
9624

## Testmerges:
#24068
#23604 
#24264

## Reproduction:
As a cyborg, cause the death of a non-human, be it plasmaman, vulpkanin or any of the various other non-human races to whom should not be applied the "this person is synthetic" warning.
Attempt to defibrillate them
Watch as they are given a brain trauma and their "circuitry is overloaded" despite being made of flesh and bone

EDIT: apparently regular defibs work fine.

**Comment by nikothedude** [comment]
pr for reference is https://github.com/Skyrat-SS13/Skyrat-tg/pull/23923

**Comment by nikothedude** [comment]
oh my fucking god how did i fuck this up im so stupid

**Comment by nikothedude** [comment]
i checked user's biotypes instead of the targets maaaaaaaaan
