### ISSUE TITLE
Synthetic tend wounds are missing

### ISSUE THREAD

**Issue by KeptheKobold** [Skyrat-SS13/Skyrat-TG#24293]
## Testmerges:
[#24068: 'URL Clickabillity. OOC Notes/Flavor Text/Species lore' by AnywayFarus at commit 2da0af6ca6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
[#23604: '[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]' by W4rd3nn at commit a5f758c848](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
[#24264: 'Disables pipe gas visuals for now' by vinylspiders at commit 849b6ed3bf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)

## Reproduction:
When going to do surgery on synths, the option for tend wounds is missing from the options, where it normally was. Both of the advanced surgeries were researched and this was done next to a synched operating computer on an Operating table

**Comment by nikothedude** [comment]
i tested this shit wth
