### ISSUE TITLE
Cargo shuttle and bay blast doors failing to work after ID changes

### ISSUE THREAD

**Issue by frostyfen77** [Skyrat-SS13/Skyrat-TG#24301]
## Reproduction:

the blast doors for the cargo shuttle stop working when attempting to change the ID's. screw driver the buttons and doors, use multitool on the button chip and doors, put everything back. the doors will fail to work forever more.

**Comment by vinylspiders** [comment]
This was a known issue upstream which the fix just got merged yesterday. The server could have not been updated yet--can you confirm that it's fixed on the next server update? 

(See: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24294)

**Comment by frostyfen77** [comment]
yes its fixed now, must have just caught it right befor it was pushed out
