### ISSUE TITLE
Interdyne Turret Connection

### ISSUE THREAD

**Issue by TripleShades** [Skyrat-SS13/Skyrat-TG#24306]
Reporting client version: 514.1589

## Round ID:
9636

## Testmerges:
- [URL Clickabillity. OOC Notes/Flavor Text/Species lore](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
- [[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)

## Reproduction:
Go into Interdyne's garden/kitchen area.
Have the funny plasma flower core that spawns butterflies around you.
Notice that the turret is shooting at them, even though you turned all of the turrets off.
Be sad because it's destroying your base and there's no way to turn that turret off because it's not responding to the button.

**Comment by vinylspiders** [comment]
Does it only happen with that one turret? And which Interydyne was it--Lava or Ice?

**Comment by vinylspiders** [comment]
Nevermind, I've found the issue and it's not anything to due with the recent mapping changes.

**Comment by TripleShades** [comment]
> Does it only happen with that one turret? And which Interydyne was it--Lava or Ice?

It was lavadyne, and we had the turrets shut off, so it shouldn't have targeted them in the first place.

**Comment by vinylspiders** [comment]
The turret control settings probably got broken upstream (again). I fixed them before...
I fixed the butterfly targeting issue at any rate as that was a separate issue. Will close this when it arrives here from tgstation.

Sometime in the future I will perhaps see about making a unit test for making sure that the turret controls are being respected
