### ISSUE TITLE
Paper Mask Adjustment

### ISSUE THREAD

**Issue by TripleShades** [Skyrat-SS13/Skyrat-TG#24324]
Reporting client version: 514.1589

## Round ID:
9642

## Testmerges:
- [URL Clickabillity. OOC Notes/Flavor Text/Species lore](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
- [[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)

## Reproduction:
Adjusting a paper mask to go under your hair resets its state if you take it off and put it back on.
1. Put mask on
2. Type adjust-mask into the status bar (because it's not a button for some reason)
3. Mask is adjusted now!
4. Take off the mask and put it back on
5. See that your mask is now over your hair again
6. Go to re-adjust it, but have to do it twice because its state is now incorrect.

**Comment by vinylspiders** [comment]
Were you by any chance playing as a character who has a snout (Top) variety? (such as) 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/49e17a1d-0f42-4bed-888a-2a0a8c836cf0)


Those are set to layer over everything basically so I suspect it's getting messed up by that.

**Comment by TripleShades** [comment]
> Were you by any chance playing as a character who has a snout (Top) variety? (such as) ![image](https://user-images.githubusercontent.com/13398309/275062539-49e17a1d-0f42-4bed-888a-2a0a8c836cf0.png)
> 
> Those are set to layer over everything basically so I suspect it's getting messed up by that.

I do not play as characters with snouts. If it helps, I'm playing as a synth with a human head. The IPC screen option is toggled off as well, so that's not an issue.

**Comment by vinylspiders** [comment]
> > Were you by any chance playing as a character who has a snout (Top) variety? (such as) ![image](https://user-images.githubusercontent.com/13398309/275062539-49e17a1d-0f42-4bed-888a-2a0a8c836cf0.png)
> > Those are set to layer over everything basically so I suspect it's getting messed up by that.
> 
> I do not play as characters with snouts. If it helps, I'm playing as a synth with a human head. The IPC screen option is toggled off as well, so that's not an issue.

Thanks, it does! I'll look into what might be the cause.
