### ISSUE TITLE
Birdboat's Not A Bird

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#24419]
Reporting client version: 514.1589

## Round ID:
9685

## Testmerges:
- [URL Clickabillity. OOC Notes/Flavor Text/Species lore](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)

## Reproduction:
Have Phobia (bird).
See Poly in the corner of your eye, have a panic attack.
Try to say "bird", you are compelled to not.
Hear "bird" over the radio, have a panic attack.

Walk up to Birdboat, the vomiting goose, don't have a panic attack.
Try to say "Birdboat". You can say it.

I get that having phobias not check for partial word matches is to avoid the Penistone problem or whatever, but a) I looked it up, no english word has "bird" in the MIDDLE that isn't actively referring to an avian, and b) just make "birdboat" a bad word too.

**Comment by vinylspiders** [comment]
It is a regex issue--you would have to remove the word boundaries aka the \\b for it to get picked up. Which as you said will introduce another issue.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/6011f9c2-8ff0-41f8-80d2-c2e731994973)

Adding birdboat to the bird phobias list list would be a simple 1 line change upstream if you want to try that.

**Comment by Majkl-J** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25573
