### ISSUE TITLE
Lost the ability to wear anything, or be touched/examined

### ISSUE THREAD

**Issue by Nekosempei** [Skyrat-SS13/Skyrat-TG#24424]
Amira Oliver, during the round, lost all ability to equip anything, and lost the ability to be touched, or examined. Everything else seemed to.. work from a user standpoint. I could grab and hold objects, and relogging to reset the UI didnt fix anything.

## Testmerges:[#24068: 'URL Clickabillity. OOC Notes/Flavor Text/Species lore' by AnywayFarus at commit 2da0af6ca6](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
[#24264: 'Disables pipe gas visuals for now' by vinylspiders at commit 849b6ed3bf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
[#23604: '[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]' by W4rd3nn at commit e6b6c1a37b](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
[#24056: 'Icecat camp but epic!! | Visual updates to stuff that made the before mentioned camp look awful | Hazardously concentrated amounts of :3' by Paxilmaniac at commit 3d57a4ce1c](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24056)
[#24058: 'Cargo Engineering Content Part 1 | My little machines that go wwwhrhhhr | Die of CO2 poisoning' by Paxilmaniac at commit 0960012ea9](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24058)

## Reproduction: I dont know how to reproduce it, specifically, but It seems related to be related to going to lavaland. perhaps legion, or more likely, some kinda hallucigens in the air, and the hallucinations, particularly a new hallucination a berating mother.

Edit: Seems  the issue has been found, and its probably being fixed. Apparently, something about the new mother hallucination taking your species, rather then copying it? I dont have the technical details, but yes, this is now more for documentations sake, I spose.

**Comment by vinylspiders** [comment]
Will be fixed by https://github.com/tgstation/tgstation/pull/79098
