### ISSUE TITLE
Searching people tries to "buckle them" to you.

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-tg#2444]
## Round ID: [392](https://scrubby.melonmesa.com/round/392)
self explanatory
## Testmerges:
#948 #1783 
#2030 #2175 
#1285 #1939 
#2341 #2438 
#2406 #2317 
#2180 

## Reproduction:

Spawn in as a human, spawn another, try to open their inventory, it'll give you a 5s buckling timer, like you're a borg.

**Comment by tf-4** [comment]
this is fixed afaik
