### ISSUE TITLE
Egg-plants broke?

### ISSUE THREAD

**Issue by RedTheChangeling** [Skyrat-SS13/Skyrat-tg#2449]
Reporting client version: 513.1534

## Round ID:
[395](https://scrubby.melonmesa.com/round/395)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[READY] Ghost roles can now be configured to allow people using their prefs character. Allows this for a good chunk of ghosties](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2341)
- [Lowers down and disables some events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2438)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)

**Comment by Owai-Seek** [comment]
Does the plant stop giving them on harvest, or do they like, not work when you peel them? Some chemicals reduce the yield on plants, and some things (when mutated) start with really low yield.

**Comment by tf-4** [comment]
Likely a low yield plant, and nobody else has mentioned it in not far off a year
