### ISSUE TITLE
Kronkaine's bonus lasts indefinitely 

### ISSUE THREAD

**Issue by Samarai** [Skyrat-SS13/Skyrat-TG#24510]
Reporting client version: 514.1589

## Round ID:
9716

## Testmerges:
- [URL Clickabillity. OOC Notes/Flavor Text/Species lore](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
- [Icecat camp but epic!! | Visual updates to stuff that made the before mentioned camp look awful | Hazardously concentrated amounts of :3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24056)
- [Cargo Engineering Content Part 1 | My little machines that go wwwhrhhhr | Die of CO2 poisoning](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24058)

## Reproduction:

- Make Kronkaine (moon rock) from Kronkus Extract (ferment kronkus vine segments in a wooden barrel), Ammonia, and Welding Fuel. 
- Eat moon rock. 
- Observe that even once the kronkaine leaves your system (noticeable as damage to the heart), you still keep the 2x bonus to do-after speed.

**Comment by vinylspiders** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/24964#pullrequestreview-1727096688 , please wait for server update
