### ISSUE TITLE
Usable Crafting Menu Bug

### ISSUE THREAD

**Issue by EpicCharger** [Skyrat-SS13/Skyrat-TG#24511]
Reporting client version: 514.1589

## Round ID:
9716

## Testmerges:
- [URL Clickabillity. OOC Notes/Flavor Text/Species lore](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24068)
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [[READY] [MODULAR] Blueshift wakes up after taking "Worst Nap Ever" [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23604)
- [Icecat camp but epic!! | Visual updates to stuff that made the before mentioned camp look awful | Hazardously concentrated amounts of :3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24056)
- [Cargo Engineering Content Part 1 | My little machines that go wwwhrhhhr | Die of CO2 poisoning](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24058)

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24513

Should be fixed on the next server update
