### ISSUE TITLE
Fireplace smoke coming out in a weird place

### ISSUE THREAD

**Issue by Compu18AI** [Skyrat-SS13/Skyrat-TG#24626]
## Reproduction: Go to ghost cafe, move to the first wooden cabin, go in, bolt the door, go over to the fireplace, throw wood in it, light it, view the smoke coming out of the dresser nearby.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/128428189/86846943-8592-4fe9-b7c8-d4703fbd4c38)

**Comment by vinylspiders** [comment]
Looks like the smoke particles just need to be updated to match the fireplace's direction. It's coming out as if the fireplace were south-facing regardless of how the fireplace is positioned.
