### ISSUE TITLE
Cryo cells in Tramstation not connecting to pipes properly until remade

### ISSUE THREAD

**Issue by Whomstbing** [Skyrat-SS13/Skyrat-TG#24637]

**Comment by Whomstbing** [comment]
Looked around in the issue tracker some more and it seems like someone put in a similar bug report about a month ago for Northstar.

**Comment by lessthnthree** [comment]
Upstream issue. You don't have to reconstruct, but you do need to screwdriver and rotate.

The cryo cell gas connector is always pointing south on mapload. So maps where the pipes aren't south of the cryo cell, it doesn't connect.

https://github.com/tgstation/tgstation/issues/78830
