### ISSUE TITLE
Chat Orbit Link Broken

### ISSUE THREAD

**Issue by TripleShades** [Skyrat-SS13/Skyrat-TG#24652]
Reporting client version: 514.1589

## Round ID:
9783

## Testmerges:
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [Finally puts our stations within compliance of the 1855 passenger act, by introducing a new quirk that gives you ration tickets to get your legally required weekly rations](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24578)
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)

## Reproduction:
Event that prints an orbit link for ghosts to dchat triggers.
Click orbit.
Orbit does not work.
Have to click the graphical button instead to orbit.

**Comment by lessthnthree** [comment]
It's an upstream issue.
