### ISSUE TITLE
Stepping on Liquid plasma rivers as a golem causes limb issues

### ISSUE THREAD

**Issue by Syrox25** [Skyrat-SS13/Skyrat-TG#24714]
Reporting client version: 514.1589

Plasma rivers seem to just melt limbs off of golems... which doesnt seem doable in general.. leading to... odd results..
This is doubly weird as golems are immune to regular lava and can cross it freely

## Round ID:
9801

## Testmerges:
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [Finally puts our stations within compliance of the 1855 passenger act, by introducing a new quirk that gives you ration tickets to get your legally required weekly rations](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24578)
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)

## Reproduction:

Try to walk across Icebox plasma rivers, suffer horrific effects:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/75050485/b2602ae1-c75c-4323-ac44-541a46318293)
(the robo limb was added later, It just deleted the leg at the time)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/75050485/d58b9f63-9fc3-4f3e-975c-4ae11bf50ac1)

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/pull/79249
upstream issue, upstream fix
