### ISSUE TITLE
High Lum eyes do not work anymore

### ISSUE THREAD

**Issue by FlickTee** [Skyrat-SS13/Skyrat-TG#24752]
## Round ID:
9817

## Reproduction:

high luminosity eyes seem to not work at all. Click button to activate-> nothing. The button to customize them works, but the light doesn't actually appear.

**Comment by vinylspiders** [comment]
Not again! It's definitely caused by this:

https://github.com/Skyrat-SS13/Skyrat-tg/pull/24644

I will look into this and see if I can add a unit test upstream so they stop breaking them.
