### ISSUE TITLE
EMP weirdness. Does brain damage, and does not stun mechs.

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#2482]
## Testmerges (If Applicable):
BYOND Version: 513.1527
Server revision compiled on: 
Master commit: 8fb85d877eb2901b4df622c1311c1ed5ba4adb95
The following pull requests are currently test merged:
#948: '[TESTMERGE] Makes icon2html not work' by Azarak at commit a7a3accaf5
#1783: '[DNM] Cryo on core maps [TESTMERGE ONLY]' by KathrinBailey at commit 79ce3f899d
#2030: '[TM] Disables sentient disease - pending rebalancing/tweaks' by Azarak at commit 113ea79ebe
#2175: 'Makes command immune to FAMILIES' by GuppyLaxx at commit eea5c92796
#1285: '[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity' by Azarak at commit c2cf3d03cf
#1939: 'Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes' by Azarak at commit 9aa4e15913
#2341: '[READY] Ghost roles can now be configured to allow people using their prefs character. Allows this for a good chunk of ghosties' by Azarak at commit 7bbfce25c3
#2438: 'Lowers down and disables some events' by Azarak at commit 09666954eb
#2406: '[TM FIRST] Wounds are applied easier on damaged bodyparts' by Azarak at commit af64f9fe6a
#2317: 'Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]' by Gandalf2k15 at commit a742605ac0
#2180: '[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets' by KathrinBailey at commit ea510ef4fe
#2443: '[TM ONLY] Tick test to reduce lag' by Azarak at commit d5ca5d4b85

Local commit: 16bd62a63062dee1b3e2f1b79367d5d4d5c368ca
TGS version: 4.4.1
DMAPI version: 5.2.10

## Reproduction:
Use any normal EMP weapons. Changeling EMP scream is the most obvious and guaranteed situation, but ion guns have been shown to be effected as well. Activating the EMP ability causes brain damage. Mechs take minor to moderate damage, but are not stunned at all when they have teir four parts, which is normal for constructing mechs. This has been demonstrated with the Oddysseus, Gygax, and Durand.

## Possible Screenshots of the Issue in question:

This might very well be some TG weirdness, but EMPs are not behaving as I expect them to right now. I can not find the PR that changed their behavior, if one was made. They seem to be dealing brain damage to organic players, not just synths. They also appear to be unable to stun mechs as they were before. Something similar is happening with ion bolts as well. EMPs are a critical counter for antags facing energy weapons, mechs, people with x-ray eye implants, borgs, etc. They are also foundational to asymmetric warfare.

The sensors on the the paramedic jumpsuit change rapidly!
The medical radio headset overloads.
You feel like your brain is being fried!
You feel lightheaded.
The electromagnetic pulse causes the surgical toolset implant to malfunction!
The flash burns out!

There was also a durand there that just kept stomping and shooting, without a care in the world.
In this instance, I was a changeling, using EMP shriek. The results were laughable. Brain damage to myself, failure to stop the mech shooting at me. Normal traitor I assume has it even worse, as they likely have limited access to medical help.

Earlier today, I was piloting an odysseus that was hit by a handful of ion bolts, with extremely minimal effect. And also recently, I tanked six EMPs as a borg, which seems a little strong for a robot. Something is not working right with EMP effects, weather by accident or design.

**Comment by YakumoChen** [comment]
EMP doesn't stun mechs, it just does fair damage and drains their battery. Stunning was a thing on citadel code, and it only disabled their modules briefly.

As for the brain damage that looks related to your implants?

**Comment by SpookyTheFox** [comment]
This was fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/2856
