### ISSUE TITLE
missing HONK mech "equipment" option

### ISSUE THREAD

**Issue by Insane-Jimmy** [Skyrat-SS13/Skyrat-tg#2492]
Reporting client version: 513.1539

## Round ID: [411](https://scrubby.melonmesa.com/round/411)

![Screenshot_2](https://user-images.githubusercontent.com/76050557/103548464-835b3200-4eae-11eb-8947-d0aa3d32dae4.png)

## Reproduction:
just open the stats tab and an admin told me that there should be an "equipment" option to de-attach things, but its not there.

**Comment by Zergspower** [comment]
Honk mech fxied in a previous issue-fix or over time - weapon detatchment is there and functional now.
