### ISSUE TITLE
Entering and exiting an Odysseyus keeps medhud

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2493]
Reporting client version: 513.1539

## Round ID:
[412](https://scrubby.melonmesa.com/round/412)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[READY] Ghost roles can now be configured to allow people using their prefs character. Allows this for a good chunk of ghosties](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2341)
- [Lowers down and disables some events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2438)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)

**Comment by SpookyTheFox** [comment]
Probably related, getting into and out of a Clarke does the same thing, but with the engineering diagnostic HUD.

**Comment by Funce** [comment]
I remember making a fix for this on the old base. I'll check it out.

**Comment by Funce** [comment]
Seems to be fixed
