### ISSUE TITLE
ai hud buttons are not where the buttons really are

### ISSUE THREAD

**Issue by Syilumi** [Skyrat-SS13/Skyrat-TG#24948]
## Round ID:
none

## Reproduction:
simply be an ai

https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/8e3b1fb8-c8e1-44e6-af09-81be1bf3e7e9

**Comment by Syilumi** [comment]
If not clear I placed my cursor over where the button seems to be and went straight down to where the button actually is

**Comment by vinylspiders** [comment]
That is very odd. The AI HUD is supposed to be where your cursor is, on the bottom.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/77312034-77ab-49f7-9826-30e8af311c86)

![dreamseeker_mIRaFzI1HW](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/c0b4a676-7b69-4dff-8965-5b436b880ef6)

That it's showing up on top for you is really strange. Does it happen every round, or was it just a one off? And are you using any custom UI settings/themes?

As for fixing it, does clearing your byond cache work? (byond client -> gear icon -> game tab -> clear cache)

**Comment by Syilumi** [comment]
happens every round for me i'll try the client thingy

**Comment by Syilumi** [comment]
![Screenshot 2023-11-14 122903](https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/21ad2ce2-aad3-48c4-bd52-091d843550c5)
fresh install and everything and its the same

**Comment by Syilumi** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/b9c3130f-621d-4df0-8b6b-0f3ac8f93103)
codes the same

**Comment by GoldenAlpharex** [comment]
Which version of BYOND are you on?

**Comment by Syilumi** [comment]
the most recent beta

**Comment by Syilumi** [comment]
changed to stable version and it fixed it, sorry for the false report or.. whatever this would be called

**Comment by vinylspiders** [comment]
Glad you were able to figure it out--yeah beta version is generally a no-go for gameplay.
