### ISSUE TITLE
Humanoid Species Errors

### ISSUE THREAD

**Issue by FunkyFetus** [Skyrat-SS13/Skyrat-tg#2497]
Reporting client version: 513.1536

## Round ID: [417](https://scrubby.melonmesa.com/round/417)
417

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [Lowers down and disables some events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2438)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)

Aight so this is pretty straight-forward, the Humanoid species is buggy as fuck.  There's a lot of clothes that either don't appear at all on them (not in the way that relogging can fix).  Often times, things like a durathread helmet for example, will make either one's hair or ears disappear, without actually loading the sprite onto the character.  

Another example as per round 417, is that Tojo clan clothes appear, but not without displaying a big green (and red) SUIT next to the player.  

Also to note, if you're playing a female humanoid, no matter what you're given a male scream.  

![image](https://user-images.githubusercontent.com/76979649/103595682-1190e180-4eca-11eb-9541-d375256d598b.png)

**Comment by Azarak** [comment]
It's an issue with digitigrade legs

**Comment by Azarak** [comment]
or rather, the sprites, and interactions with muzzles and digitigrade legs

**Comment by tf-4** [comment]
@Funce issue is mutant variants not humanoids. This can probably be closed
