### ISSUE TITLE
One Interdyne Crew is listed as Bit Avatar in the orbit menu

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#24991]
Reporting client version: 514.1589

## Round ID:
9907

## Testmerges:
- [Disables pipe gas visuals for now](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24264)
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)

## Reproduction:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/6b98d498-12fe-44ad-a755-9e657aa57681)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/ef327c09-3856-44fb-b5e5-7d1030b0e0d0)

Be ghost, go to Observe. Click the Orbit menu to see the list of folk in the round. See someone spawn at the Interdyne, on Ice Box. One is listed as "Interdyne Crew." Some are "Deck Officer." One, with the ID "Interdyne Crew" is listed as a **Bit Avatar** in the orbit menu.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/4f59d1d0-f7ce-4be6-b77b-8006c523c696)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/925a5f6a-669e-4b8c-b877-ad4ec760c71f)

**Comment by kittysmooch** [comment]
this might be a side effect of their agent ids being able to have any trim

**Comment by Zergspower** [comment]
confirmed this was just the agent ID
