### ISSUE TITLE
Loadout Conflict Between 'In-Hand' Items, and 'Musician' Quirk

### ISSUE THREAD

**Issue by BlindPoet** [Skyrat-SS13/Skyrat-TG#25025]
Reporting client version: 514.1589

## Round ID:
9917

## Reproduction: 
Select an In-Hand loadout item, a skateboard in my case, and the 'musician' quirk.

Due to both the Instrument Delivery Beacon and In-Hand loadout items spawning in the same slot, the former will overwrite the latter. 

I propose simply moving the beacon to the backpack slot, upon spawning.

**Comment by Plum-but-gayer** [comment]
Hi! I just tested this on a private build and I can't seem to reproduce it. It seems that the move to backpack solution has already been implemented. Could you included further steps for production? Perhaps you had enough loadout items in you backpack that your backpack ran out of room? 

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/93c8304d-e00e-4ea5-825a-15bc0d82c327)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/a642367b-8353-41ef-8dfc-ff6a51f76ed1)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/9192c20a-006a-4503-8dfc-a02f254db691)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/409691ec-5eba-496e-9bc1-15c68f42a9ef)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/5b7fd8fa-faa5-4188-8eab-c8bc5e6f44f0)

**Comment by BlindPoet** [comment]
I probably just had too many job items in my backpack, in that case. I tested it just now on assistant and didn't have the problem. My mistake :)
