### ISSUE TITLE
High Luminosity Eyes no longer project light

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#25041]
Reporting client version: 514.1589

## Round ID:
9925

## Testmerges:
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Hemophagus, The Hemophage Revamp, DLC Chapter V: This PR Sucks (Blood)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24903)
- [Gives blueshields a new shoulder-bruising "submachinegun" that fires .585](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24640)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[tm only] disable gutlunch breeding](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25035)

**Comment by vinylspiders** [comment]
Known issue, I have a fix upstream. See https://github.com/Skyrat-SS13/Skyrat-tg/issues/24752 and also https://github.com/tgstation/tgstation/pull/79760 for the fix
