### ISSUE TITLE
Unable to unlock illegal tech 

### ISSUE THREAD

**Issue by AquillaF** [Skyrat-SS13/Skyrat-TG#25057]
Reporting client version: 514.1589

## Round ID:
9930

## Testmerges:
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Hemophagus, The Hemophage Revamp, DLC Chapter V: This PR Sucks (Blood)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24903)
- [Gives blueshields a new shoulder-bruising "submachinegun" that fires .585](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24640)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[tm only] disable gutlunch breeding](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25035)

## Reproduction:
Looks like researching illegal tech is busted. *boowomp*

We unlocked the node with the destructive analyzer, went to research the tech only to be hit with "Node unlock failed: Either no techweb is found, node is already researched or is not available!"

**Comment by vinylspiders** [comment]
Duplicate
