### ISSUE TITLE
Illegal Technology Research Failure 

### ISSUE THREAD

**Issue by annikaRU** [Skyrat-SS13/Skyrat-TG#25058]
Reporting client version: 514.1589

ROUND ID:  9930

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # (It can be found in the Status panel or retrieved from https://sb.atlantaned.space/rounds ! The round id let's us look up valuable information and logs for the round the bug happened.)-->

## Testmerges:
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Hemophagus, The Hemophage Revamp, DLC Chapter V: This PR Sucks (Blood)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24903)
- [Gives blueshields a new shoulder-bruising "submachinegun" that fires .585](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24640)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[tm only] disable gutlunch breeding](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25035)

## Reproduction:

While using a research console, the following message will be said, 

"Node unlock failed: Either no techweb is found, node is already researched or is not available!"

This is produced after you unlock Illegal technology via using the destructive analyzer 

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/f707b697-a1a9-4ec3-8413-369b27dbecb7)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/c930771a-1422-4f3a-8e36-58557e5c30b3)

So far I have been in two rounds where I encountered this error, and from what I have heard has been present

**Comment by vinylspiders** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/5dc109b0-dcbd-4f34-93df-06d21620822d)
I was able to research all of this on the latest build, needs reproduction

**Comment by vinylspiders** [comment]
See also https://github.com/Skyrat-SS13/Skyrat-tg/issues/25057

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25122 Might be fixed by this, once the server updates

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25296 And this if not. Closing for now, just ask to reopen if it's not fixed by the next update
