### ISSUE TITLE
Bitrunning Sim Characters spawn without hands in the sim.

### ISSUE THREAD

**Issue by Kangarad** [Skyrat-SS13/Skyrat-TG#25070]
Reporting client version: 514.1589

## Round ID:
9936

## Testmerges:
- [Remove filter from render plate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24625)
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Hemophagus, The Hemophage Revamp, DLC Chapter V: This PR Sucks (Blood)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24903)
- [Gives blueshields a new shoulder-bruising "submachinegun" that fires .585](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24640)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[tm only] disable gutlunch breeding](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25035)

## Reproduction:
Bitrunners loading into the sim have simulated characters with no hands on all 3 base bitrunning sims as far as I could test. Another few bitrunners found out such too and its a knowng bug according to the admins. This means one can not complete any of the Bitrunning missions.
Rebuilding the machines/changing domain/ hacking the pods all did not help resolve that issue.

**Comment by Thlumyn** [comment]
There's a PR open upstream to fix this issue: https://github.com/tgstation/tgstation/pull/79810

**Comment by Thlumyn** [comment]
And that fix PR was mirrored here: https://github.com/Skyrat-SS13/Skyrat-tg/pull/25072

**Comment by vinylspiders** [comment]
Should be resolved on next server update
