### ISSUE TITLE
Autolathes eat PDAs and IDs

### ISSUE THREAD

**Issue by scrcr0** [Skyrat-SS13/Skyrat-TG#25165]
Reporting client version: 514.1589

## Round ID:
9963

## Testmerges:
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[SEMI-MODULAR] Resonance degradation disorder: The quirk that makes you fear death](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24041)
- [New Derelict Station (Babylon Station 13)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25061)

## Reproduction:

Attempted to use Autolathe in engineering with PDA in hand. Normally, the lathe will reject the PDA and ID and just open the UI. However, on this occasion the lathe happily ate the PDA and ID inside. It showed the rejection message in the chat window, but the ID was destroyed along with the PDA. Admin was able to replace the missing PDA and ID off-station. Later on, by accident, I made the same mistake after warning others not to use autolathes with a PDA in hand. Again, the lathe happily ate the PDA and ID. 

To replicate: 
Approach an autolathe with a PDA and inserted ID in your active hand. 
Click the lathe.
PDA and ID are consumed, UI opens. 

Expected result:
UI should just open. PDA and ID should be rejected by the lathe.

**Comment by lessthnthree** [comment]
Not a bug for the consumption. https://github.com/tgstation/tgstation/issues/69474
Bug is the UI opens.

**Comment by Zergspower** [comment]
Resolved https://github.com/tgstation/tgstation/pull/79847
