### ISSUE TITLE
Void Raptor, Bitrunners can't access the ORM

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25227]
Reporting client version: 514.1589

## Round ID:
9985

## Testmerges:
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[SEMI-MODULAR] Resonance degradation disorder: The quirk that makes you fear death](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24041)
- [New Derelict Station (Babylon Station 13)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25061)

## Reproduction:
Bitrunners do not have access to the door into the mail room, where the ORM is located. 
As per https://github.com/Skyrat-SS13/Skyrat-tg/pull/25224 , they are supposed to have access to the ORM.

**Comment by vinylspiders** [comment]
@sqnztb more gbp for you if you want!

**Comment by GreytideSkye** [comment]
fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/25224

**Comment by vinylspiders** [comment]
That was just for Blueshift

**Comment by vinylspiders** [comment]
Or is this issue just mislabeled as being for Voidraptor when it was for Blueshift?

**Comment by sqnztb** [comment]
Just tested. Void Raptor should be fine without any adjustments (though it does have a jank stack of access helpers which I'll probably change anyway).

**Comment by vinylspiders** [comment]
Cool, thank you for checking!
