### ISSUE TITLE
Gear harness has a misaligned on character sprite, and also an on character sprite at all

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#25248]
Reporting client version: 514.1589

## Round ID:
10000

## Testmerges:
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[SEMI-MODULAR] Resonance degradation disorder: The quirk that makes you fear death](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24041)
- [New Derelict Station (Babylon Station 13)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25061)

## Reproduction:

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/105110468/ddcdff44-e6ea-411d-a71b-630f68b28e2c)

The gear harness loadout item, notable for specifically showing your undergarment rizz, has an on character sprite that also appears misaligned.

**Comment by Plum-but-gayer** [comment]
investigated and it seems to be working fine, kitty also says so. weird!! I do not recognize that sprite at all....

**Comment by kittysmooch** [comment]
closed cause this was probably caused by a TM or something
