### ISSUE TITLE
Lockers don't have an open sprite.

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#25249]
Reporting client version: 514.1589

## Round ID:
10000

## Testmerges:
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[SEMI-MODULAR] Resonance degradation disorder: The quirk that makes you fear death](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24041)
- [New Derelict Station (Babylon Station 13)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25061)

## Reproduction:
Open a locker. I didn't test for other lockers but the chemistry locker loses its door when opened.

**Comment by SomeRandomOwl** [comment]
Ill test other lockers but as far as im aware currently its only the chemist locker

**Comment by vinylspiders** [comment]
Confirmed upstream too, it's from https://github.com/tgstation/tgstation/pull/79774

the `/obj/structure/closet/secure_closet/chemical` is missing the `chem_secure_open` `icon_state` @MTandi 

![dreamseeker_LfnvA3hyTT](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/fd14b744-4594-4e69-ab27-46ed194c8137)

**Comment by MTandi** [comment]
There was a typo...

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/3625094/680248e4-02f2-437d-b02d-d0231ac4be51)

**Comment by vinylspiders** [comment]
> There was a typo...
> 
> ![image](https://private-user-images.githubusercontent.com/3625094/285682286-680248e4-02f2-437d-b02d-d0231ac4be51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzQ5ODQsIm5iZiI6MTcwMTAzNDY4NCwicGF0aCI6Ii8zNjI1MDk0LzI4NTY4MjI4Ni02ODAyNDhlNC0wMmYyLTQzN2QtYjAyZC1kMDIzMWFjNGJlNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMjEzODA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjVhOWJhNDE1MTZjNGUxMjMwNjFkYTBlYWJiMDYxMWQzMTFhYWRkOGZhYjNlZTBhNDczNDExOWM3OGMwMzA2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cPRMSHU39xB3-N2LS8MU2xqDrccYu0LZJr-sSEteQHw)

That'll do it! lol
