### ISSUE TITLE
Inducer upgrades for engiborgs creating multiple inducers

### ISSUE THREAD

**Issue by Reco201** [Skyrat-SS13/Skyrat-TG#25254]
Reporting client version: 514.1589

## Round ID:
10001

## Testmerges:
- [Ancient Milsim Bitrunning Domain](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24751)
- [Deforest Medical Cargo Company Update | Not so free healthcare | Medbay watches in horror as assistants overdose themselves on dollar store medpens](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24771)
- [[SEMI-MODULAR] Resonance degradation disorder: The quirk that makes you fear death](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24041)
- [New Derelict Station (Babylon Station 13)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25061)

## Reproduction:
Spawn as engineering cyborg
Spawn inducer upgrade both tg's and ours
Add inducers

Each create two inducers 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/71794877/50518b2a-e8f9-4890-8056-60e0449085e9)

Minor issue but clogs up the inventory

**Comment by Zergspower** [comment]
Caused by TG adding their own version https://github.com/Skyrat-SS13/Skyrat-tg/pull/25199 - i'll chop it up probably tomorrow along with the other Engineering module fix
