### ISSUE TITLE
Shoredress wetsuit not displaying in inventory/on the floor

### ISSUE THREAD

**Issue by kaipokai** [Skyrat-SS13/Skyrat-TG#25288]
Reporting client version: 514.1589

## Round ID:
10015

## Testmerges:
- [CIN Evilguns | The gunnenshootening pt 3 | Long live the king | Slight rework of the CIN surplus company](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24304)
- [Bring Your Pet to Work Day (Veteran Quirk)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25142)

## Reproduction:

Wear shoredress wetsuit, displays properly ingame but not in the "inventory slot". Toss it on the ground and it also displays an error message. Checked with someone else to see if it was in fact on my end but it appears not.

Cropped screencaps of the way it displays when on the floor/in inventory.

https://i.gyazo.com/dc6c1d2946a6b8c04ef3070120a84223.png
https://i.gyazo.com/7cd709245f6dbb834c015d8b898e8b25.png

**Comment by xXPawnStarrXx** [comment]
Do you specifically know what type of wetsuit you had? I'm not seeing any issues.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/53197594/187bd0ed-f0cf-43f3-a921-5fe545ce626d)

**Comment by kaipokai** [comment]
Hello, it was the assistant one. Someone (a mentor) I asked to check alongside also saw it showing the big red "MISSING" thingy but maybe it was just a temporary issue?

**Comment by Floofies** [comment]
Hi @kaipokai is this still an issue? Thanks!
