### ISSUE TITLE
Advanced camera console can delete someone's species datum

### ISSUE THREAD

**Issue by Azarak** [Skyrat-SS13/Skyrat-tg#2529]
Reporting client version: 513.1536

I noticed 2 occurences of custom spawned ghost roles somehow loosing their .species from their dna after interacting with the advanced camera console. Cant reproduce
They wont be able to walk, be examined, and many other stuff.
## Round ID:
[432](https://scrubby.melonmesa.com/round/432)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [Lowers down and disables some events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2438)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)

## Reproduction:
Cant manage to reproduce

**Comment by Zergspower** [comment]
Cant reproduce - doesn't seem to do anything now either when going through steps
