### ISSUE TITLE
ORM doesn't give mining points when Mining Satchel emptied directly into it.

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25329]
Reporting client version: 514.1589

## Round ID:
10025

## Testmerges:
- [CIN Evilguns | The gunnenshootening pt 3 | Long live the king | Slight rework of the CIN surplus company](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24304)
- [Armor tech of the current* year | Protect yourself from all them "guncargos" the old people keep warning you about](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24947)

## Reproduction:
Collect ore in a Mining Satchel (of Holding).
Whack the ORM with it.
Get text messages about each ore being deposited, e.g. "uranium ore worth 50 sheets of material was consumed by the ore silo.
x2"
Expected: ORM now has Unclaimed Points on it.
Other Expected: your equipped ID automatically has mining points added to it.

Observed: Unclaimed Points are zero, and your ID's mining points are the same as before.

**Comment by Drayco84** [comment]
This has been a known issue downstream for a VERY long time where the ORM won't give points unless the ores are dropped onto the floor or an ore box is in the pickup spot. Using ore directly onto the ORM was supposedly fixed a while ago, but I personally haven't tested it.
