### ISSUE TITLE
Mesons allow unrestricted vision to lower levels.

### ISSUE THREAD

**Issue by ZephyrTFA** [Skyrat-SS13/Skyrat-tg#2535]
Reporting client version: 513.1539

## Round ID:
[438](https://scrubby.melonmesa.com/round/438)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [Lowers down and disables some events](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2438)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)

## Reproduction:

Wear mesons.
Easily see lower levels regardless of walls being in the way.
![image](https://user-images.githubusercontent.com/12817816/103899386-53857780-50c4-11eb-89f9-67b7bc1e6990.png)

**Comment by Zergspower** [comment]
Bug resolved in a previous bug fix or over time
