### ISSUE TITLE
Opfor panel objective buttons do not work properly

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-tg#25458]
Reporting client version: 514.1589

## Round ID:
10079

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [[modular] Adds hair ties](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24806)
- [[TM-ONLY] Disables the crafting of hash](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25447)

## Reproduction:

Open the opfor panel, make an objective. Make a second (and third and so on) button, attempt to cycle to that objective to fill it out. Instead you cycle the pages, going to admin notes etc. Going to the fourth+ objective sends you into nega-space in the UI, which is funny.

**Comment by SomeRandomOwl** [comment]
This should be fixed by #25508 will confirm in the morning
