### ISSUE TITLE
Automated Robot Factory not on spawn cooldown properly

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-tg#25524]
Reporting client version: 514.1589

## Issue Summary

During a Malf dealio a Skyrat original cyborg factory was put down. Despite the factory's description listing a cool down on when a cyborg could respawn in minutes, cyborg players were still able to constantly spawn out of it moments after they died. This lead to a bemusing, if not fitting for SR situation of the station's brave heroes crawling through dead synths while they kept respawning as they tried to get to the factory.

That's no good.

The factory timer is I think five minutes and proooobably should be increased, too, but I'll leave that up to the wahlance team.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/121744141/2df5722a-0fe3-462e-9dcf-4ba0ddb0b948)

## Round ID:
10103

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [[TM-ONLY] Disables the crafting of hash](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25447)

## Reproduction:

idk try to respawn with a factory i guess

**Comment by Floofies** [comment]
Thanks for reporting this! I saw it happen too.

I checked the code in `modular_skyrat\modules\SiliconQoL\code\robotic_factory.dm` and it looks like an old bug which no one noticed for many years. It adds to its cooldown timer until it becomes a very large number. The code is not algorithmically correct.

```
if(cooldown_timer <= world.time)
	cooldown_timer = world.time + cooldown_duration
```

**Comment by Floofies** [comment]
Fixing this now
