### ISSUE TITLE
Genetic Mutations do not properly remove

### ISSUE THREAD

**Issue by annikaRU** [Skyrat-SS13/Skyrat-TG#25543]
Reporting client version: 514.1589

## Issue Summary

Mutations do not properly remove when scrambling through the DNA scanner

## Round ID:
10110

## Reproduction:

Mutations do not remove when scambling, get yourself a telekenesis activator (example) inject and enter DNA scanner. 
Once in DNA scanner scramble DNA. Notice how the mutation is still there but does not function or show in genetic sequence analyzer.

Now place H.A.R.S activator on a humonkey with H.A.R.S, the head destroys itself. Next throw the humonkey back in the scanner and scramble DNA. Head is still missing although H.A.R.S is still technically "activated" even if it isn't a base or mutator

This applies to every mutation and you need to AHELP to force remove the mutations 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/c2eb81f3-2e18-4007-855f-6008badf5869)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/84240711-9bf7-4625-bf9e-bb3dff10a1a7)

https://cdn.discordapp.com/attachments/1157463161180536853/1183356486886359081/MedalTVScreenRecording20231210043103-1702204530.mp4?ex=6588099c&is=6575949c&hm=dbec3192bc6aa770f0d0102d75555b126eba51d84149d79dbf27663e4f146deb&

**Comment by PawnAtWork** [comment]
Is it possibly a mutadone resistant mutation?

**Comment by vinylspiders** [comment]
I think I know the cause of this, I'll work on a fix later

**Comment by annikaRU** [comment]
> Is it possibly a mutadone resistant mutation?

I did not test that far I can check

**Comment by annikaRU** [comment]
OH no only DNA vault mutations are mutadome resistant to my knowledge all mutations done via scanner can be removed or changed

**Comment by annikaRU** [comment]
Reopening as the issue is still persistent after testing genetics yesterday

**Comment by vinylspiders** [comment]
The server hasn't updated with the changes yet. It'll show up in the changelog when it does. Last update was Dec 13th.
