### ISSUE TITLE
Quartermaster Requests Console (Blueshift)

### ISSUE THREAD

**Issue by annikaRU** [Skyrat-SS13/Skyrat-TG#25540]
Reporting client version: 514.1589

## Issue Summary

Requests console on blueshield lists as unknown

## Round ID:
10109

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [[TM-ONLY] Disables the crafting of hash](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25447)

## Reproduction:

Walk into the quartermasters office, look at it and it lists as Unknown Requests Console

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/c70b2eff-c2ec-4225-ac8d-ca0350262712)

**Comment by Floofies** [comment]
Thanks for reporting this!

I investigated the map file and found the console lacks any name or department. Robotics lab has the same issue. Seems to be an oversight.

Here is an example of correct hydroponics console, which has the necessary extra bits, whereas the QM console lacks this:

```
/obj/machinery/requests_console/directional/east{
	department = "Hydroponics";
	name = "Hydroponics Requests Console";
	pixel_x = 0;
	pixel_y = -33
}
```
