### ISSUE TITLE
Broken Stamp Placement *minor bug*

### ISSUE THREAD

**Issue by Darkinite** [Skyrat-SS13/Skyrat-TG#25563]
## Issue Summary

Certain stamps has a problem being placed (i only tried with with the HoP stamp) You cannot freely place stamps anywhere on the paper and it defaults to the top left corner of the paper.

## Reproduction:

simply pick up the HoP Stamp and attempt to move around your cursor whilst trying to tamp the paper. It will not move according to your mouse location
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/29658789/1ac239de-f607-4af8-a079-49c44bf4ee18)

**Comment by vinylspiders** [comment]
Will be fixed on the next server update, see https://github.com/Skyrat-SS13/Skyrat-tg/pull/25564
