### ISSUE TITLE
Short tail added in #25500 is broken

### ISSUE THREAD

**Issue by desertmote** [Skyrat-SS13/Skyrat-TG#25562]
## Issue Summary
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25500
![onCcHxZBjI](https://github.com/Skyrat-SS13/Skyrat-tg/assets/77534246/1a0c3fd6-958d-432a-9e8d-e42c1b09981c)

**Comment by vinylspiders** [comment]
Try clearing your byond cache. Byond client->gear icon->Preferences tab

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/f814c827-7ad1-4bcc-99e2-3992ab92102c)

Invisible icons are often caused by cache corruption so always check that first.

**Comment by desertmote** [comment]
Issue persists after clearing cache.

**Comment by vinylspiders** [comment]
My bad, I assumed it was merged already. Waiting on https://github.com/Skyrat-SS13/Skyrat-tg/pull/25291 to be looked over by golden and it should be fixed then.
