### ISSUE TITLE
Cannot change names in the character screen

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-TG#25672]
Reporting client version: 514.1589

## Issue Summary

Attempting to change the names in the character lobby screen in anyway while it's selected acts like you hit enter in the past, not allowing you to change it in anyway. The randomizer button still works, so it's something to do with the input.

## Round ID:
10159

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [LOOC'ing while in crit..? Or while unconscious..? You got it!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25506)

## Reproduction:

Attempt to change the name of your character, or deity or other things. Instead of rewriting it, or editing it, it just defaults.

**Comment by vinylspiders** [comment]
Confirmed upstream as well

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25761 Should fix it I believe once the server updates
