### ISSUE TITLE
Santa hat triggers clausterphobia?

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#25688]
Reporting client version: 514.1589

## Issue Summary
When I wear a santa hat [/obj/item/clothing/head/costume/santa], around someone with the clausterphobia quirk, they start choking. I don't know how to recreate this aside from trying clausterphobia with a hat on? 

## Round ID:
10164

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [LOOC'ing while in crit..? Or while unconscious..? You got it!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25506)

**Comment by SomeRandomOwl** [comment]
Its intentional of the quirk, because its making a pun of 'claus' terphobia. It's a TG joke

![q8h0FGcx9D](https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/005e162a-2fef-46d5-871d-4d254dcdda3d)

**Comment by ghost** [comment]
While the santa costume itself is intentional, we should do a quick glance to make sure none of our modular christmas outfits cause this. It's a fear of santa _claus_, not a fear of christmas.
