### ISSUE TITLE
Text input into character preference fields laggy, frequently eatten

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-TG#25684]
Reporting client version: 514.1589

## Issue Summary

Inputting text into the fields in the character panel are horribly laggy, and inputs are frequently eaten up making inline editing practically impossible. This is not ideal. Pasting text is fine, naturally. ~~While the Opfor panel is currently broken, people were commenting on that being the same, too.~~ This is a very recent change. More or less, it's acting as shitty as paperwork is. Verbs like subtler are just fine and dandy, oddly enough.

It's an off the cuff guess, but I think it might have something to do with #25620 as I believe this started _after_ the tgui changes.

## Round ID:
10162

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [LOOC'ing while in crit..? Or while unconscious..? You got it!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25506)

## Reproduction:

idk, type something. If it's some weird lag issue it's possible it won't trigger on a local host.

**Comment by SomeRandomOwl** [comment]
I can't reproduce this, i tested it and it doesn't seem to be lagging with text inputs

**Comment by burgerenergy** [comment]
That's concerning, it's definitely happening. I'll see if I can canvas more people.

**Comment by SomeRandomOwl** [comment]
> That's concerning, it's definitely happening. I'll see if I can canvas more people.

@burgerenergy question what byond version are you on

**Comment by burgerenergy** [comment]
> > That's concerning, it's definitely happening. I'll see if I can canvas more people.
> 
> @burgerenergy question what byond version are you on

Says at the top boo, 514.1589

Given the amount of people who've brought it up and immediately recently I wouldn't think it's a version issue, but also byond

**Comment by vinylspiders** [comment]
It's probably related to https://github.com/Skyrat-SS13/Skyrat-tg/issues/25672 , text input still seems to be having issues

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25761 Does this fix it? (confirm when server next updates)

**Comment by burgerenergy** [comment]
The character preferences fields are still are performing poorly. The opfor panel is fine, though.

**Comment by Floofies** [comment]
Hi @burgerenergy is this still an issue?
