### ISSUE TITLE
Loadout Tutorial button: is it supposed to do something?

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25727]
Reporting client version: 515.1621

## Issue Summary
On the Loadout screen, there's a Tutorial button in the upper right that doesn't do anything.

## Round ID:
10173

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)
- [[TM-ONLY] Early mirror of fixing TGUI images not allowing clicks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25725)

## Reproduction:

Open Loadout. Click the Tutorial button in the upper right.
Expected: literally anything.

**Comment by vinylspiders** [comment]
It probably was, but as of right now it definitely does not do anything. It looks like it never has. Could have been a copy pasted vestige of another piece of code.
