### ISSUE TITLE
Loadout, Light Paramedic Uniform remains in all categories

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25726]
Reporting client version: 515.1621

## Issue Summary

The code that removes everything from the loadout list when you change categories does not remove Light Paramedic Uniform.

## Round ID:
10173

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)
- [[TM-ONLY] Early mirror of fixing TGUI images not allowing clicks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25725)

## Reproduction:
Edit your character's loadout.
Change tab to Uniform.
Change tab to another tab.
Observe: Light Paramedic Uniform is at the top of your list.
Observe: Medical Eyepatch from eyes comes over too.
Observe: Black Skirt from Misc. Under also comes over.

Close the Loadout window and reopen it, and these ghost entries are gone.

<details>
<summary>IMAGE: I cycled through all the tabs a few times and came back to Ears.</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/2ccdb27e-ac8e-4ff9-96c6-3b47706ec380)

</details>

For best observation, use the Ears category, because it's supposed to have only 2 entries.

**Comment by vinylspiders** [comment]
What a weird bug. They seem to multiply too each time you switch back to the Jumpsuit tab
