### ISSUE TITLE
Ghost observe doesnt update UI and as such is useless

### ISSUE THREAD

**Issue by nikothedude** [Skyrat-SS13/Skyrat-TG#25731]
Reporting client version: 515.1609

## Issue Summary

When using the Observe verb/orbit panel auto-observe, the UI fails to update, meaning you still have the ghost UI and not the observed individual's UI.

## Round ID:
10175

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)
- [[TM-ONLY] Early mirror of fixing TGUI images not allowing clicks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25725)

## Reproduction:

Step 1: Observe
Step 2: Open observe panel, hit auto-observe at top right
Step 3: Click a name

Expected behavior: Your ghost UI disappears, replaced by the UI of the orbitted individual. Actual behavior: Your ghost UI remains.

Notes: For me, it only happens on skyrat (it works on manuel). Not everyone reports this, so its inconsistant. I've cleared cache, restarted byond, my pc, updated to the latest version, downgraded back to 1609 as well.

**Comment by SomeRandomOwl** [comment]
likely caused bu this? #25714 not sure

**Comment by nikothedude** [comment]
upstream issue and being worked on
