### ISSUE TITLE
[TGUI] Opening anything in company import screen causes a NToS crash

### ISSUE THREAD

**Issue by MaSvedish** [Skyrat-SS13/Skyrat-TG#25739]
Reporting client version: 514.1589

## Round ID:
10178

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)

## Reproduction:
Just open company imports. This particular bug was noted on tram.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/104115259/128b4d19-a2f0-44ce-861c-69fe5b16193a)

**Comment by GreytideSkye** [comment]
copy of #25738
