### ISSUE TITLE
pAIs can be bricked by emoting

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-TG#25745]
## Issue Summary
It's possible to make one's pAI character unconscious using certain emotes. A bluespace tech and myself tried for several minutes to return my character (the pAI known as D.U.D.E.) to consciousness with no solution short of respawning.

## Round ID:
10179

## Reproduction:

1. Respond to a pAI request as an observer.
2. Select and project a pAI holoform at any point after you spawn in to the pAI device.
3. Go to emotes menu.
4. Click to use the *collapse emote.
5. Congratulations, your character is now in a vegetative state. The holoform is paralyzed, blind, deaf, and mute. Disrupting the holoform does not clear these effects.

This may also work with *faint or other emotes/commands that cause unconsciousness. Not yet tested for such as of the publication of this report.

**Comment by Floofies** [comment]
Thanks for reporting this!

**Comment by Floofies** [comment]
Fixing this now
