### ISSUE TITLE
Winter Coats's Hoods

### ISSUE THREAD

**Issue by SarmentiCampbell** [Skyrat-SS13/Skyrat-tg#2584]
Unlike in the old base. The winter hoods don't show your hairstyle, so you can't have bangs covering a part of your face, Would it's be possible to get that back?

**Comment by Funce** [comment]
Check out the `dynamic_hair_suffix` var for this one. Just be sure to test with big hair, specifically "Poofy" or Gandalf will get angery.

**Comment by Gandalf2k15** [comment]
intentional
