### ISSUE TITLE
Searching in techfabs and autolathes broke

### ISSUE THREAD

**Issue by annikaRU** [Skyrat-SS13/Skyrat-TG#25852]
## Issue Summary

Searching for specific items in a techfab or autolathe will not bring up items, and once you close the result (typed specific search) in all designs it will show nothing

## Reproduction:

Go to an autolathe (this is what I did) search for cable coil, it will show nothing, then remove the cable coil from the search bar and it will show nothing in all designs 

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/e354a413-2122-4d48-af69-a47cbf318e62)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/147753662/b3228c99-553e-442d-a90a-4b2af283714c)

**Comment by Floofies** [comment]
Going to take a close look at this. Thanks for reporting it!

**Comment by Floofies** [comment]
Fixed by #25808
