### ISSUE TITLE
Errant pixels showing under all uniforms for digitigrade leges 

### ISSUE THREAD

**Issue by FridayRemada** [Skyrat-SS13/Skyrat-tg#2590]
## Round ID:
452

## Reproduction:
Create anthromorph character, add digitigrade legs, under the loadout screen add a uniform with compatible pants. Ie black jeans
https://cdn.discordapp.com/attachments/511108018302091284/797373050379042816/unknown.png
https://cdn.discordapp.com/attachments/511108018302091284/797373168939302952/unknown.png

**Comment by Zergspower** [comment]
Unable to replicate - assuming layering fix was applied overtime
