### ISSUE TITLE
The Phermone Receptor Icon appears as an error instead of the actual symbol

### ISSUE THREAD

**Issue by Metrobotic** [Skyrat-SS13/Skyrat-tg#2637]
Reporting client version: 513.1539

The Phermone Receptor Icon appears as an error instead of the actual symbol
## Round ID:
470

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Automatically flag Severe+ intensity ambitions for admin review](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2421)
- [Let's turn the amount of retained messages in the chat up. [DNM]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2141)

## Reproduction:

- The problem start as soon as I evolved Phermone receptors, which is a bit strange at first, and although it's not the problem, I was worried it's also the cause of my game crashing, that or a problem from the code but even after my crash, it still appears as an eror.,

- this issue occurs over and over regardless after I clear my caches and restart my game.

**Comment by Zergspower** [comment]
Looks as though the changeling rework resolved this bug
