### ISSUE TITLE
Robotic assembly crates are just wrong in every way.

### ISSUE THREAD

**Issue by trefoils** [Skyrat-SS13/Skyrat-TG#26537]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/114451192/e193a25f-539c-46be-a752-10bf072e5474)
What the code says you get.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/114451192/257c78cb-0cbf-4e13-85b7-f6436471ba24)
What the description on the crate says you get.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/114451192/615e5fb3-0d1b-4f57-bdef-7bcaa6825685)
What you actually get.

**Comment by SpaceLoveSs13** [comment]
This has been fixed
