### ISSUE TITLE
warden's new shotgun can't be put in suit storage like most other guns

### ISSUE THREAD

**Issue by dankmemerino147** [Skyrat-SS13/Skyrat-tg#2659]
## About The Feature Request

enable the PK-12 mod 2, the warden's new combat shotgun, to fit in suit storage
edit: oh yeah it doesn't fit in backpacks either, even though it's supposedly around carbine-length

## Why It's Good For The Game

every other gun has it that i know of, certainly every one sec has access to, and i think it's also intended for it to have it anyway

**Comment by tf-4** [comment]
@Funce this gun is removed from regular play
