### ISSUE TITLE
unbuildable ds-2 machinery

### ISSUE THREAD

**Issue by lectronyx** [Skyrat-SS13/Skyrat-TG#26687]
## Issue Summary

Machine frames act like they already have a blank circuit in them. Cannot remove said circuit or replace it - they're stuck as is...

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/78713019/4040335f-0821-4b5c-8d8f-a18fd23c652f)

**Comment by Majkl-J** [comment]
@Useroth this has been fixed now
