### ISSUE TITLE
Husked Corpses Have No Sprite

### ISSUE THREAD

**Issue by SalinePotatoes** [Skyrat-SS13/Skyrat-tg#2682]

**Comment by Zergspower** [comment]
This seems to be present with mutated parts as well as hybrid species - still exists

**Comment by Quill-Weave** [comment]
![image](https://user-images.githubusercontent.com/103809013/163690208-64de2fb8-0d38-4b86-82ed-9c4d7ec18428.png)
![image](https://user-images.githubusercontent.com/103809013/163690216-82ce43d7-3bc3-4e6b-8aba-a30f3312d786.png)
![image](https://user-images.githubusercontent.com/103809013/163690222-1dc64c01-06b1-4a2a-aacc-bd019ae82b62.png)
![image](https://user-images.githubusercontent.com/103809013/163690225-4b25af86-012a-4980-ad49-55839e00175a.png)
![image](https://user-images.githubusercontent.com/103809013/163690231-df938db0-7e2b-4586-8f32-1798cbb0056f.png)
![image](https://user-images.githubusercontent.com/103809013/163690243-0c0bbb1c-2257-46cb-a31c-862dfba60b59.png)


Cannot produce after some very exciting testing!
