### ISSUE TITLE
Vox do not breath Nitrogen

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2694]
Reporting client version: 513.1539

## Round ID:
495

## Testmerges:
- [Automatically flag Severe+ intensity ambitions for admin review](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2421)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [Revert "Slimeperson race improvements - digitigrade legs, transparent markings/mutant bodyparts"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2673)

**Comment by KasparoVy** [comment]
I was breathing nitrogen last night, did the Vox in question have cybernetic lungs?

**Comment by Funce** [comment]
If this is still an issue, let me know.
