### ISSUE TITLE
Bug: HoP has default access to nearly every department. 

### ISSUE THREAD

**Issue by Tessi12** [Skyrat-SS13/Skyrat-tg#2695]
Reporting client version: 513.1536

## Round ID:
496

## Testmerges:
- [Automatically flag Severe+ intensity ambitions for admin review](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2421)
- [[TM FIRST] Wounds are applied easier on damaged bodyparts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2406)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [Revert "Slimeperson race improvements - digitigrade legs, transparent markings/mutant bodyparts"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2673)

## Reproduction:

Can you get rid of everything that falls under another Head. If they desperately need it for some reason, they can add it back themselves. Engineering as an example.

![image](https://user-images.githubusercontent.com/5411462/104608874-6bbf3e80-5650-11eb-9d8d-dcf72216ceec.png)

**Comment by YakumoChen** [comment]
Not a bug. Heads have a lot of access. The HoP manages the crew and decent HoPs can do departmental inspections and such.
