### ISSUE TITLE
Crafting medibots makes the medibot basic no matter the kit.

### ISSUE THREAD

**Issue by MerlonFire21** [Skyrat-SS13/Skyrat-tg#2739]
## Round ID:
510

## Reproduction:
1. Take any non-standard medkit such as toxins, advanced, or , a cyborg or prosthetic arm, health analyzer of any kind, and proximity sensor.
2. Use the crafting menu to craft a medibot with the supplied parts required.
3. Even if the medkit isn't a standard, default, white medkit, it will always create a standard, white, brute-healing medibot.
4. This wastes the kit entirely by converting it to a white medibot, and the kit cannot be recovered through killing the medibot.

- If an advanced kit is used, medical loses 1 of their only 2 advanced kits, and it has to be re-purchased, or cargo has to order a new restocking unit. **Greater than 600 credits** are lost through the bug, and possibly 5 to 10 minutes.
- Breaking the medibot after this does not give the kit back, only a standard white kit. 
![Screenshot (9852)](https://user-images.githubusercontent.com/75196609/104809542-11db8780-57bc-11eb-83cb-b06ce7de53d5.png)
_**Please.**_

**Comment by tf-4** [comment]
Works on live
