### ISSUE TITLE
Sprite issues when attacking.

### ISSUE THREAD

**Issue by Errrr12345** [Skyrat-SS13/Skyrat-tg#2743]
## Reproduction:

Sprites seem to appear in a radius from the player when hitting things same with entities hitting the player, mobs and other players.

**Comment by atakiya** [comment]
More information needed.
- BYOND version?
- Maybe a screenshot of what you see? **(Post after round is over to be safe)**

**Comment by Errrr12345** [comment]
No idea what version it wont display it and I can't find it. I will have to wait till next round to get a screenshot so give me like a few mins

**Comment by Errrr12345** [comment]
I was standing infront of the space sign and this is what happens when attacking things, it dosn't happen every hit just very few happens with me and other mobs and other people.
In the file version it lists it as 5.0.513.1514
![BUG](https://user-images.githubusercontent.com/77546535/104823184-3c6f2400-5840-11eb-8ccb-b95f24a2a1fb.JPG)

**Comment by atakiya** [comment]
You can always check the current version by opening the BYOND pager:
![image](https://user-images.githubusercontent.com/6952402/104823437-48f87a00-584a-11eb-9a07-85b55559f691.png)
![image](https://user-images.githubusercontent.com/6952402/104823455-66c5df00-584a-11eb-9b0a-ff73f1cca6bc.png)
![image](https://user-images.githubusercontent.com/6952402/104823445-57df2c80-584a-11eb-84f5-bbfd8210511c.png)

---
Latest version is `513.1539`.
Try updating.
1539: http://www.byond.com/download/build/513/513.1539_byond.exe

---
As a note, some have problems with the very latest versions, if that issue fixes, but you have other issues appear, try this one below:
1536: http://www.byond.com/download/build/513/513.1536_byond.exe

**Comment by Errrr12345** [comment]
Will do, thanks

**Comment by tf-4** [comment]
Byond issue at the time, since fixed.

**Comment by Errrr12345** [comment]
Eh?

Sent from my Samsung Galaxy S8 - powered by Three
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
