### ISSUE TITLE
Underbarrel grenade launchers on weapons which have them have a safety which cannot be toggled

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#2791]
Reporting client version: 513.1536

## Round ID:
539

## Testmerges:
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [MAKE BLUESHIELD COOL!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2701)
- [[Semi-Modular] Adds Shipstation, an entire station... on a shuttle.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2680)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)

## Reproduction: 

Change a weapon such as the M-90 gl carbine's fire mode to grenade launcher, and attempt to fire. It'll say your safety is on, even if the main gun's safety isn't. and oh yeah, theres no safety to toggle other than the main gun safety. OOPS.

**Comment by tf-4** [comment]
@Funce fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/3127
