### ISSUE TITLE
Potential Sabotauge from syndie prison ghost role.

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#2792]
Reporting client version: 513.1536

## Round ID:
539

## Testmerges:
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [MAKE BLUESHIELD COOL!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2701)
- [[Semi-Modular] Adds Shipstation, an entire station... on a shuttle.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2680)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)

## Reproduction:

This isn't a bug, as it's more of an oversight. There may be many more. With the ids of the private security contractors which can be obtained in maintnence, a member of the ghost role apon the assault ops base could, if they wished to, access the security records console which is present there for flavor or assault ops reasons, and sabotauge security's recordkeeping remotely, without any risk to themself.

**Comment by tf-4** [comment]
Assault ops is long gone.
