### ISSUE TITLE
Role timer issues

### ISSUE THREAD

**Issue by PsycoticCone** [Skyrat-SS13/Skyrat-tg#2794]
Reporting client version: 513.1526

## Round ID:
540
Issue is that role timers have reset to four days for Security, and a variety of other days for certain Antag roles. Ahelp indicated that there was no immediate solution to the problem.

## Testmerges:
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [MAKE BLUESHIELD COOL!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2701)
- [[Semi-Modular] Adds Shipstation, an entire station... on a shuttle.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2680)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)

## Reproduction:

Issue occurs whenever logged into Skyrat.

**Comment by tf-4** [comment]
Not seen this be an issue at all since, let me know if it still is.
