### ISSUE TITLE
ghouls unable to regrow

### ISSUE THREAD

**Issue by Syilumi** [Skyrat-SS13/Skyrat-TG#28320]
## Issue:
ghouls cant seem to mash meat back into their limbs
## Reproduction:
pop off one of your limbs and try to mash the meat back into its limb

https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/f12e9abd-7051-404c-b761-8a397b2c7853

**Comment by trefoils** [comment]
https://github.com/NovaSector/NovaSector/pull/1220

There is a fix we just need to port it.

**Comment by Syilumi** [comment]
ah nice

**Comment by Syilumi** [comment]
..i think i close
