### ISSUE TITLE
voltaic combat cyberheart is non functional

### ISSUE THREAD

**Issue by EDQW123** [Skyrat-SS13/Skyrat-TG#28466]
Reporting client version: 515.1640

## Issue Summary

the volatic combat cyberheart as printable is completely non functional. you cannot insert the flux core required to activate it.

## Testmerges:
- [[DNM] Raises the minimum players required for some events.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25898)
- [Creates Round removal opt-in (bootlegged off of nova's antag opt-in.)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/27473)
- [Adjustment of event multipliers and thresholds](https://github.com/Skyrat-SS13/Skyrat-tg/pull/27508)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/28307)

## Reproduction:

1. get a refined flux anomaly core
2. print a voltaic combat cyberheart from a science lathe or a robotics lathe
3. attempt to put the core in
4. nothing happens

**Comment by SpaceLoveSs13** [comment]
This is upstream issue

**Comment by SpaceLoveSs13** [comment]
Has been fixed
