### ISSUE TITLE
Using wirecutters on a live wire with telekinesis still shocks player

### ISSUE THREAD

**Issue by Felixx68** [Skyrat-SS13/Skyrat-tg#2849]
Reporting client version: 513.1538

## Round ID:
571

## Testmerges:
- [MAKE BLUESHIELD COOL!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2701)
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

**Comment by SpookyTheFox** [comment]
Telekinesis treats items as if you are holding/touching them, which is how you can dust yourself with the SM with telekinesis. Pretty sure it also leaves fingerprints on objects as well. Fixing this makes sense, but in practice, might be a little difficult.

**Comment by tf-4** [comment]
Still present

**Comment by Zergspower** [comment]
Bug or feature Still present, will defer before closing
