### ISSUE TITLE
Hawk Talon Marking sprite issue. When avatar facing east, their left foot would appear normal/unmarked.

### ISSUE THREAD

**Issue by Primie-Problems** [Skyrat-SS13/Skyrat-tg#2869]
Reporting client version: 513.1539

## Round ID:
585

## Reproduction:

The sprite facing east will show an unmarked foot, which kills immersion.

It's just sprite fixing, I guess? I am unsure how this all works, but I figured I should state the issue.

**Comment by Zergspower** [comment]
Seems like a layering issue that has been resolved, not seeing the sprite error anymore
