### ISSUE TITLE
Buckling to surgery operating table gives weird pixel offset

### ISSUE THREAD

**Issue by thegrb93** [Skyrat-SS13/Skyrat-TG#28715]
## Issue Summary
I tried looking into this myself, but couldn't find what custom code was causing it. The pixel offset on TG works fine, but buckling someone to a surgery operating table in this codebase makes them raise up higher than expected despite operating tables having the same pixel offset values.

## Reproduction:
Buckle yourself to a surgery operating table.

**Comment by lessthnthree** [comment]
TG upstream.

**Comment by thegrb93** [comment]
Not an upstream issue, I mentioned it works fine in TG

**Comment by thegrb93** [comment]
I just tested it again today, and it looks like this was fixed sometime after I wrote the issue.

**Comment by lessthnthree** [comment]
Partly my fault, I should have clarified my earlier comment, it was fixed upstream.
