### ISSUE TITLE
Guns Occasionally fire two times when firing once

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#2892]
Reporting client version: 513.1536

## Round ID:
590

## Testmerges:
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)

## Reproduction:

I... don't know what to say. you fire a gun, and occasionally it shoots twice at the same time, or seemingly at the same time, instead of once.

**Comment by Low3** [comment]
I hope you didnt had guns in both hands and clicking on harm.

**Comment by Zergspower** [comment]
Tried multiple weapons in both laser and ballistics - many many changes since this issue was risen and I'm unable to replicate it. Assuming resolved
