### ISSUE TITLE
Surgery bug

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2898]
Reporting client version: 513.1541

## Round ID:
594

## Testmerges:
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [[Semi-Modular] Oldstation (Charlie station) Additions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2706)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)

**Comment by tf-4** [comment]
I'm not even sure what this means

**Comment by tf-4** [comment]
Poke me if you can elaborate on this at all, or if it's still an issue.
