### ISSUE TITLE
Medical hardsuit purchased but unable to be delivered to the station due to it being missing on the transport shuttle

### ISSUE THREAD

**Issue by Metrobotic** [Skyrat-SS13/Skyrat-tg#2912]
Reporting client version: 513.1541

## Round ID:
604

## Testmerges:
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

## Reproduction:

As Cargo technician, order one medical hardsuit and wait for it to come. The hardsuit is then not found in the supply shuttle.

This happens after I ordered the hardsuit twice, so this is something that's reoccuring

**Comment by tf-4** [comment]
Pretty sure this is just a % chance and you were unlucky.
