### ISSUE TITLE
Carp munch medibot error

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#2913]
Reporting client version: 513.1541

## Round ID:
605

## Testmerges:
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

## Reproduction: A SQL error occurred during this operation, check the server logs.
A space carp spawned from the space dragon event chomps a medibot, gives up SQL error

**Comment by tf-4** [comment]
Guess the server logs were never checked. Seems unlikely to be the cause anyway.
