### ISSUE TITLE
Pre-existing link between Station and Free Golem Ship ORM

### ISSUE THREAD

**Issue by EvilCrimsonWitch** [Skyrat-SS13/Skyrat-tg#2929]
Reporting client version: 513.1541

## Round ID:
613

## Testmerges:
- [[NON-MODULAR] [TM Only] Added the SQL logging.. waf](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2668)
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [DS-1 Assault Group + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

## Reproduction:
When observing, or when going to the vault on the station, one of the links in the ore silo is to the free golem ship. Specifically, its ORM. This allows the golems to siphon off station resources and vice versa, with resources golems deposit being usable on the station from the beginning of the round. It may depend on the z-level spawn of the free golem ship. Furthermore, with issue #1881 still open, this leads to one event quite often: golems dump out all resources in their ORM before linking their own silo, to then place said resources back into the ORM. Due to the roundstart link, this means the golems are essentially stealing every resource on the station, as their new ore silo wont be linked to the station.

Furthermore, in regards to #1881 , it may be the case that the reason the materials in the ORM seem to disappear is related to this issue. It might be worth doing more testing on ice box and then another map, to see if this particular round-start link is the issue.

**Comment by Zergspower** [comment]
Mapping issue resolved between now and making of this ticket, ORM on golem ships are now segregated from the stations.
