### ISSUE TITLE
Embedded object causing a limb to be removed seems to delete the embedded object, plus produces an odd message

### ISSUE THREAD

**Issue by EvilCrimsonWitch** [Skyrat-SS13/Skyrat-tg#2953]
Reporting client version: 513.1541

## Round ID:
630

## Testmerges:
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Lopland Security and Armadyne Weaponry rework [Security Medic and Sergeant] [RFT]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2860)
- [[NON-MODULAR] Porting audible emotes from oldbase.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2795)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

## Reproduction:
Bit of a long title, but I wasn't sure how to shorten it. After a bit of messing around, testing some weapons, I decided to throw an energy sword at a human monkey target. The weapon embedded itself in their left arm, doing some nice damage. What happened next was odd.

The arm then became suddenly detached from them, being flung forwards a couple of tiles. The message in chat was as follows: "Cash Sulyard's left arm !" As you can see, seems to be missing some detail. Besides that, I noticed the energy sword didn't fall out, nor was it left embedded in the arm after it was severed. Not 100% sure how easy it is to recreate this, nor what causes it, but there seems to at least be a bug with the chat message that comes up when this happens.

**Comment by Zergspower** [comment]
Replicated - but seems that once the limb is re-attached the item re-appears - considering this a feature
