### ISSUE TITLE
When you equip the Eye of God, you cannot put on prescription glasses and are cursed to forever have a black circle around your vision if you have the nearsighted quirk.

### ISSUE THREAD

**Issue by DonutWorm** [Skyrat-SS13/Skyrat-tg#2955]
Reporting client version: 513.1541

## Round ID:
631

## Testmerges:
- [[TM ONLY] Tick test to reduce lag](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2443)
- [Lopland Security and Armadyne Weaponry rework [Security Medic and Sergeant] [RFT]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2860)
- [[NON-MODULAR] Porting audible emotes from oldbase.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2795)
- [[Ready] Maintenance Loot Overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2470)

**Comment by YakumoChen** [comment]
Not a bug. Eye of god takes up your eye slot and is nodrop. Consider being more careful with what you jam in your eye.
