### ISSUE TITLE
Huge Dozer Problem

### ISSUE THREAD

**Issue by lolman65** [Skyrat-SS13/Skyrat-tg#2987]
Reporting client version: 513.1542

## Round ID:
641

## Testmerges:
- [Lopland Security and Armadyne Weaponry rework [Security Medic and Sergeant] [RFT]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2860)

## Reproduction:
Dozer was missing its sprite completely and was unusable as an item

**Comment by Gandalf2k15** [comment]
Will fix in a bit

**Comment by tf-4** [comment]
this is fixed now i believe

**Comment by lolman65** [comment]
Yeah, i know, wish ot kept its burst fire though
