### ISSUE TITLE
No way to heal toxloss on corpses

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#2997]
The rejuvenation surgery was removed for seemingly no reason, and there's no way I know of to heal the dead if they died primarily of toxin. "Just clone them" feels like a cheap cop-out considering TG med is supposed to be done with cloning removed.

**Comment by ZephyrTFA** [comment]
If they did with only toxin; chest defib them. Chest defib sets their damage to a maximum of 90 total.

**Comment by YakumoChen** [comment]
I thought defib had an upper limit for any damage? This changes things.
