### ISSUE TITLE
Ashwalker Tendril Respawning

### ISSUE THREAD

**Issue by SpiderPsycho** [Skyrat-SS13/Skyrat-tg#3005]
Reporting client version: 513.1542

## Round ID:
647

## Reproduction:

Join as an Ashwalker with a character from prefferences. Die next to the tendril, then attempt to join as an egg immediately after using a character from prefferences. It will say "You have outlived your usefulness to the tendril". Wait, then be respawned as a randomly generated character of the same name.

**Comment by Zergspower** [comment]
Currently not replicable - respawning as an Ashwalker is functioning as designed and adjusted since this  Issue was found
