### ISSUE TITLE
changeling goal bug

### ISSUE THREAD

**Issue by realtaac** [Skyrat-SS13/Skyrat-tg#3024]
Reporting client version: 513.1536

## Round ID:
655

## Testmerges:
- [Lopland Security and Armadyne Weaponry rework [Security Medic and Sergeant] [RFT]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2860)
- [[NON-MODULAR] Porting audible emotes from oldbase.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2795)
- [[Modular] Aphrodisiacs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2914)
- [[Semi-modular] View Latest Ticket ahelp command for players](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2958)

## Reproduction: 
if as changeling you resubmit goals (to say.. add a new goal) you lose all of your powers but get your 10 points back pretty much offering free readepts

**Comment by SpookyTheFox** [comment]
It also gives you a new HUD button for the ling emporium, but does not remove the old one.

**Comment by tf-4** [comment]
No longer using ambitions
