### ISSUE TITLE
Deer HORNS replaced EAR Sprites

### ISSUE THREAD

**Issue by FridayRemada** [Skyrat-SS13/Skyrat-tg#3059]
## Reproduction: The Deer horns were moved into the EAR section of character customization, and need to be put into the HORNS section, also The deer ears themselves seem to be missing/replaced with the deer horns (picture/example included: 
![image](https://user-images.githubusercontent.com/77188588/106824814-74e07180-6638-11eb-838c-99ce66939390.png )

**Comment by thestubborn** [comment]
sorted, kinda
#6845

**Comment by Zergspower** [comment]
aged bug - redesign of character panel fixed this
