### ISSUE TITLE
Guns that got their safeties removed don't function

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#3113]
Reporting client version: 513.1542

## Round ID:
685

## Testmerges:
- [[MIRROR] Replaces intents with combat mode](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3063)
- [[Modular] Aphrodisiacs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2914)

**Comment by tf-4** [comment]
@Funce fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/3127
