### ISSUE TITLE
Sec-Grade tactical barriers

### ISSUE THREAD

**Issue by Enzoman12** [Skyrat-SS13/Skyrat-tg#3115]
## About The Feature Request

So during a game we sorta set up barricades using tables. We built the tables then kicked them. They provided really nice cover so it got me thinking what if Sec (or any other fighting group) could basically deploy stationary hallway barricades? Not like the barrier grenades, but I mean something that we could find in the armory or build from the techfab that we can lift up and carry, place on the ground, then click to activate, lifting a barrier up. Similar to CM13 barriers. I figured this would be very useful for locking down hallways. Barrier grenades are rarely used (i've personally never seen them used) so I figured this would be a great way to make some cool defensive lines. The barriers would basically cover only one or two tiles, and the party who set them up could use them as cover to safely shoot from yet provide good cover when shots are returned. Alot of the sec guys thought this was a good idea so Im making my formal suggestion. Thanks!

https://i.imgur.com/jCvX27A.png

https://i.imgur.com/OtGTsKc.png

## Why It's Good For The Game

Could make hallway fights more exciting, giving sec and whoever else a defensive line to fight from. Would make attackers actually have to use their heads rather then rush straight up a hallway. Could be damaged from heavy fire or blown up by explosives, but would stop zerg rushers as they'd potentially run into a wall of guns trying to rush a spot. So if Sec coordinates, they could potentially lock down a specific hallway and engage whatever intruders that come their way.

**Comment by Enzoman12** [comment]
Also. maybe make a certain time limit that it takes for the barrier to pop up/down like the tables. That way it wont be TOO easy to set up in the middle of a fight

**Comment by tf-4** [comment]
Has been added
