### ISSUE TITLE
Round 687, got in an Odysseus and it wouldn't stop spamming that it was "stopping reagent processing"

### ISSUE THREAD

**Issue by DonutWorm** [Skyrat-SS13/Skyrat-tg#3123]
Reporting client version: 513.1541

## Round ID:
688

## Testmerges:
- [[MIRROR] Replaces intents with combat mode](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3063)
- [[Modular] Aphrodisiacs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2914)

**Comment by SpookyTheFox** [comment]
I've noticed this too. The Oddy's sleeper currently does not have a way to shut off chemical production. If you tell it to produce nothing, the UI jumps and tries to ignore you, and will still attempt to do nothing anyway.

**Comment by Zergspower** [comment]
Unable to reproduce - seemingly resolved since the Issue was brought up
