### ISSUE TITLE
Custom burgers disappear on creation

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-tg#3203]
Reporting client version: 513.1542

## Round ID:
712

## Testmerges:
- [[Modular] Aphrodisiacs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2914)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)

## Reproduction:

- Get a bun
- Put something in it by clicking on the bun with the other ingredient
- They both disappear and don't give a burger

Tried:
 - Patty
 - Meatball
 - Cutlet

I believe someone else was able to do it, though in the same way and same round so I don't know why it didn't work for me. I've done it on previous rounds without issue.

**Comment by tf-4** [comment]
This is still an issue as of a few days ago. Likely upstream.

**Comment by Zergspower** [comment]
Able to make burg, bug resolved via time
