### ISSUE TITLE
Toxins Mixing Scrubber broken on Icebox Station

### ISSUE THREAD

**Issue by Eclipse-Presence** [Skyrat-SS13/Skyrat-tg#3254]
Reporting client version: 513.1536

The air alarms in the toxins lab on icebox both interact with the toxins lab itself, not the mixing chamber, making it impossible to do toxins.

## Round ID:
723

## Testmerges:
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)

## Reproduction:

Check the air alarms on Icebox Station, in the toxins mixing lab. Both air alarms interact with the lab itself, not the burn room. Tested by hacking the lab alarm for access, then testing first scrubber for both,

**Comment by tf-4** [comment]
This will be fixed with https://github.com/tgstation/tgstation/pull/56506, eventually

**Comment by tf-4** [comment]
@Funce see above
