### ISSUE TITLE
Chemisty Bag/Chemical Press Issues

### ISSUE THREAD

**Issue by SalinePotatoes** [Skyrat-SS13/Skyrat-tg#3265]
## Testmerges: Uncertain but current test merges for the round I.D. noted are as follows:
#3190: '[TM-ONLY] Disables jukeboxes as orderable cargo crates.' by Useroth at commit 8de3367fef
#3073: '[Non-modular] Buffs blob.' by NotRanged at commit f1073d1e85
#3255: 'Sizeplay v 0.5' by Useroth at commit 70bb5e802e

## Reproduction: Chemistry is experiencing two notable issues: 
**The first** being that chemistry bags will not mass-pickup pills/bottles/patches/beakers from anything (the floor or chem presses). 
**Reproduction:** Easy enough to reproduce, just simply try and pick pills/patches/bottles/beakers up with a chemistry bag.

**The second** is that chemical presses will continue to attempt making pills/patches/bottles even after the maximum limit is reached (10). The effect of this is that the press will not accrue excess reagents to rapidly produce the selected input from a excess supply - and in the case of some setups it will eat limited ingredients consistently (silver, for example). 
**Reproduction:** Set up a reactor and chemical press, have it make any type of medication and observe after the chemical press hits a stack of 10, the chemical press will continue to "make" more pills (though they will not show up in the stack) and both waste reagents and prevent the press from accruing excess medication.

**Comment by tf-4** [comment]
First issue should be solved by https://github.com/Skyrat-SS13/Skyrat-tg/pull/3279

Second issue is a feature. The amount of pills stacked is limited to ten intentionally.

**Comment by tf-4** [comment]
@Funce see above
