### ISSUE TITLE
plasma sheets giving ludicrous amounts of credits when exporting for own profit

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-tg#3293]
Reporting client version: 513.1539

## Round ID:
734

## Testmerges:
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Coronal Mass Ejection Event](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3280)

## Reproduction:

wrap up 2 50 stacks of plasma in a closet, use a sales tagger to set 50% profit margin and get 200000 per stack of 50

**Comment by ghost** [comment]
Its not just plasma sheets, its any item you export with a sales tagger, profits are just bugged

**Comment by tf-4** [comment]
long since fixed
