### ISSUE TITLE
Wrapping a bounty cube and using a price tagger on a bounty cube seems to give nearly 2,000 percent instead of 20 percent

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#3336]
## Testmerges:

N/A

## Reproduction:

For this, I was an assistant, and checked it with turning in normal bounty cubes, then wrapping/price tagging them.  So with that in mind:

1. Complete a credit bounty thats worth 800 credits (honestly it probably doesnt matter on the monetary value of the cube).
2.  Find a price tagger, scan your ID on it, and print/put a label on a cube after you wrap it with the packing paper/wrapper stuff.
3.  Send the cube back to cent-comm on the cargo shuttle.
4.  In the example above, Instead of getting 20 percent of 800 I was getting roughly 16,000 credits from a 800 credit valued cube, with the game telling me the cubes value at Cent-Comm was like 17,200 or something like that?.
5.  I was able to do this 3 times in a round with 3 different bounty cubes, amassing 60K credits for nearly no effort. However, the scratcher with this, is Cargos credits/funds wasn't reflecting these extreme values, leaving several crewmen richer than the entire cargo dept.

**Comment by tf-4** [comment]
Since fixed
