### ISSUE TITLE
Engineering crew don't spawn with a double oxygen tank

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#3352]
Reporting client version: 513.1542

## Round ID:
749

## Testmerges:
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Coronal Mass Ejection Event](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3280)
- [[Modular] Ports the bluespace locker from oldskyrat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2962)
- [[NONMODULAR. UPSTREAM PENDING] Nanites can now infect all MOB_HUMANOIDs.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3334)
- [Disables valentines [TM ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3350)

**Comment by YakumoChen** [comment]
Engineering is supposed to only get a single yellow tank?

**Comment by YakumoChen** [comment]
Oh, they spawn with a blue one instead, not an Extended tank.
