### ISSUE TITLE
Modernize the hotel in space

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#3373]
## About The Feature Request
The hotel that can occasionally be found in space, should be modernized to work with the how cooking is, along with fitting out the pool with hotspring/real water tile that exist. For the kitchen, it just needs to be able to hold 2 griddles

## Why It's Good For The Game

Because it allows the kitchen on the space-hotel to be used fully without issue, and for the water tiles it just a nice touch as it currently had the normal flat, two-dimensional tiles that makes it looked painted on instead an actual pool or water zone.  Realistically this is about a few minutes in Dream Maker or strong DMM of work (if you know how) to switch out the tiles in the pool area, and to add the 2 griddles.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/3409

**Comment by tf-4** [comment]
@Funce see above
