### ISSUE TITLE
Vendor Discount issue.

### ISSUE THREAD

**Issue by AppleWhisky23** [Skyrat-SS13/Skyrat-tg#3422]
Reporting client version: 513.1542

## Round ID: 
770

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)

**Comment by Zergspower** [comment]
Issue no longer present across multiple jobs ID's
