### ISSUE TITLE
Remote Signalling Device/Voice Analyzer Assembly spawns it's components at your feet when held in-hand

### ISSUE THREAD

**Issue by Mitsota101** [Skyrat-SS13/Skyrat-tg#3443]
## Round ID:
778

## Reproduction:
I've had this happen several times and I'm not exactly sure what could be causing it.
All you have to do is simply use a screwdriver on a remote signalling device, and then on a voice analyzer, and then click on one with the other. When you pick up the new assembly it will spawn an unrelated remote signalling device and voice analyzer at your feet. Every time you hold the assembly in your hand from then on the new parts will teleport to your feet.

If you use the new parts to make an additional assembly they will further spawn their own parts, and the original will stop spawning it's parts.

**Comment by Zergspower** [comment]
Similar to https://github.com/Skyrat-SS13/Skyrat-tg/issues/3084 - issue seems resolved as it's not able to be replicated
