### ISSUE TITLE
Error when compiling code for custom servers

### ISSUE THREAD

**Issue by ro3ger** [Skyrat-SS13/Skyrat-tg#3450]
what it says when compiling   (also tips on how to fix this would be nice too thanks)

loading tgstation.dme
loading interface\skin.dmf
code\modules\asset_cache\asset_list_items.dm:6:error: 'tgui/public/tgui-common.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:12:error: 'tgui/public/tgui.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:13:error: 'tgui/public/tgui.bundle.css': cannot find file
code\modules\asset_cache\asset_list_items.dm:19:error: 'tgui/public/tgui-panel.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:20:error: 'tgui/public/tgui-panel.bundle.css': cannot find file
tgstation.dmb - 5 errors, 0 warnings (2/16/21 10:10 pm)

**Comment by YakumoChen** [comment]
Upstream issue

**Comment by tf-4** [comment]
@Funce I imagine this can be closed
