### ISSUE TITLE
Egg not coming out of Egg-Plant

### ISSUE THREAD

**Issue by NonoodWhatever** [Skyrat-SS13/Skyrat-tg#3462]
Reporting client version: 513.1542

## Round ID:
783

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)

## Reproduction:
While attempt to create bunch of donuts, the egg seems to not appear out of it. While the action of revealing egg is there, the actual egg isn't there. Here's what happened:
1. Planting actual Egg-plant
2. Revealing the egg-plant for egg. at least 3 egg will still appear.
3. After that, the egg will stop spawning out of egg-plant, tried replanting, doesn't work.

**Comment by Zergspower** [comment]
Unable to reproduce - potentially resolved over time so assuming issue resolved
