### ISSUE TITLE
CIA hair clipping through hats/helmets

### ISSUE THREAD

**Issue by Enzoman12** [Skyrat-SS13/Skyrat-tg#3481]
Reporting client version: 513.1527

## Round ID:
793

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)

**Comment by Zergspower** [comment]
unable to reproduce, assuming resolved
