### ISSUE TITLE
Chemical Reactors do not work

### ISSUE THREAD

**Issue by Etgfrog** [Skyrat-SS13/Skyrat-tg#3491]
Reporting client version: 513.1542

## Round ID:
796

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [[Non-modular] Buffs blob.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3073)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)

## Reproduction:
Chemical reactors will not pull chemials at all, regardless of settings of the reactor. This was working two days ago then it didn't work yesterday.

**Comment by tf-4** [comment]
Not heard of this being an issue at all recently, feel free to poke if it still is one.
