### ISSUE TITLE
HUD button for UNBUCKLE stopped working.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#3498]
Reporting client version: 513.1525

## Round ID:
797

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)
- [Rejigs CME weight](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3496)

## Reproduction: Get in chair, don't get out of chair.
LOOC: Amos Williams: HELP I CANT UNBUCKLE MYSELF 
LOOC: K.A.T.: Suffer. 
LOOC: tobjv: Looking into it, your ticket too (FLW)
LOOC: Amos Williams: pawdmin? 
LOOC: tobjv: admeme here, try and unbuckle them if you can. 
LOOC: Amos Williams: huh 
LOOC: K.A.T.: It's probably a client side bug IMO. 
LOOC: Tobjv: now rebuckle yourself 
LOOC: Tobjv: and now unbuckle 
LOOC: Amos Williams: stuck 
LOOC: Tobjv: any error pop up yourside? 
LOOC: Amos Williams: okay so the button on my hud is bugged. 
LOOC: Amos Williams: no errors or anything 
LOOC: K.A.T.: You know what. 
LOOC: K.A.T.: Yeah, button's bugged here too. 
LOOC: K.A.T.: Gotta press B to unbuckle. 
LOOC: Tobjv: great 
LOOC: Amos Williams: DOOM MUSIC 
LOOC: K.A.T.: B works, but the HUD unbuckle doesn't. 
LOOC: Amos Williams: ban the unbuckle hud button for lrp 
LOOC: K.A.T.: It broke my prefs. 
LOOC: Amos Williams: im not into bdsm 
LOOC: K.A.T.: I didn't wanna go to chairland. 
LOOC: Tobjv: Right, I'll report the bug, becareful of the evil chairws 
LOOC: Amos Williams: yes

**Comment by tf-4** [comment]
@Funce not heard of this being an issue since then
