### ISSUE TITLE
AI unable to move multi-camera windows

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#3504]
Reporting client version: 513.1542

## Round ID:
800

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM-ONLY] Disables jukeboxes as orderable cargo crates.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3190)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)
- [Rejigs CME weight](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3496)

**Comment by Zergspower** [comment]
Unablle to reproduce - probably a client versioning issue at the time
