### ISSUE TITLE
Figured out an issue I was having with head slot.

### ISSUE THREAD

**Issue by AdventKaori** [Skyrat-SS13/Skyrat-tg#3526]
Reporting client version: 513.1539

## Round ID:
807

## Testmerges:
- [45 TC traitor update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3356)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Rejigs CME weight](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3496)
- [Changeling Rebuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3393)

## Reproduction:

For several rounds I was having an issue where I couldn't wear anything on my head slot in spite of apparently having nothing there.  Turns out, I had chosen the headphones for my loadout in character creation which were supposed to be a neck slot item.  Not only did I instead spawn with them on my head, but they spawned invisible, which is what was causing the issue.

**Comment by tf-4** [comment]
Fixed with #7691
