### ISSUE TITLE
Xenos cant wag their tails 

### ISSUE THREAD

**Issue by Swiftfeather** [Skyrat-SS13/Skyrat-tg#3530]
## Round ID:

Something like 

## Reproduction:

Xenocrew with the exitable quirk can wag their tails when headpat, but since their tails do not wag they just disappear in stead

**Comment by YakumoChen** [comment]
There isnt a sprite for it, probably because wag calls for a sprite someone forgot to add, or didnt add a duplicate in the wag dmi to prevent it vanishing.
