### ISSUE TITLE
gunlights don't seem to be working. as if miners didn't have enough problems.

### ISSUE THREAD

**Issue by OrangeHorn** [Skyrat-SS13/Skyrat-tg#3557]
## Round ID: 817

Round ID: #817

## Reproduction:

this issue has happened for me several times, flashlights attached to a proto-kinetic accelerator (ie: a gunlight) do not produce light, even when turned on before being made a gunlight. a very annoying, sometimes dangerous, bug that puts miners at risk of a goliath sneaking up on miners

**Comment by tf-4** [comment]
Seems fixed.
