### ISSUE TITLE
DS-1 Chief Engineering Officer Doesn't Start With Engineering Skillchip

### ISSUE THREAD

**Issue by GoldenAlpharex** [Skyrat-SS13/Skyrat-tg#3569]
Reporting client version: 513.1542

## Round ID:
821

## Reproduction:

Just as said in the title, really. There's no skillchip when you start as the CEO on DS-1, so you don't know the wires, and you don't have any way of knowing them aside from just testing, which makes you... Very little more than a DS-1 staff member, with funny tools.

**Comment by Swiftfeather** [comment]
@Gandalf2k15 This can be closed.
