### ISSUE TITLE
Ice Melting Quickly

### ISSUE THREAD

**Issue by AppleWhisky23** [Skyrat-SS13/Skyrat-tg#3580]
Reporting client version: 513.1542

## Round ID:
823

## Reproduction: Make Ice. Anywhere.

Issue: Ice melts too quickly and turns into water, making it unusable in recipes without a heater, which the bar doesn't have. This happened on Icebox, which, you would think wouldnt happen.

**Comment by ZephyrTFA** [comment]
print a condenser from an autolathe or the service techfab, it can be used to cool containers by 10K per use.

**Comment by YakumoChen** [comment]
https://github.com/tgstation/tgstation/pull/57171

**Comment by tf-4** [comment]
@Funce see above
