### ISSUE TITLE
Blueshield ammunition glitch

### ISSUE THREAD

**Issue by Skulldoh** [Skyrat-SS13/Skyrat-tg#3619]
Reporting client version: 513.1542

## Round ID:
839

## Testmerges:
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [More traitor items Part 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3483)
- [CQC+](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3610)

## Reproduction:

The new Blueshield weapon cannot be reloaded with bullets that are ejected from the magazine.

**Comment by tf-4** [comment]
@Funce intended behaviour (kind of)
