### ISSUE TITLE
CME event is bad

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#3626]
it lasts WAY too long, like more than half a dozen or so is overstaying its welcome, but 10 minutes of constant EMPing, flaming anomalies isn't fun.

CMEs also spew out plasma constantly, thus ensuring that even if they get disabled they have still fucked up the atmos for the room regardless.

There's no incentive to do anything about CMEs other than call the shuttle, they absolutely fuck up the station and there's no consolation to countering them because they do damage to begin with.

**Comment by tf-4** [comment]
No longer enabled
