### ISSUE TITLE
SEVA suit still causes your clothes to burn underneath it

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#3642]
despite being fireproof SEVA will burn your jumpsuit underneath of it if you're set on fire

**Comment by KasparoVy** [comment]
Lol, fuck. The one reason to take the suit

**Comment by NullDagaf** [comment]
> despite being fireproof SEVA will burn your jumpsuit underneath of it if you're set on fire

yes

**Comment by KasparoVy** [comment]
Your stuff burns through the explorer suit too, lost my scarf and jumpsuit a few times in testing with prolonged clumsy drake fights.

**Comment by YakumoChen** [comment]
the explorer suit at least isn't fireproof though

**Comment by NullDagaf** [comment]
> the explorer suit at least isn't fireproof though

Never was.

**Comment by NullDagaf** [comment]
> Your stuff burns through the explorer suit too, lost my scarf and jumpsuit a few times in testing with prolonged clumsy drake fights.

Use an extinguisher against a rock, then core. Or don't, if you're not affected by heat.
