### ISSUE TITLE
Round start silicon do not start linked to an AI

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#3673]
Reporting client version: 513.1542

## Round ID:
860

## Testmerges:
- [More traitor items Part 1](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3483)
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [CQC+](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3610)

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/7742
