### ISSUE TITLE
Prepare for trouble! Issue report: Enchanted mythril and Binary channel access for borgs in ghost cafe

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#3727]
Reporting client version: 513.1536

## Round ID:
881

## Testmerges:
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

## Reproduction:

So, simply put, so far, for the first of this double issue, you use the material spawner in the ghost cafe, and spawn mythril. Each sheet of it. is enchanted. Every last sheet. with the wizard enchants. including spawn ones, and killy ones. Thats.... not ok.

For the second issue, simply put, try talking on the binary channel as a ghost cafe borg. it works.

**Comment by ReynTheLord** [comment]
So, status update on this one! The mythril can have enchantments such as "Of Space dragon summoning" where it summons an ai controled space dragon. in the ghost cafe. where theres no real weapons to fight it.

**Comment by tf-4** [comment]
Ghost cafe got gutted. Binary issue was fixed.
