### ISSUE TITLE
Suggestion! Pick E-cigarette color

### ISSUE THREAD

**Issue by comet-husky** [Skyrat-SS13/Skyrat-tg#3815]
Currently when picking E-cigarette in loadout, it gives a random color to it.
It would be really cool if we could pick colors to it to at least have it match to fur color or clothes.

The simpliest solution would be to add several E-cigarrettes like "blue, red, orange" like hoodies.
Hope it won't be hard, thank you! <333

**Comment by Gandalf2k15** [comment]
suggestions dont go here
