### ISSUE TITLE
booba appear over items held in hand

### ISSUE THREAD

**Issue by Swiftfeather** [Skyrat-SS13/Skyrat-tg#3847]
## Round ID:

Ongoing

## Testmerges:

circuits and something else

## Reproduction:

If your character has big boob, things held in hands appear UNDER the booba, so you get things like fireaxes hidden b ehind your bust. This appears to be a layering issue.

**Comment by gonenoculer5** [comment]
Stealth milkers. The equivilent of hiding a knife under your tits to hide it from security. Feature. +1

**Comment by Swiftfeather** [comment]
This is going to be considered intended, fuck it. Boobs now hide your weapons of ass destruction.
