### ISSUE TITLE
Blueshield ID

### ISSUE THREAD

**Issue by Skulldoh** [Skyrat-SS13/Skyrat-tg#3850]
## Round ID:

Ongoing Issue

## Testmerges:

#3429 '[Modular] Ports Integrated Electronics (custom circuitry)' by NotRanged at commit e160c2d3c1
#3255 'Sizeplay v 0.5' by Useroth at commit 1c817eaa07

## Reproduction:

Just spawn in as Blueshield and you'll find they have an assistant tier ID with no access at all,  the Blueshield office also does not have a location on the HoP's console although I am unsure if this is a bug or the HoP's lack to give Command access now that causes this.

**Comment by tf-4** [comment]
@Funce fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/4029
