### ISSUE TITLE
Secure Evidence Storage Lockers Don't Have An Access Requirement

### ISSUE THREAD

**Issue by gamermomentum** [Skyrat-SS13/Skyrat-tg#3853]
## Reproduction: 
Walk up to any Secure Evidence Storage, click and open it with no ID present on your person. 
I first identified this issue back in like December, but now that I've seen it's still a thing, I mentioned it and Ironhawk asked me to make a bug report. 
I've confirmed this to happen in multiple rounds on both Kilo Station and Meta Station, but given as they're the same lockers I can't imagine that it's restricted to those two maps.

**Comment by Zergspower** [comment]
Confirmed Bug still exists, though this seems to be an upstream isssue
