### ISSUE TITLE
The redesigned hotels dorms buttons do not work to lock the appropriate doors

### ISSUE THREAD

**Issue by misterreporter** [Skyrat-SS13/Skyrat-tg#3924]
## Reproduction:

None of the buttons within the dorms work on their appropriate doors, it appears they weren't linked.

**Comment by tf-4** [comment]
yeah for some reason it's really fucking hard to make them link. I'm aware of it though

**Comment by misterreporter** [comment]
This was fixed I think the day after I reported it, It's good now!
