### ISSUE TITLE
Shock collars give no warning.

### ISSUE THREAD

**Issue by xXPawnStarrXx** [Skyrat-SS13/Skyrat-tg#3925]
Reporting client version: 513.1530

## Round ID:
926

## Testmerges:
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Simplifies antagonist scaling coefficient and adds admin feedback](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3902)

**Comment by Zergspower** [comment]
Bug? confirmed - no notification after each but may be by design since no clothing notifies you of something being put on you.
