### ISSUE TITLE
Agent ID is awful

### ISSUE THREAD

**Issue by Swiftfeather** [Skyrat-SS13/Skyrat-tg#4060]
## Round ID:

Ongoing

## Testmerges:

#3429 
#3255 
#3845 
#3999 

## Reproduction:

Try to use the agent ID to replace your main ID. You can't. Joke's on you, you just wasted 2 TC.

**Comment by Ziiro** [comment]
Working as intended from what I recall in the tg ID pr

**Comment by Swiftfeather** [comment]
> Working as intended from what I recall in the tg ID pr

Yes but it's awful, and that's an issue. This was just a reminder to myself or someone else to redo it

**Comment by unit0016** [comment]
> > Working as intended from what I recall in the tg ID pr
> 
> Yes but it's awful, and that's an issue. This was just a reminder to myself or someone else to redo it

Would you rather it worked like it used to, copying all access immediately, or had the admin wildcard limit so it could copy any and all access, but the new way?

**Comment by Swiftfeather** [comment]
> Would you rather it worked like it used to, copying all access immediately, or had the admin wildcard limit so it could copy any and all access, but the new way?

@unit0016 I planned to make it copy all access like it used to, but have become too busy to do it myself.

**Comment by tf-4** [comment]
@Funce pretty sure this can be closed now we have 2 variants of the card
