### ISSUE TITLE
Bar robots are broken

### ISSUE THREAD

**Issue by Jureiia** [Skyrat-SS13/Skyrat-tg#4082]
## Round ID: 
Ongoing

## Testmerges:
#3429
#3255
#3845
#3999

## Reproduction:

Play bartender, open the bar, serve robots. You make the drink the robot order and place it in front of them, Instead of drinking and paying for the drink like they're supposed to they just say thank you like they did drink it and leave. And nothing gets added to the service summary in the end of round screen.

**Comment by YakumoChen** [comment]
Bug is being fixed upstream iirc

**Comment by FlamingLily** [comment]
> 
> 
> Bug is being fixed upstream iirc

Think it already has

**Comment by tf-4** [comment]
@Funce see above
