### ISSUE TITLE
Paramedic jumpsuit is not digitigrade

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#4169]
## Round ID:
1001, but I have seen it on others

## Testmerges:
#3429: '[Modular] Ports Integrated Electronics (custom circuitry)' by NotRanged at commit e160c2d3c1
#3255: 'Sizeplay v 0.5' by Useroth at commit 1c817eaa07
#3845: '[Modular] Reproductive integration test' by linnpap at commit 8b464bcdef

## Reproduction:
Be a digitigrade character, and paramedic. Notice the legs and feet clipping through clothing. Switching to other clothing types eliminates it.

Hopefully this one is pretty simple. It worked fine before, something in the last week or so has changed and made the paramedic jumpsuit not select the digi version.

**Comment by tf-4** [comment]
Works for me as of round 1103

**Comment by tf-4** [comment]
@Funce fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/3517
