### ISSUE TITLE
Bluespace RPED Breaking/Disappearing.

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-tg#4218]
Reporting client version: 514.1549

## Round ID:
1018

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: 1018

## Testmerges:

None

## Reproduction:

Basically what happened was I built a Bluespace RPED loaded it up with parts and when I dumped them out the first time to seperate the parts, there was no issue, however, on the second time I dumped them out to get rid of old parts it simply broke or disappeared if you will from my hands dumping the parts but simply just gone.

**Comment by Zergspower** [comment]
Unable to replicate, due to age this may have been fixed overtime
