### ISSUE TITLE
Stealth Reactive armor doesnt work.

### ISSUE THREAD

**Issue by AppleWhisky23** [Skyrat-SS13/Skyrat-tg#4220]
Reporting client version: 513.1542

## Round ID:
1019

## Testmerges:
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[NONMODULAR, TESTMERGE ONLY] Comments out the addiction quirks, pending addiction bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4177)

## Reproduction: Make a stealth armor with a pyro core. 

Stealth armor doesnt work, makes me wonder if the other reactive armors work.

**Comment by tf-4** [comment]
Works for me as of round 1103. It does have a toggle, as well as a short cooldown after reappearing
