### ISSUE TITLE
pAI can't use PDA messenger in deployed or compact form. Plus other bugs.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#4240]
Reporting client version: 514.1547

## Round ID:
1032

## Testmerges:
- [Changeling nerf + Horror form equilibrium ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4225)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[NONMODULAR, TESTMERGE ONLY] Comments out the addiction quirks, pending addiction bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4177)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

## Reproduction: Just be a pai, it cant send or receive messages. Did not work in either on a person, in card form on ground or in holoform.

Newscaster for pAI does not work. It shows the menu but no option is useable.

Instrument panel does not work.

**Comment by Zergspower** [comment]
Just tested - seems to be all working now
