### ISSUE TITLE
Where is the maint loot lebowsky?

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4245]
## Testmerges:
#4225: 'Changeling nerf + Horror form equilibrium ' by Gandalf2k15 at commit 20de591755
#4181: '[TM ONLY] Tick reserve test' by Azarak at commit e385a12ab1
#4177: '[NONMODULAR, TESTMERGE ONLY] Comments out the addiction quirks, pending addiction bugfixes' by RatFromTheJungle at commit e42683915c
#4142: '[Semi-Modular] OutpostStation's Revengeance' by unit0016 at commit 36b2bff5d8
#3845: '[Modular] Reproductive integration test' by linnpap at commit 007d272ab5
#3255: 'Sizeplay v 0.5' by Useroth at commit 1c817eaa07

## Reproduction:
Almost all of the crates in Meta started empty, the ones that usually are full of loot spawns.

**Comment by tf-4** [comment]
This was probably the janitor / empty maint station trait. Have you seen it happen since?

**Comment by YakumoChen** [comment]
No, I didn't realize that was a trait. RIP.
