### ISSUE TITLE
Being Made A Traitor With All Antagonist Prefs Disabled

### ISSUE THREAD

**Issue by GoldenAlpharex** [Skyrat-SS13/Skyrat-tg#4253]
Reporting client version: 513.1542

## Round ID:
1038

## Testmerges:
- [Changeling nerf + Horror form equilibrium ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4225)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[NONMODULAR, TESTMERGE ONLY] Comments out the addiction quirks, pending addiction bugfixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4177)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

## Reproduction:
You just don't touch anything on the main screen, and it just makes you an antagonist regardless of your preferences. I don't think we should have to turn off the button at the start of the game so we're not an antagonist in a round if we have the prefs turned off.

**Comment by Gandalf2k15** [comment]
this is because there are no longer enough players to pick from in the antag pool, and to prevent gamemode setup failure it picks from an emeregency pool of people that aren't antagbanned from the role.

**Comment by tf-4** [comment]
Prefs rework likely solved this. Haven't seen it as an issue in a very long time regardless.
