### ISSUE TITLE
Spawning as an IPC Cybersun agent does not spawn you with the makarov pistol.

### ISSUE THREAD

**Issue by Leudoberct1** [Skyrat-SS13/Skyrat-tg#4284]
Title says it.

**Comment by unit0016** [comment]
This is probably more an issue with the quirks you chose, rather than being an IPC.

**Comment by Leudoberct1** [comment]
This is with no quirks selected.

**Comment by unit0016** [comment]
IPCs don't spawn with any unique items, unlike vox (which were already patched) or plasmamen. I'm unsure as to how exactly this has become.

**Comment by Leudoberct1** [comment]
I have tracked it down a little bit. As an IPC, I am spawning with a wayfinding pinpointer, even without the directionally challenged perk. This is taking the pocket slot that the makarov is supposed to go in.

**Comment by tf-4** [comment]
cybersun is removed
