### ISSUE TITLE
Syndie Mining base vending machines no registered ID

### ISSUE THREAD

**Issue by steamarrow6** [Skyrat-SS13/Skyrat-tg#4310]
Reporting client version: 514.1551

## Round ID:
1056

## Testmerges:
- [Changeling nerf + Horror form equilibrium ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4225)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Massive announcer/BSA overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4254)
- [Fully automatic weaponry implementation [semi, burst, automatic]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4301)

**Comment by unit0016** [comment]
This is a problem with how Icebox is set up and how vending machines work, not something we can really 'fix' per-say. Use the money and account registration machine in cargo as a workaround.

**Comment by tf-4** [comment]
Fixed in one of the many syndie mining base updates
