### ISSUE TITLE
Ling abilities.

### ISSUE THREAD

**Issue by AppleWhisky23** [Skyrat-SS13/Skyrat-tg#4325]
Reporting client version: 513.1542

## Round ID:
1062

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Massive announcer/BSA overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4254)
- [Fully automatic weaponry implementation [semi, burst, automatic]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4301)

**Comment by SpookyTheFox** [comment]
It gives a free re-roll, and also gives another emporium button. This has been going on since the introduction of the ambitions system.
