### ISSUE TITLE
Unable to craft guns

### ISSUE THREAD

**Issue by 4310V343k** [Skyrat-SS13/Skyrat-tg#4365]
Reporting client version: 513.1536

## Round ID:
370

## Testmerges:
- [Changeling nerf + Horror form equilibrium ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4225)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Massive announcer/BSA overhaul](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4254)

## Reproduction:

In #2860 you removed `/obj/item/gun/energy/laser` from general use, giving it only to centcomm and some awaymissions.
But the #2727 made some weapons craftable in crafting menu.
The problem is that you actually need the `/obj/item/gun/energy/laser` to craft those weapons

**Comment by Draganfrukts** [comment]
I'm 99% sure you just need the energy gun from the armory token in order to craft it.

**Comment by 4310V343k** [comment]
> I'm 99% sure you just need the energy gun from the armory token in order to craft it.

iirc you get `/e_gun` from the token.
I'm from mobile so i can't check it

**Comment by Cheshify** [comment]
Noticed that this is a huge issue. You don'y get /e_gun from tokens at all.

**Comment by Cheshify** [comment]
Fixed 👍

**Comment by tf-4** [comment]
@Funce fixed with #4603
