### ISSUE TITLE
Implant multitool becomes invisible when assembling circuitry.

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#4409]
Reporting client version: 513.1536

## Round ID:
1094

## Testmerges:
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Mostly non-modular] Stuff to accomodate multiple servers talking to the same database, including local/global bans.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4032)

## Reproduction:
Use multitool to try and assemble circuitry
feel sad at the fact it turns fucking invisible

**Comment by tf-4** [comment]
Likely can be closed unless it's also an issue with new circuits
