### ISSUE TITLE
Announcements feedback

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4411]
I don't really like the new announcements. Aside from the fact they're too loud, the announcements tend to drone on for ages. They're far too descriptive for voice lines, when before just the alarm blaring or the announcement title was more than sufficient as an alert. 

I don't need to hear the full description of Blue Alert 8 times a shift, just "It's Blue Alert" is more than enough, thanks.

**Comment by tf-4** [comment]
Announcers are now varied and different.
