### ISSUE TITLE
Nanites Don't Sync Up

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#4419]
Reporting client version: 513.1542

## Round ID:
1097

## Testmerges:
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Mostly non-modular] Stuff to accomodate multiple servers talking to the same database, including local/global bans.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4032)
- [Nightstick batong upgrade](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4403)

**Comment by tf-4** [comment]
You mean it doesn't retrieve the researched programs? I've personally not had that be an issue as of round 1103. Are there any specific circumstances? Off station or on station?

**Comment by Erokusan** [comment]
Uncertain, it might have been a TG issue, probably fixed by now

**Comment by tf-4** [comment]
@Funce can be closed for obvious reasons
