### ISSUE TITLE
Nicotine addiction still occurs through self-resp, cannot smoke to treat.

### ISSUE THREAD

**Issue by cmancini5493** [Skyrat-SS13/Skyrat-tg#4431]
Reporting client version: 514.1549

## Round ID:
1101

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Nightstick batong upgrade + stunsticks(in cargo)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4403)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [Civil Dispute Officers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4205)

## Reproduction:

Have a fully matured self-respiration virus in the player character. Proceed to smoke. You will get a nicotine addiction and no way to cure it, resulting in a constantly depleting mood.

**Comment by FlamingLily** [comment]
smoking addiction is bugged, even without selfresp, you can't treat it.

**Comment by FlamingLily** [comment]
smoking addiction is bugged, even without selfresp, you can't treat it.

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/5805
