### ISSUE TITLE
Pepper box ammo missing sprite.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#4437]
Reporting client version: 514.1547

## Round ID:
1102

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] OutpostStation's Revengeance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4142)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Nightstick batong upgrade + stunsticks(in cargo)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4403)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [Civil Dispute Officers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4205)

**Comment by Funce** [comment]
No longer seems to occur
![image](https://user-images.githubusercontent.com/14105827/115018664-402c4880-9f0c-11eb-9ed8-d6a1c577e0a1.png)
