### ISSUE TITLE
Not able to cum on people

### ISSUE THREAD

**Issue by lolman65** [Skyrat-SS13/Skyrat-tg#4467]
Reporting client version: 513.1542

## Round ID:
1110

## Testmerges:
- Reproductive reagent

## Reproduction: 5 times, if attempting to cum on person, action isnt started and nothing happens, but fully works on objects.

**Comment by FlamingLily** [comment]
Sure the target had it turned on in prefs?

**Comment by gonenoculer5** [comment]
Can agree, this doesnt work on people/mobs, only on turfs/objs. Likely broken by some kind of TG update. Wuh woah. Cum machine broke.

**Comment by Zergspower** [comment]
unable to replicate, able to cum on people properly

**Comment by lolman65** [comment]
Close this
