### ISSUE TITLE
Going through an emagged recycler deletes all the items on the person, but they stay on the sprite.

### ISSUE THREAD

**Issue by Swiftfeather** [Skyrat-SS13/Skyrat-tg#4480]
## Reproduction:

Go through an emagged recycler, all the clothing appears to be on the character still, but in the inventory there's nothing, and my implant buttons also disappeared. Appears to be a bug with the way we made it no longer delete bodies.

**Comment by FlamingLily** [comment]
without having looked at the code (mainly cause I haven't been able to find it) I'd say this is just an issue of the recycler code not calling a sprite update once it deletes all the inventory items.

Also the implant thing, uh probably the recycler being told to just delete all items and such, which would include implants (unless you still had the implants afterwards?)

**Comment by GoldenAlpharex** [comment]
> without having looked at the code (mainly cause I haven't been able to find it) I'd say this is just an issue of the recycler code not calling a sprite update once it deletes all the inventory items.
> 
> Also the implant thing, uh probably the recycler being told to just delete all items and such, which would include implants (unless you still had the implants afterwards?)

I know I'm very late, but, no, it's not just that, people that examine you see all of your items as if they were still on your person. Unless examine() is somehow tied to your sprite and not your body, which I highly doubt.

**Comment by FlamingLily** [comment]
> 
> I know I'm very late, but, no, it's not just that, people that examine you see all of your items as if they were still on your person. Unless examine() is somehow tied to your sprite and not your body, which I highly doubt.

Huh. Well, still not having looked at the code, maybe the examine text isn't generated with each shift+click, but instead whenever you change your inventory, by equipping and unequipping items? And recyclers fail to do that?

**Comment by Zergspower** [comment]
Unable to reproduce this in the current build - deleted items do not show on the corpse and delete items disappear properly
