### ISSUE TITLE
Pacifists can't use IHDF ammunition or pepperball ammunition

### ISSUE THREAD

**Issue by VampiricKami** [Skyrat-SS13/Skyrat-tg#4488]
## **Round ID:** 

N/A

## **Reproduction:**

IHDF and pepperballs do no damage, however, give yourself the pacifist trait and try to use either, and it will say that it is lethal, even though it does no actual damage.

**Comment by Draganfrukts** [comment]
This is because pacifists cannot use any form of ballistics. An upstream issue due to their least lethal ballistics being rubbers, which still do damage.

**_Yet another reason to add the disabler to the sidearm token_**

**Comment by YakumoChen** [comment]
Pacifist trait checks gun, not ammo. Guns need a specific exception for pacifists to work and wouldn't work on any item you could (un)knowingly load lethal (damaging at all) ammo into.

Security roles are supposed to be blanket banned for Pacifists regardless.

**Comment by tf-4** [comment]
IHDF is removed and pepperball does eye damage.
