### ISSUE TITLE
Stabilized light pink crossbreed extracts do not give any sort of speed boost, and stabilized sepia crossbreed extracts do not adjust speed at all

### ISSUE THREAD

**Issue by VampiricKami** [Skyrat-SS13/Skyrat-tg#4489]
## Round ID:

N/A.

## Testmerges:

N/A, however, there might be a specific thing that was merged that caused this, but if so, I don't know what exactly it is. It may have been a nerf PR.

## Reproduction:

Make a stabilized light pink crossbreed, and notice that your speed does not increase at ALL.

Make a stabilized sepia crossbreed, and your speed does not change whatsoever.

**Comment by tt-relay-104** [comment]
There was a nerf pr https://github.com/Skyrat-SS13/Skyrat-tg/pull/3689
