### ISSUE TITLE
Tails are still fucked, now giving the moodlet for gaining your tail again after losing it.

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#4546]
Reporting client version: 513.1536

## Round ID:
1140

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [[Semi-Modular] Adds Omegastation to the game.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3721)

## Reproduction:
Spawn in as a synthlizard/someone with a monkey tail
weep

**Comment by FlamingLily** [comment]
This ALSO happens on vox. Just.... vox. with a vox tail.

**Comment by Zergspower** [comment]
I recall this bug but havn't experienced in in recent memory, unable to reproduce with multiple spawns/depsawns
