### ISSUE TITLE
trash bag belt didnt install CSS

### ISSUE THREAD

**Issue by thestubborn** [Skyrat-SS13/Skyrat-tg#4550]
if you wear a trashbag in the belt slot, its a big ugly pink/purple line thing

that's it, that's the report, go fuckin wear a trashbag on your waist

**Comment by thestubborn** [comment]
i guess a fix would be taking a trashbag belt sprite and just calling to that itemstate

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/4795
