### ISSUE TITLE
Using a borg electronic multitool module in hand makes the icon disappear

### ISSUE THREAD

**Issue by Glue-m** [Skyrat-SS13/Skyrat-tg#4566]
## Testmerges:

#4181: '[TM ONLY] Tick reserve test' by Azarak at commit e385a12ab1
#3255: 'Sizeplay v 0.5' by Useroth at commit 87bdd38ceb
#4333: 'Gun huds V2 [NOW WITH COMPONENTS!]' by Gandalf2k15 at commit f10826d3d7
#3721: '[Semi-Modular] Adds Omegastation to the game.' by sergeirocks100 at commit afc68bf58e

**Comment by Zergspower** [comment]
Unable to reproduce - issue since resolved since it was brought up
