### ISSUE TITLE
Changing race deletes examine text / quirks / food likes

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4574]
## Round ID:

[Round ID]: # 1154

## Testmerges:

#4181: '[TM ONLY] Tick reserve test' by Azarak at commit e385a12ab1
#3255: 'Sizeplay v 0.5' by Useroth at commit 87bdd38ceb
#4333: 'Gun huds V2 [NOW WITH COMPONENTS!]' by Gandalf2k15 at commit f10826d3d7
#3721: '[Semi-Modular] Adds Omegastation to the game.' by sergeirocks100 at commit a5a0b364d2
#4548: '[TM-Only] Possible fix for hypnoflash not working' by MLGTASTICa at commit 1cc42ecec6
#4507: '[SEMI MODULAR] Discord Link Updates (Config) (TM this)' by Cheshify at commit fb2d73e2ef

## Reproduction:

<s>The two characters I use most have completely missing Examine texts in my setup screen. I have no idea what caused this, but it was likely recent.</s>

I realized I changed both of my characters to the Felinid race recently, realizing you can mismatch parts to get the bodyparts you wanted, but it caused my examines to be deleted completely as soon as I did so.

**Comment by tf-4** [comment]
Assuming to not be an issue after prefs rework, feel free to reopen or make a new issue if it is.
