### ISSUE TITLE
I can be a pacifist Secoff/HoS

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4575]
## Testmerges:
nothing relevant

## Reproduction:

![image](https://user-images.githubusercontent.com/10399117/113247134-e855d680-92a9-11eb-9e89-0d38c5111538.png)

All the NuSec jobs have correctly banned pacifists but the old jobs do not. Security medic I guess but the medic is less expected to take a lethal role in the department so shrug

@Gandalf2k15

**Comment by FlamingLily** [comment]
Just checked in a private lobby, indeed, restricted quirks are broken for everyone except the CE, Warden, sarges, det CDO and Blueshield. Think I see why, too, gonna try a fix
