### ISSUE TITLE
Gripper gloves not appearing in single-pack

### ISSUE THREAD

**Issue by Metrobotic** [Skyrat-SS13/Skyrat-tg#4618]
Reporting client version: 513.1542

## Round ID:
1178

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] Adds Omegastation to the game.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3721)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Gun huds V2 [NOW WITH COMPONENTS!]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4333)
- [w](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [[NON-MODULAR] Removes Genetics](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4585)
- [Rockplanet LZ-669 [READY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4534)

## Reproduction:
Order a goodie pack, Single pack Gripper gloves, as anything. once you receive it, unlock it and it won't appear inside the crate, other than the manifest

**Comment by Cheshify** [comment]
Looking into it now, on first glance not seeing issue in the code, testing though.

**Comment by Cheshify** [comment]
Right, so it works just fine. I tested it in a private twice, and the code is all there with no bugs. Maybe someone just stole it?
<img width="373" alt="ggggeeab" src="https://user-images.githubusercontent.com/73589390/113496297-33e4cc00-94c6-11eb-84aa-24fb83ccea06.PNG">

**Comment by FlamingLily** [comment]
CC shipments sometimes come dodgy, you probably just got a bad shipment, to which cargo should deny the manifest and send it back

**Comment by Metrobotic** [comment]
Its unlikely it was stolen as i saw  the recipient unlock it with her own ID and So did i when i get my package of the gloves. So it maybe that CC got some bad shipments, although the fact that the gloves didnt appear twice didnt seem like pure coincidence.

**Comment by Funce** [comment]
If it resurfaces, be sure to report it.
