### ISSUE TITLE
More Chaplin sects?

### ISSUE THREAD

**Issue by Enzoman12** [Skyrat-SS13/Skyrat-tg#4634]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

Me and some others enjoy playing Chaplin but sometimes the sects can be too...limiting. I am unsure of the coding process and how to make it balanced, but I figured it would be worth asking and seeing what comes of it.

I figured it would be good for the game as if the sects have benefits that grant others outside the Chaplin gifts, more people might be inclined to participate in RP stuff regarding the Chaple.

A couple ideas I heard was a tribal based sect (Hunts and slaying of beasts) and a Ratvar sect (the clock work aesthetic is just too cool to leave alone). Dunno if this will happen ever, but shooting my shot here.

**Comment by Cheshify** [comment]
This isn't an issue

**Comment by Enzoman12** [comment]
> This isn't an issue

This is a suggestion. This is where they are put...right?

**Comment by Gandalf2k15** [comment]
Take it upstream
