### ISSUE TITLE
Third party bug report- unable to perform brain washing on synthetics

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#4638]
## Round ID:
unknown, ~1180?

## Testmerges:
#4572: 'Massive shuttle refactor and arrivals system change' by Gandalf2k15 at commit 2cc4ec1df1
#4534: 'Rockplanet LZ-669 [READY]' by Gandalf2k15 at commit 798fefc1cf
#4492: '[Fully Modular] Replaces security batons with breaching hammers' by MLGTASTICa at commit 17cc1ae7f9
#4181: '[TM ONLY] Tick reserve test' by Azarak at commit c58a612f37
#3721: '[Semi-Modular] Adds Omegastation to the game.' by sergeirocks100 at commit 712ee0871d
#3255: 'Sizeplay v 0.5' by Useroth at commit 2e0c60e0f7
#4548: '[TM-Only] Possible fix for hypnoflash not working' by MLGTASTICa at commit e415329067
#4501: '[MODULAR] Latejoin cyborgs are now linked to the station AI' by FlamingLily at commit e13ae2a164
#4584: 'w' by Azarak at commit 979ad63277
#4622: '[SEMI-MODULAR] Wizards Changes and new spells' by SarmentiCampbell at commit 022390e365

## Reproduction:
I am not the one that experienced this problem, but I did witness it first hand. I suspect I know the cause, and want to get a bug report in so myself or others can go in and fix it, because it seems like an easy one. Needs a little more testing to verify.

With a surgical console with the program, you can not initiate brainwash surgery on synths. I suspect this is due to the surgery looking for a brain in the head, and for synths, it's in the chest. This bug has probably been around for a while, and only recently become more of an issue as synthetic anthros and humans have been reintroduced, meaning it's a lot more likely to be encountered.

The file I suspect is the issue, is brainwashing.dm somewhere around line 18 or 23. Bonus points if someone makes a mechanic surgery version of /datum/surgery/advanced/brainwashing , but just getting it working for those with their brain in the chest will suffice.

**Comment by gonenoculer5** [comment]
This is already in the works of being fixed by Orion, could just be as simple as putting an interrupt that checks for species first before starting the surgery, and simply states that for synths it has to be done on the chest.

**Comment by ghost** [comment]
> 
> 
> This is already in the works of being fixed by Orion, could just be as simple as putting an interrupt that checks for species first before starting the surgery, and simply states that for synths it has to be done on the chest.

hhahahaha, yea, working on it.........

I've
No clue what's happening here
NGL, from what I see it SHOULD show up already, but doesnt even appear for synthetic species. Even though they're a subtype of human
So, uh, might just be best this gets wrapped up in whatever synthetic medical rework we finally get

Or at least that I'm not expected to fix it lmao

**Comment by Zergspower** [comment]
The bug exists but it's currently in the works to be addressed, more than likely however it will be a different avenue to take since the surgery requires the target of the head but the posi exists in the chest.
