### ISSUE TITLE
sec revolvers can't fit into holsters

### ISSUE THREAD

**Issue by LeonY24** [Skyrat-SS13/Skyrat-tg#4639]
(sec revolvers can't fit into holsters)

**Comment by Cheshify** [comment]
Not an issue, pretty sure that's for balance

**Comment by LeonY24** [comment]
>literally a holster
>can't fit a handgun which is supposed to fit in
i could understand this if it would be just a webbing, but holster belt???

**Comment by tf-4** [comment]
@Funce intended behaviour
