### ISSUE TITLE
Ring Boxes are broken once the ring is taken out

### ISSUE THREAD

**Issue by Mazen-AG** [Skyrat-SS13/Skyrat-tg#4716]
Reporting client version: 513.1542

## Round ID:
1209

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[Semi-Modular] Adds Omegastation to the game.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3721)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [[SEMI-MODULAR] Wizards Changes and new spells](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4622)
- [cultures and languages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4647)
- [Mutants - HNZ1 - A medical and scientific adventure!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4664)
- [Shuttle landing and takeoff sounds](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4702)

So I have found out there the ring box is glitched, by testing multiple times the box will disappear once the ring is taken out and even if the ring is put back inside it stays invisible while it exists, it seems like the Chaplin glitch where his bible would disappear but still be there and can be used

## Reproduction:

To cause this same bug:
-> grab the ring box (visible) in one hand
-> use the other hand to open it (will remain visible)
-> take the ring out and it will disappear but remain in hand

**Comment by Cheshify** [comment]
Just doesn't have a sprite for an empty box probably, maybe intentional to avoid abuse of the box? I dunno. Might look into it
