### ISSUE TITLE
Mechs require ALL selected access

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#4747]
Reporting client version: 513.1542

## Round ID:
1237

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Engines: Return of the Singularity(and tesla)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4725)
- [[NONMODULAR]Shocks & Zaps, Episode 2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4684)
- [cultures and languages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4647)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Mutants - HNZ1 - A medical and scientific adventure!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4664)

**Comment by ZephyrTFA** [comment]
That is intended. It has always worked that way.
