### ISSUE TITLE
Vox "Not enough N2" indicator doesn't go away

### ISSUE THREAD

**Issue by FlamingLily** [Skyrat-SS13/Skyrat-tg#4778]
## Round ID:
1253 (though not that it's relevant)

## Testmerges:
Multiple, but again, highly doubtful they're relevant

## Reproduction:
Be vox
die
un-die
Not enough N2 icon from crit will not leave you alone

honestly I'm gonna be real here I'm pretty sure *I* can fix this myself when I'm able to, just popping this here for posterity

**Comment by Zergspower** [comment]
Unable to reproduce - assuming resolved
