### ISSUE TITLE
AI on tram station unable to turn off its own turrets

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#4790]
Reporting client version: 513.1542

## Round ID:
1273

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[TM-Only] Possible fix for hypnoflash not working](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4548)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Mutants - HNZ1 - A medical and scientific adventure!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4664)
- [[NONMODULAR]Shocks & Zaps, Episode 2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4684)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [Server swap - new UI addition](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4783)

**Comment by Zergspower** [comment]
able to turn off when tested on local
