### ISSUE TITLE
Cells only have the filled icon state

### ISSUE THREAD

**Issue by GoldenAlpharex** [Skyrat-SS13/Skyrat-tg#4835]
Reporting client version: 513.1542

## Round ID:
1297

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[TM-Only] Possible fix for hypnoflash not working](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4548)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Battery Component](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4827)

## Reproduction:
The batteries only have one icon-state from the looks of things, and so it's impossible just from looking at a cell to know if it's charged or not.

**Comment by GoldenAlpharex** [comment]
It's due to PR #4826, so, here, have a ping @Gandalf2k15

**Comment by Gandalf2k15** [comment]
opps, fixed

**Comment by GoldenAlpharex** [comment]
<3

**Comment by Gandalf2k15** [comment]
Fixedddd
