### ISSUE TITLE
Synthetic Anthromorph fluff options do not appear

### ISSUE THREAD

**Issue by Onyxarias** [Skyrat-SS13/Skyrat-tg#4860]
## Testmerges:
#3255: 'Sizeplay v 0.5' by Useroth at commit b622c77121
#4181: '[TM ONLY] Tick reserve test' by Azarak at commit 9af94c3ac9
#4548: '[TM-Only] Possible fix for hypnoflash not working' by MLGTASTICa at commit f433011d74
#4584: '[WIP] [DNM] Liquids system' by Azarak at commit a7e65808f4
#4827: 'Battery Component' by Gandalf2k15 at commit cab385f41f

## Reproduction:

In the Skyrat character creator, selecting any of the options for "Fluff" on the "Synthetic Anthromorph" species results in no graphical representation on the character sprite, whether the "Mismatched Parts" option is Enabled or Disabled.

**Comment by Gandalf2k15** [comment]
This relates to moff fluff

**Comment by tf-4** [comment]
Still an issue

**Comment by Zergspower** [comment]
Able to add/remove fluff without issue - bug resolved over time
