### ISSUE TITLE
Blob spores don't like their blob

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#4877]
Reporting client version: 513.1542

## Round ID:
1321

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[TM-Only] Possible fix for hypnoflash not working](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4548)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Battery Component](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4827)

**Comment by Zergspower** [comment]
Confirmed still an issue with blobs - spores are shy

**Comment by Gandalf2k15** [comment]
Recently fixed https://github.com/Skyrat-SS13/Skyrat-tg/pull/12225
