### ISSUE TITLE
PDAs do not reset their alert display after you have read the PDA message

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4918]
## Round ID:

a lot

## Testmerges:

not relevant
## Reproduction:
PDAs have the alert screen after you get a message (it's a flashing exclamation). However if you read it the PDA does not revert back to its normal screen.

**Comment by maxymax13** [comment]
upstream problem

**Comment by tf-4** [comment]
Fixed with https://github.com/tgstation/tgstation/pull/58820

**Comment by ZephyrTFA** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/5412 fixes this.  @Funce
