### ISSUE TITLE
Eguns broken

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4944]
## What Map did this Issue occur on:
icebox

## Testmerges (If Applicable):
#3255: 'Sizeplay v 0.5' by Useroth at commit b622c77121
#4181: '[TM ONLY] Tick reserve test' by Azarak at commit 9af94c3ac9
#4548: '[TM-Only] Possible fix for hypnoflash not working' by MLGTASTICa at commit f433011d74
#4584: '[WIP] [DNM] Liquids system' by Azarak at commit a7e65808f4
#4900: 'Item use power and cell component refactor' by Gandalf2k15 at commit 69e7641de9

## Reproduction:
Energy guns seem to have been completely broken either by gun change PRs or by battery components. They don't shoot the right projectile / any projectile, you can't switch the mode (they're supposed to be disabler and laser), and they don't seem to have any charge indicator on the sprite.

**Comment by FlamingLily** [comment]
Tested privately, seems to work fine
