### ISSUE TITLE
Arrivals station is full of free vendors

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#4945]
## Reproduction:
All the vendors on the arrivals station are free, which should probably not be the case. It has several food vendors and a lot of clothing and toy vendors that normally at least require some amount of funds on your ID. Because it's off the station Z level, it incorrectly does not charge credits despite items having a credit cost.

**Comment by Zergspower** [comment]
Issue resolved since, items on interlink are purposefully set to free and unless a specific map was noted the current rotation does not have that problem
