### ISSUE TITLE
Uploading to curator library archive doesn't function

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#4951]
Reporting client version: 513.1542

## Round ID:
1366

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[TM-Only] Possible fix for hypnoflash not working](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4548)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Item use power and cell component refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4900)

**Comment by Zergspower** [comment]
Able to upload now, i recall this being an issue last year
