### ISSUE TITLE
Rockplanet doesn't spawn anymore?

### ISSUE THREAD

**Issue by Suspect-One** [Skyrat-SS13/Skyrat-tg#4954]
## Testmerges: 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4900

## Reproduction:
1. Spawn on DS-1.
2. Go to the cargo shuttle straight to the navigational console.
3. Notice that it doesn't have a destination because for some reason Rockplanet doesn't spawn anymore.

**Comment by KasparoVy** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4738#issuecomment-815411702

Disabled in #4738 w/ no CL :/

**Comment by Suspect-One** [comment]
oh ok.

**Comment by KasparoVy** [comment]
Yeah sorry, I'm pretty sad about it too but there's memory issues with having so much map assets in the game at once I guess. Enjoyed it very much myself but c'est la vie
