### ISSUE TITLE
New Bounty timer dropping below zero, so no new bounty.

### ISSUE THREAD

**Issue by Ethjax** [Skyrat-SS13/Skyrat-tg#4956]
## Round ID:
1371

## Reproduction:
On the civilian bounty control terminal, there is a "new bounty" button. After completing a bounty or on your first, you press it to get a new bounty and that works fine. If you press it when it's already offering you three, red text shows up saying:

 Internal ID network spools coiling, try again in 'int' minutes!

The 'int' is indeed an integer than ticks down, but when it hits zero it just flips to negative and you still can't get new bounties.

**Comment by Funce** [comment]
I don't think we have anything too different for the bounty system. Can this be tested on /tg/?

**Comment by Zergspower** [comment]
able to make new bounties without issuess
