### ISSUE TITLE
Multitool unable to pulse wires.

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#4969]
Reporting client version: 513.1536

## Round ID:
1377

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [Item use power and cell component refactor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4900)

## Reproduction:
Attempt to hack door.
Fail.
...?

**Comment by ZephyrTFA** [comment]
I cant reproduce this.

**Comment by unit0016** [comment]
It appears to have been fixed postround. I'm assuming https://github.com/Skyrat-SS13/Skyrat-tg/pull/4900 has something to do with it, being testmerged. Still glad I caught it.
