### ISSUE TITLE
Waterkilo waste is linked to it's distro

### ISSUE THREAD

**Issue by LeChatGuide** [Skyrat-SS13/Skyrat-tg#5007]
## Round ID:
1397 (probably irrelevant)

## Reproduction:
The map probably hasn't been updated after the recent smart pipes changes , so waste is directly connected to distro

![atmo bork](https://user-images.githubusercontent.com/78511020/115146520-1df31180-a057-11eb-9a16-62cbc10fb53c.png)

**Comment by tf-4** [comment]
Waterkilo, along with fluid mechanics, is dead in the water (😎) so this is no longer an issue
