### ISSUE TITLE
Cryopods not accepting ghost roles but do accept Heads of staff.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#5010]
Reporting client version: 514.1547

## Round ID:
1399

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [[Semi-Modular?] More narcotics](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4943)
- [[Semi-Modular] The return of SpaceBox.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4884)
- [Adjusts crunch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5008)

## Reproduction:

 Be Syndie crew, try to cryo (yes cryo was powered) can't cryo.

 

I could reproduce this with fresh spawned pods and spawned in crew members and head of staff on CC thunderdome so.

**Comment by Funce** [comment]
Fixed in #5011
