### ISSUE TITLE
Changling sting bug

### ISSUE THREAD

**Issue by Lonewolf23319** [Skyrat-SS13/Skyrat-tg#5021]
Reporting client version: 513.1542

## Round ID:
1404

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [[WIP] [DNM] Liquids system](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584)
- [[Semi-Modular?] More narcotics](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4943)
- [[Semi-Modular] The return of SpaceBox.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4884)

## Reproduction:
While in chameleon mode as a changling you can sting anyone you can see regardless of walls or distance

**Comment by FlamingLily** [comment]
Just tested this locally w/o tms.


wow. that's uh... a big oversight.

You don't even need to be in chamelion mode. just. sting.

**Comment by FlamingLily** [comment]
testing w/ tg code, it looks like an upstream issue so far, BUT

**Comment by Lonewolf23319** [comment]
Yeah I was switching hands while hovering over someone on the other side of the wall and realized I had gotten their DNA. Did a bit of testing and it worked with all the types of stings, just glad no one abused it, except for me that round

**Comment by FlamingLily** [comment]
https://github.com/tgstation/tgstation/pull/58946
