### ISSUE TITLE
Canisters can't change colors

### ISSUE THREAD

**Issue by LeChatGuide** [Skyrat-SS13/Skyrat-tg#5025]
## Round ID:
1409 (probably irellevnt)

## Reproduction:
When Relabeled , a canister will get a new name , but won't get a new color , instead keeping the basic one. This is also present on all tiers of canister . To try this, build a new canister , and try to relabel it .

![Capture d’écran 2021-04-19 141435](https://user-images.githubusercontent.com/78511020/115234694-9d491980-a119-11eb-824f-e208f6e54bbc.png)

**Comment by FlamingLily** [comment]
likely fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/5124
