### ISSUE TITLE
Shuttle Sounds are EXTREMELY loud.

### ISSUE THREAD

**Issue by Owai-Seek** [Skyrat-SS13/Skyrat-tg#5121]
## Round ID:

N/A

## Reproduction:

Be anywhere near cargo or arrivals and have your ears blasted out. Both sound effects (Docking, and Landing) are loud, but the landing one goes on for longer. They're both pretty loud compared to other ingame sounds.

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/5161
