### ISSUE TITLE
Give Bug

### ISSUE THREAD

**Issue by Primie-Problems** [Skyrat-SS13/Skyrat-tg#5247]
Reporting client version: 513.1542

## Round ID:
1506

## Reproduction:

Bug: When given items, sometimes the give option remains and cause the option to still appear on your screen, despite you already have the object.

Prompt would be spammed in chat _You moved out of range of Player-Name_ whenever moving.

**Comment by maxymax13** [comment]
upstream problem, offer code is like completely broken in general

**Comment by tf-4** [comment]
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/3044
