### ISSUE TITLE
Spacebox mapping error

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#5308]
the windoor doesn't look right. It should be bordering a desk, or not using a locker as a bordering wall at the very least.

![image](https://user-images.githubusercontent.com/10399117/116503720-50e2a400-a8a6-11eb-9c9e-010e06d45c5d.png)
@unit0016

**Comment by FlamingLily** [comment]
Or at the very, very least, anchor the locker down. It's unsecured as is, if I recall correctly.

**Comment by YakumoChen** [comment]
the desk is preferable since you have to at least climb a table or some other non-instant action to bypass the door otherwise.

**Comment by ZephyrTFA** [comment]
This was fixed by a map update apparentally. 
![image](https://user-images.githubusercontent.com/12817816/117084929-70e6ed00-ad16-11eb-9a35-48272e0b4431.png)

**Comment by ZephyrTFA** [comment]
@Funce
