### ISSUE TITLE
Invisi-shoes.

### ISSUE THREAD

**Issue by FlamingLily** [Skyrat-SS13/Skyrat-tg#5311]
## Round ID:
1559

## Testmerges:
#4181: '[TM ONLY] Tick reserve test' by Azarak at commit d3e60e933e
#3255: 'Sizeplay v 0.5' by Useroth at commit d0256aa2fc
#5095: '[TM READY] Ports NTSL from Yogstation' by tf-4 at commit 82066042cb
#5277: 'Makes mold a random event + spacevine overhaul' by Gandalf2k15 at commit a2843792f5

## Reproduction:
Spawn as paramed. No shoes.  Except you do have shoes. They're invisible.

Have heard word that this may affect other jobs/shoes. But uh, witnessed firsthand as a paramedic.

**Comment by KasparoVy** [comment]
Affects all shoes I think (?) in the GAGS PR: https://github.com/Skyrat-SS13/Skyrat-tg/pull/5181
