### ISSUE TITLE
Digitigrade worn sprite missing

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-tg#5328]
The digitigrade worn sprite of 
1. Colored sneakers (/obj/item/clothing/shoes/sneakers)
2. Colored jumpsuit and jumpskirt (/obj/item/clothing/under/color) (/obj/item/clothing/under/color/jumpskirt)
3. Prisoner Jumpsuit and jumpskirt(/obj/item/clothing/under/color/prisoner)
does shown when worn on character.
likely cause by #5181 

I attempt to fix this issue myself and the shoe work just fine,but when i tried the same method on uniform it just broke.and i have no idea how to fix that.
[here is the link of the shoe fix](https://github.com/Sonic121x/Skyrat-tg/tree/patch-1) 

## Reproduction:
Make a character with digitigrade leg and choose a job that start with those clothing such as assistant

**Comment by YakumoChen** [comment]
upstream issue, upstream fix going down the line
