### ISSUE TITLE
Changelog not showing/failing to fetch changes.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#5387]
Reporting client version: 514.1547

## Round ID:
1591

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Makes mold a random event + spacevine oldbase port](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5277)

## Reproduction: load changelog in server with changelog button or when you log in and have it pop up.
![gothun](https://user-images.githubusercontent.com/13283561/116782705-bc6c7300-aa58-11eb-877c-035fe0aeb745.png)

**Comment by jjpark-kb** [comment]
this was fixed
