### ISSUE TITLE
Reattached tail mood proc'd without removal first.

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-tg#5403]
Reporting client version: 513.1542

## Round ID:
1597

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Makes mold a random event + spacevine oldbase port](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5277)

## Reproduction:

As stated in title. I'm playing an anthro insect, and at some point within five minutes of starting the round and arriving from the interlink, it decided that my tail had been removed and reattached. I don't know if it's because I'm using mismatched parts or what. The tail on my character is a bee tail, so I don't know. I also don't know precisely when the glitch happened, as the mood was there on the first time I checked my character's moods.

**Comment by Funce** [comment]
#4546 Duplicate
