### ISSUE TITLE
[SUGGESTION] Add ACTUAL Seaweed as a thing that can be grown in botany

### ISSUE THREAD

**Issue by Sigmar-alkahest** [Skyrat-SS13/Skyrat-tg#5443]
using fucking KUDZU in order to make seaweed sheets for things like sushi is **_FUCKING_** stupid, and i cannot be the only one who thinks so, perhaps someone could make it so seaweed could be grown standalone in a hydroponics tray, since, ya know, that's growing plants in just nutrient-rich water? hell make it a mutation of some other plant like... fuck i dunno, starthistle? that things fucking pointless, give it a use!

**Comment by Gandalf2k15** [comment]
suggestions dont go here
