### ISSUE TITLE
Stuck Hallucinating After Curing Hallucigen Virus

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#5534]
Reporting client version: 514.1554

## Round ID:
1666

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

## Reproduction:
Get infected with Hallucigen virus
Hallucinate
Cure virus
...keep hallucinating.

**Comment by ZephyrTFA** [comment]
Curing the virus won't remove your hallucinations. Talk to the psychiatrist or take some Synaptizine

**Comment by unit0016** [comment]
> Curing the virus won't remove your hallucinations. Talk to the psychiatrist or take some Synaptizine

Genuinely stupid. Mood mechanics n' psychology mechanics.
