### ISSUE TITLE
Miner Kinetic Crusher Ranged Attack Fails to Register Hitting

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#5540]
Reporting client version: 513.1542

## Round ID:
1672

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

**Comment by FlamingLily** [comment]
Do you recall if it occurred on any other creatures? Or just the xeno?

**Comment by Erokusan** [comment]
Uncertain if it was any other creatures, haven't heard or seen any complaints about it from anything else

**Comment by Zergspower** [comment]
Rework to the crusher changed the alt-fire to only affect giant targets rather than everything.
