### ISSUE TITLE
PAI Loudness Booster not working

### ISSUE THREAD

**Issue by DonutWorm** [Skyrat-SS13/Skyrat-tg#5542]
## Reproduction: Download the Loudness Booster as a PAI and try to press the "Import Song" button or "Make New Song" button, Respective names not remembered

The issue encountered is that trying to import a song to use or trying to make a new song while using the Loudness Booster feature as a PAI causes the window to crash, or in certain circumstances after turning back into a card being un-openable and inaccessable.

**Comment by TetrakoHateThis** [comment]
Would also like to add on the following issues from [this issue made in March](https://github.com/Skyrat-SS13/Skyrat-tg/issues/4240) seem to be on top of this - pAI seems to be riddled with issues preventing even its general functionality.
