### ISSUE TITLE
Autolathe fails to return recycled components

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat-tg#5571]
Reporting client version: 513.1542

## Round ID:
1680

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

## Reproduction:

An overzealous scientist printed several hundred stock parts, and we were encountering material shortages for other reasons besides. In an effort to recycle, I laboriously sorted and manually dropped a heap of T1-T3 parts into a basic T1 autolathe constructed at science, checked that the components were indeed counted among the materials stored, and deconstructed the machine.

Stored materials disappeared into the void, including all but the iron and glass used for the construction of the machine - it returns only the machine components, and none of the materials added to its internal storage. Reconstructing on the same space, just in case, does not retain the materials - they're simply gone.

On a related note, science really needs a better, less tedious means of recycling stock parts than individually autolathing them.

**Comment by ZephyrTFA** [comment]
Push broom, disposal bin.
Upgrading the recycler makes it give 100% material back.

**Comment by Zergspower** [comment]
Autolathe values and function tested and working correctly - an upgraded lathe also produces a higher return. No issue found in testing
