### ISSUE TITLE
Completely Broken APC's Sometimes Don't Cooperate

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#5578]
Reporting client version: 513.1542

## Round ID:
1685

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

## Reproduction: While unsure of the frequency of it occurring, when trying to fix an APC, some believe to break it until the cover breaks off, then remove the power cell, unscrew the electronics, and then crowbar out the broken electronics. Sometimes it seems to bug out and you can't remove the electronics, and you can't destroy the apc with damage either.
The bug is involving the step before removing the electronics from a "falling apart" apc.

**Comment by Zergspower** [comment]
Tested on about 10 APC's with no replication found, and in the past couple of months I've not come across this myself. Assuming bug fixed itself over time
