### ISSUE TITLE
Clock Cult AI Conversion

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#5580]
Reporting client version: 513.1542

## Round ID:
1686

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

**Comment by Vizoplez** [comment]
Known issue, will be resolved, ty anyway 👍 3

**Comment by tf-4** [comment]
@Funce CWC was closed
