### ISSUE TITLE
Bugged sprites for the wooden bow (maybe for the other bows too)

### ISSUE THREAD

**Issue by ZandraEmmie** [Skyrat-SS13/Skyrat-tg#5591]
## Reproduction: 
Step 1; grab 25 wooden planks and 2 string (to make string grab 2 pieces of cloth and make string in the crafting menu in the miscs section all the way down to the bottom)
Step 2; make the wooden bow that is in the crafting menu in the tribal section
Step 3; Put the wooden bow on your back slot
Step 4; glitched sprite

**Comment by Cheshify** [comment]
Fixing this now

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/5859
