### ISSUE TITLE
Ice Wyrm's Ice Breath Permanent Visual Ice Block

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#5592]
Reporting client version: 513.1542

## Round ID:
1695

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[FIXED] [MOSTLY MODULAR] Alt titles](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5150)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][DNM] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)

**Comment by KasparoVy** [comment]
Lmfao, that's happened to me 20210507 and it was bloody hysterical.
![skyrat ss13 Falls-Into-Chasms gets stuck in an ice block 20210507 1](https://user-images.githubusercontent.com/12377767/117688563-69a56080-b1a8-11eb-9d08-e9a04c639aaa.png)

**Comment by Zergspower** [comment]
Unable to replicate - given the age this most likely has been resolved.
