### ISSUE TITLE
[VISUAL] [MINOR] Alternative titles do not receive related symbols on (ghost's?) crew manifest

### ISSUE THREAD

**Issue by NopemanMcHalt** [Skyrat-SS13/Skyrat-tg#5608]
## Round ID:
N/A (local test)

## Testmerges:
N/A (local test)

## Reproduction:
1. Observe or go ghost;
2. Select Ghost tab and click on "View Crew Manifest" (or type it in the chat);
3. See that "Civilian" (Assistant) doesn't get its infinity sign (aka "No position limit" symbol), while "Commanding Officer" (Captain), "Executive Officer" (Head of Personnel) and etc. doesn't get their related commanding symbols.

## Media:
![image](https://user-images.githubusercontent.com/36963049/117860839-6ccc4980-b299-11eb-9ba8-e3faa41c345e.png)

**Comment by thestubborn** [comment]
oh shit yeah, this
no idea how this even works, lol, like even base game

**Comment by thestubborn** [comment]
this is a tgui thing actually

and I personally ain't gonna fuck with tgui

**Comment by FlamingLily** [comment]
aye me neither

**Comment by Zergspower** [comment]
Bug resolved in a later enhancement, no longer reproducible
