### ISSUE TITLE
Plungers don't interact with geysers (#5525 non-functional)

### ISSUE THREAD

**Issue by Muffindrake** [Skyrat-SS13/Skyrat-tg#5633]
## Round ID:
1722

## Reproduction:

- Acknowledge that #5525 was merged to your server
- Acquire plunger
- Acquire geyser
- Acquire colon closing parenthesis after attemping to activate a geyser with a plunger
- Bug acquired

**Comment by Muffindrake** [comment]
In my limited understanding of this esteemed code base, the attack_by method should probably check whether the item that is being used is a plunger, and call plunger_act if that's true. Right now it just returns if the item you use on a geyser isn't a mining scanner.

Should probably also remove the check for _reinforced in plunger_act.

**Comment by Funce** [comment]
Fixed in #5718
