### ISSUE TITLE
Vault Monitor Can't Work More Then Once

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#5634]
Reporting client version: 513.1542

## Round ID:
1723

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)
- [[Semi-Modular] Security Sergeant Update + Trim Tokens! (Plus Fixes)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5440)

**Comment by FlamingLily** [comment]
This happens on any single camera monitor, notably the toxins bomb range, as well

**Comment by Zergspower** [comment]
Camera for the vault is now tied to the QM's camera console not the station one - unable to reproduce with these parameters.
