### ISSUE TITLE
Ashwalker's Bugs Are Bugged

### ISSUE THREAD

**Issue by UltimateFluff** [Skyrat-SS13/Skyrat-tg#5649]
## Testmerges:

#5473 
#5418 
#4757 
#4690 
#3255 

## Reproduction:

Normally, how it's *supposed* to work is that the gibs that comes from anything sacrificed to the tendril gets eaten by the two bugs that exist in the nest room, and after a while, will produce milk - this is to provide ashwalkers a liquid means of slowly healing the common damage type they encounter, brute. However, at some point, they just...stopped eating gibs, so not only does the nest room become flooded with gibs that eventually rot, but the ashwalkers are denied one of their healing sources, not to mention that it sort of invalidates both the bugs existing in there in the first place, and why the mushroom bowl in the Tribal tab was even made a thing (as the only thing ashwalkers used to have was a bucket, and it made things hard to grow cactus fruit when your only bucket was holding milk). It's uncertain *when* this issue cropped up, if it's upstream or just here downstream, but it's kind of disappointing that the bugs ended up...bugged and it screws over an already survivalist ghost role out of something else they have in their limited pool. Plus, the bugs are cute and just look like round, innocent beetles that clean the place of gore.

Also, apologies if this isn't exactly done to specs, I haven't done this in a long while (and only did it once, to boot) so I'm just screaming internally as I try to remember the last time I did a bug report and hope I remember everything right.

**Comment by NullDagaf** [comment]
"upstream issue"
I think.

**Comment by Zergspower** [comment]
Udders no longer dry - test and works currently
