### ISSUE TITLE
Entering a Hilbert's Hotel room as a member of cybersun (captain or crewmember) gibs you

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-tg#5656]
Reporting client version: 513.1538

## Round ID:
1727

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)
- [[Semi-Modular] Security Sergeant Update + Trim Tokens! (Plus Fixes)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5440)

## Reproduction:

Hasn't happened to me, but as far as I'm aware simply going into a Hilbert's Hotel room as either of those roles will just gib you. Haven't tested locally.

**Comment by FlamingLily** [comment]
Tested locally
![image](https://user-images.githubusercontent.com/80451102/118230176-91f6cd00-b4d0-11eb-9653-bc708cc5f6a1.png)
![image](https://user-images.githubusercontent.com/80451102/118230710-704a1580-b4d1-11eb-9698-594ab18126f8.png)
Seems to work fine

**Comment by tf-4** [comment]
Apparently it's intended behaviour when picking up the hotel as you enter it. So yeah. Just coincidence that it happened with CSun both times.
