### ISSUE TITLE
Lings that turn into humonkeys trip over themselves.

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-tg#5678]
Reporting client version: 513.1538

## Round ID:
1729

## Testmerges:
- [[TM ONLY] Tick reserve test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4181)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[SEMI-MODULAR]CWC Port from Beestation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4757)
- [[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)
- [[Semi-Modular] Security Sergeant Update + Trim Tokens! (Plus Fixes)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5440)

## Reproduction:

Not reproduced it yet, will do when I get time. Changeling turned into a monkey and back, and got "X falls over X!" every time they tried to walk, sending them to the floor.

**Comment by FlamingLily** [comment]
Think this happens with mind magnified monkeys, too

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/7146
