### ISSUE TITLE
Chaplain's null rod in their bag won't let them change it's skin.

### ISSUE THREAD

**Issue by ZandraEmmie** [Skyrat-SS13/Skyrat-tg#5680]

**Comment by SarmentiCampbell** [comment]
Need more information, was there more chaplains or were you the only chaplain?

**Comment by ZandraEmmie** [comment]
There can be only one chaplain, so I was the only chap. (unless paper
mishap happens but I was the only chap)

**Comment by Funce** [comment]
Were you a late join Chaplain? That's a functionality that needs to be updated, only one nullrod can be form changed. Counting from the start of each round.

**Comment by ZandraEmmie** [comment]
Yeah I was a late join. Alrighty!

**Comment by Zergspower** [comment]
tried to replicate and was unable - but may be a design feature as the first chaplain may force something in the sect code to be 'set' rather than by person
