### ISSUE TITLE
Reimplement xenotongue/hivespeak for xenohybrid crew.

### ISSUE THREAD

**Issue by Ross-665** [Skyrat-SS13/Skyrat-tg#5684]
As discussed in the Q&A on the 14/05/2021, the question as to why xenohybrid crew did not have access to the xenotongue/hivespeak language, despite a variety of languages being implemented and available to the crew already. I understand it was originally removed since there was a concern about hybrid crew and feral antags teaming up, but since ferals are not in the current rotation, it seems a bit odd to not have the language available outside of being the curator, since it limits RP possibilities.

**Comment by Zergspower** [comment]
Language is in the current build

**Comment by Ross-665** [comment]
.....It wasn't when I made the issue. Which was nearly a year ago.
