### ISSUE TITLE
Geneticist not selectable round start.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#5699]
Reporting client version: 514.1547

## Round ID:
1739

## Testmerges:
- [Expeditionary corps + Black Mesa + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

**Comment by unit0016** [comment]
Not a bug, done on purpose with the genetics nerfs

**Comment by tobjv** [comment]
> Not a bug, done on purpose with the genetics nerfs

Um, "Honestly it was just for the April fools I had assumed it was reverted

**Comment by tobjv** [comment]
https://discord.com/channels/596783386295795713/647323868423520256/843088320933658654

**Comment by Funce** [comment]
Config? @hugmeorelse

**Comment by tf-4** [comment]
Has been fixed
