### ISSUE TITLE
Gateway missions can be teleported out of by any item instead of just gateway.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#5704]
Reporting client version: 514.1547

## Round ID:
1739

## Testmerges:
- [Expeditionary corps + Black Mesa + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

**Comment by Swiftfeather** [comment]
Let's see how #5971 does.

**Comment by tf-4** [comment]
^
