### ISSUE TITLE
ghosts can remove power cells from items with the battery components

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-tg#5735]
## Round ID:
1752

## Reproduction:

be a ghost, orbit next to any thing with a battery component, aka a flash light, gas analyzer, health analyzer, and ctrl shift click it, even as a ghost, plop a batter cell pops out depowering the device leaving someone in the dark

**Comment by Cheshify** [comment]
Right, I actually testing this on private AND on main. Ghosts can do this on both, but they need to be on the floor or on a table.

**Comment by Cheshify** [comment]
NEVERMIND THEY CAN DO IT IN HAND OH GOD THIS IS BAD

**Comment by Funce** [comment]
Fixed in #5888 
@GoldenAlpharex Be sure to include `fixes #issuenumber` in your PRs so they close the issues applicable when merged.

**Comment by GoldenAlpharex** [comment]
> Fixed in #5888
> @GoldenAlpharex Be sure to include `fixes #issuenumber` in your PRs so they close the issues applicable when merged.

I didn't actually know there was an issue about it, whoops!
