### ISSUE TITLE
Cybernetic Ears don't look like the ears set in preferences.

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#5736]
Reporting client version: 514.1554

## Round ID:
1751

## Testmerges:
- [Expeditionary corps + Black Mesa + Trusted Player System[TBA(WIP)]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

## Reproduction:
Please. For the love of god. Change it so that cybernetic ears will look like the ones you set in your preferences. I set myself to DNR every time a doctor prints cybernetic ears for me because it looks so jarring without regular ears. I just did this round, in fact. Please. PLEASE. PLEASE.

**Comment by Fikou** [comment]
Please. For the love of god. Change it so that cybernetic ears will look like the ones you set in your preferences. I set myself to DNR every time a doctor prints cybernetic ears for me because it looks so jarring without regular ears. I just did this round, in fact. Please. PLEASE. PLEASE.

**Comment by Zergspower** [comment]
SAD resolves all character deformities such as this

**Comment by unit0016** [comment]
fun copypasta this was but this is almost a year on now leave me alone thanks
