### ISSUE TITLE
AI sat Securitron immobile  / unable to move to AI remote control

### ISSUE THREAD

**Issue by Strazyplus** [Skyrat-SS13/Skyrat-tg#5746]
## Reproduction:  

Step one: play as AI.
Step two: attempt to move the beepsky in AI to any floor tile on the sat.
step three: cry in dispair as the beepsky refuses to obey and calls you a nerd.

Some time ago this beepsky (no matter what map) used to be control-able and moveable on the AI Sat. now I can't move it at all on any map.

Why is this important. if theres baddies on the AI sat having control of your last line of defense is vital for AI defense. having it broken is crippling for rather already easily-to-overcome-defenses.

**Comment by YakumoChen** [comment]
What map

**Comment by Strazyplus** [comment]
All maps (I have not found a map that does not suffer from this. and this bug is specifically tied to the AI sat, the bots work on the station just fine.

**Comment by Zergspower** [comment]
Unable to recreate - AI Sat beeps starts as stationary but can be moved and interacted with if forced

**Comment by YakumoChen** [comment]
I only see this problem occur if the bot is off camera or you're trying to move a bot to a tile with a dense object or between the sat and station

**Comment by Strazyplus** [comment]
Forgot about this old bug report, I cant recall when it got fixed but clearly was a undocumented fix. I will assume its fixed on all maps as sometimes it'd be map specific it can be weird like that. This "bug" will rear its head again whenever someone screws with bots. its one of those reoccurring bugs as I can recall two other times in span of three years of something like this occuring.

anyway closing.
