### ISSUE TITLE
Being assigned as a Traitor can place non-whitelisted players into the Clown role and add them to the whitelist

### ISSUE THREAD

**Issue by faaaay** [Skyrat-SS13/Skyrat-tg#5757]
## Round ID:  
If you discovered this issue from playing tgstation hosted servers:   
[Round ID]: Currently uncertain.   

## Testmerges:  

#3255: 'Sizeplay v 0.5' by Useroth at commit 63855a05a7  
#5473: '[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'' by GoldenKeyboard at commit 7615a6679c  

## Reproduction:  

Before the round began, my job preferences were set as follows:   
- Quartermaster as High  
- Atmospheric Technician and Cargo Technician as Low  
- Be an Assistant if preferences unavailable  
- All antagonist roles disabled except for Traitor  
At the start of the round, I was assigned as a Clown, despite not being whitelisted for this job. I was also a traitor. After the end of that round, **I saw that the Clown role was now able to be assigned a priority and that I could select it when joining the game.**

**Comment by Funce** [comment]
First part is related to #5418
Second part is related to the _lack_ of the test merge of the above PR while the clown was enabled.
