### ISSUE TITLE
Disposals Recycling room is broken

### ISSUE THREAD

**Issue by CCorvet** [Skyrat-SS13/Skyrat-tg#5779]
Reporting client version: 513.1542

## Round ID:
1782

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5473)
- [[TM ONLY] Pre-'ports' tgs looping sounds fix, until merged upstream [DNM] i dont know any other tags](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5759)

## Reproduction:

On several maps, such as iceboxstation and i'm pretty sure others, (Though not delta, i checked), the recycling machine and the conveyor belt under it are missing.
Another issue is, that the stacking machine in the recyclying room, unilaterally doesnt seem to work. The only object that i saw it pick up, was monkey hide. Not steel or glass, even if i throw that on the conveyor right next to it.

**Comment by YakumoChen** [comment]
Upstream issue

**Comment by ZephyrTFA** [comment]
This is caused by a bug with connect_loc causing the recycler to quite simply eat itself.

**Comment by YakumoChen** [comment]
The fix is already upstream iirc
