### ISSUE TITLE
PAI hat sprite bug

### ISSUE THREAD

**Issue by Echopsychotic** [Skyrat-SS13/Skyrat-tg#5821]
## Testmerges:
#3255: 'Sizeplay v 0.5' by Useroth at commit 63855a05a7
#5473: '[SEMI-MODULAR][READY] Recreates the admin verb 'Create Antagonist(s)'' by GoldenKeyboard at commit f4e6546030
#5418: 'Expeditionary corps + Black Mesa + Trusted Player System[TBA(WIP)]' by Gandalf2k15 at commit a2cf2aa163
#5767: '[NONMODULAR] Ports Arcing APCs from paradise.' by FlamingLily at commit 3b60cc9a9e

## Reproduction:
Put a pAI cat or something similar on your head

**Comment by thestubborn** [comment]
are they showing weird?
not showing at all?
etc, etc
because if its the latter that's an east fix, just drop the old on head icons into the new folder for heads

**Comment by Zergspower** [comment]
able to put little critters on your head again
