### ISSUE TITLE
Crusader Belt has no textures

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#5854]
Reporting client version: 513.1542

When built the crusader belt has no textures whatsoever, completely invisible.
## Round ID:
1830

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Black Mesa + Trusted Player System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[NONMODULAR] Ports Arcing APCs from paradise.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5767)
- [[TM-ONLY][IMPORTANT][NONMODULAR]Disables mold until gandalf fixes it](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5848)

## Reproduction:

Build the crusader belt as normal and it should be invisible

**Comment by ghost** [comment]
's my item, I'll look into this. Thanks for the report!

**Comment by ghost** [comment]
Tested, works fine
https://gyazo.com/845eb1ee2dc13e34c3c40aaafe3f7f61
Might have been cache issues, code-wise its clean. This can probably be closed @Funce
