### ISSUE TITLE
Solar flares bugged. Minimal was extreme

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#5863]
Reporting client version: 514.1547

## Round ID:
1836

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [Expeditionary corps + Black Mesa + Trusted Player System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5418)
- [[NONMODULAR] Ports Arcing APCs from paradise.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5767)
- [[TM-ONLY][IMPORTANT][NONMODULAR]Disables mold until gandalf fixes it](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5848)
- [[NON-MODULAR][TM-FIRST] Cryopods can now store items.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5857)

## Reproduction: as random chance the Mass ejections stated as minimum showed up as extreme.
![eject wrong](https://user-images.githubusercontent.com/13283561/119234595-c8e66780-bafc-11eb-9e5d-882b7f87d005.png)
![eject](https://user-images.githubusercontent.com/13283561/119234596-c97efe00-bafc-11eb-816f-5929f35a121f.png)
![eject2](https://user-images.githubusercontent.com/13283561/119234597-c97efe00-bafc-11eb-9669-81877b0698fb.png)

**Comment by Gandalf2k15** [comment]
Ah, its just the event naming convention.
