### ISSUE TITLE
Civil Disputes Officers have detective access.

### ISSUE THREAD

**Issue by LeChatGuide** [Skyrat-SS13/Skyrat-tg#5865]
## Round ID:
1839

## Reproduction:
join in as Civil Disputes Officer and try to open the detective's office. it's not a map issue , since they also can open their lockers.

**Comment by Cheshify** [comment]
What map was it, still matters

**Comment by FlamingLily** [comment]
Ah, really? Shit.

**Comment by LeChatGuide** [comment]
it was on meta I think ?
