### ISSUE TITLE
Non admin have access to Toggle Delete Sparks 

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-tg#5881]
## Reproduction:
Take a look in the preferences tab
clicking it as non admin wouldn't do anthing though
![image](https://user-images.githubusercontent.com/64410541/119269503-9175d900-bc2a-11eb-98f9-5af8810bef34.png)
#5791

**Comment by Zergspower** [comment]
Issue assumed resolved with the rework of the game preferences menu - Option appears after admin role has been granted
