### ISSUE TITLE
Modular Tablet/Laptop/PC Issues & PDA Newscaster issue

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-tg#5886]
## Round ID: 
1854

## Reproduction:
Using the modular tablet, the Atmos app will fail to update its variables and instead show 0c and 0kpa at all times. Also using the ChatRoom app will crash the TGUI to bluescreen, and since you can't refresh it, the tablet becomes unusable.

PDA Newscaster app has problems also, stating there are no news feeds even after one has been created and not being able to see main station announcements.

**Comment by FlamingLily** [comment]
Upstream, pretty sure

**Comment by ZephyrTFA** [comment]
I have tested both of these things and these issues are not reproducible.
@Funce do we have a [Cannot Reproduce] label?

**Comment by Zergspower** [comment]
unable to replicate: due to the age of this bug report assuming resolved over time.
