### ISSUE TITLE
Ice Box Station Equipment Room Vendor out of place

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#6000]
Reporting client version: 513.1542

## Round ID:
1897

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[MODULAR][TM-FIRST][READY] Interaction Menu Framework and Basic Interactions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5884)

**Comment by tf-4** [comment]
This was fixed in one of the many map resets.
