### ISSUE TITLE
Syndicate Bioweapons Spawner Ghost role - unusable vendors

### ISSUE THREAD

**Issue by Kalesonki** [Skyrat-SS13/Skyrat-tg#6006]
## Reproduction:

![obraz](https://user-images.githubusercontent.com/79363897/119860650-d6de2300-bf16-11eb-9d71-597781a5e7df.png)
Syndicate weapon scientists spawner roles are unable to use vending machines, unless using IDs with linked account (ergo: robbing people).

**Comment by unit0016** [comment]
Known Issue. Happens only on Icebox, part of the middle cave z-level being considered part of the station. Literally nothing we can do about it.

**Comment by ghost** [comment]
> 
> 
> Known Issue. Happens only on Icebox, part of the middle cave z-level being considered part of the station. Literally nothing we can do about it.

Does the vendor really go off area code? We can't remove the prices from the vendor type itself?

**Comment by ghost** [comment]
yep, easy fix :) just needed to var-edit the Vendors' **onstation** variable to zero in the map

**Comment by unit0016** [comment]
> yep, easy fix :) just needed to var-edit the Vendors' **onstation** variable to zero in the map

Did you actually test it? Because I swear I did exactly this before the original remap and it didn't fix anything.

**Comment by unit0016** [comment]
Fixed, close this issue out.
