### ISSUE TITLE
player characters disappear when laying down

### ISSUE THREAD

**Issue by esf345** [Skyrat-SS13/Skyrat-tg#6024]
## Round ID:
any round

## Testmerges:
unknown

## Reproduction:
i do not know how to reproduce this bug however it has happened since i reinstalled windows 10 and installed byond with latest beta version and any player character including my own will disappear when laying with the head facing to the right on anything bed, table, floor, and so on the player characters do not even show up on the pop up window when shift right clicking but i still see words appear above them when talking, and this only human shaped characters cyborgs and robots are fine

before![Capture](https://user-images.githubusercontent.com/77134459/120060312-ebe8ae00-c00b-11eb-9a8f-0e07653076f7.PNG)

after![Capture2](https://user-images.githubusercontent.com/77134459/120060323-f440e900-c00b-11eb-9a04-e077b25b6028.PNG)

**Comment by ZephyrTFA** [comment]
This is an issue with Byond beta. Switch to Stable.

**Comment by tf-4** [comment]
@Funce byond issue that i think is resolved anyway
