### ISSUE TITLE
Examine icon missing

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-tg#6036]
## Round ID:
Localhost

## Reproduction:
shift click some item
current:
![image](https://user-images.githubusercontent.com/64410541/120110297-77df0f00-c19f-11eb-9ad5-a8e19f626a9e.png)
what should happen(on tgstation):
![image](https://user-images.githubusercontent.com/64410541/120104989-a7831c80-c189-11eb-9a5f-dd5d52ecbcd6.png)

**Comment by FlamingLily** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/5182

**Comment by tf-4** [comment]
@Funce #5182
