### ISSUE TITLE
load away mission issue

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-tg#6040]
## Round ID:
Localhost

## Reproduction:

- Load a away mission like snowdin or blackmesa.

Loading away mission cause lots of problem.
includeing:

1. unable to get backup after slip or knockdown(only able to craw around)(unless useing fullheal)
2. atmospheric complete lock up(gas stay in same tile)(pipe stop working)
3. Machine stop working correctly(like reaction chamber stop heating up reagent)
4. Random spark spawning with no reason(just move around and you will see them)

load away mission from round start useing config setting seems to be fine.

**Comment by tf-4** [comment]
Just symptoms of high TD - not purely an away mission issue.
