### ISSUE TITLE
Issue in Genetics

### ISSUE THREAD

**Issue by Kraos052** [Skyrat-SS13/Skyrat-tg#6045]
It seems that the DNA console is having the inability to transfer mutations from disk to console. It always brings up an ERROR message every time you try to do it.

"ERROR: This mutation is anomalous, and cannot be saved."
(This was with the Medieval mutation)

![ERROR in Skyrat](https://user-images.githubusercontent.com/32678874/120126948-d4d0ca00-c18b-11eb-81ad-7b2b26462c07.PNG)

**Comment by Sigmar-alkahest** [comment]
not just that, it's with ALL mutations.
source: i am a genetics player aswell.

**Comment by softcerv** [comment]
https://github.com/tgstation/tgstation/pull/59785
Is currently being fixed with this PR

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/6534
