### ISSUE TITLE
Loss of static as AI.

### ISSUE THREAD

**Issue by ChronoRigger** [Skyrat-SS13/Skyrat-tg#6061]
Reporting client version: 513.1542

## Round ID:
1935

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[MODULAR][TM-FIRST][READY] Interaction Menu Framework and Basic Interactions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5884)

## Reproduction:

Basically ghost vision as an AI. No need to see through cameras
I'm not exactly sure how to do it but here's how it went for me. 

I'd start lagging lots ( round 180 ping then it jumps to 1100 ) whilst moving around. This would cause the reconnect prompt to appear. Reconnecting and just waiting it out makes it happen anyways. After it passes, when i look around, there'd be no static.
I believe I have to be looking somewhere with no static in the first place to make it happen as I only then realise that the bug is active when I pan over to some part that isnt usually covered by cams.

Many things break this such as jumping to a person or moving layers. Or just lagging again. It most it had given me 20 minutes of free ghost vision at one time, thankfully it was on an uneventful shift. Images attached. Notice the lack of static.

![dreamseeker_X63NojYV0u](https://user-images.githubusercontent.com/50192958/120234609-3a18cf80-c20d-11eb-9983-3aae06cabdb3.png)
![dreamseeker_PkAHnN526N](https://user-images.githubusercontent.com/50192958/120234623-400eb080-c20d-11eb-9d50-fb533f731fab.png)
![dreamseeker_hXACGkrUQ4](https://user-images.githubusercontent.com/50192958/120234688-59176180-c20d-11eb-8614-623a8f97eb93.png)

As a side, Multi-cam mode removes darkness, rendering lighting moot
![dreamseeker_i06JZACH99](https://user-images.githubusercontent.com/50192958/120234750-76e4c680-c20d-11eb-974c-ac3b0618abf0.png)

**Comment by ChronoRigger** [comment]
Oh right, i failed to mention how it also let me see Xenos trying to nest in maint as well as antags doing antag stuff. I'll add more to this as commends and report my observations to better see how to replicate it.

**Comment by ZephyrTFA** [comment]
This is an issue where your client has fallen behind the server and so it skips some vital things to try and get back in sync with the server.

TL;DR: You lagged so it didn't send the static overlay

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10652
