### ISSUE TITLE
Heat Exchangers not moving heat to space 

### ISSUE THREAD

**Issue by DuffCreeper** [Skyrat-SS13/Skyrat-tg#6107]
## Round ID:

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # 1964

## Testmerges:

#3255: 'Sizeplay v 0.5' by Useroth at commit 63855a05a7
#5884: '[MODULAR][TM-FIRST][READY] Interaction Menu Framework and Basic Interactions' by ZephyrTFA at commit 38923468cc

## Reproduction:

![image](https://user-images.githubusercontent.com/25504173/120663832-be00df00-c4cd-11eb-8101-2c5135195505.png)
![image](https://user-images.githubusercontent.com/25504173/120663910-d244dc00-c4cd-11eb-8c37-480742c78c32.png)

Basically spent a round having delams that never cooled down once proper steps were taken. Did many theory testing and learnt the fucking space loop never cooled down and just somehow stayed in this mediation of being hot. Mind you it was fully bypassed and the gas never moved from the heat pipes so they should be cooling.

Results of analysis of  the grey pipe.
Moles: 1576.09 mol
Volume: 5250 L
Pressure: 5853.58 kPa
Nitrogen: 99.81 % (1573.03 mol)
Plasma: 0 % (0.01 mol)
Carbon Dioxide: 0.08 % (1.33 mol)
Water Vapor: 0.03 % (0.45 mol)
Oxygen: 0.08 % (1.25 mol)
Tritium: 0 % (0.01 mol)
Temperature: 2073.24 °C (2346.39 K)

Like bruh theres no fusion going on

**Comment by FlamingLily** [comment]
Ah yes, thermal dynamics in action. Realistic, not an issue 😎 /j

Which map was this?

**Comment by DuffCreeper** [comment]
> Ah yes, thermal dynamics in action. Realistic, not an issue 😎 /j
> 
> Which map was this?

It'd be the NSS Journey

I went out of my way to try and replicate the issue but I wasn't able to manage it so I'm not sure what happened for this one

**Comment by tf-4** [comment]
Atmos has generally been shitting the bed recently, don't think it's a mapping issue

**Comment by DuffCreeper** [comment]
> Atmos has generally been shitting the bed recently, don't think it's a mapping issue

Nah I assumed it wouldnt be a mapping issue. If it was then I would've picked it up. Otherwise yeah the only fix for this is to keep engineering aware that they seriously need to valve that space loop or else that SM will delam

**Comment by tf-4** [comment]
This is fixed - though I'm unable to find the specific PR. Feel free to re-open if it's still an issue.
