### ISSUE TITLE
AI nameing scheme reverting back to random.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#6152]
Reporting client version: 514.1547

## Round ID:
1986

## Testmerges:
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[MODULAR][TM-FIRST][READY] Interaction Menu Framework and Basic Interactions](https://github.com/Skyrat-SS13/Skyrat-tg/pull/5884)
- [[DNM] [TM-ONLY] FLAVOUR TEXT TEMPORARY REVERT](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6116)

## Reproduction: Note: this is for late join. Hard to repeat this but AI players have been reporting their names not being used for their AI models.
If it is set to say DANDY it can just random to T-1000.

In this case it was F.A.I.T.H. whos name did not work.

**Comment by tf-4** [comment]
Since fixed.
