### ISSUE TITLE
Security Sergeant Roundstart spawn is busted

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#6201]
Reporting client version: 513.1542

Round start security sergeants start at the interlink instead of on station.
## Round ID:
2016

## Testmerges:
- [[DNM] [TM-ONLY] FLAVOUR TEXT TEMPORARY REVERT](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6116)

## Reproduction:

Check the spawn areas for Security Sergeants or just spawn in as a sec sergeant round start.

**Comment by tf-4** [comment]
Security sergeant has since been removed
