### ISSUE TITLE
[NEEDS DEBUGGING] Quirks Resetting

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#6260]
## Round ID:
Repeat Issue

## Testmerges:
Across Several Month's Timespan, many PRs were TM'd and un-TM'd.

## Reproduction:
Be Ruby Miller
attain quirks
spawn in as ghostrole
...Quirks reset in prefsmenu afterwards randomly... for some reason.

My hunch is that this has something to do with augmentations.

**Comment by Zergspower** [comment]
Quirks no longer reset after leaving a ghost role, character creation rework resolved this. Unable to recreate in current build
