### ISSUE TITLE
Bluespace body bag when fried can not be opened.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#6283]
Reporting client version: 514.1547

## Round ID:
2051

## Testmerges:
- [[TM-ONLY] Pellet cloud tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6257)

**Comment by unit0016** [comment]
This is how deepfrying works. Deepfrying pets works similarly. Also, upstream thing.

**Comment by FlamingLily** [comment]
I think the issue is that, normally inside a bluespace bodybag, you can resist to try and escape, but you can't in this example.

**Comment by Zergspower** [comment]
Deep drying changes the state of the object to no longer be usable and edible, would be either an upstream enhancement or feature of the game
