### ISSUE TITLE
Icebox perma has mapping errors

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-tg#6403]
@KathrinBailey 

Icebox has several mapping errors around perma due to perma's design and size expanding.

[Round ID]: # 2119

Testmerges: none relevant to mapping

Reproduction:

![image](https://user-images.githubusercontent.com/10399117/122660919-d3843300-d174-11eb-9b07-67c0f0777f68.png)
The 'chasm moat' is filled over with rocks, allowing much easier access to free prisoners from that angle

![image](https://user-images.githubusercontent.com/10399117/122661052-e5b2a100-d175-11eb-8772-169755109bcd.png)
Prison Atmos is not connected to anything. The pipes running to the prison are nonsensically connected - it should be airgapped through Prison Atmos to allow a controlled flooding of N2O.

![image](https://user-images.githubusercontent.com/10399117/122661085-375b2b80-d176-11eb-94e4-a905841ade4f.png)
Transfer does not have a chasm like it is supposed to. The actual chasm is not moved to line up with it.

**Comment by YakumoChen** [comment]
![image](https://user-images.githubusercontent.com/10399117/122661789-9e301300-d17d-11eb-846d-8141b4da6a8f.png)
this is probably not normal

**Comment by tf-4** [comment]
Atmos and escape pod issues still relevant, others fixed
