### ISSUE TITLE
Stamps de-sync with cursor on scroll. 

### ISSUE THREAD

**Issue by Ironnhawk** [Skyrat-SS13/Skyrat-tg#6430]
Reporting client version: 514.1557

## Round ID:
2132

## Testmerges:
- [S&T Additional Emotes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6259)
- [Synthetic wounds](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6369)

## Reproduction:
When using a stamp on a document, scrolling down leaves the stamp placement where it was and de-sync's from the mouse cursor making it nearly impossible to stamp long documents. 

![image](https://user-images.githubusercontent.com/60765218/122771568-9010ee00-d274-11eb-8203-37979923c19f.png)

**Comment by Zergspower** [comment]
Bug exists only when scrolling on paper

**Comment by vinylspiders** [comment]
No longer seems to be an issue. Carnage from testing...
![image](https://user-images.githubusercontent.com/13398309/217749623-64b39bc0-eee6-4070-82e1-a32d68fdbb37.png)

**Comment by vinylspiders** [comment]
@lessthnthree fixed upstream.

**Comment by vinylspiders** [comment]
@Jolly-66 another close able
