### ISSUE TITLE
Attempting to buckle someone to an operation table does not lay them down.

### ISSUE THREAD

**Issue by weesnaw-ops** [Skyrat-SS13/Skyrat-tg#6448]
Attempting to buckle someone to an operation table does not lay them down.

This became evident when I was trying to force the captain to get a brainwashing surgery when they had handcuffs on, and it did not let me lay them down.

**Comment by ZephyrTFA** [comment]
Upstream issue

**Comment by Zergspower** [comment]
unable to replicate in current state
