### ISSUE TITLE
Sholean Grapes can't eat food, despite code suggesting they can

### ISSUE THREAD

**Issue by Somememeguy** [Skyrat-SS13/Skyrat-tg#6558]
## Round ID:
2197

## Testmerges:
#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit 3670f45083
#6314: '[READY] Global Ticket System / Ticket Handling' by ZephyrTFA at commit d28b0f7018
#6482: 'Update Changelog.js' by Gandalf2k15 at commit 3d32b9c509
#6488: '[MODULAR] New Station Trait! Sector Overseer!' by Cheshify at commit fae6a6a209
#6480: 'SSdecay - Making the station dirty(and creepy)' by Gandalf2k15 at commit 23ba2e30c6

## Reproduction:

Click on any food item, unable to eat them.

Try everything to eat any sort of food item, be unable to.

Due to this they can't gain nutrient, and will slowly die as time goes on and they lose nutrients.

**Comment by Elli-Skala** [comment]
i believe this is also a upstream problem, but can confirm Sholean Grapes will starve

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/8366
