### ISSUE TITLE
Rod stopper vortex too large

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#6667]
Reporting client version: 514.1557

## Round ID:
2248

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[MODULAR] Change mold weight and min players](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6637)
- [EORG bans](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6659)

**Comment by Zergspower** [comment]
Resolved overtime and is working correctly in the current build
