### ISSUE TITLE
Nightsticks Cannot Stamcrit Anymore

### ISSUE THREAD

**Issue by CameronWoof** [Skyrat-SS13/Skyrat-tg#6714]
Tin. No amount of beating on someone with a nightstick (even *two* people beating on someone with a nightstick) will ever cause them to enter stamcrit. 

Combat mode on or off, harmbatonning or not, *nothing* causes stamcrit.

## Testmerges:

#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit a462568ea5
#6637: '[MODULAR] Change mold weight and min players' by Swiftfeather at commit 79ac35ea5d
#6659: 'EORG bans' by Gandalf2k15 at commit 9bbee88f8d
#6671: '[semi-modular] xenoarch' by jjpark-kb at commit 5174d1d43b
#6669: 'Revert "Synthetic wounds"' by SpaceVampire at commit e685f13b12
#6643: '[semi-modular] reagent forge' by jjpark-kb at commit 3f6c1e8918
#6314: '[READY] Global Ticket System / Ticket Handling' by ZephyrTFA at commit c93feacfb2

## Reproduction:

Do it. Hit them.

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/6995
