### ISSUE TITLE
Space Law books are blank

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#6830]
Reporting client version: 514.1557

## Round ID:
2313

When trying to read the space law book it shows up as "Blank" This is most likely an issue with the page for corporate regulations not being linked correctly to the book.

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[READY] Global Ticket System / Ticket Handling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6314)
- [[MODULAR] Vanguard Class Reworks (also another things)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6696)
- [[SEMI-MODULAR]Neural Lacing (Or copyright infringement)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6576)
- [[TM-ONLY] Temp. Disables grav anomaly events in CODE.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6819)

## Reproduction:

Simply attempt to open a book on space law and it should say in the chat long that it is blank.

**Comment by thestubborn** [comment]
think this is a config issue, maybe

**Comment by ghost** [comment]
Tested, didnt see the issue. Can someone else confirm?

**Comment by Sir-Lagsalot** [comment]
> 
> 
> Tested, didnt see the issue. Can someone else confirm?

I can confirm, I have the same issue with space law books. I basically only carry them for use as a prop now.

**Comment by Zergspower** [comment]
Confirmed simply states This Book is blank! for both sec and non-sec - believe this should be a config fix

**Comment by theselfish** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12578 should have closed this.

Try again and report back.
