### ISSUE TITLE
Peacekeeper boomerangs don't return.

### ISSUE THREAD

**Issue by oilysnake** [Skyrat-SS13/Skyrat-tg#6930]
## Reproduction:

Throw a peacekeeper boomerang. It does not come back.

Caused by https://github.com/Skyrat-SS13/Skyrat-tg/pull/5153 which replaced OZtek boomerangs with peacekeeper boomerangs.

Edit: Extra suggestion? Just edit oztek boomerangs to only stun when thrown. It's fucking hilarious to see sec officers forget how to catch a boomerang and stunbaton themselves.

**Comment by tf-4** [comment]
We have oztek boomerangs once again
