### ISSUE TITLE
You cannot craft sandwiches.

### ISSUE THREAD

**Issue by oilysnake** [Skyrat-SS13/Skyrat-tg#6954]
## Reproduction:

Put item on bread. Put another slice of bread on item. What. it says bread does not belong on the sandwich. Cry.

Possibly caused because, when you inspect bread, it believes bread to ALREADY have stuff on it, the stuff is just 'nothing'.

**Comment by Zergspower** [comment]
unable to reproduce, able to make sammich, however unable to confirm if tasty as my robotic tongue will eat anything
