### ISSUE TITLE
Savannah Ivanovs no longer have the MMI bug and ate a small nerf and should be re-added.

### ISSUE THREAD

**Issue by oilysnake** [Skyrat-SS13/Skyrat-tg#6973]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6272 Removed it

https://github.com/Skyrat-SS13/Skyrat-tg/pull/6703 Fixed it 12 days ago

**Comment by Zergspower** [comment]
Would be upstream as the mech isn't obtainable on SR
