### ISSUE TITLE
Synth wounds are untreatable

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#6981]
## Testmerges:
Round ID: 2403
BYOND Version: 514.1557
Server revision compiled on: 2021-07-16T12:08:15+00:00
Master commit: 658a587342ae58ea97636687c5b7e59f94e3eff3
The following pull requests are currently test merged:
#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit a462568ea5
#6671: '[semi-modular] xenoarch' by jjpark-kb at commit 16c52559ce
#6314: '[READY] Global Ticket System / Ticket Handling' by ZephyrTFA at commit 25a9e66f5a
#6819: '[TM-ONLY] Temp. Disables grav anomaly events in CODE.' by Yawet330 at commit 31ab4dfbfa
#6886: 'Rebalances mutants [PENDING TEST]' by Gandalf2k15 at commit 47bc2c2542
#6906: '[MODULAR] Veegee Station' by Squird5 at commit bfba3a33b2
#6921: 'Armory minidate' by Gandalf2k15 at commit 626a27dfc4
#6914: '[MODULAR] Ashwalker Village (Fixed this time)' by ForrestWick at commit adc912b895
#6740: 'organic interface update' by Lamella-0587 at commit 3387530825

Local commit: 6bce617df5c19193836b0c9b86361cd0a3c9dc21
TGS version: 4.12.1
DMAPI version: 5.3.0

Notably, the synth wound temporary revert is not on that list.

## Reproduction:
Try to treat a synth with third degree burns, heat warping, or anything really. They can get organic spaceman wounds like infected third degree burns, and the surgeries for treating heat warping and similar do not show up when you put the drapes over the effected limbs. Health analyzer says the wound is treated and healing, but, it doesn't seem to be.

**Comment by tf-4** [comment]
Reverted with https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669
