### ISSUE TITLE
Cocaine is just fucked

### ISSUE THREAD

**Issue by oilysnake** [Skyrat-SS13/Skyrat-tg#7003]
You can't craft cocaine bricks OR even get coca leaf plants legitimately.

## Round ID:

2420

## Reproduction:

Try to mutate Cocoa into Coca leaf, it is impossible. Floral somatory confirms it.

Can't turn Cocaine into Cocaine Bricks, button just doesn't WORK in the crafting menu

**Comment by tf-4** [comment]
Cocoa does not mutate into coca. It's its own plant, in the contraband section of the seed vendor.

I'm also having no issues with crafting. It has to be 5 powdered cocaine, not 5u of liquid cocaine.

**Comment by linnpap** [comment]
just for reference, to make powdered cocaine, you have to freeze liquid cocaine

**Comment by oilysnake** [comment]
> Cocoa does not mutate into coca. It's its own plant, in the contraband section of the seed vendor.
> 
> I'm also having no issues with crafting. It has to be 5 powdered cocaine, not 5u of liquid cocaine.

Unless the code has been recently changed, it’s supposed to. You’re supposed to be able to mutate cocoa into coca.

**Comment by tf-4** [comment]
No you aren't. It was never that way
