### ISSUE TITLE
Armored mining harduits lack sprites for taurs, causing body to become invisible

### ISSUE THREAD

**Issue by WerepyreX** [Skyrat-SS13/Skyrat-tg#7008]
Reporting client version: 514.1557

## Round ID:
2423

Adding goliath plates to a mining hardsuit will change its sprite. Twice, in fact. However, these new sprites do not exist for the tauric version of the mining hardsuit. Thus, it causes the character sprite's body to bug out and become mostly invisible, with only a few glitchy bits of clothing visible.

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Rebalances mutants [PENDING TEST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6886)
- [[MODULAR] Veegee Station](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6906)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [[MODULAR] Ashwalker Village (Fixed this time)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6914)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)

**Comment by tf-4** [comment]
We no longer have hardsuits
