### ISSUE TITLE
Fireman's Carry and Back bugged

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#7031]
Reporting client version: 514.1557

When attempting to fireman carry a carbon it will state that you "Failed to fireman carry x" Likewise you cannot climb onto someones back. This is...obviously a problem, not only for the simple utility but for paramedics or anyone else trying to pull a dead body to medical.

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Rebalances mutants [PENDING TEST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6886)
- [[MODULAR] Veegee Station](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6906)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [[MODULAR] Ashwalker Village (Fixed this time)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6914)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)

## Reproduction:

Load up a game and try to fireman carry someone or climb on someones back. It should fail every time.

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/6988
