### ISSUE TITLE
The Zomboner

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#7064]
## Testmerges:

Uhh, main problematic one is organic interface whatever

## Reproduction:
Just climax when you're fucking dead or in crit.

Relevant image to this silly bug, courtesy of Usuario2#0286
![image](https://user-images.githubusercontent.com/37010048/126573742-233f9b67-1d24-42d0-b6a8-057a1afbce7b.png)

**Comment by Kroto-Ker** [comment]
If you die face-down, your blood could also conceivably settle in your penis—which creates the appearance of a boner. But the chances of going out with a bang are pretty slim, says Judy Melinek, M.D., forensic pathologist and coauthor of Working Stiff: Two Years, 262 Bodies, and the Making of a Medical Examiner.

It’s actually more possible that your penis will look like it’s ejaculated after you’ve died. “Sometimes we’ll find discharge near the penis on a corpse, but this comes from the passive seeping of fluid from the prostate gland,” Dr. Melinek says. “It’s leakage—not ejaculate.” 
---
It's not a bug, it's realism. :)
