### ISSUE TITLE
Optical Material Scanners Bugged

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#7065]
Reporting client version: 514.1557

For whatever reason in order to see objects through walls you need a flashlight to "light up" the areas you're trying to see through, even through walls. Suffice to say this is pretty jank.

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Rebalances mutants [PENDING TEST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6886)
- [[MODULAR] Veegee Station](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6906)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [[MODULAR] Ashwalker Village (Fixed this time)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6914)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[SEMI-MODULAR]Fixes playtime cloak & adds support for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7012)

## Reproduction:
Equip material goggles and try to look at items through walls. If you don't see them try to shine a flashlight through the wall
and they should show up.

**Comment by Zergspower** [comment]
unable to reproduce in current build - i do remember this bug however so I assume it has since been resolved
