### ISSUE TITLE
Issue with foot wraps on digi-legs, they do not work from the side-view. 

### ISSUE THREAD

**Issue by ImHoppingMad** [Skyrat-SS13/Skyrat-tg#7083]
Image of issue
![image](https://user-images.githubusercontent.com/87835029/126716586-edb478b9-bb89-4a81-9cd7-c81e8cc31b7f.png)

I was told to report this to the github, so here I am, doing so!

Reporting client version: 514.1557

## Round ID:
2463

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Rebalances mutants [PENDING TEST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6886)
- [[MODULAR] Veegee Station](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6906)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [[MODULAR] Ashwalker Village (Fixed this time)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6914)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[SEMI-MODULAR]Fixes playtime cloak & adds support for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7012)

**Comment by ghost** [comment]
It seems a lot of random items stopped working from the side view, from boots to jumpsuits. Brown Jackboots are an example.

**Comment by Zergspower** [comment]
not reproduceable any longer, assuming resolved due to time
