### ISSUE TITLE
Incubus draft is a scam, does not expand dong

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-tg#7095]
Reporting client version: 514.1557

## Round ID:
2466

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)
- [Rebalances mutants [PENDING TEST]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6886)
- [[MODULAR] Veegee Station](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6906)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [[MODULAR] Ashwalker Village (Fixed this time)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6914)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[SEMI-MODULAR]Fixes playtime cloak & adds support for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7012)

## Reproduction:
Three separate characters of mine took incubus draft: one male, one hermaphroditic, and one female. Didn't have an effect on a hermaphroditic or full-female character aside from the overdose effect of reducing breast size to A-cups at minimum and changing the character's pronouns to male. Seems to work OK for characters that are 100% male. I had every single OOC preference set to enabled. I get that the formula is 'Chinese Dragon Powder,' but having it do nothing aside from unintended side effects for 2/3 of the most common character genders is a little too immersive.

**Comment by Zergspower** [comment]
Steps taken to reproduce resulted in 19 inches of meat - marking issue as resolved
