### ISSUE TITLE
Delta Station disposals mass driver yeets trash at the prison block.

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-tg#7132]
Reporting client version: 514.1557

## Round ID:
2497

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[SEMI-MODULAR]Fixes playtime cloak & adds support for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7012)
- [[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6995)
- [[TM-ONLY]Revert "[MIRROR] Change ashwalkers to have custom lungs"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6907)
- [[NONMODULAR][A DIRECT BORG BUFF]Mining cyborgs now have crushie back](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6843)
- [[SEMI-MODULAR] Engineering Cyborg Advanced Materials Upgrade](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6808)

## Reproduction:
Go to Delta station. Launch something out of the disposals room. Observe impact. Recommend using eggs, cream pies, live/dead monkeys, or something else that makes a satisfying SPLAT when it hits.

You could fix this by shifting the disposals area three tiles to the north, or pivoting the mass driver and door to fire out through the solars. You'd need to remove a few grilles for the latter fix to be effective.

**Comment by ghost** [comment]
Should have been fixed with our prison remap prs; no clue if the mapping reset re-fucked this though

**Comment by GoldenAlpharex** [comment]
Should be fixed now I think.
