### ISSUE TITLE
Secway doesn't function

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#7171]
Reporting client version: 514.1561

## Round ID:
2511

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [Armory minidate](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921)
- [organic interface update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6740)
- [Revert "Synthetic wounds"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6669)
- [[SEMI-MODULAR]Fixes playtime cloak & adds support for admins](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7012)
- [[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6995)
- [[TM-ONLY]Revert "[MIRROR] Change ashwalkers to have custom lungs"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6907)
- [[NONMODULAR][A DIRECT BORG BUFF]Mining cyborgs now have crushie back](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6843)
- [[SEMI-MODULAR] Engineering Cyborg Advanced Materials Upgrade](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6808)

**Comment by tf-4** [comment]
Upstream issue, fixed with https://github.com/tgstation/tgstation/pull/60624

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/7330
