### ISSUE TITLE
the spider mid round event doesnt work

### ISSUE THREAD

**Issue by Elli-Skala** [Skyrat-SS13/Skyrat-tg#7176]
## Round ID:

2517

## Testmerges:

#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit a462568ea5
#6740: 'organic interface update' by Lamella-0587 at commit bb57a10ca0
#7012: '[SEMI-MODULAR]Fixes playtime cloak & adds support for admins' by Yawet330 at commit cdddcb4d0a
#6995: '[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again' by Seris02 at commit 15f9b2dfc5
#6907: '[TM-ONLY]Revert "[MIRROR] Change ashwalkers to have custom lungs"' by Yawet330 at commit b198d458b7
#6843: '[NONMODULAR][A DIRECT BORG BUFF]Mining cyborgs now have crushie back' by Yawet330 at commit d88c331250

## Reproduction:

mid wife spider eggs spawned in during the round, all though they messaged all the ghost to spawn in as them, clicking on the egg or using the spawner menu both failed to spawn you in any way

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10073
