### ISSUE TITLE
Incrementer button not working on Delta station for HoP's ticket system

### ISSUE THREAD

**Issue by tudeslildude** [Skyrat-SS13/Skyrat-tg#7248]
Reporting client version: 514.1557

## Round ID:
2538

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6995)
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [The final nail in the unfun round removal coffin](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6943)
- [[MODULAR] New species: Ghouls](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6928)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)

## Reproduction:

So the issue is, is that I'm on delta station, and the HoP's ticket counter isn't doing anything. I have a ticket 1, and a ticket 2 on my desk. I press the ticket incrementer, which is directly above me. That's supposed to make the ticket vibrate, and then when you press it again it makes it dissappear, but it's not working

**Comment by jjpark-kb** [comment]
I could not replicate this issue.

**Comment by tudeslildude** [comment]
Could not replicate? Non of the increment ticket buttons work. I'm on meta right now, have a ticket infront of me, I'm pressing the button and nothing happens.

________________________________

**Comment by Zergspower** [comment]
Unable to replicate.

Ticket conditions must be:

Taken: Ticket 1 is either on the ground or in someone's hand
Tap 1: Removes ticket from existence and notifies
Tap 2: cycles to the next ticket - if none exist counter does not change.

**Comment by tf-4** [comment]
assuming resolved over time
