### ISSUE TITLE
Forked tongue does not work

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-tg#7271]
## Testmerges:

BYOND Version: 514.1557
Server revision compiled on: 2021-07-30T03:18:43+00:00
Master commit: b2d98480a33b7f44b970f7287260e839d77db716
The following pull requests are currently test merged:
#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit a462568ea5
#6995: '[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again' by Seris02 at commit 15f9b2dfc5
#7173: 'Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"' by Funce at commit d70ef855e8
#6943: 'The final nail in the unfun round removal coffin' by Gandalf2k15 at commit ea55a0d8b6
#6928: '[MODULAR] New species: Ghouls' by linnpap at commit 2458d5008e
#3255: 'Sizeplay v 0.5' by Useroth at commit 08e7778fd5
#6740: 'organic interface update' by Lamella-0587 at commit 51c5cd90f6

Local commit: 7ac6ab416f407a30b6bbe8071079417c5dfbe983
TGS version: 4.12.1
DMAPI version: 5.3.0

## Reproduction:
Play character with forked tongue, chosen from the augments menu. Try to talk. Receive normal speech. Expected lizard Ssssecksy speech.

I suspect this has something to do with the huge pile of test merges failing in the last few days and wrecking things like sizeplay.

**Comment by tf-4** [comment]
This was due to an issue with augments not loading correctly, since fixed
