### ISSUE TITLE
HoP's alternative female uniforms are missing textures when worn

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#7492]
Reporting client version: 514.1561

## Round ID:
2655

## Testmerges:
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [[NON-MODULAR] Runtime Begone](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7357)
- [Nanotrasen Fleet Command Expansion](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7418)
- [Ports pollution from Horizon - Original PR: https://github.com/hrzntal/horizon/pull/468 (Made by Azarak)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7453)
- [[MODULAR] New species: Ghouls](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6928)

**Comment by axietheaxolotl** [comment]
What you get for playing digitigrade 😎 

it's cause I am monkey brain and didn't program digitigrade versions for the HoP's alternate clothing. I'll fuck around with it and see what I can do.
