### ISSUE TITLE
doing *wag again after your tail is wagging doesn't stop your tail from wagging(as felinid). 

### ISSUE THREAD

**Issue by Tumesuo** [Skyrat-SS13/Skyrat-tg#7543]
Reporting client version: 514.1548

## Round ID:
2697

## Testmerges:
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [Nanotrasen Fleet Command Expansion](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7418)
- [Ports pollution from Horizon - Original PR: https://github.com/hrzntal/horizon/pull/468 (Made by Azarak)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7453)
- [No conversion cult](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7493)

## Reproduction:

Wag tail, try to stop wagging tail by typing *wag again.

**Comment by softcerv** [comment]
Weird, I tried testing this out and it applies here but not on base TG

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/8722
