### ISSUE TITLE
Gasmasks cannot have filters removed

### ISSUE THREAD

**Issue by ARandomAlien** [Skyrat-SS13/Skyrat-tg#7555]
Reporting client version: 514.1561

As said, gasmasks cannot have their filters removed for whatever reason.

## Round ID:
2702
<!--- **INCLUDE THE ROUND ID**

## Testmerges:
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [Nanotrasen Fleet Command Expansion](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7418)
- [Ports pollution from Horizon - Original PR: https://github.com/hrzntal/horizon/pull/468 (Made by Azarak)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7453)
- [No conversion cult](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7493)

## Reproduction:

Just try to remove filters from a gasmask, nothing works nor does the right click that the gasmask filter pr says removes filters

**Comment by tf-4** [comment]
Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/8006
