### ISSUE TITLE
Rotting carcasses are currently invisible and are unable to be clicked on, even after alt clicking their tile

### ISSUE THREAD

**Issue by Ebin-Halcyon** [Skyrat-SS13/Skyrat-tg#7604]
Reporting client version: 514.1557

## Round ID:
2732

## Testmerges:
- [Nanotrasen Fleet Command Expansion](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7418)
- [No conversion cult](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7493)
- [[MODULAR] Adds Manage Player Ranks verb](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7581)

## Reproduction:
Find medical whiteship in space, find invisible rotten carcass mobs.

**Comment by ghost** [comment]
Worth noting this applies to Humantraps as well; may be an issue with simplemob corpses in general
