### ISSUE TITLE
Unable to call cargoshuttle

### ISSUE THREAD

**Issue by Sonic121x** [Skyrat-SS13/Skyrat-tg#7638]
## Reproduction:

1. Use the supply console and call the cargoshuttle
2. Nothing happen
3. ADMIN LOG: Shuttle the supply shuttle cannot dock at Cargo Bay, error: docking width too large
4. (Even when you manualy control NLV Consign Flight Console,it still tell you the same error)

(tested on kilo and deltaStation)

**Comment by lyricalpaws** [comment]
It happens on meta too.

**Comment by tf-4** [comment]
This needs to be fixed with a map update. Meta works fine the last I saw, though.

**Comment by Sonic121x** [comment]
OK i figuer out the problem.
1:delta,kilo and meta's json file are still giving them there original cargo shuttle
2:also on kilo,its cargo port docking width(dwidth) set to 4 insteaded of 5.
I have no idea how to do map merge stuff.so if someone want to fix this here is the solution.

**Comment by ghost** [comment]
@tf-4 this should be fixed with the removal of the fleet
