### ISSUE TITLE
Nympho messages proc on named monkies.

### ISSUE THREAD

**Issue by TehSplinterCell** [Skyrat-SS13/Skyrat-tg#7750]
Reporting client version: 514.1557

## Round ID:
2795

## Testmerges:
- [cortical borer](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7554)

## Reproduction:

I was playing a character with the Nymphomania quirk.
I encountered a named NPC monkey in Icebox xenobio maint. God only knows how it got there, but it was named Ivy Heckendora.
Shortly after my flashlight shone upon the screeching, diapered ape, I got purple text in my chat box.

> Yeah, you'd hit that. That's at least a six out of ten.

Dude. No.
I signed up for my character to be horny IC, not for _this_. At the very least, please bump up the 'you'd fuck anything that moves' threshold a few stress levels once you figure out what's making this happen. Split the perk into one that makes characters attracted to other sapients and another that makes them attracted to everything if you're feeling ambitious. It must be **someone's** preference if the trend of ERP-ing with dog/drake borgs is any indication.

**Comment by FlamingLily** [comment]
This is actually a bug, the code only sends stress messages if you're in company, which is *explicity* "humans" (as in the mob type). While YES monkeys are a human, the code also checks for whether or not the mob has a client

THEORETICALLY this would mean monkeys with clients are also a cause of this, which I will be fixing

**Comment by FlamingLily** [comment]
> 
> 
> This is actually a bug, the code only sends stress messages if you're in company, which is _explicity_ "humans" (as in the mob type). While YES monkeys are a human, the code also checks for whether or not the mob has a client
> 
> THEORETICALLY this would mean monkeys with clients are also a cause of this, which I will be fixing

OR FUCKING NOT

**Comment by tf-4** [comment]
since fixed
