### ISSUE TITLE
meteor sat hydraulic clamp dupe bug

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-tg#7817]
Reporting client version: 514.1557

## Round ID:
2832

## Testmerges:
- [cortical borer](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7554)
- [venus changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7692)

## Reproduction:

Third party report: "When you try to pick up a satellite with a Hydraulic Clamp, it "activates" then you pick it up. However, because of that, the original remains yet I got another inside of the Cargo Compartment. "

**Comment by Zergspower** [comment]
unable to reproduce - clamp does indeed activate it but the original disappears.

**Comment by Zergspower** [comment]
unable to reproduce with the same results noted above
