### ISSUE TITLE
Soulstone doesn't summon ghosts from monkeys

### ISSUE THREAD

**Issue by Drowzyleaf** [Skyrat-SS13/Skyrat-tg#7855]
## Round ID:
2847, 2848

## Reproduction:
>Purchase the Cult Construction Kit as Chaplain, which has six purified soulstone shards and two construct shells.
>In the past, I've used the soulstone shards on monkeys, which summons a ghost to inhabit the shard. I find this very good, as it either allows the chaplain to get minions without having to kill others or helps a chaplain planning on killing humans get an established squad for when he moves on to human souls. 
>In round 2857, I rolled traitor, and my gimmick was nonlethally summoning as many ghost as possible into purifed shades to do whatever around the station. I was only able to summon three over the two hour round, all three of which I'm pretty sure was because of admin intervention - after I died, I was informed by an admin that using the soulstone wasn't offering any prompt to ghosts.
>in round 2848, I rolled traitor again, and planned on doing a more lethal gimmick of taking over the station with my shells. I got a grand total of zero shades summoned into my soulstones. I then died of a heart attack from supermatter delamination shenanigans before I was about to move on to human targets, after realizing it wasn't going to work. I confirmed the fact that no prompt was being offered to ghosts with another admin.

**Comment by Zergspower** [comment]
Soulstones require a body to have a soul now - it will work like a defib on dead entities
