### ISSUE TITLE
[Potential duplicate]  Returned to lobby despite being readied up, and having highest priority job slot open.

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#7858]
Reporting client version: 514.1561

## Round ID:
2852

## Reproduction:

I don't know. I fiddled with the be antag and ready up buttons a bit, but they were both on. My highest priority was mime, and the mime slot was open.  I had my fallback prefrence as be random job if prefrences unavailable. This has happened before with my prefrence set to be assistant if prefrences unavailable.  

Hell, I think my job prefs have overall been acting fucky. I'm just... confused.

**Comment by Vizoplez** [comment]
@ReynTheLord You switched characters/jobs while in lobby, which makes the ready-up button display false data as being readied up. Previous issue with the old menu system.
