### ISSUE TITLE
Plumbing Bug 

### ISSUE THREAD

**Issue by kaka-jpn** [Skyrat-SS13/Skyrat-tg#7972]
## Reproduction:

1. Use the Reaction Chamber, make the recipe using phenol, oxygen and nitrogen. This will give Libital.
2. Store the Libital in the Tank.
3. Then use the Reaction Chamber to make synthflesh, libital, blood and carbon.
4. The reaction doesn't complete, because Libital doesn't want to go inside the Reaction Chamber. (I don't know why Libital won't enter, other chemicals will enter the chamber)

**Comment by Enig-Code** [comment]
funny is the cause of this, the chamber seeks the libital made by borer.
