### ISSUE TITLE
Plasma chamber borked on Ice Box Station

### ISSUE THREAD

**Issue by LeChatGuide** [Skyrat-SS13/Skyrat-tg#8025]
Reporting client version: 514.1557

## Round ID:
2927

## Testmerges:
- [Revert "[MIRROR] Refactor area and turf lighting"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7902)
- [Capping Threat Level to 70 [Test Merge Only]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7698)

## Reproduction:

No idea really . Basically, if the plasma chamber console is facing south and isn't working properly, chances are it's this bug

**Comment by tf-4** [comment]
Map resets have caught this.
