### ISSUE TITLE
Weed joints make you nauseous as shit.

### ISSUE THREAD

**Issue by sergeirocks100** [Skyrat-SS13/Skyrat-tg#8135]
Reporting client version: 514.1557

## Round ID:
2987

## Testmerges:
- [Capping Threat Level to 70 [Test Merge Only]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7698)

## Reproduction:

Grow some chronic.

Roll it up in a rolling paper.

Light it up and smoke it.

Watch as it makes you feel ill and vomit.

I do not know if this is intended behavior or not, but i'm reporting it anyways.

**Comment by tf-4** [comment]
This isn't the case with all, and depends on your 'strain'.
