### ISSUE TITLE
Ollying a skateboard onto a z level drop (Possibly only with stairs at front) will cause you to float above the pit and skateboard above the pit

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#8144]
Reporting client version: 514.1561

## Round ID:
2991

## Testmerges:
- [Capping Threat Level to 70 [Test Merge Only]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7698)

## Reproduction:

I don't bloody know, flip jump your board into the icebox bar stairwell. EDIT: Its not just ollying. Skateboarding over a pit allows you to hover over it

**Comment by ReynTheLord** [comment]
Status update. this also applies to roller scates and wheelie heelies

**Comment by ghost** [comment]
I love the idea of the situation you found this in IC

Either way, worth testing upstream. Might be an error from there

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12649
