### ISSUE TITLE
the "fun"_toggle isnt working. 

### ISSUE THREAD

**Issue by Minuspurple** [Skyrat-SS13/Skyrat-TG#8151]
Reporting client version: 514.1557

## Round ID: 
3000-3001

## Testmerges:
- [Capping Threat Level to 70 [Test Merge Only]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7698)

## Reproduction: 
i havent played in a couple of months, and joined round id 3000 really late into the round. the "fun"_toggle menu thing for fun toys and such isnt opening up, the icon is there and i have my preferences set to yes but when i click on the icon in-game the menu is not popping up. ive tried reconnecting, exiting and closing the game, minimizing and maximizing my screen, toggling the preference on and off, but nothing seems to be working. i joined round 3001 and the issue continued to persist even though it was a new round. ive used up all the help the mentors gave and nothing seemed to work, something must of gone wrong some how.

**Comment by Tastyfish** [comment]
Likely obsolete as the menu is opened completely differently now.
