### ISSUE TITLE
Have no way to get rid of combustible substance on the body

### ISSUE THREAD

**Issue by WitherVictor** [Skyrat-SS13/Skyrat-TG#8196]
## Reproduction: 
Once covered with something flammable player can never get rid of that and can be lighted up anytime
That's fatal when doing something dangerous experiment or producing chemicals

**Comment by ghost** [comment]
Just to make sure all methods were tried: showering, using a sink, or being sprayed/wiped down/soapscrubbed... NOTHING worked?

**Comment by Zergspower** [comment]
tested on welding fuel and oil and was able to clean it off - unable to replicate with the common chemicals and no steps were provided/details missing on specific chemicals. Some will not come off due to their properties(Napalm).
