### ISSUE TITLE
.38 missing from lathes, research, and cargo.

### ISSUE THREAD

**Issue by ghost** [Skyrat-SS13/Skyrat-TG#8249]
So for some reason .38 ammo was removed from the cargo options which means there’s no reasonable way to actually acquire .38 dumdum ammo or .38 rubber ammo. they are nowhere in cargo even when hacked, not in the research listings, and not in the protolathes or autolathes. rubber .38 shows up in ammo forge thing in security, but you can’t print it individually and you can’t fill standard speedloaders with it cause it says it’s not a matching ammo type. ~ Mia Shore.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10353
