### ISSUE TITLE
Monkey still chase player after died

### ISSUE THREAD

**Issue by WitherVictor** [Skyrat-SS13/Skyrat-TG#8263]
## Reproduction:
Monkey will keep on chasing players even after died. The only way to stop them is to butcher then they'll stop

**Comment by Sonic121x** [comment]
actually,monkey still have their AI when turn into human,or even after their control giving to a player

**Comment by Zergspower** [comment]
Would be upstream, however unable to reproduce. Corpses stay dead in current build
