### ISSUE TITLE
genital slot hud cannot be opened.

### ISSUE THREAD

**Issue by StarHorder** [Skyrat-SS13/Skyrat-TG#8289]
## Round ID:
3049 - ongoing

## Testmerges:
#7698
Capping Threat Level to 70 [Test Merge Only] by @jjpark-kb
Commit: 2439ea2
#8124
[SEMI-MODULAR] [READY] Blueshift by @axietheaxolotl
Commit: e584491

## Reproduction:
click on the sex toy slots backpack icon. nothing happens. someone else has to put them on for you.

**Comment by YakumoChen** [comment]
seems fixed
