### ISSUE TITLE
Booze Dispenser brings up NTOS error

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#8367]
Reporting client version: 514.1557

## Round ID:
3097

**Comment by ghost** [comment]
I didnt have this error just yesterday, was there a specific item put inside or anything? Perhaps you have the error log on-hand still?

**Comment by Erokusan** [comment]
I believe I put a normal flask in before I started using the booze dispenser, I unfortunately do not have the error long on hand

**Comment by GoldenAlpharex** [comment]
Haven't heard of this happening again. Open another issue if it's still broken.
