### ISSUE TITLE
Painkillers are not working

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-TG#8407]
## Testmerges:
The server revision button doesn't seem to show any

## Reproduction:
Do surgery with a pain killer, have the patient scream after every step. Tested with Morphine and Miner's salve, neither one stopped the patient from screaming. The numbing status is applied and appears on the HUD, but the screams from surgery still happen.

**Comment by Zergspower** [comment]
Tested with all substances listed and functioned normally, we've had many many updates since this issue has been risen.
