### ISSUE TITLE
Permanant Invisibility.

### ISSUE THREAD

**Issue by lolc4n** [Skyrat-SS13/Skyrat-TG#8416]
Reporting client version: 514.1557

## Round ID:
3122

## Reproduction:
1. Use the chameleon skin ability, and turn fully invisible while wearing a polychromic item. 
2. Change the color of a polychromic item to anything.
3. You are invisible, can move, interact with items, open airlocks, stab people, everything.

**Comment by Funce** [comment]
Tested on current live.

**Comment by Avacadbro** [comment]
I have been testing this after stumbling across it. No polychromic item on my character. Made my character a monkey, turn back into a person using mutadone (though probably could be in any way) then give chameleon mutator. Permanent invisibility as soon as you let it fade out fully. I was able to replicate it 2 times, first by accident and then on purpose to check how it worked. Unsure if this is much help but I hope it might help a bit!

**Comment by Zergspower** [comment]
unable to reproduce in current state - tried suit, jacket and pants and it did not trigger perma-invis. Assuming upstream resolved this or another PR did.
