### ISSUE TITLE
Plexagon Access Management (ID console) templates broken

### ISSUE THREAD

**Issue by lessthnthree** [Skyrat-SS13/Skyrat-TG#8418]
## Testmerges:
Round ID: 3127
BYOND Version: 514.1560
Server revision compiled on: 2021-09-27T02:56:12+00:00
Master commit: 0089dd6c29a01984c0ea45ebac688b4740cf35f5
The following pull requests are currently test merged:
#8350: 'Skyrat Prefs Menu: Fixing everything to work correctly' by Iamgoofball at commit 8c812ede0c

Local commit: 704415c25a97a23ca1f97d6b0e178fa8aab6d8e4
TGS version: 4.12.1
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:
Open Plexagon Access Management
Insert HoP or equiv. card and log in.
Insert card into secondary slot.
Open Trim Templates dropdown

**Comment by lessthnthree** [comment]
![image](https://user-images.githubusercontent.com/83487515/134845989-06c08268-1891-43a6-ad6a-4f777a2ceca7.png)

**Comment by ORCACommander** [comment]
looks like it was an upstream issue https://github.com/Skyrat-SS13/Skyrat-tg/pull/8470
