### ISSUE TITLE
The Voracious Quirk no longer works

### ISSUE THREAD

**Issue by BurgerLUA** [Skyrat-SS13/Skyrat-TG#8419]
Reporting client version: 514.1566

## Round ID:
3127

## Testmerges:
- [Skyrat Prefs Menu: Fixing everything to work correctly](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8350)

## Reproduction:

1. Choose Voracious Quirk
2. Confirm its added to character.
3. Being fat still slows you down.

Not sure why this broke or whatever but it's pretty annoying.

**Comment by Seris02** [comment]
it never stopped you from getting slowed down
