### ISSUE TITLE
Borg medical modules have no sprite and medi borgs can not be interacted with

### ISSUE THREAD

**Issue by Aether217** [Skyrat-SS13/Skyrat-TG#8422]
Reporting client version: 514.1557

## Round ID:
3131

## Testmerges:
- [Skyrat Prefs Menu: Fixing everything to work correctly](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8350)

## Reproduction:
When picking a medical skin you will be prompted with this choice no matter what you choose:
![Screenshot_55](https://user-images.githubusercontent.com/80391087/134891294-74dc7d2c-23a6-4b4d-a2d5-86594abc5bd3.png)

After selecting either of the options the sprite is invisible even after reconnecting
![Screenshot_54](https://user-images.githubusercontent.com/80391087/134891417-f23aa36b-c937-4d51-9d1d-57017aee8619.png)

In this state people can not see you and you can not be interacted with, it's making the borg module unusable

**Comment by tobjv** [comment]
yeah, it is acting like you hit the "next" button to go to the next page selection of the models.

**Comment by SpookyTheFox** [comment]
I believe the cyborg_icon_override is not working correctly. Currently, when you try to select a MEDICAL borg that uses it, you are shown a second radial menu with only default and qualified doctor.

**Comment by Funce** [comment]
This has been fixed.
