### ISSUE TITLE
Large breasted characters gain random nutrition until they're fat

### ISSUE THREAD

**Issue by ThatGuyPhil** [Skyrat-SS13/Skyrat-TG#8446]
Reporting client version: 514.1566

## Round ID:
3138

## Testmerges:
- [Skyrat Prefs Menu: Fixing everything to work correctly](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8350)

## Reproduction:
step 1: give your character large breasts (like maximum size i guess)
step 2: wait an hour or two, (optional: notice how you never become hungry)
step 3: gain the overweight status or whatever

seriously its annoying and keeps happening whenever i play as one specific character. Any of my other characters with average sized chests dont have this problem. I have not checked if lactation is also a factor in causing this. This has been happening before the testmerge as well.

**Comment by ThatGuyPhil** [comment]
I suspect that it might also have something to do with whether or not arousal is toggled for the genitals or not

**Comment by ThatGuyPhil** [comment]
after trying a few rounds without activating genital arousal i still never had the need to eat at all. I mean I bet its totally some really simple bug that can be fixed in an instant.

**Comment by ghost** [comment]
fixed by #8592 @tf-4  (I hope you're the right person to ping for the bugtracker)

**Comment by ThatGuyPhil** [comment]
should i close this now then if its fixed?
