### ISSUE TITLE
New selection UI made character customization unusable

### ISSUE THREAD

**Issue by boniblade** [Skyrat-SS13/Skyrat-TG#8481]
Reporting client version: 514.1568

## Round ID:
3157

## Testmerges:
- [Skyrat Prefs Menu: Fixing everything to work correctly](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8350)
- [Temporarily reverts powerarmor](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8458)
- [[SEMI-MODULAR] [READY] Blueshift](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8124)

## Reproduction: Might be user-specific. If it helps, I use Windows 8 / Firefox. I opened the character customization screen and the character selection button at first showed small names, then started shrinking as I clicked away, eventually becoming completely unusable. I hope it's just a problem with Windows 8, because I swear I'm going to stop using this OS one day.

![image](https://user-images.githubusercontent.com/41778816/135289472-dbe15f59-c720-4500-9cf4-8dce8e0105e9.png)

**Comment by Iamgoofball** [comment]
What version of Internet Explorer do you have installed?

**Comment by Iamgoofball** [comment]
also PLEASE stop using windows 8

**Comment by gonenoculer5** [comment]
Yeah. Please do not use 8/8.1. It leads to nothing but problems and the upgrade to windows 10 is free.

**Comment by tf-4** [comment]
Windows 8 is what causes this issue.
