### ISSUE TITLE
HIS HUNGER CANNOT BE CONTAINED

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#8497]
## Round ID:
3164

## Testmerges:
#8458: 'Temporarily reverts powerarmor' by Gandalf2k15 at commit 2acd37275d
#8124: '[SEMI-MODULAR] [READY] Blueshift' by axietheaxolotl at commit 9bd00d936a

### Step 1:
Build a singulo in a Standard Singularity 7x7 Containment
![image](https://user-images.githubusercontent.com/10399117/135422274-761e0e79-f901-42a2-a23a-8842749aae19.png)

### Step 2:
Watch it escape during a lag spike because it straight up eats an energy wall
![image](https://user-images.githubusercontent.com/10399117/135422547-f5c6ebb7-b896-4ae3-8bb0-fe4e5f75357c.png)
just the beamy part, right here

## ITS LOOSE

**Comment by gonenoculer5** [comment]
Is this a stage two or three singulo?

**Comment by YakumoChen** [comment]
Stage 2

**Comment by YakumoChen** [comment]
Fixed
