### ISSUE TITLE
MISSING CLOTHING ITEMS

### ISSUE THREAD

**Issue by Gandalf2k15** [Skyrat-SS13/Skyrat-tg#856]
# **THIS IS FOR ALL THE ANTHRO/MUZZLED/DIGI ERRORS.**

**Comment by Gandalf2k15** [comment]
SHOE

/obj/item/clothing/shoes/clown_shoes
--

DOES NOT HAVE DIGI SPRITE, INVISIBLE FOR DIGI.

**Comment by Gandalf2k15** [comment]
SUIT

/obj/item/clothing/suit/toggle/chef
--

NO DIGI SPRITE, SUIT ERROR.

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/toggle/chef
--


HEAD, NO SPRITE.

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/det_suit
--


SUIT, SUIT ERROR.

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/hos/beret
--


HEAD, NO SPRITE

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/toggle/lawyer
--


SUIT, NO SPRITE

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/toggle/suspenders
--


SUIT, NO SPRITE, SUIT ERROR

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/under/rank/medical/paramedic
--


WRONG SPRITE, TOO BLUE. JUMPSUIT.

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/toggle/labcoat/paramedic
--


SUIT ERROR

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/soft/paramedic
--


MISSING SPRITE

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/hooded/explorer
--


MISSING SPRITE

**Comment by Gandalf2k15** [comment]
## HEAD
- /obj/item/clothing/head/helmet/sec > No muzzled sprite, just invisible.

## JUMPSUIT
- /obj/item/clothing/under/rank/security/officer > Defaults to human sprite, legs do not reset.
- /obj/item/clothing/under/rank/security/blueshield > No sprite for anthros, just suit error.
- /obj/item/clothing/under/rank/cargo/tech > No sprite, just suit error

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/warden
--


MISSING

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/helmet/abductor
--
needs muzzled sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/under/color/lightpurple
--

needs digi sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/wizard/red
--

no muzzle needed.

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/wizrobe/red
--
needs digi sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/under/costume/gladiator/ash_walker
--


needs digi sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/helmet/gladiator
--

needs muzzled

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/hooded/bee_costume
--

needs digi sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/wizrobe
--


needs digi sprite

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/head/wizard
--
no sprites needed

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/suit/bio_suit/cmo
--


**Sprite issues**

**Comment by Jamini** [comment]
Missing sprites: (possibly just digi)

Military Jacket
Bomber Jacket
Leather Jacket
Leather Overcoat
Puffer Jacket
Puffer Vest
Brown letterman Jacket
Red Letterman JAcket
Nanotrasen Letterman Jacket

**Comment by Jamini** [comment]
Make that every jacket in the loadout screen.

**Comment by Jamini** [comment]
![image](https://user-images.githubusercontent.com/1775680/93639188-9a8d1700-f9c6-11ea-8311-ec4e6f30c775.png)

I don't know what the doublebarrel is even doing here. It's pink. Somehow.

**Comment by Gandalf2k15** [comment]
also certain sec berets don't work + wintercoat hoods

**Comment by Gandalf2k15** [comment]
/obj/item/clothing/under/misc/gear_harness
--

**Comment by Gandalf2k15** [comment]
icon = /icon (icons/mob/robots.dmi)
(E) (C) (M) icon_state = "zoomba_sec"
