### ISSUE TITLE
Arborlink Vault Tango missing pieces

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#8564]
Reporting client version: 514.1557

## Round ID:
3193

**Comment by Erokusan** [comment]
So it seems to be more of an issue of all the /obj/structure/window/reinforced/plasma/plastitanium not spawning correctly, a few syndicate ruins seem to be missing it.

**Comment by ghost** [comment]
@t_ this should have been fixed by now, seen several PRs mention updating our window paths. After someone else doublechecks it should be good to close.
