### ISSUE TITLE
Turn the light toward where you can't see shows background of universe

### ISSUE THREAD

**Issue by WitherVictor** [Skyrat-SS13/Skyrat-TG#8570]
## Reproduction:
Turn on the flashlight or something light toward where you have no vision will show the background of universe. This happened on map Blueshift, but I guess upstream TG made this bug instead of map. And here's the picture: 
![example](https://user-images.githubusercontent.com/83024635/135722331-526c41c7-2cd8-4c64-ae65-09e4563d83ed.png)

**Comment by tf-4** [comment]
Since fixed, dunno where though.
