### ISSUE TITLE
Split Personality sometimes boots the actual player out of their own body.

### ISSUE THREAD

**Issue by Kapu1178** [Skyrat-SS13/Skyrat-TG#8628]
## Testmerges:
#8524: 'GoofSec: Departmental Guards, Stamina Crit Fixes, Armory Rework, 3-Hit-Stamcrit Batons, Flashbang fixes' by Iamgoofball at commit e07d62e2d7
#8599: 'Revert "[MIRROR] ClickOn now actually calls ranged right click attacks [MDB IGNORE]"' by Gandalf2k15 at commit 4c7d5f6cbb

## Reproduction:
1. Get a head Compound Fracture
2. Get Split Personality brain trauma from it
3. After 2 control swaps, be ghosted as a generic ghost with the name of the body.
4. Lose access to Personality Commune verb, and be stuck as a ghost forever.

![image](https://user-images.githubusercontent.com/75460809/136089589-80924f60-5bc3-4756-a800-6915bed57bb9.png)
This was what I saw immediately before being ghosted

**Comment by tf-4** [comment]
Should be fixed with ambitions removal. Lemme know if it's not.
