### ISSUE TITLE
Detective's aren't registered correctly

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#8660]
Reporting client version: 514.1557

## Round ID:
3242

## Testmerges:
- [GoofSec: Departmental Guards, Stamina Crit Fixes, Armory Rework, 3-Hit-Stamcrit Batons, Flashbang fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)

## Reproduction: A Detective coming into the round spawns with an unregistered ID (Their name and age are not recorded correctly, it gives NULL for the name, and defaults to 18)
In addition, they do not spawn pre mind shielded, this is recorded on round 3242

**Comment by Zergspower** [comment]
Rare bug but hasn't been seen in a while
