### ISSUE TITLE
Floating gun/Duplicate

### ISSUE THREAD

**Issue by Enzoman12** [Skyrat-SS13/Skyrat-TG#8673]
## Reproduction: Pick up a gun and put it on your suit storage

https://i.imgur.com/xUt5F43.png Look at the floating gun infront of me, and look at the suit storage. When I place the gun on my suit storage, a floating sprite of the gun pops up. When I click on the floating sprite, I pull the gun from my storage.

**Comment by gonenoculer5** [comment]
@Iamgoofball Unsure if this is related to your code or just suit storage code being jank as always.

**Comment by Zergspower** [comment]
Was an issue with that specific rifle for a time but has since been resolved
