### ISSUE TITLE
borgs/silicons no longer are able to set a flavor text for them selves

### ISSUE THREAD

**Issue by Minuspurple** [Skyrat-SS13/Skyrat-tg#8721]
Reporting client version: 514.1557

## Round ID:
3261

## Testmerges:
- [GoofSec: Departmental Guards, Stamina Crit Fixes, Armory Rework, 3-Hit-Stamcrit Batons, Flashbang fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)

## Reproduction:

flavor texts arent saved

**Comment by tf-4** [comment]
Is the issue that they can't set one, or that it doesn't save? This report isn't clear.

**Comment by GoldenAlpharex** [comment]
Pretty sure it's fully functional now, since I merged the Sillycons flavor text.
