### ISSUE TITLE
The NT Reps SWAT suit has a broken helmet, even on humans/but also with Anthromorphs

### ISSUE THREAD

**Issue by FridayRemada** [Skyrat-SS13/Skyrat-TG#8770]
## Round ID:
Universal/has happened every round I've played on blueshift.

## Reproduction:

 Put on the armor. Tick the box in the corner to put on a helmet. As far as I know, the hard suit hat does work in space still its just invisible/its sprite shows up in the slot as flashing red ERROR

![CCrepSwatsuitbug](https://user-images.githubusercontent.com/77188588/136889394-f464face-6595-44a0-81fd-133bb739534a.png)
![CCrepSwatsuitbug2](https://user-images.githubusercontent.com/77188588/136889395-1e71a547-1167-49df-9fb0-94071931044f.png)

**Comment by Deek-Za** [comment]
Helmet doesn't seem to exist currently. Though I suppose someone could easily recolor the cap's SWAT helmet for a similar appeal.

![image](https://user-images.githubusercontent.com/84706993/136938908-bf55799f-0910-4ebe-8ea9-961ea6cd4fa0.png)

**Comment by FridayRemada** [comment]
This would be good. I would definitely use the suit more if it were fixed.

**Comment by gonenoculer5** [comment]
Is this purely just a sprite issue?

**Comment by gonenoculer5** [comment]
@GoldenAlpharex Fixed by https://github.com/tgstation/tgstation/pull/60865 , please close.
