### ISSUE TITLE
Port Beestation's Typing Indicator

### ISSUE THREAD

**Issue by Kapu1178** [Skyrat-SS13/Skyrat-TG#8833]
https://github.com/BeeStation/BeeStation-Hornet/pull/5417

Moves the delay from window open to window close, and doesn't have skyrat's sticky overlay problem.

**Comment by tf-4** [comment]
Whether https://github.com/Skyrat-SS13/Skyrat-tg/pull/10486 is merged or closed, this can be resolved either way.
