### ISSUE TITLE
Ice Box Chapel stairs start blocked.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-tg#8839]
Reporting client version: 514.1547

## Round ID:
3313

## Testmerges:
- [cargo teleporter](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8492)
- [[Host Request] Temporarily disables CMEs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8277)
- [New job! Barber and salon!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8756)
- [GoofSec: Departmental Guards, Stamina Crit Fixes, Armory Rework, 3-Hit-Stamcrit Batons, Flashbang fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)
- [Moves hair gradients to the preferences menu ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8801)
- [GoofMed: Self-Actualization Device, Stasis Operating Tables!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8791)

## Reproduction: Ice box chapel stairs started blocked off. See picture for tiles that got removed to use stairs.
![broken stairs](https://user-images.githubusercontent.com/13283561/137530778-79fc0360-bcc3-4f02-8a62-442a3387171e.png)

**Comment by tf-4** [comment]
This is since fixed
