### ISSUE TITLE
Holding CTRL and trying to face a direction just causes you to move in that direction instead.

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat-tg#888]
## Round ID:
[2](https://scrubby.melonmesa.com/round/2)

## Testmerges:
Null

## Reproduction:
Hold CTRL and try to press a movement key to turn to that direction
end up moving in that direction instead of just turning
feel like a busted bayblade

**Comment by Rohesie** [comment]
If this is up to latest tg, then stopping movement has been turned into a customizable keybind of its own, alt by default.

**Comment by Gandalf2k15** [comment]
This is fixed.
