### ISSUE TITLE
Temporal scarring not an option in customizaiton menu

### ISSUE THREAD

**Issue by oranchepopsicle** [Skyrat-SS13/Skyrat-TG#8903]
Reporting client version: 514.1568

## Round ID:
3339

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [GoofSec: Departmental Guards, Stamina Crit Fixes, Armory Rework, 3-Hit-Stamcrit Batons, Flashbang fixes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)

## Reproduction:

1. Open customization menu.
2. Look for temporal scarring.
3. Find no temporal scarring.
4. Cry as you will forever be labeled as **"completely fucked up".**

Jokes aside, I think the cause is simply that it wasn't defined or is just missing. This is my first time reporting an issue. It's probably garbage.

**Comment by oranchepopsicle** [comment]
note to self: fucking check if the issues exist before posting.

edit: they do not.

**Comment by KittyNoodle** [comment]
I reported this exact issue downstream, currently yelling at mothblocks to fix their code
