### ISSUE TITLE
"Sentient mob" option is gone?

### ISSUE THREAD

**Issue by TW1STaL1CKY** [Skyrat-SS13/Skyrat-TG#8925]
## Round ID:
3344

## Reproduction:
A xenobiologist was trying to give a sentience potion to multiple animals (eg. a penguin chick, a rabbit, Markus), however I wasn't seeing any prompt to start controlling any of the sentient animals. The xeno was trying again and again but no prompt for me, eventually someone else would take them. I thought I had to enable something in preference but I couldn't find the option, so I asked mentors.

The mentor Reco201 said there used to be a "Sentient mob" option you had to enable, however it looks like it's gone with the new preferences menu. They advised me to report it here.

**Comment by gonenoculer5** [comment]
This is likely an issue with the new preferences menu, as I do not believe TG independently recognizes Sentient Mobs as a proper antagonist, so it probably just wasnt added to the pref menu. I might look into this.

**Comment by Zergspower** [comment]
working on current build as intended when granting a mob sentience.
