### ISSUE TITLE
Benches are broken

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#9057]
Reporting client version: 514.1561

## Round ID:
3422

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[Semi-modular] Adds Teshari](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8663)
- [[TESTMERGE ONLY] Telecrystal increased from 35 to 60 for 1 week.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9052)
- [[TESTMERGE ONLY] Haha, very funny. The Ancient Toolbox is 27 TC for the duration of the 60 TC test.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9053)

## Reproduction: Just... look at the benches

![image](https://user-images.githubusercontent.com/37010048/138922651-24b13452-8a57-4695-bb12-fb493d7e20b5.png)

**Comment by thestubborn** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9091

fixed

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9091
