### ISSUE TITLE
Station AI able to see DS-2

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#9148]
Reporting client version: 514.1547

## Round ID:
3460

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TESTMERGE ONLY] Telecrystal increased from 35 to 60 for 1 week.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9052)
- [[TESTMERGE ONLY] Haha, very funny. The Ancient Toolbox is 27 TC for the duration of the 60 TC test.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9053)
- [[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8960)

**Comment by Zergspower** [comment]
Cameras removed from DS-2 in a recent update
