### ISSUE TITLE
Teshari Wing sprites are still at an offset.

### ISSUE THREAD

**Issue by Kraos052** [Skyrat-SS13/Skyrat-TG#9149]
## **Round ID:**

3460

## **Related Bug Report:**

#9135 

## Testmerges:

Testmerges listed here and in related issue report with Teshari tail sprite report assuming the same Testmerges caused this issue as well.

#8842
#9052
#9053
#8960
#9130

## Reproduction:

Upon entering the character creation and enabling the wings selection, then choosing Low wings (Top)/ Low wings it becomes apparent that the sprites are off centered from the actual character sprite, at times disappearing when turned certain directions.

![Winged Tesh Back](https://user-images.githubusercontent.com/32678874/139554032-d98918bd-f778-4f7b-9048-cd26167bd85a.png)
![Winged Tesh Forward](https://user-images.githubusercontent.com/32678874/139554053-739397e7-86ba-4977-8ec8-d9da05d888e3.png)
![Winged Tesh Right](https://user-images.githubusercontent.com/32678874/139554054-8a6e5460-05e0-41da-a33a-3acc2bc91d99.png)
![Winged Tesh Left](https://user-images.githubusercontent.com/32678874/139554057-afa087ac-8d5f-46c4-b2db-c4ab23e25855.png)

**Comment by Zergspower** [comment]
seems working as intended now
