### ISSUE TITLE
Engineering Guard uniform has no inhand sprite or is incorrectly defined.

### ISSUE THREAD

**Issue by gonenoculer5** [Skyrat-SS13/Skyrat-TG#9154]
## Round ID:
3465

## Testmerges:
The following pull requests are currently test merged:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#9052: '[TESTMERGE ONLY] Telecrystal increased from 35 to 60 for 1 week.' by Iamgoofball at commit 939bcdde0b
#9053: '[TESTMERGE ONLY] Haha, very funny. The Ancient Toolbox is 27 TC for the duration of the 60 TC test.' by Iamgoofball at commit 9d83d65e20
#8960: '[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes' by Seris02 at commit b769e1dbbc

## Reproduction:

https://gyazo.com/2a1c6df4d66938696d95781c337af575

**Comment by gonenoculer5** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
over an entire month, nobody reported this 😔

**Comment by gonenoculer5** [comment]
> over an entire month, nobody reported this 😔

Its funny because I didnt know it was in existance until I became an engisec.

**Comment by gonenoculer5** [comment]
@tf-4 This isnt my first issue friend

**Comment by tf-4** [comment]
That's not what the tag is for. It's to point out issues that are good for first time contributors to fix.

**Comment by gonenoculer5** [comment]
OH okay. Whoopsie.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9702
