### ISSUE TITLE
funny infinite temperature change wrecks local liznerd (hardcore coldblooded™)

### ISSUE THREAD

**Issue by whataboutism-alos** [Skyrat-SS13/Skyrat-TG#9155]
## Round ID:

3465

## Reproduction:

My character Ahn'Dr Hollen alone suffers from what is so far as I can tell a unique bug, that does not affect any other character slots of mine (with further backing for this explained further down) nor any other known player. She is a lizardperson with a custom species name, she has no quirks nor augmented organs. Attempts to recreate this glitch on Skyrat on the same device, network, etc. using a different slot but otherwise identical lizardperson fail. Changing any of the affected slot's information including her species does not remove the bug, whether those changes persist into a round to be tested or not. I have recreated the bug at least six times while the necessary conditions (Skyrat, that specific character slot) are met, which is a 100% rate when compared to the total number of times of the character's exposure to the bug's catalyst.

**The glitch is as follows:**

While her temperature variable numerically functions correctly, the thermostat UI icon, wounded UI icon, and respective rate of temperature-induced damage function as though any significant temperature change caused by the environment is permanent\*. This renders medical players unable to understand why she is suffering burn damage frequently, and heavily impedes her ability to be revived and return to the round.

For example, a half-second of vacuum exposure instantly yields the cold blue thermostat and she enters crit in seconds no matter how quickly I remove the character from that situation; conversely (this happening in the listed round ID), being on fire for a moment instantly yields the max-red thermostat and unending blistering and burn damage, again putting her in crit in seconds. In the prior case, intervention by _multiple_ medical-dept. characters kept her 'stable' in crit for several minutes until the "cure" (included at bottom) was discovered. In the latter, she died almost immediately after the last of all of my anti-burn meds had been used up keeping her stable. It should be noted a nearby vulpkanin character, who does not have a species-intrinsic _resistance_ to high temperatures like lizardpeople _should_ have, was on fire from the same time for an even longer duration, yet did not suffer any blistering beyond a few seconds after the fire was extinguished nor did they even need medical department treatment (both were wearing explorer suits and situated on lavaland). Comparatively, my character died in a stasis pod right next to the incident's location, before even trying to go to the mining base let alone medical, and it took that round's well-staffed medical department roughly seven full minutes to figure out a remedy to fix her temperature without my ability to tell them what to do.

> \*The cure is to simply place her under a wrenched showerhead of either extreme temperature. This instantly removes the 
> thermostat and all associated incoming damage. For some reason wrenched showerheads don't seem to affect her at all when used to restore her baseline temperature _until_ she exits and re-enters the shower stream. This is probably another glitch.

I understand the difference between the simple burn damage variable and effects like those that cause the thermostat icon with respect to the code, I am fairly certain the issue lies there, and is something in my character preference data in specific. I am open to help in any way I can to get this issue fixed, because I highly doubt I will be the only player who has a slot that suffers from this. 

I did verify with each instance that this was not caused by admin pranks!

**Comment by GoldenAlpharex** [comment]
Marking it as DEVCON 3 because it's kinda bad and it's even worse due to how annoying it seems to reproduce. Thank you for reporting it.

**Comment by YakumoChen** [comment]
I bet it has something to do with the name somehow fucking with the var? have you tried recreating the character EXACTLY in another slot?

**Comment by Zergspower** [comment]
not able to reproduce this in current state- assuming resolved
