### ISSUE TITLE
Sizes of characters

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-tg#918]
While not quite a priority, I feel we should sooner or later get the size adjustments in
I know a lot of people, if not basically almost everyone fiddled with the sizes of their characters at some point, and I joined in on one of the tests, and its almost _comical_ on how much you can tell when your used to a character that was either really big or really small

**Comment by Gandalf2k15** [comment]
We will look into this for you, I reckon azarak will do this.

**Comment by Azarak** [comment]
Done in here https://github.com/Skyrat-SS13/Skyrat-tg/pull/1010
