### ISSUE TITLE
Spirits can drag crew, and they keep their usual VERY VERY fast speed.

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#9181]
Reporting client version: 514.1547

## Round ID:
3478

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8960)

**Comment by gonenoculer5** [comment]
Pretty sure this is just a like. Slight oversight. Drag speed is dependant on whos dragging them and since shades dont exactly have any way to be slowed down they just move at full tilt. Not really sure theres anything we can do about this downstream. Might want to report it on TG and see what they can do.

**Comment by tobjv** [comment]
> Pretty sure this is just a like. Slight oversight. Drag speed is dependant on whos dragging them and since shades dont exactly have any way to be slowed down they just move at full tilt. Not really sure theres anything we can do about this downstream. Might want to report it on TG and see what they can do.

What is the proper way to post a bug report to a upstream?

**Comment by tf-4** [comment]
An issue report like this one, but on their repo.

**Comment by gonenoculer5** [comment]
@tobjv Please link this issue to the upstream report aswell please.

**Comment by tobjv** [comment]
> @tobjv Please link this issue to the upstream report aswell please.

I did, TG reports this is intended and not a bug.

**Comment by Zergspower** [comment]
Upstream 'issue' unless otherwise determined later - working as intended currently
