### ISSUE TITLE
Loadout put in case pref deletes job item in hand

### ISSUE THREAD

**Issue by tf-4** [Skyrat-SS13/Skyrat-TG#9202]
## Round ID: 

N/A

## Testmerges:

N/A

## Reproduction:

Use case loadout option when spawning as a job with an item spawned in hand by default, i.e. cargo tech. The case will delete the export scanner, which is also kind of a pain to get a new one of.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/8630 Relevant PR

`modular_skyrat/modules/loadouts/loadout_ui/loadout_outfit_helpers.dm` relevant file

**Comment by gonenoculer5** [comment]
Bit of an oversight yeah. I believe I yelled at gandalf about this exact potential usecase being an issue. [screaming]

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/17965
