### ISSUE TITLE
AI Borg shells cannot state laws due to OOC Chat filter.

### ISSUE THREAD

**Issue by gonenoculer5** [Skyrat-SS13/Skyrat-TG#9286]
## Round ID:
3525
## Reproduction:
Attempt to state your laws as an AI shell. Fuckery commences.

https://gyazo.com/b9cdce9c7f36189081e611c485c708e3

**Comment by Tastyfish** [comment]
The chat filter bug appears to have been captured upstream. https://github.com/tgstation/tgstation/issues/62655

**Comment by gonenoculer5** [comment]
> The chat filter bug appears to have been captured upstream. [tgstation/tgstation#62655](https://github.com/tgstation/tgstation/issues/62655)

Good find.

**Comment by GoldenAlpharex** [comment]
> The chat filter bug appears to have been captured upstream. [tgstation/tgstation#62655](https://github.com/tgstation/tgstation/issues/62655)

You mean, *Golden went upstream to fix one hell of an annoying bug.*

Yes. Yes I did.
