### ISSUE TITLE
DS-2/Interdyne scuffed to hell, multiple problems

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#9435]
Reporting client version: 514.1547

## Round ID:
3582

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[NonModular] Rebalances, and makes >just vampires< available year-round.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9144)
- [zephyr's admin mark PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7959)
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [Making kudzu more utilitarian](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9217)

**Comment by tf-4** [comment]
Please post each issue individually. Multi-issue posts just make it awkward to resolve.
