### ISSUE TITLE
Medical borg models are shifted to the right.

### ISSUE THREAD

**Issue by Aether217** [Skyrat-SS13/Skyrat-TG#9479]
Reporting client version: 514.1557

## Round ID:
3602

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[NonModular] Rebalances, and makes >just vampires< available year-round.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9144)
- [zephyr's admin mark PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7959)
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [Making kudzu more utilitarian](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9217)

## Reproduction:

Seemingly all medical dogborg modules are shifted to the side about 16-17 pixels as it can be seen in this screenshot
![Screenshot_39](https://user-images.githubusercontent.com/80391087/141834380-fa50cb63-d0f8-49ec-9881-5b462ab5dd95.png)
![Screenshot_38](https://user-images.githubusercontent.com/80391087/141834395-68f914af-0a5d-48ff-a204-9f3305d8e3b6.png)

**Comment by Zergspower** [comment]
Resolved in a later fix
