### ISSUE TITLE
All cameras facing the wrong way

### ISSUE THREAD

**Issue by Tastyfish** [Skyrat-SS13/Skyrat-TG#9485]
## Testmerges:
* #8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
* #9144: '[NonModular] Rebalances, and makes >just vampires< available year-round.' by RatFromTheJungle at commit 9c11be1cd5
* #7959: 'zephyr's admin mark PR' by jjpark-kb at commit fde0ad76d6
* #9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
* #9217: 'Making kudzu more utilitarian' by Gandalf2k15 at commit f68bec95e5

## Reproduction:
1. Launch the production server into MetaStation.
2. Literally all cameras are facing the opposite direction. Unknown if the issue is occurring for other maps.

![Imgur](https://i.imgur.com/MkSPoZK.png)

**Comment by Saisni** [comment]
Oh yeah, plenty of those floating all over the place
![4JmmSIud7d](https://user-images.githubusercontent.com/71731828/141917808-3fe6346b-dd57-4a1b-bfb6-b57c3b67294a.png)
.
