### ISSUE TITLE
.8 percent sprite size makes it so you get defaulted to 1.0

### ISSUE THREAD

**Issue by FridayRemada** [Skyrat-SS13/Skyrat-TG#9507]
## Reproduction:

 Very simply, in the character creation/preferences menu, turn the size slider all the way down to 0.8, and you will see, both in round and in the menu you DON'T get turned down to that size. Works on every species/every instance of character I've tried, Anthromorphs, Vox, Ipc's and Humans.

![pointeightzero](https://user-images.githubusercontent.com/77188588/142106649-30e4aaee-c777-4bed-bd24-ef104742499c.PNG)
![zeropointeightone](https://user-images.githubusercontent.com/77188588/142106733-9d887d8e-c9ce-4004-9729-91a741cc5b85.PNG)

<!-- **For Admins:** Oddities induced 

by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them. --

**Comment by Zergspower** [comment]
Bug still present in current state
