### ISSUE TITLE
All items from people drop on the ground when they enter cryo.

### ISSUE THREAD

**Issue by Tastyfish** [Skyrat-SS13/Skyrat-TG#9509]
## Testmerges:
None relevant, but the full list:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#9144: '[NonModular] Rebalances, and makes >just vampires< available year-round.' by RatFromTheJungle at commit 9c11be1cd5
#7959: 'zephyr's admin mark PR' by jjpark-kb at commit fde0ad76d6
#9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
#9217: 'Making kudzu more utilitarian' by Gandalf2k15 at commit f68bec95e5
#9395: 'The Roleplay Update - Slightly more versatile emotes' by GoldenAlpharex at commit a91f72e149

## Reproduction:
1. Enter cryo.
2. All your stuff falls out on tg before they removed it.

Cryo is now fully our issue since it's now a skyrat module.

![Imgur](https://i.imgur.com/hSqcWDh.png)

**Comment by GoldenAlpharex** [comment]
This should now be fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/9517
