### ISSUE TITLE
Turning cleanbots off makes them invisible and clicking them does nothing

### ISSUE THREAD

**Issue by chizzyyyy** [Skyrat-SS13/Skyrat-TG#9516]
Reporting client version: 514.1568

## Round ID:
3618
 
## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[NonModular] Rebalances, and makes >just vampires< available year-round.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9144)
- [zephyr's admin mark PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7959)
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [Making kudzu more utilitarian](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9217)
- [The Roleplay Update - Slightly more versatile emotes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9395)

## Reproduction:
Create a cleanbot, swipe your ID to unlock their cover, turn them off using the power button. They disappear.

![potion of invisible jannies](https://user-images.githubusercontent.com/90527540/142218749-243db194-d848-4641-ab93-b45d875106d1.png)

**Comment by tf-4** [comment]
https://github.com/tgstation/tgstation/pull/63001

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9788
