### ISSUE TITLE
DS-2/interdyne teleporter teleports itself

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#9575]
## Testmerges:
[TM-Only] First attempt at stopping tgchat from eating messages
[NonModular] Rebalances, and makes >just vampires< available year-round.
zephyr's admin mark PR
[TM-ONLY] Disabling 911 until it's fully fleshed out
Making kudzu more utilitarian

**Comment by GoldenAlpharex** [comment]
Already fixed by a PR of mine.
