### ISSUE TITLE
Suplex has broken text formatting

### ISSUE THREAD

**Issue by mazzinsanity** [Skyrat-SS13/Skyrat-TG#9658]
Reporting client version: 514.1557

## Round ID:
3669

## Testmerges:
- [[NonModular] Rebalances, and makes >just vampires< available year-round.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9144)
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [The Roleplay Update - Slightly more versatile emotes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9395)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM-Only] Temp fix until I fix the actual problem with drinking glasses](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9633)

## Reproduction:

Suplexing has bad formatting.

![image](https://user-images.githubusercontent.com/77054674/143058716-bc4078ff-de3c-49b0-be8c-f541373bbaf1.png)

**Comment by GoldenAlpharex** [comment]
@tf-4 😔

**Comment by mazzinsanity** [comment]
teefor broken the game wtf man why :rage: :rage: :rage: 👎
