### ISSUE TITLE
Invisible potted plant in Interlink

### ISSUE THREAD

**Issue by W4rd3nn** [Skyrat-SS13/Skyrat-TG#9671]
## Round ID:
3673

## Reproduction:
The potted plant just south of the shuttle terminal in the Interlink appears to be invisible. You can shift+right-click on it to open the context menu and pick it up. Doing so will make your sprite completely invisible save for HUD elements such as MedHUD and SecHUD. This also makes it incredibly difficult for other players to click on you for combat or other functions. I spoke with an admin during the round and they confirmed that the potted plant should not be doing this according to its variables.

**Comment by YakumoChen** [comment]
needs reproducing, the plant is randomly generated.
