### ISSUE TITLE
Liquids don't evaporate and are annoying to clean

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#9677]
## Reproduction:
1. throw any container contaning any liquid
2. watch as a huge, slippery mess forms
3. cry because it is permanent without an extremely specific, annoying to use item (mops) unless it's water
4. cry more because you have to empty the mop into something and there's no sane way to dispose liquids
5. smile as you realize you can use this to grief the station and make huge Slip Zones that are obnoxious to clean but extremely easy to spread

Bonus points for oil/plasma spills which are nearly impossible to extinguish once ignited and play extremely poorly with the atmos subsystem.

**Comment by Zergspower** [comment]
some fluids evaporate over time, but this enhancement would be upstream for sure

**Comment by YakumoChen** [comment]
The liquids system is not upstream code.

I have never seen liquid puddles or pools outside of water evaporate.
