### ISSUE TITLE
Jumpsuits have random colors

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#9682]
So when you put on, for example, the dark blue jumpsuit it will most of the time not actually be that color and instead be green or black or something else. The same issue exists with prisoner jumpsuits, most of the time they're not even orange. Most of the time they end up being black but i've seen other colors aswell.
![Screenshot_1](https://user-images.githubusercontent.com/75141807/143266455-4fd12672-bc02-44fc-ae1a-7f062b1313a9.png)

**Comment by tf-4** [comment]
How long ago did this start, roughly?

**Comment by Mithrun** [comment]
i'm not sure honestly but it has to have been over a month at least.

**Comment by tf-4** [comment]
Unable to reproduce this on local

**Comment by Mithrun** [comment]
Dunno just today i had a purple jumpsuit but it was brown.

**Comment by tf-4** [comment]
Any notable information? Where did you get it from? What was the name of the item? Anything that could be helpful.

**Comment by tf-4** [comment]
Located the issue, it's a problem with GAGS and having a female body type. Reproduced reliably on live.

It also stops the worn sprite updating on mob. For any GAGS clothing. So it's slightly higher severity than I first realised.

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/11292
