### ISSUE TITLE
Medical Cyborg Hypospray not working

### ISSUE THREAD

**Issue by jwc1015** [Skyrat-SS13/Skyrat-TG#9737]
Reporting client version: 514.1568

## Round ID:
3697

## Testmerges:
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [The Roleplay Update - Slightly more versatile emotes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9395)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[STILL NOT MODULAR] #9411's Hemophages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9681)

## Reproduction:
I was playing as medborg, and all of a sudden, my hypospray stopped being able to select certain chemicals. I am unsure exactly as to _why_ but it may be that I had used all of the chemicals in that stock even if it regenerated afterwards - this may have broken that 'slot' of the hypospray. I also ran into an issue where alt+clicking and setting the transfer amount is always only 5 available - but it always _sets it_ to 2u instead of 5u.

**Comment by Zergspower** [comment]
current build allows it to function normally, assuming issue resolved with time
