### ISSUE TITLE
Medical Drakeborgs are Off-Center and unable to use certain Verbs.

### ISSUE THREAD

**Issue by Pascal125** [Skyrat-SS13/Skyrat-TG#9771]
## Round ID: 
3724

## Testmerges:

#9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#9750: '[s] [IDB IGNORE] [TM-ONLY] A temporary fix' by GoldenAlpharex at commit 2c7db8148d
#9749: '[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115' by Iamgoofball at commit 2807abd120
#9581: 'GoofSec 1.5: Departmental Batons, Departmental Guard Offices, Batons from Backpacks -> Belts, Guard Cuffs -> Cableties, Mapping Icons for Jobs, Belt Reskinning, Brig Officer Baton Change, Sec Medic Gun Removal + Medical Access Removal, Security Sergeant Removal' by Iamgoofball at commit 6e9f56bf3e

## Reproduction:

Medical Drake Borg Model is permanently off center, and cannot use the "Lay Down" or "Switch Rest Style" verb under "AI Commands", this has a similar effect as an AI when using a shell. Albeit also stripping the "AI Commands" section entirely.

1. Join as a Cyborg.
2. Select a medical model.
3. Select the Medical Drake Borg Model which is off-center unlike with say, the Engineering one. (And possibly other drake borg models currently have this issue as well.)

**Comment by Tastyfish** [comment]
It's likely more the issue with all medical borgs. #9479

**Comment by tf-4** [comment]
Will be fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/9701

**Comment by Zergspower** [comment]
Resolved in a later fix
