### ISSUE TITLE
SQL error while using telekinesis on an engineering guard locker.

### ISSUE THREAD

**Issue by GuiltyNeko** [Skyrat-SS13/Skyrat-TG#9772]
## Testmerges:
#9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#9750: '[s] [IDB IGNORE] [TM-ONLY] A temporary fix' by GoldenAlpharex at commit 2c7db8148d
#9749: '[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115' by Iamgoofball at commit 2807abd120
#9581: 'GoofSec 1.5: Departmental Batons, Departmental Guard Offices, Batons from Backpacks -> Belts, Guard Cuffs -> Cableties, Mapping Icons for Jobs, Belt Reskinning, Brig Officer Baton Change, Sec Medic Gun Removal + Medical Access Removal, Security Sergeant Removal' by Iamgoofball at commit 6e9f56bf3e

## Reproduction:
Unknown for sure, I opened and closed the lockers while they were in TK grab, and attempted to lock them as well, which of course didn't work. At some point, it said "A SQL error occurred during this operation, check the server logs." I'm not sure if this is what caused it, but it's what I was doing when it happened. After that I couldn't get it to happen again.

**Comment by tf-4** [comment]
This issue is quite unlikely to be related to the locker and would only be identifiable by looking at logs.
