### ISSUE TITLE
Ninja Borg hacking doesnt seem to work

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#9773]
Reporting client version: 514.1561

## Round ID:
3726

## Testmerges:
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[s] [IDB IGNORE] [TM-ONLY] A temporary fix](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9750)
- [[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9749)
- [GoofSec 1.5: Departmental Batons, Departmental Guard Offices, Batons from Backpacks -> Belts, Guard Cuffs -> Cableties, Mapping Icons for Jobs, Belt Reskinning, Brig Officer Baton Change, Sec Medic Gun Removal + Medical Access Removal, Security Sergeant Removal](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9581)

## Reproduction:
Be borg. Choose moduele or not. Get hacked by ninja, select assault moduele. It doesnt work. Might be due to choosing the maid sprite.

**Comment by Zergspower** [comment]
Resolved
