### ISSUE TITLE
Plasmaman dont spawn with plasmaman envirosuits in DS-2

### ISSUE THREAD

**Issue by oranchepopsicle** [Skyrat-SS13/Skyrat-TG#9783]
Reporting client version: 514.1568

## Round ID:
3728

## Testmerges:
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[s] [IDB IGNORE] [TM-ONLY] A temporary fix](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9750)
- [[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9749)
- [GoofSec 1.5: Departmental Batons, Departmental Guard Offices, Batons from Backpacks -> Belts, Guard Cuffs -> Cableties, Mapping Icons for Jobs, Belt Reskinning, Brig Officer Baton Change, Sec Medic Gun Removal + Medical Access Removal, Security Sergeant Removal](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9581)

## Reproduction:

-Spawn as Plasmaman in your preferences.
-Go through the "don't use your station character" spiel, use your plasmaman Syndicate character.
-Spawn with a utility uniform
**-BURN.**

-Strangley enough, I dont remember this being an issue when spawning on syndicate mining station, but that needs testing I think.

**Comment by CandleJaxx** [comment]
there lacks a plasmaman syndie sprite anyway, weirdly. if any code devs wanna handle this, i can sprite one up

**Comment by oranchepopsicle** [comment]
i would love that. You could alternativeley just not use a plasmaman syndie suit sprite, but where's the fun in that?

...now that i think of it, polychromic plasmaman suits/gloves/helmets sound awesome.

**Comment by ghost** [comment]
Dupe of #4251 (Ghost roles dont like plasmamen)
