### ISSUE TITLE
2 Skyrat's semi-security jobs issue

### ISSUE THREAD

**Issue by Archemagus** [Skyrat-SS13/Skyrat-TG#9867]
## Reproduction:
(all of dep guards like orderly, custom agent, e.t.c. i'll call simply Bouncer)
- [ ] Bouncers are guards, and they HAVE access to brig, and sec office, which means sec protolathe too. But they are not mindshielded.
Who are they for doing that? Heads of Staff? Implant all of them!

- [ ]  Also Bouncers are equiped with stunbaton. Which counts as a weapon. Do you know what happend, if Bouner will try to preform arrest infront of Beepsky with Weapon Check on? Right - Bouncer will be stuned and cuffed. Cause they have no Weapon Permit Access.
That also can be applied to Corrections Officer.

**Comment by Zergspower** [comment]
Oversight resolved with current coding
