### ISSUE TITLE
MicroFusion Guns Bug report

### ISSUE THREAD

**Issue by Kalesonki** [Skyrat-SS13/Skyrat-TG#9906]
## Reproduction:
There are few issues we have encountered in Nobuharas' weapons testing:

- Disabler attachment breaks when toggled too fast on and off (Time Dilation was about 40%-50%), using new attachment fixes that
- Disabler attachment causes 3rd degree burns
![obraz](https://user-images.githubusercontent.com/79363897/144897323-49b35190-8175-46f0-bd7e-9ddf038e89ea.png)

- Spreadshot breaks on a gun permamently after being used with disabler attachment toggled on. Replacing attachments doesnt fix that, it is permament on given carbine
![obraz](https://user-images.githubusercontent.com/79363897/144897530-6cb92fd0-8878-4fde-b237-11022c8a2932.png)

- When using broken spreadshot, we discovered that when aimed properly, despite there being 2 projectiles only, game is able to register 3 hits (2 hits on one monkey, 1 hit on the adjacent monkey)
- Battery charge on the sprite does not sync properly with actual charge sometimes (displays full when cell is at 50% capacity for example)
- One carbine just stopped working. Replaced all attachments, it just refused to shoot again. Can't tell what caused it.

**Comment by tf-4** [comment]
Please make these as separate reports, as it'll be far harder to close an issue like this with them all bundled up.
