### ISSUE TITLE
Syndicate christmas tree has presents while on station ones do not

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-TG#9913]
Reporting client version: 514.1561

## Round ID:
3795

## Testmerges:
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9749)
- [Added walls and floors made of meat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9806)

**Comment by Zergspower** [comment]
aged but did get resolved
