### ISSUE TITLE
Combat mode for borgs makes their eyes turn off

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-TG#9923]
Round ID: 3800
BYOND Version: 514.1560
Server revision compiled on: 2021-12-07T00:13:59+00:00
Master commit: a93adf7776de28cd7aacb15adaad259b40b137ab
The following pull requests are currently test merged:
#9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#9749: '[TM ONLY] temp mirror of https://github.com/tgstation/tgstation/pull/63115' by Iamgoofball at commit 2807abd120
#9806: 'Added walls and floors made of meat' by Useroth at commit f5179ae995
#9912: 'Field of View component [bounty]' by Azarak at commit 8fcaad9518
## Reproduction:
Be borg. Press C or F since they are the same thing for borgs. Watch your eyes turn off, as if you have no power. Also darkens bodies of drake borgs. This is more serious than it sounds, because it makes some of the drake borg types turn grey and thus look similar to peacekeeper borgs when they are really medical. Still not super serious. I thought I'd get this one in quick, since it's almost certainly related to the FoV test merge.

**Comment by Zergspower** [comment]
C/f no longer turns the eyes off but turning on walkmode does as by design
