### ISSUE TITLE
Stechkin APS pistol's suppressor sprite isn't offset correctly

### ISSUE THREAD

**Issue by Zonespace27** [Skyrat-SS13/Skyrat-TG#9949]
## Round ID: 3807

The Stechkin APS autopistol's suppressor sprite isn't offset properly, meaning the suppressor does not appear to be on the barrel at all.

## Reproduction:

1. Obtain Stechkin APS
2. Obtain Suppressor
3. Attach Suppressor to Stechkin
4. See offset error

**Comment by Zergspower** [comment]
looks normal in current build - marking this resolved overtime
