### ISSUE TITLE
Moth fluff does not display if wings are also selected

### ISSUE THREAD

**Issue by Shroopy** [Skyrat-SS13/Skyrat-TG#9968]
## Reproduction:
Make a moth character, and give them both fluff and wings that are different colors. The fluff will not show, and will instead be overwritten by the fluff from the wings. You can check to make sure that you have fluff if you disable the wings, but adding the wings back hides the fluff again.

**Comment by Zergspower** [comment]
Moffs are fluffy and have wings again
