### ISSUE TITLE
Donksoft LMG can not be reloaded

### ISSUE THREAD

**Issue by SpookyTheFox** [Skyrat-SS13/Skyrat-TG#9987]
Round ID: 3828
BYOND Version: 514.1560
Server revision compiled on: 2021-12-10T05:29:43+00:00
Master commit: d37f96bd2b8f1c0731350908a1c488865db9ba79
The following pull requests are currently test merged:
#9919: 'Adds an autockick subsystem' by Gandalf2k15 at commit 3b843d5707
#9267: '[TM-ONLY] Disabling 911 until it's fully fleshed out' by GoldenAlpharex at commit 749e91d8f9
#9912: '[DNM] Field of View component [bounty]' by Azarak at commit b1a245aed8
#9941: 'Events audit, moving overrides to modular files + TEMP FIX' by Gandalf2k15 at commit 8316973ae8
#9963: 'New Security Drip! :)' by Gandalf2k15 at commit 2fc263f865
#9984: 'Revert "[MIRROR] Speeds up the preference menu, significantly. Adds object pooling, other stuff too [MDB IGNORE]"' by Seris02 at commit db15a4abcb

## Reproduction:
Remove donksoft LMG ammo box with alt+click and then empty hand. Put the ammo box back on, then try to close the cover with alt+click, which just removes the magazine again. I didn't test it with the non-donksoft version, but it's probably the same.

This was almost certainly broken by mod guns and reloading changes

**Comment by tf-4** [comment]
Reproduced and confirmed to be an issue on the regular SAW as well

**Comment by TheBonded** [comment]
have you tried using it in hand to close the bolt? afaik that's how it works upstream

**Comment by SpookyTheFox** [comment]
> have you tried using it in hand to close the bolt? afaik that's how it works upstream

You can't. I suspect LMGs badly inherited something from https://github.com/Skyrat-SS13/Skyrat-tg/pull/9638 which was at about the same time made a change to magazines. That's my guess anyway.

**Comment by tf-4** [comment]
fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/10152
